### ISSUE TITLE
Durable Function not scaling out in UK South. However UK West is working fine.

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1036]
DF : 1.8.3
Runtime version, UK South and UK West : 2.0.12858.0
Consumption plan on UK South and UK West

We have the exact same Function App deployed to UK South and UK West Regions.

Given a load test scenario of 40,000 instances, the function app receives work over a `ServiceBusTrigger` and then starts a unique orchestration.

UK West performance is as expected and scaling correctly. UK South however does not scale at all. What could be causing this? 

- We haven't knowingly changed the underlying Azure Storage configurations for the TaskHub in either region. 
- Function App configs are the same 
- `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT ` is not set.
- We've tried deleting the TaskHub and letting the Function App recreate it.
- We've redeployed the binaries from DevOps
- We've manually resynced the triggers on the function Host.
---

**UK West - Good throughput** - Example Execution ID : 2a218994e414447e90b2fc7a1ec4e49e

In UK West, the Function App begins to scale out, adding many instances (checked with `cloud_RoleInstance` in App Insights)

Approx 4k throughput per minute :
![image](https://user-images.githubusercontent.com/4224880/68488869-e404c580-023d-11ea-8968-91ca0459d8bd.png)

Many cloud_roleInstances involved - scales up after a few minute :
![image](https://user-images.githubusercontent.com/4224880/68488983-1adadb80-023e-11ea-9687-edea1784d319.png)

---

**UK South - Poor throughput** - Example Execution ID : a96c889089c2418682dfb8096beb411a

In UK South, the function App sticks to just one instance and the throughput is consistently slow.

Approx 200-300 per minute :
![image](https://user-images.githubusercontent.com/4224880/68485318-02b38e00-0237-11ea-97e0-6e18626bcdde.png)

Just 1 `cloud_RoleInstance` involved - no scaling at all :
![image](https://user-images.githubusercontent.com/4224880/68489713-883b3c00-023f-11ea-865b-4de540cbb24a.png)

**Comment by cgillum** [comment]
Hi @olitomlinson can you share a more specific time range we should be looking for? I see your app and I do see some warnings from the scale controller regarding your app, but I can't say with confidence if they correlate to the no-scale issue you're observing.

For what it's worth, it appears the scale controller is occasionally running into timeouts while trying to access information in your app's storage account - specifically, I think it's timing out trying to read the `TaskHub-leases/taskhub.json` file. You mentioned you already tried deleting and recreating the task hub? Again, I'm not entirely sure if this represents a root cause. I'll need to narrow down the date/time range to build more confidence on the cause.

**Comment by olitomlinson** [comment]
@cgillum Thanks for taking a look!

Its been slow all day, every time we have tested. But if you need a specific time, the last graph above shows the start of a load test, starting at approx 14:32:30 UTC today (Friday) and onward through to 14:53.

Yes we have definitely deleted the TaskHub and restarted the App to cause the TaskHub to be created once again.

---

Here are a few more examples from this morning, the blocks of colour represent a different load test.

![image](https://user-images.githubusercontent.com/4224880/68508858-6fdf1780-0267-11ea-8217-ea6a2c10dc12.png)

Notice the 4th load test represents a higher throughput, this is because we had a go at downgrading the runtime version to `2.0.12835.0`, which introduced a second host! but never scaled beyond the second host.

![image](https://user-images.githubusercontent.com/4224880/68509028-e67c1500-0267-11ea-9426-4aaa59a17fa8.png)

**Comment by cgillum** [comment]
Thanks for these details. I'm having a few engineers from the App Service team look at this with me, and it appears your UK South app is running into an infrastructure issue where we're failing to allocate additional capacity for your function app. We're currently trying to narrow down the exact cause and figure out how to fix it.

Would you mind opening a support case for this? I want to make sure it gets the right traction, especially since I will be out most of next week.

Depending on how urgent the situation is for you, you may be able to get around this issue by redeploying your app. Two options I can think of right now:

1. Redeploy to a new resource group in the Consumption plan. The problem you're currently facing is related to the compute stamp that your app has been placed on.
2. Redeploy to a new plan type - e.g. App Service Plan or Elastic Premium plan (which is now GA). These plan types should be immune to this particular capacity allocation issue.

I realize neither of these options are ideal - I just wanted to throw them out there in case you need a faster mitigation.  We have people looking at this with priority, but I still recommend opening that support case.

**Comment by cgillum** [comment]
What I'm hearing is that the issue may also be related to certificates - i.e. if your app or plan has certificates that you uploaded/registered, it may cause capacity allocation problems in certain situations.

**Comment by olitomlinson** [comment]
@cgillum wow that is interesting!

We did refresh some expiring SSL certs on the 6th, but those certs were installed on a totally separate App Service Plan (probably in the same Resource Group IIRC). 

If you need more details on that I can provide it.

Will raise a support case today. Cheers.

**Comment by olitomlinson** [comment]
@cgillum 

Raised the support case with Azure Support - 119110925000084

Also, my colleague has informed me that we didn't update the SSL certs in UK West, just UK South.

**Comment by olitomlinson** [comment]
@cgillum just had a notice from Azure Support that his has been fixed so I'll close this now. As you identified, the problem was with failure to propagate certs across stamps. Thanks so much for jumping on this issue!

Out of my own curiosity, what is a _stamp_ in relation to azures compute fabric?

**Comment by cgillum** [comment]
I'm glad we were able to get this resolved!

Think of a stamp as a compute cluster. In most cases, it's actually a Cloud Services hosted service behind the scenes. We have potentially dozens of them in every region, depending on demand. Consumption functions are special in that they can scale across multiple stamps when there isn't enough capacity in the "home" stamp. What we found in your case was that there is a failure to do cross stamp scaling in certain situations when apps have certificates uploaded. My team manually mitigated your app and are deploying a permanent fix in all of our other stamps globally.
