### ISSUE TITLE
Notification when queue messages are expired

### ISSUE THREAD

**Issue by austvik** [Azure/azure-functions-durable-extension#1050]
**Is your feature request related to a problem? Please describe.**

We have a queue where we want process all elements on the queue. If we time out, the queue elements that has expired seems to be pruned at read time (based on read taking long time and on approximate queue size). We want to know when that has happened, so we know that our queue is incomplete.

**Describe the solution you'd like**

At queue read (gett messages): add a response header or parameter to the response saying NumMessagesExpired = 4

If that is set on any read, the client can act accordingly.

**Describe alternatives you've considered**

Unlimited TTL will work around it for us. I still think it is a good idea to signal clients that queue messages has been deleted because of TTL expiry.

**Comment by cgillum** [comment]
Hi @austvik - thanks for submitting this suggestion. I think I may need a bit more information to fully understand it. A few questions:

* Does the problem you're trying to solve involve Azure Functions queue triggers?
* Can you clarify what you mean when you say the queue elements are "pruned"?
* Can you clarify who the "client" is in your scenario?
* You mentioned a solution that involves a "response header or parameter to the response". Can you clarify what response you're asking about? Since queues usually involve one-way messaging, there isn't usually any "response", so I might be missing some context about what you're describing.

Thanks!

**Comment by austvik** [comment]
Azure Functions: No.

"Pruned": Sorry, I don't know the correct term. It seems like expired messages are deleted at the time the client reads messages from the queue. I was referring to this "deletion for real".

Client: I was thinking about any user of the Azure Storage Queues APIs

Response: I was referring to the response of this REST call: https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages

**Comment by austvik** [comment]
Sorry, should be on Azure storage.
