### ISSUE TITLE
Question on usage of IDurableOrchestrationClient.StartNewAsync() in Durable Function 2.0.0

### ISSUE THREAD

**Issue by sebader** [Azure/azure-functions-durable-extension#1056]
### Description
I just switched to Durable Functions extension 2.0. I have a simple Timer Triggered function that starts an orchestrator with some input. In v1 I had this:
```csharp
int input = 1;
string instanceId = await starter.StartNewAsync("UpdateHutsOrchestrator", input);
```
after switching to v2 I had to change to
```csharp
string instanceId = await starter.StartNewAsync("UpdateHutsOrchestrator", null, input);
```

for this to work again (setting the instanceId parameter to null).
However, when input is neither `int` nor `string`, for instance `List<int>` the old behavior still works in v2:
```csharp
List<int> input = new List<int>();
string instanceId = await starter.StartNewAsync("UpdateHutsOrchestrator", input);
```

Could you explain why the behaviour is different for different types? 

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

**Comment by ltouro** [comment]
I think it is a matter of overloaded methods. Looks like when using a string primitive as input, it will be regarded as the instanceId:

```
public System.Threading.Tasks.Task<string> StartNewAsync<T> (string orchestratorFunctionName, string instanceId, T input);
```

In these cases, you should pass null as instanceid

See the overloads:
https://docs.microsoft.com/pt-br/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.durablecontextextensions.startnewasync

**Comment by cgillum** [comment]
We found that some users were accidentally passing what they thought was an instance ID instead as the input argument, so we accepted a PR that changed the method signature to prevent this mistake. You can effectively get the previous behavior if you call the StartNewAsync<string>(...) overload instead of calling the non-generic overload.

**Comment by sebader** [comment]
sorry for the late reply. It makes sense for string input. But why is the behavior the same for int input?

**Comment by brandonh-msft** [comment]
More accurately, the PR required that users, when using the 2-parameter overload, specify that the 2nd parameter is the _payload_ and not the _instanceId_ (in particular in the case of `string` payload) by specifying the type argument (in most cases this ends up being `<string>` for those affected).

for instance in v1 you'd do something like this:
```csharp
string myArgs = "doThis";
string instanceId = await starter.StartNewAsync<string>("UpdateHutsOrchestrator", input);
```
thinking you'd just sent the args in to your orchestrator, but in fact you send an instanceId of `doThis` instead, and you'd need to add the `null` as param #2 then your argument (much like how you cited you needed to change your code).

in v2, this should get called this to your attention by giving you an "ambiguous reference" compile-time error. you'd get the old behavior by simply adding `<string>` to your call like this:
```csharp
string myArgs = "doThis";
string instanceId = await starter.StartNewAsync<string>("UpdateHutsOrchestrator", input);
```

you should _not_ have had to add anything when using any arg type other than `null` or `string` so it's curious to me that your argument is `int` and you needed to make this change.

Could you by chance share a sample that repros? Hopefully it's a misunderstanding or, at worst, something we can fix w/o a breaking change.

Thanks!

**Comment by sebader** [comment]
sure, we look if I can repro and post the code here then

**Comment by sebader** [comment]
So this works without error:
`string instanceId = await starter.StartNewAsync<string>(nameof(UpdateHutsOrchestrator), "abc");`

This does not:
`string instanceId = await starter.StartNewAsync<int>(nameof(UpdateHutsOrchestrator), 1);`

![image](https://user-images.githubusercontent.com/11445087/69612764-a7eca580-1030-11ea-8c50-d9eb8514e032.png)

**Comment by brandonh-msft** [comment]
Ah yes... the key here lies in the definition of `StartNewAsync<T>`:
```csharp
public static Task<string> StartNewAsync<T>(
    this IDurableOrchestrationClient client,
    string orchestratorFunctionName,
    T input)
    where T : class
...
```

notice the Type restriction: `where T : class`. In your scenario `int` is not a class so that's why this fails.

Why do we have this restriction?
Internally, whenever you _weren't_ passing input to a new orchestrator, we do this:
```csharp
public static Task<string> StartNewAsync(
    this IDurableOrchestrationClient client,
    string orchestratorFunctionName,
    string instanceId)
{
    return client.StartNewAsync<object>(orchestratorFunctionName, instanceId, null);
}
```
notice the usage of `null` here. If your orchestrator accepted `int` but we sent `null` that would be a mismatch - or at worst it just wouldn't get fired. The type restriction `: class` ensures we can send `null` to your target "safely" (as long as you handle it).

I'm open to relaxing this restriction (wouldn't be a breaking change), but I think in your scenario what would be more idea would be perhaps to pass a JObject that contains your int w/ a meaningful property name. e.g.
```json
{
  "numberOfThings" : 1
}
```

Thoughts?

**Comment by sebader** [comment]
thanks for the deep explaination @brandonh-msft It is ok for me as it is. I just wanted to understand the behavior - and why in certain cases it seemed to differ. So I'm all good now :)
