### ISSUE TITLE
Instance with id not found

### ISSUE THREAD

**Issue by OwenPattison** [Azure/azure-functions-durable-extension#1071]
### Description
I have just upgraded to 2.0.0 from 1.8.3, since deploying some of my instances are failing to be found when orchestratorClient.RaiseEventAsync(id, eventName) is called.

Upon investigation, this seems to be down to storage changing the default name, my durable function instance names pre deploying 2.0.0:
```
DurableFunctionsHubHistory
DurableFunctionsHubInstances
```
and post deploying 2.0.0:
```
functionnameHistory
functionnameInstances
```

### Expected behavior
Previously created instances should still be used if they exist, perhaps look for the old default naming if not found in the new naming pattern?

Should be classified as a breaking change in the release notes.

### Actual behavior
```chsarp
No instance with ID '87ac39f2d4ce4108ab64e313f86deb9f' was found.
Parameter name: instanceId
```

### Relevant source code snippets
```csharp
await starter.RaiseEventAsync(vettingItem.ResetVettingItemInstanceId, ResetVettingItemStateNames.Cancel);
```

### Known workarounds
Exporting all old data from original History + Instances into the newly created tables and re-queueing poison messages

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
![StorageExplorer_2019-11-27_10-45-19](https://user-images.githubusercontent.com/5864244/69717017-26b21300-1103-11ea-8dfa-977e8230d435.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 
- **Function App name**: 
- **Function name(s)**: ResetVettingItemState_Start
- **Azure region**: North Europe
- **Orchestration instance ID(s)**: 87ac39f2d4ce4108ab64e313f86deb9f
- **Azure storage account name**: 

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ConnorMcMahon** [comment]
So this was an intentional breaking change made for Durable 2.0. We originally had a breaking change that made TaskHubName required in 2.0.0-alpha, but it was decided that this was too extreme. If you look at the [2.0.0-beta2 release notes](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.0.0-beta2) under "Misc Updates", we noted our restoration of default values for TaskHubName, but now to site names instead. That being said, it is very unreasonable for us to expect users upgrading from 1.x to 2.x to look through the breaking changes across all of our 2.0.0 prereleases, and this is something that should be more clearly documented in [our migration guide](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versions#migrate-from-1x-to-2x).

As far as the expected behavior, unfortunately the "look for old default as a backup" option is not feasibly possible, as Durable Functions is designed to work with only one TaskHub. However, I will definitely make the appropriate changes to our migration guide.

**Comment by ConnorMcMahon** [comment]
PR is [here](https://github.com/MicrosoftDocs/azure-docs-pr/pull/97738).

**Comment by OwenPattison** [comment]
@ConnorMcMahon thanks for the response and taking the steps to update the documentation.

**Comment by ConnorMcMahon** [comment]
Documentation change finally merged.
