### ISSUE TITLE
increase activity timeout

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-functions-durable-extension#1088]
Is there a way to increase the 30 min default timeout for an Activity?

**Comment by ConnorMcMahon** [comment]
Function timeouts are something that are globally configured in your host.json. You can see a handy chart of the timeout limitations [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout).

Considering you mentioned the default is 30 minutes, I am guessing that you are running on a dedicated App Service Plan. If that is the case, then you can configure your timeout as large as you want, by changing the value of `functionTimeout` in your host.json.

One caveat I would add to that is that having long running activity functions increases the chance that you will have to repeat work in the case where your function app stops unexpectedly.  For instance, if your app restarted 40 minutes into a 60 minute activity function execution, you would have to repeat all of that work again. If you break your activity function into 12 smaller pieces, each taking ~5 minutes, you at most have to repeat 5 minutes of work. Since you are running on a dedicated app service plan, application restarts should be far less frequent, but it is still something to consider.
