### ISSUE TITLE
Azure Durable Functions - Only 1 Control Queue keeps growing with messages

### ISSUE THREAD

**Issue by OTedikov** [Azure/azure-functions-durable-extension#1096]
I have application that uses Azure Durable Functions which has Orchestrator Functions (HTTP Trigger) and several Activities Functions (from 5 to 15) within this Orchestrator. Activities are being executed one after the other. I have configured host.json to have 12 Control Queues. 

For some period of time (week) Orchestrator Functions were executing correctly and number of messages in Control Queues were more or less equal. As of now I have 1 Queue with approximately 600 messages in it, and others have not more that 10-20. What can be the reason that only 1 Control Queue has its messages growing, while others not and how can I mitigate this?

**Comment by olitomlinson** [comment]
@OTedikov  What version of `Microsoft.Azure.WebJobs.Etensions.DurableTask` are you using?

I've recently had a scenario where one or more control queues were not being processed effectively due to a bug in a dependency of the Durable Task, which may be similar to what you're experiencing. 

Try following the official guidance here to see if this fix makes a difference for you https://github.com/Azure/azure-functions-durable-extension/issues/1059#issuecomment-556405631

**Comment by cgillum** [comment]
@OTedikov one thing to note about control queues is that a single orchestration has all of its _orchestration_ messages (activity function results, timer messages, etc.) go through a single queue. The specific queue used is computed using a hash function over the instance ID. So if you have one instance with a lot of messages being sent to it, all of those messages must go through a single control queue.  I'm mentioning this just in case the behavior you're seeing might be by design.

More information here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale
