### ISSUE TITLE
Azure Function App v2 Stops Working

### ISSUE THREAD

**Issue by tehmas** [Azure/azure-functions-durable-extension#1105]
Sometimes, Azure Function App v2 stops processing messages in queues. No function gets triggered when this happens. The function app starts to work again when I restart it.

Target Framework: .NET Core 2.2
Microsoft.Azure.WebJobs.Extensions.DurableTask: 1.7.1
Microsoft.Azure.WebJobs.Extensions.Storage: 3.0.3
Microsoft.NET.Sdk.Functions: 1.0.24
Microsoft.NETCore.App: 2.2.0
Newtonsoft.Json: 11.0.2
SqlBulkTools.NetStandard: 2.1.30
SqlBulkToolsCore: 1.0.3
StackExchange.Redis: 2.0.519
System.Data.SqlClient: 4.6.0
Z.BulkOperations: 3.0.0

The function app is using durable functions only.

**Comment by cgillum** [comment]
Hi @tehmas. I suggest you upgrade to a more recent version of Microsoft.Azure.WebJobs.Extensions.DurableTask, such as [1.8.3](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.8.3) or [2.0.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/2.0.0). We've made a lot of fixes since the 1.7.1 release.

**Comment by tehmas** [comment]
Thanks for the reply. I will update Microsoft.Azure.WebJobs.Extensions.DurableTask and open this issue if this happens again.
