### ISSUE TITLE
Entity Operation called too many times under load

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1131]
DF 2.1 
Consumption Plan
UK South

---

@cgillum I'm doing a load test of Entites and getting some unexpected results.

Given 3 Event types **G**, **N**, **D**

Each event is published to 10,000 entities using the `IDurableEntityClient` Proxy such like...

`client.SignalEntityAsync<IActor>(entityId, proxy => ...`

When handling an event inside the Entity, the last operation is to `signal` to a singleton aggregation Entity which keep a running total of how many instances of each event type has been received.

I expected that when I read back the entity state of the aggregation Entity, it would be :

`G = 10,000`
`N = 10,000`
`D = 10,000`

but what I'm actually seeing is : 

`G = 10,086`
`N = 10,111`
`D = 10,163`

---

I've added App Insights telemetry to my Entities so I could observe how many times each entity is processing an event by tracking a `customEvent` as the last operation when handling an event.

![image](https://user-images.githubusercontent.com/4224880/71605508-1efde800-2b61-11ea-848a-fcd890ee483e.png)

The results don't add up.

My assumption is that the entity state is being persisted, but the control queue message is not being completed, so it may be replayed thus running the method again causing downstream duplication of signals etc. Notice how the events are duplicated on another host

![image](https://user-images.githubusercontent.com/4224880/71605800-d4319f80-2b63-11ea-9c6c-eb285c4575e6.png)
---

Another thing that I've noticed is that the Function App appears to just stop processing for 10 minutes and then resumes. There is no user-code in the App that would explain this.

![image](https://user-images.githubusercontent.com/4224880/71604941-4fdc1e00-2b5d-11ea-9d26-9a7c6a7c1851.png)

--- 

I've ran the above test a few times now, I keep getting similar results so its not a one-off.

```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "MessagesTaskHub",
      "storageProvider": {
        "partitionCount": 4
      }
    }
  },
  "logging": {
    "logLevel": {
      "Function": "Warning",
      "Host" : "Warning"
    }
  }
}

```

Example execution ID of an entity that generated too many events  between the time of `12/30/2019, 9:20:11.826  UTC` and `12/30/2019, 9:27:11.624 PM`

`5c720ba8f91b4396912987555ac175db`

**Comment by cgillum** [comment]
My guess is that the partition movement is resulting in duplicate executions of your entity operations. There is a known issue here which tracks this: https://github.com/Azure/azure-functions-durable-extension/issues/382 (the issue originally only talked about activity functions, but entity function execution could also be duplicated). The fact that you see duplicates on different hosts supports this theory.

One question: when you observed this, did you detect any duplicated state in your entities? For example, if your entity keeps a list of all the operations it received, would that list contain any duplicates? Or is it just that you see multiple executions in App Insights but the state is persisted as if there wasn't any duplication? I ask because the entity scheduler is supposed to be doing some of it's own de-duplication which would prevent duplicate updates to entity state, but would not be sufficient for detecting split-brain scenarios where an entity with a common state are executed twice.

I don't have an explanation for the 10 minute window of silence. I'll need to spend some time debugging to see what could be causing that.

**Comment by olitomlinson** [comment]
To answer your question, the logic in the actor is like this when handling the** N** event : 

```
{
    stored_N_events.Add(N_event);

    if (stored_N_events.Count == 1)
    {
        //do some other logic like serialise this actor out to table storage for reporting

        _context.SignalEntity<IAggregator>(
            new EntityId(nameof(Aggregator), @N_event.BatchID),
            proxy => proxy.Increment(new List<AggregateOperation>()
            {
                new AggregateOperation()
                {
                    AmountToIncrement = 1,
                    Event = "N"
                }
            }));

        AppInsights.TrackEvent("MessageActor-N*******");
    }
}
```

This logic should store multiple events into the `stored_N_events` but only perform side-affects when receiving the first instance of that event.

Given that my `TrackEvent` is contained inside the branch, I would anticipate that I should get **at most one**  `customEvent` _providing_ that the Entity operation completes successfully and persists its state, but what I'm seeing is multiple N `CustomEvent`s in App Insights

What I'm seeing from the entity state in the `TaskHubInstances` table  Execution `5c720ba8f91b4396912987555ac175db` is despite receiving multiple N event in App Insights, I'm only seeing just _one_ object in `stored_N_events` list.

**Comment by olitomlinson** [comment]
Just spotted a correlation of the timestamps in App Insights vs the entity state

![image](https://user-images.githubusercontent.com/4224880/71617399-c820fe80-2bb2-11ea-82e8-26dd444529b8.png)

![image](https://user-images.githubusercontent.com/4224880/71617465-20f09700-2bb3-11ea-9bdf-c8201d1d4e61.png)

I don't know the significance of this, but thought it worth sharing just in case it helps.

**Comment by olitomlinson** [comment]
Did another test run, getting a similar delay between the work, although not 10 minutes in this instance, but 5.

![image](https://user-images.githubusercontent.com/4224880/71618717-cb1eed80-2bb8-11ea-93b6-5f6c34aa2a3b.png)

**Comment by olitomlinson** [comment]
Done another test with just 1 instance (not 10,000) and this really struggled to give an expected accurate result. 

I ended up with 5 **G** events instead of the expected just one.

![image](https://user-images.githubusercontent.com/4224880/71620987-b7798400-2bc4-11ea-8c09-b01eda1bc9c0.png)

Notice the very regular timing between the Entity re-processing the message, and making a signal to the aggregation Entity.

Execution ID `d13472078f66494c843231ad46a8e396`

**Comment by cgillum** [comment]
Based on what you described [here](https://github.com/Azure/azure-functions-durable-extension/issues/1131#issuecomment-569896669) it sounds like this could be the split brain problem described in #382, though I'll need to check and confirm. I do have a fix that I've been working on that should significantly reduce the resulting duplication. I'm hoping to sneak it into the v2.1.1 release.

I still need to investigate your other responses to see if there might be something else going on.

**Comment by olitomlinson** [comment]
@cgillum Thanks chris! Just holla' if you want me to test a pre-release etc.

**Comment by olitomlinson** [comment]
@cgillum great stuff! I will get on it tomorrow.

**Comment by cgillum** [comment]
Or you could just move to the 2.1.1 release (out yesterday, Redmond time). That defaults to the updated version of DurableTask.AzureStorage.

**Comment by olitomlinson** [comment]
@cgillum Using 2.1.1, there has been some improvement at low volumes.

It seems stable when aggregating small volumes (up to 500 events), however, around 1000 sometimes it is accurate, other times its not. 

Latest run reported this when aggregating 1000 events of type **G**,**N** and **D** :

```
{
  "entityExists": true,
  "entityState": {
    "g": 1034,
    "n": 1028,
    "d": 1021
  }
}

Unfortunately for my use-case as an aggregator/counter, I need 100% accuracy :(

**Comment by cgillum** [comment]
Hmm...that's concerning. Adding @sebastianburckhardt for FYI.

We can probably do specific work to improve this further, but I'm not sure if we can guarantee 100% given that we're building on top of an "at least once" messaging system. Would it be possible to do any de-duplication at the application layer - i.e. in your entity code? For example, if each of your operations included a unique identifier or a timestamp, could you use that for custom de-dup logic?

**Comment by sebastianburckhardt** [comment]
The `IDurableClient` is by design unreliable (for example, it cannot resume execution precisely where it left off after a machine failure), so complete guarantees are not possible when sending signals from `IDurableClient`. The situation is better with `IDurableOrchestrationClient` since we can resume it precisely - so we guarantee that signals sent from `IDurableOrchestrationClient` are delivered in order and exactly once. 

That said, I don't think you should be seeing what you are seeing. If the `IDurableClient` does not actually crash, messages should still be delivered exactly once. Perhaps there is another bug somewhere.

**Comment by cgillum** [comment]
@sebastianburckhardt my expectation is that this is caused by split-brains when rapidly adding or removing VM instances. Lease ownership changes can happen at any time in which case there are windows where two VMs are reading messages from the same queue. In those cases, I expect an entity can be running on two VMs at once, each with the exact same copy of its state. Only one of those instances will be able to actually save updates to its state, but both of them will be able to execute side-effects.

I'm just now realizing that this probably goes back to our discussion about the order of persistence in DurableTask.AzureStorage (history updates vs. message updates)....

**Comment by olitomlinson** [comment]
@cgillum 

If I was just aggregating a small amount of events, then sure I could maintain a list of processed event Ids (which in my case are GUIDs) and de-dupe in the entity itself, however in my use-case I will be aggregating between 10k - 100,000k events. My understanding of how Entities works is that it will be serializing and persisting an ever-growing list of IDs, which would be wasteful and not great for a performant design.

---

Anecdotally, it does seem like the integrity of the aggregator result improves if the App is warmed-up.

I've back-to-back tested the test scenarios from 250, 500, 750, 100, 1500, 2000, 5000 and interestingly they perform _better_ when the App is warm, perhaps over-counting just 1/2/3 in the 5000 scenario.

after 10-20 minutes of inactivity and do another test of 2000 and once again get very poor results.

I'm 95% convinced whether the App is warm or not has a large effect on the results....

**Comment by cgillum** [comment]
@olitomlinson I understand. It's a very imperfect workaround.

Your comments about improved integrity when the app is warm is consistent with my theory about what's going on. When the app is warmed up, it has likely finished scaling out and lease partition movement stops because everything is already balanced. At that point, the risk of split-brain drops to basically zero.

I think the two approaches we can take for permanently fixing this is either a) fundamentally changing the way we handle partition movement or b) changing the way we checkpoint state and side-effects.

**Comment by olitomlinson** [comment]
@cgillum  Great! Glad I could help you become more certain.

Either of those options sound like they involve considerable effort to remediate? I need to make a decision on wether to continue perusing this line of development or postpone for a few months and focus on something else. Where are you at priority-wise? Either is fine I just need to make a decision 👍🏻

**Comment by sebastianburckhardt** [comment]
It looks like a lot of issues have the same root cause: the way leases are managed. The algorithm in the Partition manager is really more of a load-balancing device than a precise lease management; it uses (optimistic) lease stealing and does not prevent the situation where multiple nodes think they own the same control queue (at least for some time, until they try to renew or release the lease). I think this can be improved; we can use another set of (pessimistic) leases to hand off control queues without overlap. 

I am planning to implement this algorithm for the new back-end anyway. It may be possible to backport the same logic to the current back-end.

**Comment by olitomlinson** [comment]
@cgillum What can you tell me about the "new back-end" that Sebastian has mentioned above? Is this something to replace Azure Storage?

**Comment by olitomlinson** [comment]
@cgillum Sorry to bump this again, but can I expect it getting fixed for 2.2.0 or are we looking further into the future? Either answer is fine, I just need to set some expectations. Many thanks!

**Comment by cgillum** [comment]
Sebastian and I discussed this further. We think we need to redesign how partitioning works in the Durable Task Framework storage backend in order to fix this problem. We don't have the resources to do this in time for 2.2 but it's the next big thing I want to focus on after that.

**Comment by olitomlinson** [comment]
@cgillum understood and much appreciated!

**Comment by olitomlinson** [comment]
@cgillum Just thought I would revist this on 2.2.0. As expected, this is still a problem.

Running the same code, I get some very weird behavior, particularly messages not processing straight away.

Here you can see the client-to-entity signals firing up every 10 seconds for a duration of approx 5 minutes, (whereby it processes 3 signals for 1 specific entity every 10 seconds) and then a peak of activity at the end.

![image](https://user-images.githubusercontent.com/4224880/78591305-25c08900-783b-11ea-8770-bf93fe546429.png)

I also observe in TaskHub Storage that many of the control queue messages have growing `Dequeue Count` properties, as though something is failing, but I see no exceptions in my logs that would hint towards why messages are being dequeued multiple times.

I know the solution here is to wait for the new back-end so I'm not expecting a solution, but here is the diagnosis for above if that helps :

UK South 
orchestration Id : @messageactor@359b1ac4-c3c5-4f0d-9a82-0d7b23515df9
execution Id : ec4082ae4c9e402bb2e8ee444c5000d3

**Comment by cgillum** [comment]
@ConnorMcMahon does Oliver's recent results resemble that weird slow-processing behavior we noticed in our scale tests since v2.0.0 and v1.8.4? (messages only being processed every N seconds)? I'm wondering if it could be the same root cause.

**Comment by ConnorMcMahon** [comment]
That does look very similar. I noticed that this pattern of execution only really happened when we bump up against the max value of PendingOrchestrationMessages. I'm not exactly sure why (could have to do with the sleep we do on prefetch operations when we hit the max), but I'm not convinced that is the entire root cause, or just part of the issue.

I am hoping the fix we made to pending orchestration message counts should at least partially mitigate this. I will run some load tests in the next day or two to see if the situation has improved at all.

**Comment by AdrianPell** [comment]
@cgillum Is this issue still open? I'm seeing some strange issues with durable entities which look to only be explained by a replay of messages. The only calls are coming from orchestrations which should also be reliable if I  understand correctly.

I'm just adding some more protective code in the entities to detect and ignore this, but it seems it ought to be unnecessary, right?

**Comment by sebastianburckhardt** [comment]
Yes, this ought to be unnecessary. We guarantee "effectively exactly-once" delivery of messages sent from orchestrators to entities.

Where "effectively" means that the total number of executions performed (e.g. as appearing in logging) could be more than once, but the effect of such executions on the entity state is exactly once, in the sense that the entity state is rolled back before receiving the same message again.

**Comment by sebastianburckhardt** [comment]
@olitomlinson, are you still experiencing this issue? It has been a while and there have been various fixes.

**Comment by olitomlinson** [comment]
@sebastianburckhardt 

It's been over 3 years since I raised this issue, and no longer work at the same org, so unfortunately I can't provide any insight.

If you need a quick repro, just spin up a bunch of Orchestrations which send signals to a singleton Entity, and the Entity simply aggregates those signals into a `count` (don't hand roll any event de-dupe logic in the Entity itself, let the framework do its thing). 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/4224880/219015336-8e235c1d-aa22-4635-b361-6480f3a49a66.png">

---

Personally, I would close it given how much time has passed, and that Netherite was always specified to be a better solution for this kind of work.
