### ISSUE TITLE
Old orchestration instances cannot be terminated

### ISSUE THREAD

**Issue by bobbytreed** [Azure/azure-functions-durable-extension#1192]
### Description
How do you terminate old running orchestration instances? Is there an executable I can kill? I removed an orchestration function called "ProcessMessage" 4 days ago, and every time I debug my cleaned fully built function I see the message:

The function 'ProcessMessage' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the known orchestrator functions: 'ProcessEvent'.. InstanceId: xxxxxxxxxxxxxxxxx. Function: ProcessMessage. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.1. SequenceNumber: 2.

I have even searched for that string all throughout my code and dlls and its' nowhere to be found.

### Expected behavior
I expect to be able to terminate function instances and have them remain terminated so I can test and debug.

### Actual behavior
The function 'ProcessMessage' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the known orchestrator functions: 'ProcessEvent'.. InstanceId: xxxxxxxxxxxxxxxxx. Function: ProcessMessage. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.1. SequenceNumber: 2.

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

Running locally

**Comment by cgillum** [comment]
This is because at one point you had a function with this name, tried to call it, and then changed your app before the associated messages could be consumed. The easy way to mitigate this is to clear all messages from your queues in Azure Storage (or delete the queues; they’ll get recreated automatically). Because executions are “durable”, they will survive across multiple debug sessions. 

More info here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#debugging

**Comment by bobbytreed** [comment]
Thank you for the response. Could I ask a follow up? How do the orchestration replays work.

**Comment by cgillum** [comment]
Sure. Take a look at our orchestration conceptual docs for information on orchestration replays: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations
