### ISSUE TITLE
Cannot terminate pending function instances

### ISSUE THREAD

**Issue by bobbytreed** [Azure/azure-functions-durable-extension#1193]
### Description
During local debugging I cannot manage to terminate old orchestration instances.

I am attempting to run a SINGLETON orchestration instances based on available documentation.

I consistently get the error message "A orchestration with that instance already existst" when executing StartAsync.

### Expected behavior
I execute TerminateInstances(below) with a blank string to find and terminate all instances before starting a new one.  I even return the running count so if the StartAsync STILL fails, I can append a count+1 to the instance id to at least not be blocked.

### Actual behavior
I want to understand how to properly terminate all instances in any state (waiting, pending, failed, etc).

### Relevant source code snippets
Code used to terminate ALL running instances because I am attempting a SINGLETON execution.

```csharp
 public static async Task<int> TerminateInstances([DurableClient]this IDurableOrchestrationClient starter, string instanceid = "")
        {
            IList<DurableOrchestrationStatus> instances = instances = await starter.GetStatusAsync(); // You can pass CancellationToken as a parameter.
            List<DurableOrchestrationStatus> runningInstance = instances.Where(e => (!String.IsNullOrWhiteSpace(instanceid) && e.InstanceId == instanceid)
                                                                                    && (e.RuntimeStatus != OrchestrationRuntimeStatus.Terminated
                                                                                    && e.RuntimeStatus != OrchestrationRuntimeStatus.Failed)).ToList();

            foreach (DurableOrchestrationStatus running in runningInstance)
            {
                try
                {
                    await starter.TerminateAsync(running.InstanceId, "None");
                }
                catch (Exception inner)
                {
                    throw inner;
                }
            }

            return runningInstance.Count();
        }
```
### Known workarounds
Above code.

### App Details

running locally.

**Comment by cgillum** [comment]
Sorry for the delayed response on this. If I'm understanding correctly, the problem is that you're not waiting for the instances to transition into the Terminated state before starting new instances.  I see that the documentation is not clear about the behavior of `TerminateAsync`, so I'm taking a note to update this.

Essentially, you need to check the status of the terminated instances and wait for them to stop running before you can start new ones. Here is a code sample that might be helpful. It currently terminates all running instances.

```csharp
public static async Task<int> TerminateInstances(
    [DurableClient]this IDurableOrchestrationClient starter)
{
    // Query for all running instances
    OrchestrationStatusQueryResult result = await starter.GetStatusAsync(
        new OrchestrationStatusQueryCondition
        {
            RuntimeStatus = new[]
        {
            OrchestrationRuntimeStatus.Pending,
            OrchestrationRuntimeStatus.Running,
        }
        },
        CancellationToken.None);

    // Make a hash set to track all instances we got back
    var running = new HashSet<string>(result.DurableOrchestrationState.Select(s => s.InstanceId));
    int instanceCount = running.Count;

    // Send terminate commands to all instances in parallel
    var terminateTasks = new List<Task>();
    foreach (string instanceId in running)
    {
        terminateTasks.Add(starter.TerminateAsync(instanceId, "None"));
    }

    await Task.WhenAll(terminateTasks);

    // Wait for the orchestrations to actually terminate
    while (true)
    {
        // Query all "running" instances in parallel
        DurableOrchestrationStatus[] results = await Task.WhenAll(
            running.Select(id => starter.GetStatusAsync(id)));

        foreach (DurableOrchestrationStatus status in results)
        {
            // Remove any terminated or completed instances from the hashset
            if (status != null &&
                status.RuntimeStatus != OrchestrationRuntimeStatus.Pending &&
                status.RuntimeStatus != OrchestrationRuntimeStatus.Running)
            {
                running.Remove(status.InstanceId);
            }
        }

        // We are done once the HashSet has no more items in it
        if (running.Count == 0)
        {
            break;
        }

        // Still waiting for some instances to complete
        await Task.Delay(TimeSpan.FromSeconds(1));
    }

    return instanceCount;
}
```

**Comment by cgillum** [comment]
I've submitted an update to the [Instance Management](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#terminate-instances) topic for Durable Functions as well as the [TerminateAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.terminateasync?view=azure-dotnet) API reference documentation to clarify this behavior.

Thanks for opening this issue to draw our attention to this point of confusion. Let me know if this information and code sample is helpful for you.

**Comment by StephenQuirolgico** [comment]
@cgillum Hi Chris. I'm developing a Python Durable Function and I have similar questions:
- Is it possible to turn off (or opt out of) replay, at least during development/debugging? Having a replay start running while you are developing/debugging significantly complicates things for the developer. 
- In Python, how can we get a list of all existing instance IDs and is there an easy to terminate (actually, delete) them before creating a new durable orchestration client (i.e., client = df.DurableOrchestrationClient(starter))? What I want to do is terminate all existing instances before creating a new one. 
- In my code, I am using client.purge_instance_history(instance_id). Does this actually delete the instance, or does it delete something else? I want to delete the instance to prevent a replay.
- Currently, I am having to manually log into the Azure portal and delete everything in my Storage before I can get Replay to stop. At the moment, however, Azure is incorrectly saying I don't have any Storage and is not showing my storage files so I can delete them. Oddly, a Replay of old data is still occurring for me locally even though the portal says I have no storage 
- Under what circumstances does a replay occur? If I write a Durable Function that throws an exception and does not complete, is that replayed? If so, why? 
- It would be good if Azure could provide an option to turn off replaying of previous instances. Its not clear to me that this is really valuable in all use-cases, but I can't really tell from the documentation.

**Comment by cgillum** [comment]
Hi @StephenQuirolgico. Usually it's best to open new issues rather than responding to closed ones. That makes it easier for us to track things and ensures folks don't get notifications if they don't want them. However, still happy to answer questions:

> Is it possible to turn off (or opt out of) replay, at least during development/debugging?

Unfortunately this is not currently possible with Python. We need to change the way we implement out-of-process language handling in order to do this, which is on our radar but we don't have a concrete timeline yet.

> In Python, how can we get a list of all existing instance IDs and is there an easy to terminate (actually, delete) them before creating a new durable orchestration client (i.e., client = df.DurableOrchestrationClient(starter))?

Yes, you should be able to use our [instance management APIs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=python) to enumerate and terminate any existing instances. Or, if you just want to kill everything and start from scratch, you can either delete the underlying Azure Storage artifacts (queues/tables/blobs) or change the name of your task hub in host.json to create a new set of storage artifacts the next time your app starts up. If you're developing on Windows and using the Azure Storage Emulator, then you can use the Azure Storage Emulator to delete all storage artifacts in a single command. If all you want to do is stop replays, then you can just delete the control queues. Everything will be recreated automatically the next time your app starts up.

> In my code, I am using client.purge_instance_history(instance_id). Does this actually delete the instance, or does it delete something else? I want to delete the instance to prevent a replay.

This actually deletes the data in Azure Storage. However, the instance needs to be in a non-running state in order for it to work. If it's still running and replaying, then you'll need to terminate it first or let it complete/fail.

> Currently, I am having to manually log into the Azure portal and delete everything in my Storage before I can get Replay to stop. At the moment, however, Azure is incorrectly saying I don't have any Storage and is not showing my storage files so I can delete them. Oddly, a Replay of old data is still occurring for me locally even though the portal says I have no storage.

That's odd. I wonder if you're looking at the wrong subscription? Instead of logging into the Azure Portal, I recommend you use the [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) desktop tool. You can just use your connection string to access your account from there.

> Under what circumstances does a replay occur? If I write a Durable Function that throws an exception and does not complete, is that replayed? If so, why?

If you throw an exception in the orchestrator function, then there shouldn't be any replays after that. If you throw it from an activity function, then the orchestrator function will replay once more until it observes the exception and fails.

> It would be good if Azure could provide an option to turn off replaying of previous instances. Its not clear to me that this is really valuable in all use-cases, but I can't really tell from the documentation.

We support this for .NET apps but unfortunately not yet for JavaScript and Python apps. It's something we're working towards. The main benefits of having it enabled are 1) it's easier for you to find accidental non-determinism errors during development and 2) there is less memory overhead for your app because it can aggressively unload orchestrations that are waiting for inputs.

**Comment by StephenQuirolgico** [comment]
Thank you, Chris. This is very helpful!

**Comment by cargilltay** [comment]
Hey Chris we're also encountering a use case for full termination of all orchestrations on a project I'm working on. The scenario is the following:

1. A HTTP trigger hit. 
2. A config is pulled which contains N number of routes.
3. An orchestration is started for each route. Each route restarts itself upon completion via `ContinueAsNew`. 

**What we're trying to do:**
Hit the same HTTP endpoint and teardown all executions, clear all history, clear all queues, and then start fresh with a new config.

**What we're running into:**
Doing a looped approach for termination takes too long for us. Local it seems to work after many minutes. Deployed we both hit the HTTP timeout limit on HTTP Triggers & other timeout limits on queues when we tried to offload this work to a queue. 

Is it possible to accomplish the scenario I just described in an easy manner? Turning off the function app and deleting the storage tables/queues takes no time at all so I'd imagine a complete stop & clear must be feasible in code.

**Comment by cgillum** [comment]
Hey @cargilltay, would you mind asking this in the [Discussions section](https://github.com/Azure/azure-functions-durable-extension/discussions)? I have thoughts on this but it might make more sense to discuss somewhere other than in a closed issue (which is too easy to lose track of).
