### ISSUE TITLE
Input Parameter value in IDurableOrchestrationContext is always null after upgrading the Microsoft.Azure.WebJobs.Extensions.DurableTask package from 1.8.3 to 2.1.1

### ISSUE THREAD

**Issue by SailajaS** [Azure/azure-functions-durable-extension#1199]
### Description
Input Parameter value in IDurableOrchestrationContext is always null after upgrading the Microsoft.Azure.WebJobs.Extensions.DurableTask package from 1.8.3 to 2.1.1

### Expected behavior
Passing in the input parameter as a string value when creating an instance. So that the IDurableOrchestrationContext context should have that value.

### Actual behavior
 The input parameter value is always null.

### Relevant source code snippets
A code snippnet that creates the instance with input parameter CompanyID(string value)
var instanceId = await DurableClient.StartNewAsync(nameof(CompleteOrchestrator), CompanyID);

A code snippet that gets the value from the Context
Context.GetInput<string>()

### App Details
- Durable Functions extension version (e.g. v1.8.3)**: V2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: V3
- **Programming language used**: ASP NET Core 3.1

- **Orchestration instance ID(s)**: 01E0B2NFN4PT4DZJAECN176NK5

**Comment by ConnorMcMahon** [comment]
This is expected behavior. We made a breaking change in the API surface of StartNewAsync() in 2.0 release.

In your example, CompanyID is being used as the instance id, not as the input, due to the extension method signature

```csharp
        public static Task<string> StartNewAsync(
            this IDurableOrchestrationClient client,
            string orchestratorFunctionName,
            string instanceId)
```

If you do not want to set your own instance id, you can use our extension method with the following signature:

```csharp
        public static Task<string> StartNewAsync<T>(
            this IDurableOrchestrationClient client,
            string orchestratorFunctionName,
            T input)
```

In this case, your code should look like the following:
```csharp
var instanceId = await DurableClient.StartNewAsync<string>(
    nameof(CompleteOrchestrator),
    CompanyID);
```

or

```csharp
var instanceId = await DurableClient.StartNewAsync(
    nameof(CompleteOrchestrator),
    input: CompanyID);
```

Either way, C# will now recognize your second parameter is meant to be the input. You can tell by hovering over the code you wrote and seeing which method signature Intellisense provides you.
