### ISSUE TITLE
Durable Orchestration Client/Triggers aren't part of generated function.json in VS2017; execution fails

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#120]
When using the Visual Studio 2017 Functions Tools, creating an Azure Functions v2 Durable Function results in a failure at runtime due to a malformed function.json file which doesn't contain the correct binding information for the `OrchestrationTrigger` or `OrchestrationClient` objects in the function signature
#### Repro steps

Provide the steps required to reproduce the problem
1. Create a new Azure Function v2 Project in VS2017.15.5.2 with Azure Functions and Web Jobs Tools v15.0.31201.0
1. Select HTTPTrigger as the function type
1. Update the Webjobs nuget package to v1.0.7
1. Add the [Microsoft.Azure.WebJobs.extensions.DurableTask v1.1.0-beta2](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.1.0-beta2) nuget package to the project
1. Change the code for the Function created from step 2 to:
```csharp
[FunctionName("Function1")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequestMessage req, [OrchestrationClient]DurableOrchestrationClient starter, TraceWriter log)
{
    return new HttpResponseMessage(HttpStatusCode.OK);
}
```
6. Hit F5

#### Expected behavior

The Functions runtime executes in .Net Core (dotnet.exe) and gives me the URL to hit for the created Durable Function.

#### Actual behavior

Functions runtime spits out errors like:
~~~
[1/3/2018 11:21:16 PM] ScriptHost initialization failed
[1/3/2018 11:21:16 PM] System.Private.CoreLib: 'TriggerHandlesReturnValue' property specified was not found.
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Object reference not set to an instance of an object.
~~~

Upon further investigation one can find the generated `function.json` file in bin\debug\netstandard2.0\Function1 and see it's missing the binding for the `OrchestratorClient` object:
```js
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.7",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "post"
      ],
      "authLevel": "function",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/AzureFunctions.Durable.dll",
  "entryPoint": "AzureFunctions.Durable.Orchestrator.Run"
}
```

Changing the Function code to:
```csharp
[FunctionName("Function1")]
public static void Run([OrchestrationTrigger]DurableOrchestrationClient starter, TraceWriter log)
{
    return;
}
```
will generate the exepected values in `function.json` of:
```js
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.7",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "orchestrationTrigger",
      "name": "starter"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/FunctionApp1.dll",
  "entryPoint": "FunctionApp1.Function1.Run"
}
```
but the same errors occur during runtime.

**Comment by cgillum** [comment]
Thanks for opening this detailed issue. I'll follow up with the tooling team to see what might be going on.

**Comment by brandonh-msft** [comment]
*Workaround*
Downgrade `Microsoft.Azure.WebJobs.Extensions.DurableTask` to v1.0.0-beta and `Microsoft.NET.Sdk.Functions` to v1.0.6

Functions runtime executes project w/o issue in this state.

**Comment by cgillum** [comment]
Using your setup, I was able to workaround the issue by simply downgrading the `Microsoft.Azure.WebJobs.Extensions.DurableTask` to **v1.0.0-beta**. It didn't matter which version of `Microsoft.NET.Sdk.Functions` I used. Note that I had to do a clean build in between tests because it seems not everything gets cleaned up properly between regular builds.

I think the root of the problem is that VS runs a particular version of the Functions CLI, and that CLI targets a specific version of the Functions runtime, which may be different from the version required by the extension. I used the _Modules_ window in Visual Studio to locate all the loaded assemblies and made this determination. The runtime assemblies are under **%LOCALAPPDATA%\2.0.1-beta\**. From what I can tell, these are the "3.0.0**-beta3**" versions of the WebJobs runtime (the latest Durable Functions release requires 3.0.0-**beta4**).

If this is all true, then I think the proper fix is to have a new version of the CLI released which takes a dependency on the latest version of the Functions runtime bits. 1.0.7 is loading an older runtime.

**Comment by brandonh-msft** [comment]
related to your needing to do clean builds, I filed a bug for this longtime annoyance of mine w/ the VS 2017 extension [here](https://github.com/Azure/azure-webjobs-sdk/issues/1494) ;)

**Comment by kashimiz** [comment]
This is related to Azure/Azure-Functions#625, where the Functions V2 CLI version is bound to the version of the VS Functions extension installed. A v2 HttpTrigger on SDK 1.0.7 works if you force the project to use the latest Functions V2 CLI by following the [workaround](https://github.com/Azure/Azure-Functions/issues/625) I posted in that issue.
