### ISSUE TITLE
Document custom message/error serialization capabilities

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1208]
In the 2.1 release, we introduced the DI-compatible `IMessageSerializerSettingsFactory` and `IErrorSerializerSettingsFactory`. There are many serialization issues that pop up on the repo, and we should probably have a single source of official documentation to point customers to.

**Comment by rameshjanjyam** [comment]
just checking if there is documentation on how to use this interface. unless I am not doing it wrong, it is becoming painful to handle exceptions like this 
```
 if (exceptionMsg.Contains("Microsoft.Rest.Azure.CloudException") && exceptionMsg.Contains("\"StatusCode\":404"))
```

**Comment by ConnorMcMahon** [comment]
@rameshjanjyam 

There still is not official documentation. That beings said, @anthonychu described how to use the `IMessageSerializerSettingsFactory` interface in [this stack overflow answer](https://stackoverflow.com/a/60424415/9035640). The `IErrorSerializerSettingsFactory` should work in an identical manner, but only be applied to exceptions.

**Comment by rameshjanjyam** [comment]
thank you @ConnorMcMahon  I will verify that post

**Comment by ConnorMcMahon** [comment]
This is now documented properly.

**Comment by FFranz93** [comment]
Sorry that I have to ask again even this issue was closed over 2 years ago, but where is this documented?
In the official MS documentation for [Handling errors in Durable Functions](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp-inproc) there are no capabilities mentioned (like which types of exceptions can be serialized by default, which can not be serialized and how to handle that).

I'm still running into the same problem as mentioned in #1453. Sure I could just use an exception type that is more friendly to serialization or inject a custom `IErrorSerializerSettingsFactory`, but it would be nice to have an overview of the serialization capabilities, as well as exception types that are serializeable and those who are not with a simple example on how to handle unserializeable exception types (there don't seem to be many examples out there).
