### ISSUE TITLE
If taskhub name not provided, and site name starts with a number, default task hub is invalid

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-functions-durable-extension#1210]
### Description
Azure Durable Function after deployment shows following error message that didn't help to troubleshoot it.

"The function runtime is unable to start. Microsoft.WindowsAzure.Storage: Invalid table name."
Table name - didn't not specified in an exception test. 

### Expected behavior
Application is up and running

### Actual behavior
Error message

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
Unknown

### App Details

    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.12.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
- C#

### Screenshots
![image](https://user-images.githubusercontent.com/578954/74230582-bd8b7600-4cd5-11ea-9d39-890dca988344.png)

Storage account exist and table exist
![image](https://user-images.githubusercontent.com/578954/74229784-1b1ec300-4cd4-11ea-8ba1-c017b40d9c4e.png)
I even try to explicitly specify connection name in a host file, but it didn't help 
![image](https://user-images.githubusercontent.com/578954/74229857-46091700-4cd4-11ea-9bb1-a76e6c51c69d.png)
Application itself is up and running 
![image](https://user-images.githubusercontent.com/578954/74229917-633de580-4cd4-11ea-8e30-c4b1c62b2b41.png)
Account names specified by VS 
![image](https://user-images.githubusercontent.com/578954/74230011-8d8fa300-4cd4-11ea-8bb6-ace572c59386.png)

If I will directly call http trigger- I will receive 
![image](https://user-images.githubusercontent.com/578954/74230551-a64c8880-4cd5-11ea-99e5-ae06beefa800.png)

### If deployed to Azure
It deployed, but don't want to disclose

**Comment by ConnorMcMahon** [comment]
So when you do not specify a taskhub, we pick one for you based on your site name.

We strip all non-alphanumeric characters, and we strip the length down to 45 characters. This way it passes all of the naming requirements for the objects in storage we create.

Unfortunately, it turns out that there is an [additional requirement](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage) for Table storage that I did not realize. It MUST start with a letter.

In your case, since your application name starts with a number, the default task hub name we create for you is invalid for table storage. I would recommend setting a taskhub manually, and that will mitigate for you.

We will have to come up with a fix for default task hub names in this scenario.

**Comment by SychevIgor** [comment]
Interesting, my storage account starts from "3". Name was generated by visual studio 2019 "deploy". Maybe Microsoft could speak with Visual Studio team and fix the name generation rules? 

![image](https://user-images.githubusercontent.com/578954/74405665-b5027f00-4e3e-11ea-8fbf-2aab6c29adff.png)
![image](https://user-images.githubusercontent.com/578954/74405727-e1b69680-4e3e-11ea-878d-6e3968649ca4.png)

**Comment by ConnorMcMahon** [comment]
@SychevIgor,

To clarify, the issue is not with storage accounts starting with a number.

In Durable Functions, we have the notion of a [TaskHub](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs?tabs=csharp), which is essentially a prefix-based naming convention for the object we create in Azure Storage (i.e. the queues, tables, and blobs). If you do not provide one, we default to use your application name. However, it turns out that for Azure Tables, we cannot create a table that starts with a number, hence the issue.

You can override the default task hub name by setting it in the host.json, which will mitigate the issue for you. We will make improvements to ensure that the default task hub name we generate is always valid.

**Comment by SychevIgor** [comment]
@ConnorMcMahon thank you. will try this workaround. 
P.S. but still, I would expect that VS will respect this specific.

**Comment by ConnorMcMahon** [comment]
This fix will go out in 2.2.0.

Note that this will only fix the issue at runtime. The scaling infrastructure still does not know about this new default value, so if you are using consumption function apps I would still highly recommend providing a TaskHub.
