### ISSUE TITLE
Support for declarative binding expressions

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-durable-extension#123]
With normal Azure Functions, I'm able to bind to do some nice declarative work:

        [FunctionName("InjestAndProcessFile")]
        public static async Task Run(
            [BlobTrigger("test/{name}")] Stream input, 
            string name,
            [Blob("archive/0/test/{name}", FileAccess.Write)] Stream output)
        {
            Console.WriteLine($"Archiving {name}...");
            await input.CopyToAsync(output);
        }

However, if I wanted to use Durable Functions, I have to switch an imperative model, which is much noisier:

        [FunctionName("InjestFile")]
        public static async Task Run(
            [BlobTrigger("test/{name}")] Stream input,    // BlobTrigger is required, but the stream is useless here
            string name,
            [OrchestrationClient] DurableOrchestrationClient starter)
        {
            await starter.StartNewAsync("ProcessFile", name);
        }

        [FunctionName("ProcessFile")]
        public static async Task Run(
            [OrchestrationTrigger] DurableOrchestrationContext context,
            IBinder binder)
        {
            var name = context.GetInput<string>();
            using (var input = await binder.BindAsync<Stream>(new BlobAttribute($"test/{name}", FileAccess.Read)))    // For some reason I'm getting an error here: "Cannot access a disposed object"
            using (var output = await binder.BindAsync<Stream>(new BlobAttribute($"archive/0/test/{name}", FileAccess.Write)))
            {
                Console.WriteLine($"Archiving {name}...");
                await input.CopyToAsync(output);
            }
        }

This is just one sample off the top of my head, but you can see how quickly the existing bindings are pushed aside to make way for the Orchestration bindings. Is there anything that can be done to preserve  the existing bindings while still using Durable Functions. The bindings are such a great feature of Azure Functions and I'd like to see them continue to shine.

**Comment by cgillum** [comment]
I'm not sure this is a valid sample. For one, your orchestrator function is doing I/O which is not allowed (I/O should only be done from activity functions). But more importantly, this example doesn't leverage any of the orchestration capabilities of Durable Functions.

To your point about declarative bindings, your example specifically takes advantage of a feature of blob triggers, which is that you can bind to the name of a blob. With activity triggers in durable functions, there really isn't any metadata that you can bind to since the data being passed around is just raw data from function to function. In that sense, declarative input bindings don't really apply to orchestration scenarios. 

Let me know if you have any other thoughts or questions related to this.

**Comment by cgillum** [comment]
@MikeStall what are your thoughts on this? Do you think there is a way to make binding expressions work in Durable Functions, similar to how the work with queue or blob triggers? It's very possible that I'm missing something.

**Comment by MikeStall** [comment]
@MisinformedDNA  - can you update your sample given @cgillum 's feedback? What would you like to be able to write?  

While Orchestration's shouldn't have any I/O bindings, Activities could. I think we could reasonably support binding expressions with Activity Triggers - the challenge is just where does the binding data come from? For example, it's be pretty easy to have the activity trigger populate binding data based on it's incoming JObject, similar to how a Queue trigger does for pocos.

**Comment by MisinformedDNA** [comment]
Thanks @cgillum. That explains the runtime errors. (Added issue #124), 

Here's a version that compiles

        [FunctionName("InjestFile")]
        public static async Task Run(
            [BlobTrigger("test/{name}")] Stream input,
            string name,
            [OrchestrationClient] DurableOrchestrationClient starter)
        {
            await starter.StartNewAsync("ProcessFile", name);
        }

        [FunctionName("ProcessFile")]
        public static async Task Run(
            [OrchestrationTrigger] DurableOrchestrationContext context)
        {
            var name = context.GetInput<string>();
            await context.CallActivityAsync("CopyFile", name);
        }

        [FunctionName("CopyFile")]
        public static async Task Run2(
            [ActivityTrigger] DurableActivityContext context,
            IBinder binder)
        {
            var name = context.GetInput<string>();
            using (var input = await binder.BindAsync<Stream>(new BlobAttribute($"test/{name}", FileAccess.Read)))
            using (var output = await binder.BindAsync<Stream>(new BlobAttribute($"archive/1/test/{name}", FileAccess.Write)))
            {
                Console.WriteLine($"Archiving {name}...");
                await input.CopyToAsync(output);
            }
        }

And, ideally, I'd like the last function to look like this:

        [FunctionName("CopyFile")]
        public static async Task Run3(
            [ActivityTrigger] DurableActivityContext context,
            string name,    // Derived from context.GetInput<T>()
            [Blob("test/{name}", FileAccess.Read)] Stream input,
            [Blob("archive/1/{name}", FileAccess.Write)] Stream output)
        {
            Console.WriteLine($"Archiving {name}...");
            await input.CopyToAsync(output);
        }

**Comment by MikeStall** [comment]
@cgillum  - I think the update would be here: https://github.com/Azure/azure-functions-durable-extension/blob/730133ae9c31a4a25842c92dabad0a55b26b6784/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L93 
Instead of a Static Contract, include the Activity's JObject properties in the contract. This is similar to what QueueTrigger does (see https://github.com/Azure/azure-webjobs-sdk/blob/73127679089e244a4fe25fe321bda8114b153878/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingDataProvider.cs )

**Comment by cgillum** [comment]
@MikeStall How do you know what the JObject fields are at function indexing time? I see how I can use reflection to build the contract for POCOs, but I don't see how this can be done for JObject.

**Comment by MikeStall** [comment]
@cgillum - you're right. queue is using a strongly typed POCO and not just a JObject, so it can reflect over the properties. Although we could do something like what HttpTrigger does  ... only the top-level properties need to be strongly known, you can use dot expressions  `{request.query.param1}` which can refer into jobjects and be loosely typed. So maybe we can do something like that? The top property would be fixed, give it a generic name like 'data'.  So `{data}` would refer to the JObject, and  `{data.prop1}` would be prop1 on the jobject.

**Comment by cgillum** [comment]
The `{data}` idea is interesting, but if a user tries to bind to `{data.prop1}`, won't that fail because `{data.prop1}` isn't defined in the contract?

It seems like HttpTrigger can bind to names defined in the route template, which is nice, but I didn't see how to bind to parameters or payload content that is only known at runtime ([reference](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/60629201329d9b7b07458dcc8b7dc0bc41888754/src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs#L225)).

**Comment by MikeStall** [comment]
@cgillum  - In this approach, the contract would define {data} for JObject.  This is like what http trigger does.  The tests have some examples of this in action: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/60629201329d9b7b07458dcc8b7dc0bc41888754/test/WebJobs.Extensions.Tests/Extensions/Http/HttpTriggerBindingTests.cs#L116

**Comment by cgillum** [comment]
@MikeStall Oh - so it just works!

I did what you suggested and simply added `data` to the contract when I see a `JObject` parameter type. I was able to successfully bind to a blob named `container/{data.Foo}` using a `JObject` as the activity function input containing the text `{"Foo","MyBlobName"}. So it looks like WebJobs implements the dot-resolution for me. I thought i was going to have to do that myself.  

Awesome!! I'll send out a PR tomorrow. Thanks for the after-hours help!! :)
