### ISSUE TITLE
Orchestration instance started stuck in pending status.

### ISSUE THREAD

**Issue by Muhammad-Bilal-Gits** [Azure/azure-functions-durable-extension#1252]
**Description**
Durable functions are getting stuck in the pending state for long long time, and this behavior is not permanent. Sometime orchestration function is running as expected and sometimes they are getting stuck in pending state and then magically starting. I getting this behavior in local mode when running from visual studio as well as when deployed to Azure.

**Expected behavior**
They should run normally without getting stuck in pending state. 

**Actual behavior**
Sometime they get stuck and then magically starting. And sometimes they do not stuck.

**App Config**
Azure Functions Version: V2
Microsoft.Azure.WebJobs.Extensions.DurableTask Version=1.7.1
Microsoft.NET.Sdk.Functions Version=1.0.29
Snowflake.Data Version=1.1.1

**App Details**
Timestamp: 2020-03-03T11:51:33.866Z
Function App Name: SnowflakeDurableFunctionApp
Region: East US 2
Orchestration ID: d01fad4a08874e6fb359311b0060df48
Storage Account Name: bswas

More Information can be provided if needed.

**Comment by Muhammad-Bilal-Gits** [comment]
@cgillum 
Can you please give it a look.

**Comment by ConnorMcMahon** [comment]
@Muhammad-Bilal-Gits 

At this point, we have made many fixes to reliability around stuck pending/running orchestration instances. If it is at all possible, could you try upgrading to 1.8.5 and see if you are still getting stuck orchestrations? 

It should be very safe to upgrade to 1.8.5, as we have made no breaking changes in the releases from 1.7.1 -> 1.8.5

**Comment by Muhammad-Bilal-Gits** [comment]
Apologies for late reply as I was off work, So as @ConnorMcMahon suggested I updated my nugets in such a way:

Azure Functions Version: V2
Microsoft.Azure.WebJobs.Extensions.DurableTask Version: From v1.7.1 to v2.1.1
Microsoft.NET.Sdk.Functions Version: From v1.0.29 to v1.0.31
Microsoft.NETCore.App: v2.1.0
Microsoft.Azure.WebJobs.Extensions: v3.0.6  -- Added this additionally because of this error as reported: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/607

Current Finding with updated nugets:
My local and azure runs are going perfect and orchestrator is going into pending state.

@ConnorMcMahon want to know is it safe to switch to v3.0.5 from v1.0.31 because v1.0.31 seems too old (correct me if I am wrong), are there any breaking changes or not.

**Comment by spzSource** [comment]
Hi @ConnorMcMahon 

Unfortunately I've got the issue even with fix [#347](https://github.com/Azure/durabletask/pull/347) in place. In overall this is only single case I've observed for a long time, which means that the issue happens not so frequent as before.

The code is pretty much the same as was described [here](https://github.com/Azure/azure-functions-durable-extension/issues/1020):

```cs
        [FunctionName(nameof(CheckAvailableSqlBatchesTimer))]
        public async Task Run(
            [TimerTrigger("%DataLakeMigrationSchedule%")] TimerInfo timer,
            [DurableClient] IDurableOrchestrationClient client)
        {
            const string instanceId = nameof(MigrateBatchesOrchestrator);
            var instance = await client.GetStatusAsync(instanceId);

            if (instance == null || !(instance.RuntimeStatus == OrchestrationRuntimeStatus.Pending ||
                instance.RuntimeStatus == OrchestrationRuntimeStatus.Running ||
                instance.RuntimeStatus == OrchestrationRuntimeStatus.ContinuedAsNew))
            {
                await client.StartNewAsync(
                    nameof(MigrateBatchesOrchestrator),
                    instanceId);
            }
            else
            {
                _telemetry.TrackTrace(
                    $"{nameof(MigrateBatchesOrchestrator)} function execution was skipped, " +
                    "as there is another instance running.");
            }
        }
```

In that particular case the function `MigrateBatchesOrchestrator` stuck on `Running` state.

**Correlation information:**
_InstanceId:_ MigrateBatchesOrchestrator
_Region:_ NorthEurope
_Function app name:_ faneurjatcsl12cmnrsrce
_Time-frame issue observed (UTC):_ 2020-03-17T22:50:00.010Z - 2020-03-17T22:57:00.010Z

**Records from DurableFunctionsHubInstances table:**
| PartitionKey  |  RowKey | Timestamp | CreatedTime  | ExecutionId  | Input  | LastUpdateTime  | Name  |  RuntimeStatus |
|---|---|---|---|---|---|---|---|---|
|  MigrateBatchesOrchestrator |   |  2020-03-17T22:54:00.2321979Z |  2020-03-17T22:54:00.1585313Z | a739fd6bcbf04db0b7d624f3c62e7c85 |  null |  2020-03-17T22:54:00.2127342Z |  MigrateBatchesOrchestrator | Running | 

**Dependencies:**
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.1.0
Microsoft.Azure.DurableTask.AzureStorage 1.7.0
Microsoft.Azure.DurableTask.Core 2.2.0
Functions Runtime v3
.NET Runtime: NET Core 3.1

Please let me know if additional information required. I'm happy to assist.

**Comment by ConnorMcMahon** [comment]
Will take a look at your instance in our telemetry @spzSource. Glad to hear it is at least happening less frequently!

**Comment by ConnorMcMahon** [comment]
@spzSource 

Sorry for the delay here, got distracted by on-call responsibilities.

So this is the timeline that caused this glitch.

2020-03-17 22:54:00.1812289: Execution scheduled
2020-03-17 22:54:00.2268718: First execution finishes, we update instance history and set status to pending
2020-03-17 22:54:00.4091354: The second execution finishes and updates the instance history. The orchestration execution should be completed at this point.
2020-03-17 22:54:27.6364705: The Storage SDK throws the following exception when trying to update the execution status table

```
Microsoft.WindowsAzure.Storage.StorageException: Service Unavailable
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1056
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 901
Request Information
RequestID:****************
RequestDate:Tue, 17 Mar 2020 22:54:27 GMT
StatusMessage:Service Unavailable
ErrorCode:
ErrorMessage:The server is busy.
RequestId:*****************
Time:2020-03-17T22:54:27.5424792Z
```

2020-03-17 22:54:27.6717613: Because of the failure to update the instance status table, we abandon the control queue message to try reprocessing the whole orchestration message after a timeout.
2020-03-17 22:54:49.5920298: We receive the message again to reprocess it again.
2020-03-17 22:54:49.6359876: We detect that the instance is completed, because we have rebuilt the orchestration state locally from the instance history. Because the orchestration is already complete, we refuse to reprocess the event. We discard the message, leaving the orchestration instance perpetually in the pending state.

In general, this bug was due to the failure happening right in-between when we update the instance history and when we update the orchestration status, and due to the fact that this happened on the final replay. Without all of those conditions being met, this would not have happened.

I will have to think about the best way to handle this specific case. Note that this will likely take slightly lower priority than it did before, as the chances of these circumstances happening is very rare.

**Comment by spzSource** [comment]
Hi @ConnorMcMahon 

Thanks you for the time you've spent for investigating the issue. Much appreciated. Anyway I'll keep eye on my production service.

Low priority for the issue is understood, so I'm trying to find a plan B. Based on code I've attached above, can you confirm that the issue will be solved if I rewrite the code in favor of using Eternal orchestrator?

**Comment by AlessandroH** [comment]
Hi,
we faced the same issue but systematically and in production;
Durable functions are getting stuck in the pending state for long long time.
These are our versions:
Azure Functions Version: V2
Microsoft.Azure.WebJobs.Extensions.DurableTask   2.2.1
Microsoft.NET.Sdk.Functions 3.0.7
Microsoft.Azure.WebJobs.Extensions 3.0.6
Can you please help us? Thanks

**Comment by ConnorMcMahon** [comment]
@AlessandroH 

Thanks for letting us know about your issue. Unfortunately, orchestrations stuck in a pending state can have many different root causes, and each case is likely different. To make sure each case gets the attention it needs, could you open up a separate issue.

When you open the issue, make sure to share the following information:

1. Orchestration Instance ID
2. Region that orchestration executed in Azure
3. Timestamp in UTC of affected orchestration.

**Comment by ravz4010** [comment]
Hi , i am facing a similar issue in which the durable functions instances are getting stuck in pending state for long ..once such issue 
![image](https://user-images.githubusercontent.com/84508791/154643733-85c2090b-c181-44a2-9008-4440c41a0d7b.png)
![image](https://user-images.githubusercontent.com/84508791/154643823-cb71e13b-8ae5-4f99-bd04-6f1b8e193498.png)

**Comment by ravz4010** [comment]
My durable function orchestrator code : 
![image](https://user-images.githubusercontent.com/84508791/154644045-71bedef0-5e70-4e4d-9a4d-112203f2cbbe.png)

**Comment by ravz4010** [comment]
The function runs in the West Europe Region .

**Comment by azeezoe** [comment]
Not sure who might benefit from this, but my issue was based around trying to use a User Assigned Managed identity to access the storage account associated with the Durable function. From the azure documentation (https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-configure-managed-identity) I thought that I would be able to use a managed identity to access the storage account without credentials. 

From what I read here (https://techcommunity.microsoft.com/blog/appsonazureblog/use-managed-identity-instead-of-azurewebjobsstorage-to-connect-a-function-app-to/3657606) It seemed like deleting the AzureWebJobsStorage app setting and replacing with AzureWebJobsStorage__accountName = <your_storage_account_name> would allow me to do this. (I did also make sure the managed ID had the necessary RBAC contribution roles to Table, Blob, and Queue services as well as being the storage account owner)

Turns out you MUST use the AzureWebJobsStorage app setting for the durable function orchestration to work properly, and you have to provide the connection string as the value for that app setting (in terraform you can get it from azurerm_storage_account.account_name.primary_connection_string). 

After doing that everything worked fine. I'm sure I missed some documentation somewhere, just wanted to put this here in case anyone else is also in the same circumstance!

**Comment by cgillum** [comment]
@azeezoe it should be possible to use managed identity in Durable Functions without storage credentials.

I see you mentioned that you tried using user-assigned managed identity. In that case, I'd expect you also need to specify `AzureWebJobsStorage__clientId` to mention the ID of the user-assigned identity, and `AzureWebJobsStorage__credential`. This is mentioned in the following section of the documentation:

![Image](https://github.com/user-attachments/assets/2498c56a-68b9-4c26-a1a3-e043431ee126)

**Comment by azeezoe** [comment]
@cgillum thank you! Indeed adding `AzureWebJobsStorage__credential` and `AzureWebJobsStorage__clientId` into my app settings (I set `AzureWebJobsStorage` blank although I'm not sure it makes a difference) fixed my issues are, and I can successfully use the user-assigned managed ID.
