### ISSUE TITLE
Breaking change when upgrade to V2 | In-flight instances

### ISSUE THREAD

**Issue by anhhnguyen206** [Azure/azure-functions-durable-extension#1264]
Hi,

We are going to upgrade Microsoft.Azure.WebJobs.Extensions.DurableTask in our project from 1.8.3 to 2.1.1.  Our Azure Function apps are already on Azure Functions v2 runtime.

From my understanding, the breaking changes when upgrade from 1.8.3 to 2.1.1 are more on the developer usage of those bindings and it won't break in-flight instances.  We will only upgrade the library and our orchestrator logic will remain the same.

Are we risking breaking in flight orchestrators if we don't do proper versioning ((i.e. side-by-side deployment with two different function apps) in this case?

Any insights would be very helpful.  Thanks!

**Comment by ConnorMcMahon** [comment]
v1.x and v2.x of Microsoft.Azure.WebJobs.Extensions.DurableTask both use the same underlying major version of DurableTask.AzureStorage, so there are NO intentional breaking changes around the underlying architecture.

There are a few caveats to this.

1. You need to make sure that the overall structure of your orchestrations is the same, so that the in-flight orchestrations will replay the same way they did with your v1.x code.
2. We changed the default TaskHub names from 1.x to 2.x. If you have not specified a [TaskHub name](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs?tabs=csharp#task-hub-names) in your 1.x version of your app, then make sure to set "hubName" to "DurableFunctionsHub". If you don't do this, when you upgrade your app it won't be listening for your inflight orchestrations, as they lie in a different task hub.

In general, make sure to follow our [upgrade guide](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versions#migrate-from-1x-to-2x).

**Comment by anhhnguyen206** [comment]
@ConnorMcMahon thanks for the quick response.  I'm aware of the hub name change and yes we don't have any change to the orchestration logic so I think I'm good here.  Thanks again.
