### ISSUE TITLE
Analyzers reporting wrong info

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-functions-durable-extension#1304]
Hello,

The analyzers that check for the activity function name is not working as expected when using `nameof(something)` as the name of the function being called on `CallActivity`:

![image](https://user-images.githubusercontent.com/4714040/78568835-0ef94280-77f9-11ea-9df0-a682362068dc.png)

As you may see, clearly the function name is valid and the code run just fine but the yellow squiggle don't go away.

**Comment by galvesribeiro** [comment]
In fact, it happens when you use any string variable. If I have a `const`, local variable, whatever. Anything but a direct string on the method parameter throw that warning which for people like us that treat warning as error, will have a broken build.

**Comment by amdeel** [comment]
Hello, @galvesribeiro. We actually fixed this nameof(functionName) problem with this PR: #1263.
There is another issue open (#1287) defining the problem with constants. I'm closing this issue because it is a duplicate. These issues will be fixed in the next release of my analyzer, which I expect to happen later this week.
