### ISSUE TITLE
Analyzer: 'Environment.GetEnvironmentVariable' violates the orchestrator deterministic code constraint

### ISSUE THREAD

**Issue by Methuselah96** [Azure/azure-functions-durable-extension#1326]
### Description
Using `Environment.GetEnvironmentVariable` in order to access app settings (as recommended in  the Azure Functions docs here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#environment-variables).

### Expected behavior
Build without warnings.

### Actual behavior
Warning DF0106 "'Environment.GetEnvironmentVariable' violates the orchestrator deterministic code constraint."

### Relevant source code snippets
N/A

### Known workarounds
Ignore warning.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.2.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

### Screenshots
N/A

### If deployed to Azure
N/A

**Comment by ConnorMcMahon** [comment]
This is expected behavior, as this violates the requirements for [determinism in orchestration code](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-code-constraints#orchestrator-code-constraints). You can put this code inside of an activity function and get the result using `CallActivityAsync()` instead.

**Comment by Methuselah96** [comment]
Thank you, sorry to bother you.

**Comment by frazur** [comment]
I propose [this solution](https://medium.com/@frazur/injecting-custom-settings-in-azure-durable-orchestrator-8d116acd0a58)

**Comment by John-Bosch** [comment]
> I propose [this solution](https://medium.com/@frazur/injecting-custom-settings-in-azure-durable-orchestrator-8d116acd0a58)

I believe this would still violate the deterministic constraint. By using DI, shutting down the function while an orchestration is running, changing the configuration, and then starting the function again would provide different values and, therefore, possibly different execution paths through the orchestration.

**Comment by ConnorMcMahon** [comment]
@frazur,

John-Bosch is correct, you essentially just tricked the analyzer into thinking that you aren't reading the environment variable on every orchestration replay when you are. 

The reason you are supposed to embed environment variable reads in an activity function is to ensure that the environment variable is read once per orchestration instance, rather than every replay. This ensures deterministic behavior.
