### ISSUE TITLE
Project.Json does not add reference in Project

### ISSUE THREAD

**Issue by loges16** [Azure/azure-functions-durable-extension#136]
Hi 
I am adding project.json file to the Durable functions but the packages are not getting restored 
Where i am going wrong ?
`{
  "frameworks": {
    "net46":{
      "dependencies": {
        "StackExchange.Redis": "1.2.6"
      }
    }
  }
}`

**Comment by cgillum** [comment]
Which version of the functions runtime are you targeting? ~1 or beta (which is v2)?

**Comment by loges16** [comment]
Beta

**Comment by cgillum** [comment]
Does it work on a regular function app? I believe support for project.json in Azure Functions was removed in v2/beta. More discussion on this topic can be found here: https://github.com/Azure/azure-webjobs-sdk-script/issues/363

**Comment by loges16** [comment]
Thanks For the Info
@cgillum What is the best alternate for adding external references then in beta?

**Comment by fabiocav** [comment]
Will add some documentation about this, but V2 was updated to use the new project based references. Instead of a project.json file, please use a function.proj following the new model.

Here's an example you can reference: https://github.com/fabiocav/azure-webjobs-sdk-script/blob/4080da19c7cda035dcc7be0316374fc37ab5d628/test/WebJobs.Script.Tests/Description/DotNet/TestFiles/PackageReferences/ProjectWithoutLock/function.proj
