### ISSUE TITLE
ListEntitiesAsync should not return deleted entities

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-functions-durable-extension#1364]
I would like to verify my assumption regarding the results of a call to `IDurableEntityClient.ListEntitiesAsync`. As far as I can understand there is no way to actually delete an entity. Once can call `Entity.Current.DeleteState()` from within an Entity but it will just clear the state.

Am I correct to assume that, if I want only to list really exisiting entities (ones having state) I have to do something like this?:

```csharp
           var entities = await entityClient.ListEntitiesAsync(new EntityQuery
           {
                EntityName = nameof(SubjectEntity),
                FetchState = true
            }, CancellationToken.None);
            var existingEntitiesInUse = entities.Entities.Where(e => e.State != null).ToList();
```

If so, it feels a bit akward to me and I would love to be able to set a property of `EntityQuery` to do this for me. Or is there another way to accomplish what I want?

**Comment by sebastianburckhardt** [comment]
I agree that the current semantics is not ideal. One would expect that entities that were deleted (i.e. have no state) should not be returned by this query *by default*.

**Comment by cgillum** [comment]
Agreed with Sebastian. I've turned this issue from a question to a feature request.

**Comment by cgillum** [comment]
Although it seems like we could implicitly fix this via [Garbage Collection for Deleted Entities (#1065)](https://github.com/Azure/azure-functions-durable-extension/issues/1065).

**Comment by sebastianburckhardt** [comment]
I think the garbage collection would not directly fix this - after an entity is deleted, it still takes some time until its metadata is removed by the garbage collection. During that time we don't want it to show up in queries, because it has been "logically deleted" already.

**Comment by Expecho** [comment]
> I agree that the current semantics is not ideal. One would expect that entities that were deleted (i.e. have no state) should not be returned by this query _by default_.

What would be a right way to introduce this without introduces breaking changes to existing code. Any code written today using the method as it is might expect all entities to be returned. 

Introducing a new method like `ListExistingEntitiesAsync` doesn't seem right as well. If you have an idea about how to design this change I wouldn't mind giving it a try to implement this.

**Comment by holietenk** [comment]
What about adding a new property `IncludeDeleted` in `EntityQuery`. The default value of that property is `true`. In this case there is no breaking change, but an extension to the current implementation.

I'm currently facing this issue. It would be super helpful to have some kind of fix for this :)

**Comment by cgillum** [comment]
@bachuv this might be a good issue for you to look into. I think the fix may be a little hacky because the underlying storage layer doesn't understand the concept of a "deleted" entity, but here is what I'm thinking we could do to make things a little better:

1. Add a `IncludeDeleted` flag to `EntityQuery` (as suggested) with a default value of `true` to avoid a breaking change.
2. In the actual implementation, we may need to do multiple queries to storage. For example, if a user queries for 10 entities and of the 10 we get back, we find out that 5 of them are deleted, then we should do another query to get another batch of entities. We would repeat this until we have 10 non-deleted entities.

This would be a potentially very expensive operation if a user has a lot of deleted entities, but I think it could be acceptable as a first step. At a later point, we will want to look into making entities a first-class concept in the DTFx layer so that we can do more efficient filtering.

**Comment by sebastianburckhardt** [comment]
Although it may be a breaking change to stop returning deleted entities, I still think it is the right call to do so. I don't think we really need this to be an option on the queries. I cannot imagine any valid scenarios where users actually want deleted entities to be returned in a query, it just causes confusion (see #1418). 

There is no guarantee for that anyway. Our backend is free to remove deleted entities from storage any time it chooses to. Ideally it would do so immediately, and our new backends do, so any new query option is meaningless for those.
