### ISSUE TITLE
Stuck/Delayed Orchestrations and SubOrchestrations

### ISSUE THREAD

**Issue by dsm0880** [Azure/azure-functions-durable-extension#1374]
### Description
We have had a successfully running application utilizing durable functions for a year or so now. One issue seems to persist that we cannot track down. I can tell you what our theory is and what the root cause seems to be linked to.

Every 2 weeks we perform a release, during that release we run a single orchestration that runs across our client base which stops and starts eternal orchestrations. That triggers ~350 termination events. Recently we have noticed that those all get stuck in the queue. We check to ensure that those orchestrations exists and that they have not been already terminated, yet they still seem to fail. Nonetheless, the result afterwards is a drastic loss in performance throughput. It seems things get better after a day and then completely gone in a week (the time it takes for the queue message to expire).

We released last night and now I'm in the hot seat again with slowed throughput. I have attempted increases the instance counts, partitions, max concurrency of both the activity triggers and orchestrations. Things will eventually process through, but it can take upwards of 3 hours, sometimes 24 hours.

I feel like I'm missing a piece of information on how the throughput is managed. Please note we are using an App Service Plan with 3 instances of the S2 plan. Note that in the instance below it will eventually work, but why is it taking so long to progress forward?

### Expected behavior
The throughput takes full advantage of the available CPU and Memory so we can readily control and mange the hub throughput.

### Actual behavior
Orchestrations extensively delayed for hours or maximum days.

### Known workarounds
Wait it out unfortunately

### App Details

- **Durable Functions extension version (e.g. v2.1.1)**:
- **Azure Functions runtime version 2.0**:
- **Programming language used**: .NET

### If deployed to Azure

- **Timeframe issue observed**: 4:14 pm EST
- **Azure region**: East US
- **Orchestration instance ID(s)**: 80_ContractRecord_895_CONTRACTRECORD-PrimaryWorkflow

**Comment by dsm0880** [comment]
@cgillum Here is the new ticket, FYI

**Comment by cgillum** [comment]
Thanks @dsm0880! First thing I'll mention is that you should consider upgrading to our latest nuget package version (currently v2.2.2). We often have important fixes that go into each release and you may find that things work better: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/

I'll take a closer look though to see what might be causing your issues based on the information you've given me.

**Comment by dsm0880** [comment]
@cgillum Thanks, I've been working on it since I posted. Couple of data points, queue messages are not getting dequeued which is good. I have a script which loops and constantly peeks then filters out the unique values so I can generally see what is flowing through. What appears to be happening is each orchestration/sub-orchestration is taking 5 min to complete. The delay is basically felt by our clients because when this is added up you could be waiting an hour. The question I'm now trying to figure out is why would this go quickly prior to our release and slowly after. Definitely will put in the backlog an upgrade. Will let you know when I find something else.

**Comment by cgillum** [comment]
@dsm0880 I appreciate understanding the impact to your customers.

**Question for you**: Do you have any orchestrations that use the `context.ContinueAsNew()` API? I ask because I detected an internal error in your app that seems to be the source of significant orchestration processing delays for ALL orchestrations in the app. We've fixed that `ContinueAsNew` issue, but the version of the extension you're using does not contain that fix. Looking specifically at `80_ContractRecord_895_CONTRACTRECORD-PrimaryWorkflow`, I see a lot of delays in processing that are possibly connected.

**Comment by cgillum** [comment]
I answered my own question - it looks like you have a lot of orchestrations that use ContinueAsNew (orchestrations prefixed with the name "Orchestration" and then sometimes a version number) . That increases the odds that upgrading to the latest extension version may fix the performance problems, but I'm trying to confirm.

**Comment by dsm0880** [comment]
@cgillum Yes we do use quite a few orchestrations that use ContinueAsNew(), specifically the eternal orchestrations. All 350 noted above use that ContinueAsNew as they are scheduled jobs created by our clients (send emails). In talking with my team we also use it in our non-eternal Orchestrations as well. So yes, we use it a lot :) We are looking at the release notes now to assess risk.

**Comment by dsm0880** [comment]
@cgillum Let's say we upgrade, and the ContinueAsNew is the culprit, will things automagically start working or should we stop and start all the eternal orchestrations? If you are not sure then no worries. Also, anyway we can see the same level of logging you see on your end?

**Comment by cgillum** [comment]
If I remember correctly, for this particular issue, I expect it should fix itself without needing to stop and start the eternal orchestrations.

Regarding logging, some context: there are actually about 4 different layers of logs involved:

1. Azure Functions app logging
2. Durable Functions tracking
3. Durable Task Framework Azure Storage logs
4. Durable Task Framework core engine logs

The first two log sources (1 & 2) are available to you via Application Insights. However, the problem is only visible in the bottom two layers (3 & 4). We haven't yet figured out a good way to expose those to our customers yet, though it's something I want to address soon'ish. In the meantime, I have access to those and Azure Support has access to those lower layers, so you'd need us to confirm whether the problem has been completely fixed.

From your perspective, you would know because these specific performance problems (long delays - often in ~10 second intervals) would start going away.

**Comment by dsm0880** [comment]
@cgillum Things are looking much better after the upgrade. Do you mind if we keep this open for a day and see if it sticks. I'm feeling pretty confident the ContinueAsNew was the issue.

**Comment by cgillum** [comment]
@dsm0880 that's encouraging to hear! Yes, let's keep this open for a little while to make sure.

**Comment by dsm0880** [comment]
@cgillum The issue appears resolved. Thanks a ton, closing.

**Comment by Trixic** [comment]
Hi, @cgillum! I have a similar issue.
The problem is related to orchestration completing. When all suborchestration instances are completed main orchestration remains in Running status for several hours or even days.
The issue is reproduced when you have some number of suborchestrations with large input/outputs.

Code example that easily reproduces that stuck orchestration:
```csharp
[FunctionName(nameof(MainOrchestration))]
public static async Task<string> MainOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
{
    for (int i = 0; i < 20; i++)
    {
        var result =
            await context.CallSubOrchestratorAsync<string[]>(nameof(SubOrchestration),
                $"{context.InstanceId}:sub{i}", "input");
    }

    log.LogInformation("MainOrchestration finished");
    return "Completed";
}

[FunctionName(nameof(SubOrchestration))]
public static async Task<string[]> SubOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
{
    var largeOutput = Enumerable.Range(0, 1000000).Select(i => $"string{i}").ToArray();
    return largeOutput;
}
```

In my test app it's in Running state for a day already:
![image](https://user-images.githubusercontent.com/3503594/84024768-225c9180-a993-11ea-8059-57dd3d469357.png)

Could you take a look on app's logs?

### App Details

- **Durable Functions extension version**: v2.2.2
- **Azure Functions runtime version**: 2.0
- **C#**:

- **Timeframe issue observed**: 2020-06-07T13:02:51.606Z
- **Function App name**: odmpftvjo2hlqa7um2af
- **Function name(s)**: MainOrchestration, SubOrchestration
- **Azure region**: East US
- **Orchestration instance ID(s)**: 56eca7be5a6e4b1f82f8cec360ba3d27
- **Azure storage account name**: ogpfstuckdur

**Comment by cgillum** [comment]
@Trixic since this issue is closed, it's better to create a new issue. I went ahead and created a new issue for you, but feel free to create one yourself for tracking and I can close the one I created.

**Comment by Trixic** [comment]
> @Trixic since this issue is closed, it's better to create a new issue. I went ahead and created a new issue for you, but feel free to create one yourself for tracking and I can close the one I created.

I'm ok with the one already created.
Thanks!
