### ISSUE TITLE
Service Bus Message Lock not renewed

### ISSUE THREAD

**Issue by royarin** [Azure/azure-functions-durable-extension#1393]
### Description
> In my attempt to implement a Service Bus trigger on a Durable Client function, it has come to my notice that if the message is not handled within the lock duration, the function runtime does not renew the peek lock - which is the case with standard functions. I assume it is due to the fact that the client function where the trigger is attached already completes before the orchestrator can complete all activities. However, for complex orchestrations where the state of the message might be tied to the outcome of the activities, how do we manage the messages? Is there a recommended pattern to handle this in Durable Functions.

>**EDIT
I have in my host.json set autoComplete to false for messageHandlerOptions. This is because I want to handle the message in the orchestrator based on the outcome of the activity functions. If I do allow autocomplete, then the message is completed automatically(as expected) when the client function ends. However, that is not the desired outcome for me.

### Expected behavior
> Expected that the Durable Functions extension in conjunction with the Functions Runtime is handling peek lock renewals as normal functions do.

### Actual behavior
> Right now the behavior is:
 1. Client function triggered.
 2. Orchestration started for trigger 1
 3. Client Function completed.
 4. Peek lock expires
 5. Client Function re-triggered with incremented delivery count
 6. Orchestration started for trigger 2
 7. Orchestration ended for trigger 1
and so on......

While the behavior in terms of how service bus retries with incremented delivery count on lock expiration makes sense, that the Durable Extension cannot handle the lock renewal is sort of a let down.

### Known workarounds
> Unknown

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.2
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.13353.0
- **Programming language used**: C#

### Screenshots
> 
![image](https://user-images.githubusercontent.com/4621796/85465186-c9067c00-b5a8-11ea-944d-3fb37e8bab5a.png)

**Comment by cgillum** [comment]
Indeed, Durable Functions doesn't know anything about the trigger you used to call into the client, so it will not be able to renew your Service Bus peek lock. However, I'm confused about why the Service Bus message isn't consumed after your client function completes and why the trigger is getting retried. Can you share your client function code so I can get a better idea of what's going on?

**Comment by royarin** [comment]
I should have mentioned that I have in my host.json set autoComplete to false for messageHandlerOptions. This is because I want to handle the message in the orchestrator based on the outcome of the activity functions. If I do allow autocomplete, then the message is completed automatically(as expected) when the client function ends. However, that is not the desired outcome for me.

**Comment by olitomlinson** [comment]
So you are wanting to ack the triggering service bus message _inside_ the orchestration function, not in the ‘ServiceBusTrigger’ function?

I’m assuming you are using ‘MessageReceiver’ and then calling Complete on message.LockToken etc

I believe the runtime will ONLY renew the lock automatically _while_ the originating ‘ServiceBusTrigger’ function is executing?

Assuming ‘DurableClient.StartNewAsync’ Is returning correctly, depending on your function code after that it possible that your originating function is completing? (Therefor no auto renews) so when your orchestration (or activity) eventually tries to complete the lockToken, it’s already been lost?

I’d need to see some code to get a better handle on your scenario if I’m off the mark.

**Comment by royarin** [comment]
You can check some sample code that I posted here: https://github.com/royarin/AzureFunctions/tree/master/DurableFunction_SBTrigger

**Comment by olitomlinson** [comment]
Hey @royarin thanks for sharing

Unfortunately you can’t use static variables (you have 3 of them) to share state between the trigger/orchestration/activity function as it’s highly likely that one or more of the functions will execute on a separate host. You might not see this happening at low volume using just 1 partition (1 host) but it is possible, particularly when scaling out.

The only way to safely pass data around is through the arguments on StartNewAsync and via the activity input and return result.

Having said that, given that your serbiceBusTrigger function is completing, immediately after the call to StartNewAsync, I’m pretty sure the opportunity to renew the lock is lost as this would be done automatically by the host while this function is executing. You can prove this by simulating a couple of sleep periods (I would probably use await Task.Delay) immediately after your call to StartNewAsync to prove that the host is automatically renewing the lock.

The only thing I could think is some how manually renewing the lock inside the orchestration, but I think this is going to get complex. If you do go down this path I would first check the APIs exist to manually renew the lock and they can be used in a separate context to where the SB message was originally received (in the ServiceBusTrigger function)

**Comment by royarin** [comment]
Hey @olitomlinson ,

Correct, using statics was a bit of shortcut when creating the sample. Not best practice.

I have thought of renewing the lock inside the orchestration, but that would mean keeping a timer to renew the lock every X seconds, and if an execution in your activities runs over that X seconds, the lock is lost and you have a different problem. Overall, could get quite complex.

**Comment by olitomlinson** [comment]
@royarin correct. it would be complex and due to the nature of how Timers work, they aren't precise if the system is under load.

It might be worth considering rearchitecting your solution so that you don't rely on completing messages _inside_ your durable function app.

**Comment by felicss** [comment]
@royarin have you found a solution to the problem? We are facing the same issues as yourself with on top using isSessionEnabled=true where it seems to complete sessions locks after the trigger-function is completed

**Comment by olitomlinson** [comment]
It’s a real interesting scenario to have the orchestration aware of, and potentially renew, the message lock.

A couple of thoughts.

Why must you use the service bus redelivery mechanism to handle the scenario of an orchestration going into a failed state?

Typically the `Failed` Runtime state of An orchestration is when the orchestration allows an Uncaught exception to propagate. However if you surround your orchestration code with the appropriate exception handling (try /catch etc) there should be enough control in your orchestration code to recover gracefully from failures.

If you absolutely must rely on retrying at service bus level, instead I would personally republish a brand new message back to the Service Bus Broker with the same payload, and utilise my own custom redelivered count header on the Message. This way you can use the default peek-lock behaviour for your triggering function and allow the message to complete organically. Obviously this wouldn’t be so simple in the case where you republish to a topic, as the message may be delivered to multiple subscribers and you only wanted it to publish to your Durable Function subscriber, but it’s not impossible with some creative routing/filtering rules on the topic.

If this is not a viable solution I would love to learn more about any use-cases.

—-

As a side note, try not to rely on Service Bus redelivery for handling user-code errors in your Function which is processing the message. Prefer to use Polly instead, this will give you greater control of the retry behaviour and allow you to do advanced retry logic using the various policies that Polly excels with. 

Service Bus retries are typically better suited for handling scenarios where the client (your function) and the service bus broker are struggling to reliably send signals to each other due to transient network issues, or port exhaustion on the client, or contention in the broker.

**Comment by ConnorMcMahon** [comment]
@royarin, does the solution provided by @olitomlinson work for you? In general, I think trying to manage session locks over a potentially long running orchestration is going to lead to a very complicated architecture, and implementing your own retry logic would likely result in both better reliability, debuggability, and observability.
