### ISSUE TITLE
Durable Entities - Retries from Orchestration

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#1396]
I would like to get some clarification on how to handle retries while using durable entities. Is there a reason why you cannot signal or call and entity from an orchestration with a retry? Not needing this makes sense when entities only deal with internal state mutation but when external services are involved this is a desired behavior otherwise the orchestration would have to wrap the call in a try..catch and call ContinueAsNew and start back from the beginning.

It's possible I am missing something fundamental here but any clarification would be appreciated!

**Comment by olitomlinson** [comment]
@mpaul31 Is there a reason why you can't handle retrying of the external service _inside_ of the entity? This way you can rollback any mutations made to internal state of your entity before you return to the caller etc.

**Comment by cgillum** [comment]
@sebastianburckhardt do you have any thoughts on this?

**Comment by sebastianburckhardt** [comment]
First, note that retrying an entity call from an orchestration is not a problem (even if it is not explicitly supported by the API). This can be done using a simple retry loop, e.g.:
```csharp
T result;
for (int numRetries = 0; numRetries < 3; numRetries++)
{
   try
   {
        result = await ...; // call entity and/or do whatever else
        break;
   }
   catch(Exception)
   {
       await Task.Delay(numRetries * Timespan.FromSeconds(1));
   }
}
```
It does not involve `ContinueAsNew` - we allow loops in orchestrations. In fact, the overloads for calling activities or suborchestrations with retries do just that - they run a loop that catches exceptions and retries the request. There is nothing special going on other than a bit of convenience so you don't have to write the retry loop yourself. 

**However**, the story is a bit different for entity signals. Wrapping an entity signal in a retry loop does not make sense because there are no exceptions propagated back to the caller.

I think the best idea, as @olitomlison suggests, it  to **handle exceptions and issue retries inside the entity itself**. This also makes more sense from an encapsulation perspective - the caller should not be exposed to internal retry choices made by the entity. I think it is an overall better design.

Perhaps we could provide some extra convenience. For example, we could provide a utility function
```csharp
Task<T> ExecuteWithRetries<T>(Func<Task<T>>code, RetryOptions retryOptions)
```

**Comment by mpaul31** [comment]
makes sense thanks everyone!

**Comment by alrz** [comment]
@cgillum If I read this correctly, `CallEntityAsync` eventually calls `CallDurableTaskFunctionAsync` wich takes a reply option. From docs "Calling an entity from an orchestrator function is similar to calling an activity function", so I guess `CallEntityWithRetryAsync` could be provided here right?
