### ISSUE TITLE
[Design/API] Some methods of DurableOrchestrationContext should belong to a service/client instead of being directly on the context class.

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-durable-extension#140]
The DurableOrchestrationContext  classe responsibilities are a bit mixed. 

For example, when I create a new workflow I have access to something similar to a service through DurableOrchestrationClient, to start and interact with my initial workflow, but once workflow is started, I interact with it through a DurableOrchestrationContext class which has methods similar to the DurableOrchestrationClient (DurableOrchestrationClient.StartNewAsync vs DurableOrchestrationContext.CallActivityAsync). 

Context classes are usually information containers and methods are usually to manipulate the content of the container (ex: https://docs.microsoft.com/en-us/dotnet/api/system.threading.executioncontext?view=netframework-4.7).

**Comment by cgillum** [comment]
For the most part, we're just providing Azure Functions-friendly wrappers around corresponding Durable Task Framework primitives. The idea of the `DurableOrchestrationClient` is that the "client" is external to the orchestrator. The "context" type is probably not a great name, but it's distinct from the client because it doesn't do any I/O and instead directs the underlying orchestration engine to carry out various "durable" tasks.

I don't see a strong reason to change this and would prefer to keep these classes closely aligned with the underlying DTFx primitives, which are more mature and have a longer history of real-world usage (though they are certainly far from perfect).
