### ISSUE TITLE
Tracing not including input to signal

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#1420]
I have a durable entity that receives a signal and fires off an http request and does not mutate any internal state.

I have `traceInputsAndOutputs` set to `true` and when I look at my app insights logs I am not able to find the input that used when signaling the entity. Shouldn't this be traced?

Thanks!

**Comment by cgillum** [comment]
I took a look at the [code](https://github.com/Azure/azure-functions-durable-extension/blob/c97025e0b229248b2a1dcc1c852ca0bbee519ae7/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs#L820-L826) and I think we should be correctly honoring the `traceInputsAndOutputs` setting (signals are internally implemented as external events). When this is not enabled, we simply [show the number of bytes](https://github.com/Azure/azure-functions-durable-extension/blob/c97025e0b229248b2a1dcc1c852ca0bbee519ae7/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L1114) rather than the actual payload. Can you share a screenshot of what you're seeing in Application Insights?

**Comment by mpaul31** [comment]
sure.

![image](https://user-images.githubusercontent.com/206767/89069519-4a3bf600-d341-11ea-8ade-a0366a4fc19e.png)

**Comment by cgillum** [comment]
The `prop__input` field should represent the payload of the entity signals. We will say `(null)` like this if there is no payload associated with that event. Are you sure you're sending a non-null input with your signal?

**Comment by mpaul31** [comment]
yep definitely. i tested another entity that stores the input in the state and same result. i even added my own logging to verify it shows up in AI from within the signaled method.

**Comment by cgillum** [comment]
ok - thanks for confirming. I'll treat this as a logging bug that we need to investigate.

**Comment by mpaul31** [comment]
thank you.

**Comment by bachuv** [comment]
Hi @mpaul31, I took a look at this issue and wasn't able to reproduce it. Are you sure that this is running in Azure? I wasn't able to find any telemetry that correlated with the instanceId that you provided. 

Can you provide the following information?
- The timestamp
- The entire trace message that you see in Application Insights including information about the state of the Entity (i.e. started, completed, etc.)
