### ISSUE TITLE
Code flow doesn't always continue after using IDurableOrchestrationContext.CreateTimer()

### ISSUE THREAD

**Issue by nadavbj** [Azure/azure-functions-durable-extension#1427]
Hi,
I'm using IDurableOrchestrationContext.CreateTimer() in the following code:
```csharp
var sleepId = context.NewGuid().ToString(); // For investigation

Log("TransactionalIngestor - sleeping for {delay} milliseconds (sleepId ={sleepId})", delayMilliseconds, sleepId);
var delayUntil = context.CurrentUtcDateTime.AddMilliseconds(delayMilliseconds);
await context.CreateTimer(delayUntil, CancellationToken.None);
Log("TransactionalIngestor - finished sleeping for {delay} milliseconds (sleepId ={sleepId})", delayMilliseconds, sleepId);
```

I correlated the first log with the second log by 'sleepId' I expected to find 100% correlation between them but found out that  ~12% of the times this code runs, the second log is missing, meaning that the code flow doesn't continue after using the timer.

### App Details

- Durable Functions extension version: 2.2.1
- Azure web jobs runtime version: 3.0.16
- Programming language used: c# (.net core 3.1)
- Eviroment- Kubernetes
- InvocationId- f264e563-0b90-41b0-829a-93abf5106183

**Comment by cgillum** [comment]
Since you're running in your own Kubernetes cluster, it's a little tricky for us to investigate what might be causing this behavior. In the v2.3.0 release, we're exposing more of our internal telemetry to make it possible for you to more directly understand what's going on. In the meantime, are you able to reproduce this behavior in an Azure environment, like the Azure Functions Consumption plan or in a Free App Service plan? If you run your code there, we will have access to the detailed orchestration telemetry to better help with investigations.

**Comment by ravi-bamrotiya** [comment]
I am facing the similar issue.

I am using Azure Durable function (C#), .Net 6.0

**Comment by cgillum** [comment]
@ravi-bamrotiya would you mind opening a new issue so we can track it better?

**Comment by ravi-bamrotiya** [comment]
@cgillum Sure
