### ISSUE TITLE
Set automatic decompression for CallHttpAsync

### ISSUE THREAD

**Issue by David-Stark** [Azure/azure-functions-durable-extension#1429]
**Is your feature request related to a problem? Please describe.**
Be able to get gziped messages with CallHttpAsync 

**Describe the solution you'd like**

With HttpClient I can create a HttpClientHandler with AutomaticDecompression:

```
HttpClientHandler handler = new HttpClientHandler()
{
          AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
};
var client = new HttpClient(handler); 

```
I want to do be able to do the same settings with CallHttpAsync.

**Describe alternatives you've considered**
Create an Activity that inserts IHttpClientFactory with a HttpClientHandler with the structure as mentioned above. 

Thanks in advance! =)

**Comment by cgillum** [comment]
@bachuv or @ConnorMcMahon as an alterenative workaround, is it possible to configure the `HttpClientHandler` like this with dependency injection? Ideally we'd support this in a more straight-forward way, but I'm just wondering what other options there might be as workarounds.

**Comment by bachuv** [comment]
`HttpClientHandler` can be figured using dependency injection. There are 2 steps to this process: 

1. Create a class that implements `IDurableHttpMessageHandlerFactory` (a public interface in the durable extension). This is where you can implement `CreateHttpMessageHandler()` and have it return an `HttpClientHandler` with the `AutomaticDecompression` setting.

2. Add a file called `Startup.cs` to your project (if you don't already have one) and register your implementation of `IDurableHttpMessageHandlerFactory` using `AddSingleton()`. 


Here's an example of what the Startup.cs file could look like:

```
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(VSSample.Startup))]

namespace VSSample
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IDurableHttpMessageHandlerFactory, CustomHttpMessageHandlerFactory>();
        }
    }
}
```

Here's an additional link that helps explain dependency injections in .NET Azure Functions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection
 
Hopefully that helps! @David-Stark let us know if you have any other questions.

**Comment by David-Stark** [comment]
@bachuv Big thanks for the help! I didnt know IDurableHttpMessageHandlerFactory existed. It works perfectly :)

Just for future reference. Lets say i have two implementeation of IDurableHttpMessageHandlerFactory. How can i choose which one to use?

```
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(VSSample.Startup))]

namespace VSSample
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IDurableHttpMessageHandlerFactory, CustomHttpMessageHandlerFactoryOne>();
            builder.Services.AddSingleton<IDurableHttpMessageHandlerFactory, CustomHttpMessageHandlerFactoryTwo>();
        }
    }
}
```

With IHttpClientFactory i can do something like this:

```
public Example(IHttpClientFactory httpClientFactory)
{
       _httpClient = httpClientFactory.CreateClient("httpClientOne");
}
```

**Comment by ConnorMcMahon** [comment]
@David-Stark,

Unfortunately, we have no way to distinguish between which `IDurableHttpMessageHandlerFactory` you want. If you think this would be a worthwhile enhancement, I would recommend opening an issue with a proposal of how this would work, especially with how you would distinguish which one you would want to use when you use the `CallHttpAsync()` API.

For some workarounds in the menatime:

If it is something you want to differentiate between running in test vs production environments, you could write logic in your `Startup.Configure()` method that runs during application startup to register different `IDurableHttpMessageHandlerFactory` depending on what environment it is running in.

If you need to have different `HttpMessageHandler` objects depending on attributes of your `HttpRequestMessage` at runtime, you could imagine writing some `CompositeHttpMessageHandler` that overwrites the `SendAsync()` method. It could then have several interior `HttpMessageHandler` objects inside of it, and route to the appropriate one based on the `HttpRequestMessage`.

Since the original question is answered at this point, I am going to close the issue.

**Comment by David-Stark** [comment]
@ConnorMcMahon Big thanks for the answer ! :)
