### ISSUE TITLE
Fan in activity function is not executed

### ISSUE THREAD

**Issue by kirillNevedrov** [Azure/azure-functions-durable-extension#1430]
### Description
I created test fan out/fan in app to test the possibility to move our real app to durable functions. 
Source code of test app can be found here [https://github.com/kirillNevedrov/azure-functions-test](https://github.com/kirillNevedrov/azure-functions-test).
Activity functions in our real app are CPU bound. So in order to scale to maximum instances and make execution as fast as possible I added following configuration to host.json:
```
{
  "version": "2.0",
  "extensions": {
    "queues": {
      "batchSize": 1,
      "newBatchThreshold": 0
    },
    "durableTask": {
      "maxConcurrentActivityFunctions": 1,
      "extendedSessionsEnabled": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```
(Not sure if 'queues' section is used by durable functions, so added it just in case.)

The problem is that with such configuration fan in activity function (test_fan_in_activity) is never executed.

The problem does not appear when I delete ` "extendedSessionsEnabled": true` setting from host.json.

### Expected behavior
test_orchestrator function calls multiple test_fan_out_activity functions in parallel. test_orchestrator function calls test_fan_in_activity function when exection of all test_fan_out_activity funcions completed.

### Actual behavior
test_orchestrator function calls multiple test_fan_out_activity functions in parallel. But test_orchestrator function does not call test_fan_in_activity function. Actually it does not execute any code after:
```
outputs = yield context.task_all(parallel_tasks)
```

### Relevant source code snippets
Source code of test app can be found here [https://github.com/kirillNevedrov/azure-functions-test](https://github.com/kirillNevedrov/azure-functions-test).
Following script is used to send messages to the queue to trigger orchestration client function (test_starter)
```
import json
import uuid

from azure.core.exceptions import ResourceExistsError
from azure.storage.queue import QueueClient, TextBase64EncodePolicy

connection_string = '' # storage account connection string

def run():
    queue_client = QueueClient.from_connection_string(
        connection_string,
        'test-fan-in-fan-out-1',
        message_encode_policy=TextBase64EncodePolicy()
    )
    try:
        queue_client.create_queue()
    except ResourceExistsError:
        pass

    queue_client.send_message(json.dumps({
        'chunks_ids': [str(uuid.uuid1()) for i in range(0, 30)]
    }))

    test = 1


if __name__ == "__main__":
    run()
```

### Known workarounds
The problem does not appear when I delete ` "extendedSessionsEnabled": true` setting from host.json.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: azure-functions-durable-python 1.0.0b7
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: python

### If deployed to Azure

- **Timeframe issue observed**: 2020-08-12T16:00:00Z - 2020-08-12T16:10:00Z
- **Function App name**: k-n-test-func-1
- **Function name(s)**: test_starter, test_orchestrator, test_fan_out_activity, test_fan_in_activity
- **Azure region**: North Europe
- **Orchestration instance ID(s)**: b928b604-3ecb-4b76-bea6-d09150572e82, 5b0784b8-4342-4949-9c9e-5f33ab98e20a
- **Azure storage account name**: kntestfunc1

**Comment by kirillNevedrov** [comment]
@olitomlinson thank you for recommendation on how to test application. But my problem is not that function execution time is too long. My problem is that function is not executed at all.

To clarify the issue.
 
This orchestrator function:
```
def orchestrator_function(context: df.DurableOrchestrationContext):
    try:
        logging.info("test_orchestrator started")

        msg_body = context.get_input()

        parallel_tasks = []
        for chunk_id in msg_body['chunks_ids']:
            parallel_tasks.append(context.call_activity(
                'test_fan_out_activity',
                {
                    'id': chunk_id
                }
            ))

        outputs = yield context.task_all(parallel_tasks)

        yield context.call_activity("test_fan_in_activity", outputs)

        logging.info(
            "test_orchestrator succeed")
    except Exception as ex:
        logging.exception(
            "test_orchestrator failed", exc_info=ex)

        raise
```

Does NOT execute this code:
```
        yield context.call_activity("test_fan_in_activity", outputs)

        logging.info(
            "test_orchestrator succeed")
```

When `host.json` file has this configuration:
```
{
  "version": "2.0",
  "extensions": {
    "queues": {
      "batchSize": 1,
      "newBatchThreshold": 0
    },
    "durableTask": {
      "maxConcurrentActivityFunctions": 1,
      "extendedSessionsEnabled": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

Isn't it a bug? 

(Link to source code and deployed function information are in issue description.)

**Comment by kirillNevedrov** [comment]
@olitomlinson is case you still need answers to your questions.

**How many orchestration instances do you typically expect to be executing concurrently? magnitudes are fine here - 1? 10? 100? 1000? etc**
1-10

**How many activities do you typically execute as part of an orchestration? magnitudes are fine here - 1? 10? 100? 1000? etc**
100-300 fan out, 1 fan in

**Are all of those activities expected to execute concurrently, or sequentially?**
fan out - concurrently, fan in - after all fan out execution completed

**How long does each activity typically take to complete? or is there a range of time? seconds, minutes, hours? etc**
~10 seconds

**What is the E2E orchestration time you are expecting and what are you actually observing? seconds, minutes, hours, days, weeks? etc**
expecting:
All execution can be split into ~10 seconds concurrent fan out tasks, fan in task also takes ~10 seconds. With immediate instances scale out it can be executed in ~20 seconds, I understand that immediate instances scale out is not possible. So I expect that new instances will be added as fast as possible to minimize time of E2E execution.

actually observing:
3 minutes with "maxConcurrentActivityFunctions": 1
12 minutes without "maxConcurrentActivityFunctions"

**Comment by olitomlinson** [comment]
@kirillNevedrov 

I understand that there may be a bug here when using `extendedSessionsEnabled : true` - but I would not recommend using this setting at this point, as from what you've mentioned it doesn't sound like you would benefit from it. _But as with all Durable Functions Apps, the only way to be sure is to experiment and try it out._

There is no silver bullet, as latency & throughput is very much dictated by the characteristics of your workflows and workloads, but here are a few simple things that you can try out.

- It might be worth increasing the `partitionCount` setting. If you set it to 10 and you have a uniform distributed orchestration Id, this would allow your App to achieve a better degree of concurrency and therefor a lower E2E, particularly when executing 10 orchestrations at the same time. The default is 4 partitions, so there may be times when your orchestrations are competing for processing time which would introduce latency.

- If you want your workloads to be picked up faster than normal in order to achieve a lower E2E, I would also recommend decreasing the [maxQueuePollingInterval](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#concurrency-throttles) setting. The effect of decreasing is more noticeable when the App has been idle for some time, or scaling from 0. _Bare in mind that this will incur more storage transaction charges._


**Another train of thought**

- Given that your activities are CPU bound and you could potentially have 300 of them running concurrently, is this OK? would it be better to schedule less work concurrently? There is a pattern documented [here](https://github.com/Azure/azure-functions-durable-extension/issues/596#issuecomment-459906400) which allows you to limit the amount of Acitivities that you schedule, it might be worth experimenting with that?

Its worth noting that Durable Functions uses a breadth-first approach to executing orchestrations and activities.

If your first orchestration floods the activity queue with N events, any subsequent activities scheduled by any other orchestration will be placed behind those N events already in the activity Queue. At scale when many orchestrations are competing, that can feel like a general slow down in the overall E2E of orchestrations. The way to minimise this effect, is to artificially reduce the amount of concurrent work that orchestrations schedule, thus giving more capacity to other orchestrations that may need to operate at the same time. 

If you wanted to ensure a true FIFO approach to orchestration completion, there is a nice orchestration _limiter_ pattern described [here](https://github.com/Azure/azure-functions-durable-extension/issues/1067#issuecomment-589856474) and [here](https://github.com/Azure/azure-functions-durable-extension/issues/1272#issuecomment-601825205) - but until sub-orchestrations and Entities are supported in Python you might be out of luck.

---

With regards to the bug, this looks to be a really simple/common orchestration pattern which I'm surprised isn't working. But having said that Python support is very recent so there could be a bug there. Might be worth taking a look at @cgillum

**Comment by kirillNevedrov** [comment]
@olitomlinson thank you for such detailed information. I'll try those optimizations. 

The reason why I set maxConcurrentActivityFunctions to 1 is that by default python azure functions instance has a single process (worker) to handle messages. With default maxConcurrentActivityFunctions value (10), each instance takes batch of 10 messages from queue. But Instance handles only one message at the time because of signle process limitation and because my activity function is cpu bound. I've obtained described behavior from experiment. 
There is the setting FUNCTIONS_WORKER_PROCESS_COUNT that can be used to increase number of processes per instance. But it will help for i/o bound tasks only.

So I do not see the point in batching of cpu bound tasks. 
(But from your explanation I see that I can combine "maxConcurrentActivityFunctions" : 1 with other optimization techniques)

Do I miss something?

**Comment by ConnorMcMahon** [comment]
@kirillNevedrov 

Extended sessions is a broken scenario for non-.NET languages. We are working in the short term to make this a fail-fast scenario so it doesn't silently fail, as well as improving our documentation: https://github.com/MicrosoftDocs/azure-docs-pr/pull/127199.

In the long term, we hope to make extended sessions work better with non-.NET languages.

**Comment by kirillNevedrov** [comment]
@ConnorMcMahon thank you for information.
