### ISSUE TITLE
Orchestration that never ends

### ISSUE THREAD

**Issue by petarvucetin** [Azure/azure-functions-durable-extension#1432]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

Orchestration never ends. 

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.

Should ended

### Actual behavior
> A clear and concise description of what actually happened.

Stuck in running state

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

Terminate running instance

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:  latest
- **Azure Functions runtime version (1.0 or 2.0)**: latest

- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/179653/90160000-06d08700-dd46-11ea-9d18-99869daf4d12.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**: SouthcentralUS
- **Orchestration instance ID(s)**:60bd0d498a144f82848ecb6f62354403, 4190d0c0c25a420ea80b65c713ef3f3d:1, 33d7e0d51ede45f1b5c9ac430bc41672:8, 2a12f1ee61714b6999c21dfec046af7a:3
- **Azure storage account name**: jdecwatchdogdev
- **HubName: ADFWatchdog

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
Hi @petarvucetin. I took a look at instance `60bd0d498a144f82848ecb6f62354403` and saw a few interesting things:
* According to our telemetry, it appears the instance actually completed at **2020-07-29 09:54:55.6896339**. Are you also seeing that it completed?
* Our telemetry also shows that there were several process recycles during this time that impacted your orchestrations. Was your app crashing or being restarted? There are definitely some duplicate message processing going on that was causing things to be duplicated and run slow. I mention this as FYI because it should not actually cause anything to get stuck permanently or for more than a few extra minutes.
* I noticed that some of the messages in the control queue were processed by something outside of our hosted service. Is it possible that someone on your development team had a local copy of the app running and pointing to the same storage account (or even on some CI machine)? That might explain what we're seeing. Having multiple apps listening on the same storage account can definitely cause unpredictable behavior like this.

Also, I noticed you're running **v2.2.1** of our extension, which is a bit out of date. I recommend updating to the latest version to make sure you have the latest reliability updates. Later this week we hope to release **v2.3.0** which will have even more improvements. However, I don't know for sure if it will help your issue specifically since it's not clear what the root cause is.

Let me know if there's any other information you can provide that can help narrow down this issue.

**Comment by petarvucetin** [comment]
Thanks @cgillum . Let me take some time to review and compile the answer.

**Comment by petarvucetin** [comment]
#3 control queue: There are no known processes that interact with the control queues.
#2 process recycles: if there were any recycles they were not induced by anything we have (that I know of). 
#1 completion: I am not seeing completion using the [Durable Instance Monitor](https://scale-tone.github.io/2019/07/26/introducing-durable-functions-monitor) This is the screenshot from above.

re: version - thanks for point this out. Will upgrade asap.

The only other process that is interacting with the orchestration is the Completed Purge History which fires every 30 minutes and clears the completed activities. Otherwise history gets enormous.

Attached is the Instance and History
[instance-and-history.zip](https://github.com/Azure/azure-functions-durable-extension/files/5086402/instance-and-history.zip)

**Comment by lilyjma** [comment]
@petarvucetin -- apologies for the delayed response. Are you still experiencing this issue?
