### ISSUE TITLE
Issues on running durable functions: multi-thread. Code never completes all tasks

### ISSUE THREAD

**Issue by luccasmf** [Azure/azure-functions-durable-extension#1434]
### Description
I'm Running an Orchestration Function that iterates until I have a flag in the request result that request to stop. I'm adding the results in a collection (Dictionary) to use it later, as you can see in the following piece of code. The problem here is that I have around 218 pages, and everytime I reach the async task, it starts another thread, and not all the started ones returns me some value to add in my dictionary, I tried to use the _await context.LockAsync()_ but when the code reaches the line that I call it, it stops and don't run the "protected" code

I'm using dependency injection in the functions, that's why it's not an "static" method.

###The Orchestrator
 ```
        static Dictionary<int, UsersModel> dic = new Dictionary<int, UsersModel>();
        static int Page = 1;
        static EntityId lockId;
        static List<UsersModel> users = new List<UsersModel>();
        static int maxPage = 0;
        [FunctionName("RunUserOrchestrator")]
        public async Task RunUserOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            string token = _reader.Login();
            try
            {

                while (maxPage == 0 || maxPage <= Page)
                {
                    UsersModel usersModel = new UsersModel();

                    int p = Page++;
                    log.LogInformation($"Current page: {p}");
                    usersModel = await context.CallActivityAsync<UsersModel>("RunUserOrchestrator_Load", (token, p));

                    if (maxPage == 0)
                    {
                        maxPage = usersModel.data.total_page_count;
                    }

                    if (usersModel.data.items != null && usersModel.data.items.Any())
                    {
                        if (!dic.ContainsKey(usersModel.data.current_page))
                        {
                            dic.Add(usersModel.data.current_page, usersModel);
                            dic = dic.OrderBy(x => x.Key).ToDictionary();
                            log.LogInformation($"Page {usersModel.data.current_page} added");
                        }

                        if (!usersModel.data.has_more_data)
                            break;
                    }
                }

                users.AddRange(dic.Values);

                List<Item> items = new List<Item>();
                var y = users.Select(x => x.data.items).ToList();
                y.ForEach(x => items.AddRange(x));

                items = items.DistinctBy(x => x.user_id).ToList();

                MemoryStream file = FileCreator.CreateCSV(items);
                string url = _reader.SendToStorage(file, "userList.csv", "docebopwbiusers");

                bool result = !string.IsNullOrWhiteSpace(url);

                if (result)
                    log.LogInformation($"Sucesso - {DateTime.Now}");
                else
                    log.LogInformation($"Arquivo não enviado - {DateTime.Now}");

                users = new List<UsersModel>();
                //UserDataPersistence.usersPage = 1;

            }
            catch (Exception e)
            {
                log.LogInformation($"Exception: {e.Message} - {DateTime.Now}");
            }
        }
```

### The Activity
```
[FunctionName("RunUserOrchestrator_Load")]
        public async Task<UsersModel> LoadUsers([ActivityTrigger] IDurableActivityContext inputs, ILogger log)
        {
            (string token, int usersPage) = inputs.GetInput<(string token, int usersPage)>();

            return _reader.ReadUsers(token, usersPage);
        }
```

**Comment by cgillum** [comment]
I'm not sure I fully understand the symptoms you're describing, but what I can tell you is that you should never use static variables like this in your orchestrator code. They violate the deterministic requirements. See this docs article for more information: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-code-constraints


API category | Reason | Workaround
-- | -- | --
Static variables | Avoid using nonconstant static variables in orchestrator functions because their values can change over time, resulting in nondeterministic runtime behavior. | Use constants, or limit the use of static variables to activity functions.

I'm not sure what `_reader.Login()` is doing, but that may be problematic as well if it is not deterministic.

**Comment by luccasmf** [comment]
@cgillum using static variables was the only way I found to keed my data through different calls. Since I'm using dependency injection, everytime a new "thread" is called, it calls the constructor and all non-static variables are reseted.

the _reader.Login() is just an synchronous call to external API, it is working fine.

**Comment by luccasmf** [comment]
For example, instead of running "linear" and wait for the task completion, everytime my code reaches the "await context.CallActivityAsync<UsersModel>()" it stops and, then, a new instance of the Orchestrator is called, then all my "non-static variables are reseted, it's something like another thread, in each loop the page is being incremented, so, sometimes, I'm requesting the page 4 or 6 already when the page 1 returns and is added to my dictionary.

**Comment by cgillum** [comment]
> using static variables was the only way I found to keed my data through different calls

You can just use local variables for this. Each replay (I think that's what you're referring to when you say "thread"?) will start from scratch and rebuild the state captured in your local variables. We automatically store/replay the results of activity functions in storage so that they don't get called multiple times.

As an aside, dependency injection should not be used in orchestrator functions as well, because that too is inherently non-deterministic. 

> the _reader.Login() is just an synchronous call to external API, it is working fine.

It's still not correct to have orchestrations directly invoke external APIs. External APIs are inherently non-deterministic and will get replayed multiple times. It goes against the rules for authoring orchestrator functions.

The correct way to provide data to your orchestrator function is either via orchestrator function inputs or via activity function return values. So `_reader.Login()` and all your I/O operations need to be implemented in an activity function. We can't guarantee correct execution behavior otherwise.  I strongly suggest taking the time to read through the [Orchestrations](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations?tabs=csharp) documentation to make sure you understand how orchestrator functions are intended to work.

**Comment by luccasmf** [comment]
@cgillum thanks for your kindness on helping me, I have read the documentation already but I got some misinformation and got some wrong concepts. I have change my code for not using dependency injection and static variables as well. As I could notice these were my problem, Now it's working for every step, I'll make just some minor adjusts for call another activity to upload de resultant file.

Thanks again, you rock, man.
