### ISSUE TITLE
Activity function restarts after Durable Function is restarted

### ISSUE THREAD

**Issue by azachert** [Azure/azure-functions-durable-extension#1465]
I have noticed a strange behaviour of activity functions after restarting entire Azure Function.
After a restart - due to deploy or any maintenance in Azure on Azure Function component, activity function sometimes is started again. This is not a required behaviour, as I cannot distinguish it from properly started activity.

It seems that Azure Function, when starting, is spotting activity function, which was not finished, and starts it again.

Anyone noticed similar behaviour?

I'm using .NET Core 3.1 and Microsoft.Azure.WebJobs.Extensions.DurableTask = 2.2.2.

**Comment by mpaul31** [comment]
activity function executions are at-least-once delivery. you need to ensure you design your functions to be idempotent for this exact case.

**Comment by ConnorMcMahon** [comment]
As @mpaul31, site restarts in the middle of in-flight activity executions, along with some rare race conditions during site restarts during orchestration checkpoints can result in duplicate activity function executions, hence why we only guarantee at-least-once delivery, instead of exactly-once. While we aim to make these duplicate activity function executions as rare as possible, it is impossible to completely avoid.

In general, if site restarts are occurring do to your own deployments, I would recommend following our [versioning guidelines](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning), which often involve forming a new taskhub and utilizing our slot features, which should limit the number of site restarts that occur. Unfortunately, you have little visibility into upgrades/maintenance on the Azure side, so I would recommend trying to add some sort of idempotency to your activity functions as mpaul31 suggested.
