### ISSUE TITLE
Scaling infrastructure does not listen to non-Production slots.

### ISSUE THREAD

**Issue by emilbm** [Azure/azure-functions-durable-extension#1470]
### Description
We're doing a project where an Orchestrator fans out by adding hundreds (tested with ~285) activities, and then waiting for them all to finish. No further activities are added until all activities are completed. We are seeing every activity being slowly handled by one instance over the course of 7-10 minutes, messages lying in wait for as much as 5+ minutes without a single scaleout.

I'm using the following insights query in insights to detect scale out:
```
requests
| where name contains "ExportOrchestrator_HandleChunk"
| distinct cloud_RoleInstance
```

My host settings are as follows: 
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "extensions": {
    "durableTask": {
      "hubName": "%TaskHubName%", (Setting in question is 'ExportServiceHubStaging')
      "maxConcurrentActivityFunctions": 1 (also tried higher counts)
    }
  }
}
```

I have also tried with a controlQueueBatchSize of 1, to no avail.

### Expected behavior
I would expect the service to scale out every 30 seconds, thereby adding additional cloud_RoleInstances to the above query results.

### Actual behavior
One instance handles every activity in a ~7-10 minute time period.

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

- **Timeframe issue observed**: 10th september 2020, ~7 am to ~9 am UTC
- **Function App name**: lasso-exportservice-staging
- **Function name(s)**: ExportOrchestrator_HandleChunk (and other ExportOrchestrator_ prefixed functions.)
- **Azure region**: West Europe
- **Azure storage account name**: lassoservices

**Note**: The history and instance tables are cleared after a succesful run, so there are no logs to find there.

**Comment by emilbm** [comment]
I think this might be related to deployment slots. for this project we've gone straight to our Staging slot, and scaling does not work there. When deploying the same code, same settings to the default slot/production, scaling happens correctly.

Any thoughts?

**Comment by ConnorMcMahon** [comment]
@emilbm sorry for the delay in responding to this issue.

I believe this is expected behavior. Looking at the telemetry in our scaling infrastructure, your production slot was voting to scale in while your staging slot was voting to scale out. In general, our scaling infrastructure only listens to production slots. Non production slot sites will run on every site that the production slot scales out to.

This is currently by design. If you have feedback for this, I think the best location to file an issue would be the main [Azure Functions repo](https://github.com/Azure/Azure-Functions).
