### ISSUE TITLE
Allow app lease swap without turning off a function instance

### ISSUE THREAD

**Issue by bendursley** [Azure/azure-functions-durable-extension#1503]
Off the back of #1128 , it would be nice if we could force an application to loose it's lease and return to its previous state.

This would allow us to support staging slots \ DR better without having to turn off a function instance to ensure it hasn't got a lock.

**Comment by olitomlinson** [comment]
> IMO the danger of automatically failing back over to the primary is that we can't know if all other application dependencies have been similarly failed over. For example, if the Durable processing fails back over to the primary, what happens if the HTTP load balancer or some other dependency has not yet failed over? I feel that it's safer to let the app owner make the call about when it's safe to fail back over to the primary because they ultimately understand the full end-to-end architecture of the system and its dependencies.

@cgillum Not quite sure what you mean "some other dependency has not yet failed over?" Can you provide an example?

In my use-case, we are going to use a Traffic Manager in front of both Primary and Secondary Function Apps in a active-failover configuration so all traffic by default goes to the primary if that probe is getting a satisfactory response from the healthcheck endpoint. If the primary probe failed (possibly due to a compute outage), requests would eventually route to the Secondary. The requests to `DurableClient` (like `StartNewAsync`/`WaitForEventAsync`/`RaiseEventAsync`) would queue up in the TaskHub, and eventually the Secondary would take ownership of the TaskHub and begin orchestration execution.

Now suppose the Primary Function App came back online, the Traffic Manager probe would eventually route requests back to the Primary Function App. But now my orchestrations will indefinitely continue to process on the Secondary, incurring latency and additional ingress/egress if out of the region.

Ideally, once the Function App has failed over to the Secondary, The secondary should be willing to give up its lease if the Primary was to come along and make a claim for ownership.

This means that the Primary and Secondary would need to be explicitly told which is the Primary and Secondary. An App Setting configuration would be best here as that can be easily varied across environments (unlike `host.json`) using any kind of Infrastructure-As-Code. 

` "DURABLE_FUNCTIONS_PRIMARY" : true ` <- for the primary
` "DURABLE_FUNCTIONS_PRIMARY" : false ` <- for the secondary(ies)

No App Setting configured? No problem, the default behavior wouldn't provide any auto-recovery to the primary and keep the behavior as-is today.

**Comment by luthus** [comment]
I quite like the idea of the app setting option as this also covers apps that aren't using Traffic Manager and HTTP triggers to start the orchestrations, for example, timer or blob triggers.

**Comment by olitomlinson** [comment]
@cgillum any thoughts on my comment?

**Comment by cgillum** [comment]
@olitomlinson I haven't had a chance to think about it too deeply yet, but between the two options I likely to lean towards an API-based solution rather than an app settings-based solution.

**Comment by bendursley** [comment]
@cgillum I think an API based solution would make sense, as it means we can initiate the swap when we are ready to.

**Comment by olitomlinson** [comment]
I think you need an App Setting/environment variable anyway, otherwise how can each app instance identify wether or not it is the *desired* primary?

**Comment by olitomlinson** [comment]
@cgillum 

after some testing and pondering, I really need a way to bias the lease towards a primary environment.

This is because the rest of my system is running in UK South, so I want to keep the orchestrations running in South where ever possible (to minimise cross-regional costs and latency), unless of course south becomes unavailable in which case UK West can steal the lease while south is down.

But when South becomes available again, and is in a position to start attempting to claim the lease, then West should give it up at the first opportunity.

I’d also like to reiterate that I rarely use traffic managers as my durable Apps are mostly queue-driven back-end services, so any mechanism of switching the lease between regions should ideally be decoupled to traffic manager probing.

Thanks 😊

**Comment by olitomlinson** [comment]
Hey @cgillum !

There is a few of us that seem interested in this with a few varied uses-cases. Any chance that this can be prioritised?

**Comment by cgillum** [comment]
Adding @ConnorMcMahon

**Comment by olitomlinson** [comment]
Hey @ConnorMcMahon 

I'm sure you have a million things on right now, but may I ask when you will be looking at the priority of this?

If there is anything you need from me to help, please give me a shout :)

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

I see this as a feature for our next minor release (v2.5.0).

We are releasing v2.4.1 this week, and it will probably be another 6-8 weeks after that before our next feature release.

@amdeel and I have started discussing the design of this offline, and will post one here in the next week or two. I imagine that we will start by exposing some sort of API that allows you to change/set the preferred app lease owner. I think other mechanisms (like app setting based) would come later, as we don't have a design we feel comfortable with at this time.

**Comment by olitomlinson** [comment]
@ConnorMcMahon awesome! Thanks!
