### ISSUE TITLE
Durable entities - Synchronous Updates

### ISSUE THREAD

**Issue by davebally** [Azure/azure-functions-durable-extension#1544]
Hi ,

Just want to clarify my thinking of the use of durable entities. 

So,  im working on splitting up a monolith and would like to use durable entities to aid this.  If i have a simplistic locking mechanism and  i want the monolith to do a HTTP call and have returned whether the 'event' can be locked or is already locked.

The path i have inside the durable function is  HttpTrigger -> Orchestration -> Entity Proxy.

When i call the orchestrator from the httpEvent i use  
```
          [FunctionName("lockEvent")]
          public static async Task<IActionResult> lockEvent(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequestMessage req,
            ILogger log,
            [DurableClient] IDurableClient client)
        {
            var eventLock = await req.Content.ReadAsAsync<EventLock>();
            var instanceId = await client.StartNewAsync<object>(nameof(LockEventProcess), eventLock.EventId.ToString());
            using var httpResponse = await client.WaitForCompletionOrCreateCheckStatusResponseAsync(req, instanceId);
            var stringResult = await httpResponse.Content.ReadAsStringAsync();
            if(stringResult=="true") return new OkResult();
            return new BadRequestObjectResult("Already Locked");
        }
```

Which all functionally works, the issue is with WaitForCompletionOrCreateCheckStatusResponseAsync,  this will 'poll' the orchestrator for the present status, right ? By default its a second interval i think.

Can this process be made more synchronous ?  Or am i missing something ?!

Thanks
Dave

**Comment by ConnorMcMahon** [comment]
If you want a call/response from an entity, unfortunately this is probably the most synchronous you can get. `IDurableClient` only has the capability to signal entities in a fire and forget fashion. "Calling" an entity, where you send a signal and wait for the response, is only possible on an orchestration.

Unfortunately, there is no real way around this from a technical level. I think the workaround you have, where you create an orchestration that calls the entity, and your DurableClient blocks until the orchestration completes is really the only way. Note though that in Azure App Service, HTTP requests are limited to ~240 seconds, so if you have a long backlog in your internal queues, the orchestration request may not finish in this time period.

Do you have more details about why you need this to be synchronous? In general, entities and orchestrations are fairly asynchronous by design.

**Comment by cgillum** [comment]
Alternatively, you could use something like SignalR/websockets to have the entity notify the client when the entity has completed its work. That would be better from a latency perspective.

**Comment by ConnorMcMahon** [comment]
Ah yes, following the callback model (be that the traditional HTTP model callback, or something with websockets/SignalR) would be a way to have your client block while waiting for the entity response. 

I would make sure to do the waiting in your monolith as opposed to in your HTTP triggered function, due to the time limits App Service imposes.

**Comment by davebally** [comment]
Thanks both,  will look at SignalR.   I guess from my initial reading reading i was expecting some equivalency with say service fabric stateful services where you issue the request, something simple like an atomic persisted  "counter ++" even, so very short lived, and have the new value of that counter be returned to the caller.   Im sure that SignalR/websockets route will work (though its not something ive done before). I obviously wasnt expecting to have to handle the response with such a level of complexity.

**Comment by cgillum** [comment]
This is understandable, especially if you're accustomed with other virtual actor implementations like Orleans or Service Fabric Actors (which is a port of Orleans). Durable entities is actually quite different from these. Take a look at our documentation for additional comparisons to make sure that Durable Entities is the right tool for your use case: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#comparison-with-virtual-actors. Feel free to send us any additional questions as well.
