### ISSUE TITLE
Orchestration function stuck in "Running status" or execute with huge delay

### ISSUE THREAD

**Issue by Haletski** [Azure/azure-functions-durable-extension#1549]
### Description
Orchestration instance is stuck in running status and not being processed further or executed after with delay. I can assume that this is because of large payload if this is true could you confirm this? And what is the possible solution to handle such a case?

### Expected behavior
Suborchestation function should be executed.

### Actual behavior
Suborchetration function is stuck in running state

### App Details
- **Azure function version: 2**
- **Durable Functions extension version:  2.3.1**
- **Location: UK South**
- **App Name: func-dataforseo-dave-dev**
- **Orchetration Id 5c371b2934c4404ca8794a65509305db**
- **.NET Core 3.1**:
- **Storage account: stdavemaindevenv**
- **Date: from 2020-11-05 14:30 UTC to 2020-11-05 15:00 UTC**

### Screenshots
![image](https://user-images.githubusercontent.com/30402551/98257018-42b76900-1f90-11eb-8d96-5715352cfec7.png)

**Comment by ConnorMcMahon** [comment]
@Haletski 

I took a look. It looks like around 14:45 UTC, your orchestration hit a point where it takes too much memory to process. Essentially, as soon as we load your history into memory, we hit over 1.5 GB, meaning the site is kicked off the worker before we are able to successfully checkpoint the timer expiration that is in the queue. Unfortunately, because we don't checkpoint the message, it stays in the queue, causing us to be stuck in an infinite loop where we keep trying to process this message, but not having enough memory to do so.

Unfortunately, the only real workaround to unblock you is one of the following:

1. Stop this app. Then deploy your code to a new function app on a dedicated app service plan or premium plan with more memory and point it at your storage account + taskhub. This function app should have enough memory to process this suborchestration, and once that happens, you can delete this function app and resume.
2. Stop the app. Delete anything with this partition key from your history and instance status tables in Storage. The queue messages will remain, but after it hits a dequeue count of 5 (which it already has due to the memory issues discussed), the message will be deleted.

This unfortunately only unblocks the current orchestration, and other large inputs or orchestration with long history could get you into this state again . If you want to fix the root cause, my suggestion would be to avoid sending large data as inputs/outputs to your activities and orchestrations. Due to how Durable Functions (and the underlying Durable Task Framework) works, we have to load all of the input and outputs into memory every time we replay the orchestration. This can lead to some major memory usage (not to mention heavy IO against Azure Storage).  Passing around references to these large pieces of data ensures that you can lazily download the data you need only when you need it, keeping memory in check and almost certainly helping performance with large datasets.

@cgillum, this is the second time in the past month I have seen a large history cause an app to get stuck in an infinite reboot loop. We may want to actually look into a "poison" strategy, where after a certain dequeue count, we don't bother abandoning the message and just delete it (and maybe fail the whole orchestration instance?).

**Comment by Haletski** [comment]
HI @ConnorMcMahon. Thank you for you clarification. I have updated my orchestration functions to use smaller input/outputs but memory is still growing up. I'm using SubOrchestration function with ContinueAsNew loop. At some point memory become more then 3-4 GB. I've pointed the biggest objects in the screenshots. Please see attached screenshot. The most biggest is Task Completed Event. Is it expected behavior?

![image](https://user-images.githubusercontent.com/30402551/98371011-87083f00-204c-11eb-82e8-acc6bc43c45a.png)

**Comment by ConnorMcMahon** [comment]
@Haletski 

Thanks for the quick update.

Doing some quick math, it looks like each TaskCompletedEvent is taking a little over 1 MB worth of data, which is not necessarily too large, but it is still a bit larger than I would expect. It shouldn't be a problem as long as we prevent loading too many of them at once. Without the full dump, it is a bit hard to tell where the memory usage in these objects is coming from. My guess is either the size of `List<Keyword>` or from the size of `BatchKeywordState`. Again, this may not be a problem, as long as we don't try to load too many at once.

There are a [few knobs in the host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#host-json) that may affect how many `TaskCompletedEvents` we load. It is important to note that they can come from one of two places: new messages from the control queue that we need to process, or from the history table for orchestrations we are about to execute.

The biggest knob you can likely tweak is `controlQueueBufferThreshold`. This controls how many messages from the control queue we prefetch as a performance optimization. It defaults to 256, meaning that this is likely a large source of how many TaskCompletedEvents we pull in. It's important to note that if we have these messages prefetched, we oftentimes prefetch their orchestration's entire history so that it is ready to process. Tweaking this down should decrease your memory in fairly large manner.

The second knob to tweak is `maxConcurrentOrchestratorFunctions`. The more concurrent orchestrations we have running on a worker at a time, the more histories are loaded, so the more memory consumed. What is particularly interesting about this field is that we default it to 10 * the number of cores, so on the consumption plan each worker will have this value at 10. However, I imagine your local dev box has many more cores than 1, so the theoretical maximum concurrent orchestration functions may be much higher. This could lead to much higher memory usage when running on your dev box than running in production, so I wanted to highlight this. You could try setting it to a fixed value to get a more consistent experience with memory usage across your dev box and production.

Finally, you can try setting `extendedSessions` to `true`. This is mainly more of a throughput/performance knob, but it does have impacts on memory usage. The impact on memory usage is a bit unpredictable unfortunately, as depending on your workload, it could decrease _or increase_ your memory usage. For consumption plans, I would generally expect it to increase memory usage slightly, but it's worth testing.

I realize I just threw a lot of details at you, so feel free to follow up with any questions. We are looking to improve our documentation for performance best practices, and post v2.4.0 I think we may want to start looking into ways that we can have dynamic defaults so that you don't need to tweak all of these settings just to keep memory usage down, but I have a feeling that is a while off.

**Comment by Haletski** [comment]
@ConnorMcMahon thanks for your detailed answer. I'm going to try all that suggestions and come back to you shortly if still have any issues.

**Comment by ConnorMcMahon** [comment]
@Haletski, just checking in to see if you have had any success over the past couple of weeks implementing these suggestions.
