### ISSUE TITLE
DF0108 incorrectly fires on custom CallActivityAsync overload

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-functions-durable-extension#1562]
### Description
I have the following custom extension method in my code:

```csharp
public static Task<TResult> CallActivityAsync<TResult>(
	this IDurableOrchestrationContext context, string functionName, object input, RetryOptions retryOptions
)
{
    return retryOptions != null
        ? context.CallActivityWithRetryAsync<TResult>(functionName, retryOptions, input)
        : context.CallActivityAsync<TResult>(functionName, input);
}
```
Using it like
```csharp 
context.CallActivityAsync<List<(string, short)>>(nameof(GetMakes), x, retryOptions)
```
 triggers a false compiler warning on build: `warning DF0108: Activity function named 'GetMakes' takes 'short' but was given 'Microsoft.Azure.WebJobs.Extensions.DurableTask.RetryOptions'.`

### App Details

- **Durable Functions Analyzers version**: 0.3.0 
- **IDE**: Visual Studio 2019 (16.8)
- **Programming language used**: C#

**Comment by ConnorMcMahon** [comment]
Thanks for bringing this to our attention.

@amdeel, I know our v2.4.0 release is this week, and you have other features you are working for on that release. I'm guessing the best target for this release would be the following release?

**Comment by amdeel** [comment]
@ConnorMcMahon Yes, I plan to do another analyzer release for our 2.4.1 release of Durable to address these bugs.

@Arithmomaniac Thanks for this submission!

The reason this is being flagged is because the analyzer looks for the last parameter on CallActivityAsync.

To fix this, I can add a check if the method is defined in user code, as opposed to in our library. In order to keep the benefit of the analyzer in this case, I could look at the method parameter list of the user defined method and check specifically for "object input" to determine which parameter represents the input. If the user doesn't have a parameter like that, then I wouldn't continue analysis to avoid creating an unnecessary warning.
