### ISSUE TITLE
RaiseEventAsync fails to determine the correct orchestration status

### ISSUE THREAD

**Issue by stratever** [Azure/azure-functions-durable-extension#1618]
### Description
Given an application which uses SubOrchestration for frequent polling of an external service. The SubOrchestration invokes an activity which sends the request to a ServiceBus instance and keeps waiting for an external event. The remote service receives the request message and sends back the response to the same ServicBus instance. The response message is processed by a SB triggered function and it sends the response body back to the suborchestration by raising an event.  A RetryOption is configured for the SubOrchestration, like this:

```csharp
await context.CallSubOrchestratorWithRetryAsync(
                nameof(WorkflowSteps.WaitForCalculationReadiness),
                new RetryOptions(TimeSpan.FromSeconds(2), 150)
                {
                    Handle = e => e.SubOrchestrationShouldHandle()
                },
                readinessRequest);
```
The SubOrchestation triggers the retry mechanism by throwing an Exception as long as it gets unexpected response (basically this is the polling mechanism)

> NOTE: Due to some security gates, it's not possible to simply invoke the remote service with http call

![image](https://user-images.githubusercontent.com/17195530/102469854-899a8300-4053-11eb-8edd-e117771e0adc.png)

### Expected behavior
The receiver function raises the event without any error so the suborchestration can continue the process.

### Actual behavior
During this polling mechanism, the receiver function sometimes fails to raise the event with one of the following exceptions:

System.ArgumentException: No instance with ID '5d6623f8e64f4c70ab06cc99ef950498_19e01e32-8f34-549c-9472-94168287debc' was found.

System.InvalidOperationException: Cannot raise event CheckCalculationReadiness for orchestration instance dec2c4686b6b48f5afb77bc3c7a47d22_98fde17b-4f56-5ae4-a98f-baaff6f26d8b because instance is in Failed state

As the issue happens occasionally, I suspect the problem is the state synchronization of the SubOrchestration in the storage account. As it throws exceptions and keeps retrying, the orchestration state changes quite frequently (from Failed to Running) and it maybe out of sync when the IDurableOrchestrationClient.RaiseEventAsync fired. 

Is there any way to improve this so the RaiseEventAsync will detect the latest and up-to-date status without delay?

### Known workarounds
Exponential retry of raising the event to the SubOrchestration but this slows down the polling mechanism.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.2/2.4.0
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
Deployed in AKS, in the actual behavior, there are 2 orchestration IDs.

**Comment by liyubupt** [comment]
This is an issue that caused the workflow process to stop working, We're currently using this for one of the most critical business processes. This critical business process needs to be executed successfully and stable. I am very interested in any advice to solve this issue

**Comment by olitomlinson** [comment]
@stratever 
 
hmm interesting!

If your Orchestration is flipping between `Running` and `Failed` due to retrys, then it is reasonable to expect that at some point the RaiseEventAsync will fail when it attempts to raise an Event to a Failed orchestration.

My guess is that the SubOrchestration is spending a long time in the Failed state while the parent orchestration is waiting for the signal that it has failed and the async nature of how Orchestrations communicate through queue messages is exacerbating this problem, although I'm not 100% on this.

In the meantime, Is it a possibility to rework your Sub Orchestration such that your retries are internalised into the Sub Orchestration and an exception is only propagated to the parent orchestration under a terminal failure scenario? This way, your Sub Orchestration is never going to flap between Running and Failed, and you will have a much better chance of the Sub Orchestration being in the correct state (`Running`) to handle the event.

**Comment by ConnorMcMahon** [comment]
I noticed you are not specifying an instance id for your `CallSubOrchestratorWithRetryAsync` call. What orchestration instance id are you raising the event to from your receiver function? It doesn't look like what I would expect from the algorithm we use when you don't specify a suborchestration instance id. The algorithm is shown below.

`<parent-orchestration-execution-id>:<number-of-suborchestrations-scheduled>`.

This means that with `CallSubOrchestratorWithRetryAsync()`, will have each of its retries have a separate instance id.

**Comment by stratever** [comment]
@ConnorMcMahon The code below is just an example of how RetryOption is configured, the instance ID is explicitly specified:

```csharp
public static Task CallSubOrchestratorWithRetryAndCustomIdAsync(this IDurableOrchestrationContext context, string functionName, RetryOptions retryOptions, object input)
        {
            return context.CallSubOrchestratorWithRetryAsync(
                functionName,
                retryOptions,
                context.CreateNewCustomInstanceId(),
                input);
        }

        public static string CreateNewCustomInstanceId(this IDurableOrchestrationContext context)
        {
            return $"{context.InstanceId}_{context.NewGuid()}";
        }
```
The receiver gets the instance ID from the servicebus message.

**Comment by stratever** [comment]
@olitomlinson yes, it's possible to rework in that way (or introducing an exponential retry in the receiver can make the trick however it would slow down the polling process), If this is the expected behavior then it should be at least documented that suborchestration with RetryOption cannot be used for this purpose. The question is: Is it possible to improve the RaiseEventAsync in a way that it always finds the correct/latest status of the invoked (sub)orchestration?

**Comment by olitomlinson** [comment]
@ConnorMcMahon was in the right ball park with this hypothesis?

> My guess is that the SubOrchestration is spending a long time in the Failed state while the parent orchestration is waiting for the signal that it has failed and the async nature of how Orchestrations communicate through queue messages is exacerbating this problem, although I'm not 100% on this.

**Comment by cgillum** [comment]
It sounds like there are two distinct issues being mentioned here.

> System.ArgumentException: No instance with ID '5d6623f8e64f4c70ab06cc99ef950498_19e01e32-8f34-549c-9472-94168287debc' was found.

This could be potentially caused by a race condition. The sub orchestration won't actually save its state until after it performs its first action. If the first action taken by the sub-orchestration is to call the activity function, and if the external service sends a response back before the sub-orchestration has actually saved its state changes, then I would expect to see this problem. There are two potential workarounds for this:

1. Have the external service retry sending the response.
2. Have the sub-orchestration perform some other action first before sending a message to the external service. For example, scheduling a durable timer that expires immediately is a simple way to accomplish this.

> System.InvalidOperationException: Cannot raise event CheckCalculationReadiness for orchestration instance dec2c4686b6b48f5afb77bc3c7a47d22_98fde17b-4f56-5ae4-a98f-baaff6f26d8b because instance is in Failed state

In this case, it sounds like the sub-orchestration failed before it had a chance to get the response from the external service? My first question would be to understand why the sub-orchestration is failing, but putting that aside, there isn't really much more that can be done. If the sub-orchestration is being retried, then it will send another notification to the external service anyways so it should be fine to just ignore the failed delivery for a failed orchestration instance.

Generally speaking, there is always going to be a race condition between checking the status of the orchestration and then raising the event. This is unfortunately unavoidable since the external client has no control over the asynchronous state transitions of the target orchestration. The best that you can do is implement retry policies, either in the sub-orchestration itself or the external service.

Let me know if there are any other questions or clarifications I can provide for this issue.
