### ISSUE TITLE
Hibernating async/await state machine?

### ISSUE THREAD

**Issue by epsitec** [Azure/azure-functions-durable-extension#162]
You have taken the option to replay the full orchestration function on every _continuation_.

Would it have been possible to expand the experiment started by Lucian Wischik (back in 2012) where he hibernates and resumes an async function by serializing and deserializing the compiler generated state machine?

Blog post:

https://blogs.msdn.microsoft.com/lucian/2012/11/23/how-to-hibernate-async-methods-how-to-serialize-task/

**Comment by cgillum** [comment]
Thanks for the suggestion. Yes, we considered this general approach and it's really interesting. The main concern we identified is that the serialization format would be sensitive to changes in the CLR over time, and that kind of risk is very concerning. There are also concerns about how this would work for cross-language support.

The replay approach we chose is based on the event sourcing pattern and generally scales quite nicely. The payloads tend to be compact and saving state is a matter of making small appends to the existing history rather than reserializing the entire program state. We are also exploring ways to use caching to reduce the number of replays for very active orchestrations.
