### ISSUE TITLE
[Question] Entity persistence and output bindings

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1623]
When using a Service Bus output binding (such as `IAsyncCollector<Message>`) inside an entity operation, in what order do things happen?

Is the Entity State serialised and committed _before_ the async collector is flushed?

or is the async collector processed first, and only when it has successfully flushed, does the entity state get serialised and committed?

I ask the question because I want to ensure that service bus messages are successfully submitted first before the entity state is updated. I know I can just call `.Flush()` on the async collector manually, but there is no point doing this if the runtime is guaranteed to perform the operations in the desired order.

**Comment by ConnorMcMahon** [comment]
This is a great question. From an initial look at the code, I believe that the input bindings would be refreshed at every operation (even if we receive a batch of operations), and output bindings would be flushed after every operation as well. 

It also looks like for each operation, the "function execution" completes before we update the state, so the output bindings will flush then.

It's worth noting that I think JavaScript and Python entity functions execute all of an operation batches together as a single "function execution", meaning they have slightly different semantics. I don't think that is intentional, and we may want to consider the design here. @davidmrdavid for awareness here.

Regardless, I think we will want to verify this by stepping through the code here, and codify this somewhere in our documentation.

**Comment by davidmrdavid** [comment]
Noted.  I too suspect that out-of-proc SDKs will have a slightly different behavior, which is unintended. I'll look to fix this :)

Just to clarify your answer to @olitomlinson , @ConnorMcMahon: are you saying that the output binding gets flushed *after* each state update, right?

**Comment by ConnorMcMahon** [comment]
The opposite. The output binding flushes when we finish the function execution, and then the orchestration state is updated.
