### ISSUE TITLE
ReadEntityStateAsync xml comments mentions 16KB limit for returning serialized state

### ISSUE THREAD

**Issue by andybooth** [Azure/azure-functions-durable-extension#1631]
As large entity state is serialized to blob storage, is the phrase "Returns default(T)... if the JSON-serialized state of the entity is larger than 16KB" still valid in the xml comments?

https://github.com/Azure/azure-functions-durable-extension/blob/3bdd5704f8ac41b4c549d6e0d811a6428d9c4c1f/src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityClient.cs#L86

```
        /// <summary>
        /// Tries to read the current state of an entity. Returns default(<typeparamref name="T"/>) if the entity does not
        /// exist, or if the JSON-serialized state of the entity is larger than 16KB.
        /// </summary>
        /// <typeparam name="T">The JSON-serializable type of the entity.</typeparam>
        /// <param name="entityId">The target entity.</param>
        /// <param name="taskHubName">The TaskHubName of the target entity.</param>
        /// <param name="connectionName">The name of the connection string associated with <paramref name="taskHubName"/>.</param>
        /// <returns>a response containing the current state of the entity.</returns>
        Task<EntityStateResponse<T>> ReadEntityStateAsync<T>(EntityId entityId, string taskHubName = null, string connectionName = null);
```

**Comment by ConnorMcMahon** [comment]
@sebastianburckhardt, is this limitation still in affect, or do we end up storing the state in storage blobs at this point?

If not, how much work would adding support for larger states be?

**Comment by sebastianburckhardt** [comment]
This limitation is not in effect anymore (I am not even sure if it ever was). We have a unit test `DurableEntity_LargeEntity` that tests using a large entity state.

This wording was probably added out of caution to reflect limitations of table storage. However, since the entity state is stored as the orchestration input for continue as new, it is automatically stored in a blob if its size exceeds table storage limitations.

We will need to update the limitation.
