### ISSUE TITLE
Guidance on enabling scaling for Durable Functions integrated with VNET

### ISSUE THREAD

**Issue by gled4er** [Azure/azure-functions-durable-extension#1632]
### Description

It will be beneficial to have a link or paragraph in the Durable Functions documentation explaining that if Durable Functions and the Storage Account it is using are integrated with VNET [Runtime Scaling Monitoring](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#premium-plan-with-virtual-network-triggers) should be enabled. Without it Durable Functions is not scaling as expected.

**Comment by ConnorMcMahon** [comment]
I'm not sure if we should duplicate that information in Durable Functions, since we don't have anything additional to add that isn't already present in the Azure Functions documentation.

In general, unless there are networking specific parts to Durable Functions (which there shouldn't be now that alot of the storage account details have been simplified), I don't think we should maintain separate docs in our own documentation.
