### ISSUE TITLE
Azure durable function in custom container - monitoring CPU doesn't work and long high memory usage

### ISSUE THREAD

**Issue by 0gust1** [Azure/azure-functions-durable-extension#1654]
### Description
Hi, we use Azure durable functions in Python to deploy and use a ML inference workload.

Due to the dependencies complexity (our workload uses several non-standard python deps and C++ code), we wrapped everything in a custom container, running on ElasticPremium plan 1. As custom container imply long cold-start times, we let 1 instance always on.

During our stress/scaling tests, we noticed that very few metrics are outputted on AppInsights, notably the CPU is not OK During the computation, it should be between 50 and 100%, this was verified by ssh-ing to the instance and issuing a `top` command. In AppInsight it barely go above 1%.

We also noticed, that even after computation completion, the memory usage stays quite high (1Gb-ish), and it takes between 10-15 hours to come back to 300-400 Mb-ish that seems the baseline of the memory used by an idle function app instance.

### Expected behavior

* We would like to monitor the CPU usage (mainly to analyze and take the good scaling decisions according to our user demand)
* We would like to understand and remedy to this long-term high memory usage, as it will impact our costs consequently.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: `"version": "[2.*, 3.0.0)"`
- **Azure Functions runtime version (1.0 or 2.0)**: 2
- **Programming language used**: Python

### Screenshots

![Capture d’écran 2021-01-19 à 21 47 54](https://user-images.githubusercontent.com/578154/105099398-e7cfe100-5aab-11eb-8ff4-a1fc0f81c7ea.png)

**Comment by cgillum** [comment]
Hi @0gust1. This appears to be an issue with the Azure Functions Elastic Premium plan and probably not a Durable Functions issue. The best way to resolve this would be to open a support ticket against the Azure Functions service so that the platform engineers can investigate. If I understand correctly, the biggest problem to emphasize is the incorrect reporting of CPU usage in Application Insights.

Regarding high memory usage, this might be specific to your app or to the Python runtime. It's hard to know for sure. One thing that isn't clear to me is whether this is actually causing any problems. The billing for the elastic premium plan is the same whether memory usage is high or low. In your support ticket, if you choose to also ask about the memory usage, it would be good to include more details about _why_ the memory usage is problematic so that customer support can properly assess the urgency.

Let us know if there's anything else we can help clarify.

**Comment by 0gust1** [comment]
Hi @cgillum ,
Thanks for the feedback! 

Some precisions about memory usage:
* Premium plan for functions *are* billed with CPU & memory usage: https://azure.microsoft.com/en-us/pricing/details/functions/ ("Premium" section) - it's not very expensive for our current usage but may become a problem later
* We're pretty sure that the idle memory usage doesn't come from our code (we know pretty well the behavior of our code). If we have time, we'll conduct dichotomy tests to be sure.

Thanks again for your time, we'll go along with your suggestions.
