### ISSUE TITLE
Document precise conditions for an orchestrator's "completed" status

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-durable-extension#1665]
**Is your feature request related to a problem? Please describe.**
I would argue that, intuitively speaking, an orchestrator would be marked as completed when it has returned (via a return statement not just completed an invocation). However, orchestrators won't be marked as complete until all of their "open tasks" have complete *and* the orchestrator has returned. This can cause some confusion, especially when `WhenAny` is used.

**Describe the solution you'd like**
To add a "warning" block in the [Instance Management](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp) docs explaining when an orchestrator's runtimeStatus would be set as completed. It would read something like "Currently, an orchestrator is not marked as completed until all of its scheduled tasks have completed *and* it has returned. This is particularly noteworthy for cases where `WhenAny` is used".

**Describe alternatives you've considered**
Another alternative would be to change the implementation of this logic [here](https://github.com/Azure/durabletask/blob/075b2ef8ca173203a7e9777a7cc846c44224233b/src/DurableTask.Core/TaskOrchestrationExecutor.cs#L86-L112) to make it so an orchestrator is marked as completed as soon as it returns (via a return statement) but that might have unwanted consequences. While this might be more intuitive, I don't believe it's worth the risk.

**Additional context**
Related to: https://github.com/Azure/azure-functions-durable-js/issues/234

**Comment by olitomlinson** [comment]
@davidmrdavid

I strongly agree with you that an orchestration should go to complete when an orchestration returns, rather than when all tasks have completed. 

This tripped me up when I was first learning DF and I got very frustrated about it, as I had to rework my App to support this unexpected behavior.

I get that changing the behaviour might not be desirable, but certainly an option to override the default behaviour would be welcome IMO.
