### ISSUE TITLE
Communicating with Durable Entities from Orchestrations Clarification

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#1679]
The documentation states the following:

> Only orchestrations can read an entity's in-memory state, as described in the following section.

Just to clarify my understanding, when an orchestration "calls" an entity, is the communication happening behind the scenes using storage queues message passing? Or is the orchestration communicating with the entity in memory?

I know these are implementation details but I always like to keep these types of things in mind when I am designing my read and write access patterns. I'm seeing my usage pattern following "ask-tell" multiple times in my orchestration flow and the answer to my above question will help me with my design and implementation.

Thanks!

**Comment by cgillum** [comment]
@sebastianburckhardt can you help clarify?

**Comment by sebastianburckhardt** [comment]
Yes, the communication happens via storage queues and is thus reliable. There is a "call operation" message that goes through the control queue that owns the entity, and then a "operation response" message that goes through the control queue owning the orchestration. 

The "operation call" message is processed transactionally with respect to the entity state: each operation is applied to the entity state exactly once. 

The wording "in-memory state" in the docs is unfortunate, since in the DF programming model we do not make a distinction between the state in memory and the state in storage. The execution engine has flexibility in choosing when to move things between memory and storage.

**Comment by mpaul31** [comment]
Thanks you @sebastianburckhardt
