### ISSUE TITLE
Log only on non-replay executions

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-extension#170]
Currently, log statements are output on every execution, non-replay and replay alike. To log only on non-replay executions, code must look something like:

`if (!ctx.IsReplaying) log.Info("Calling F1.");`

This is tedious to write, clutters up code, and is easily missed or forgotten. it would make for a better developer experience and cleaner code to simplify logging for our users and make logging only on non-replay executions the default behavior.

**Comment by gled4er** [comment]
Hello @cgillum,

Shall this change apply to the logs we send to Application Insights as well? 

Thank you!

**Comment by cgillum** [comment]
That's a great question. I had not thought about it deeply yet, but it probably makes a lot of sense since that is potentially a huge amount of data going to Application Insights that will cost the customer money.

Here is my thinking for the implementation design of this work item:

* I don't think we can implement this for `TraceWriter` because I don't think it is extensible. `TraceWriter` is being deprecated though so maybe that's not an issue.
* Let's create a Boolean flag that controls whether to log replays or not. By default, let's not log replays. Developers can turn replay logging on if they really want it for deeper debugging purposes.
* Let's find a way to wrap the `ILogger` we use with one that can filter out replay logs. I'm not sure yet exactly how to do this, but I feel reasonably confident that we can control this somehow using the host extensibility.

We should continue to write ETW analytics for replays regardless of any user settings - that's because we want that data for our own internal diagnostics. If we focus our changes on `ILogger` then this should not be an issue.

**Comment by gled4er** [comment]
Hello @cgillum,

I just saw your comment only after submitting the initial pull request. 

Thank you very much for the insights! 

I will improve my pull request based on your suggestions.

Thank you!
