### ISSUE TITLE
How to send acknowledgment to azure stream analytic from azure durable function ?

### ISSUE THREAD

**Issue by asthanarht** [Azure/azure-functions-durable-extension#1705]
I have Azure stream analytics event and outputting to azure durable function and we need to send acknowledgment from the starter function when my orchestrator function is completed but from current flow durable function will return new status (**CreateCheckStatusResponse**) response and I dont know how to send back httprequest req status as OK. 

```
[FunctionName("EmailSentimentalStarter")]
        public static async Task<HttpResponseMessage> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestMessage req,
            [OrchestrationClient] DurableOrchestrationClient starter,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            var con = req.Content;
            var inp = await req.Content.ReadAsStringAsync();
            var payload = JsonConvert.DeserializeObject<IEnumerable<EmailModelEntity>>(inp);

            var orchestrationResult= await starter.StartNewAsync("O_EmailSentimentalAnalysis", payload);
         
             return starter.CreateCheckStatusResponse(req, orchestrationResult);
        }
```

what is the best way to send ack from starter like 

`return req.CreateResponse(HttpStatusCode.OK)`

**Comment by olitomlinson** [comment]
@asthanarht 

Assuming that ASA is requiring a **synchronous** response, the only way you can do this is by implementing a loop in the starter function which repeatedly checks the status of the orchestration using the `starter.GetStatusAsync()` API and return OK when the orchestration status is `complete`. 

This is going to be blocking of course, so if your orchestration takes a while to complete, you can expect your starter function to be running at least that long before the HTTP returns its response to ASA.

I'm no ASA expert, but depending on your use-case I'm pretty sure that waiting for a response from the starter function is going to damage your ASA job throughput, which might be worth considering. I also wouldn't be surprised if ASA will terminate the request if it has to wait too long for a response.

If your ASA job doesn't have a downstream dependency on the result of the orchestration, I would strongly recommend treating the Orchestration as Fire and Forget invocation from ASAs perspective, and not wait for an orchestration result.

**Comment by ConnorMcMahon** [comment]
I am not super familiar with Azure Stream Analytics, or the specific scenario that you are trying to use it with, but from your description, it sounds like all that Azure Stream Analytics is expecting is an HTTP response with a 200 status code.

In that case, you can just use `return new HttpResponseMessage(HttpStatusCode.OK)` to return a 200.

That does leave the question of how you are going to keep track of the orchestrations you are starting via these stream analytics events. This really depends on how your overall application structure is set up, but we also provide [helpful orchestration management APIs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#query-instances) so you can keep track of your in-flight orchestrations, as well as failed and completed orchestrations.

**Comment by olitomlinson** [comment]
@ConnorMcMahon 

> we need to send acknowledgment from the starter function when my orchestrator function is completed

Sounds like he needs to return a response when the orchestration is _completed_, not _started_ ?

**Comment by ConnorMcMahon** [comment]
Ah yes, good call out @olitomlinson.

In that case, we do provide [a method](https://github.com/Azure/azure-functions-durable-extension/blob/e600de93b78eb45335947741232292ea60c1530e/src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs#L85) that allows you to wait for the orchestration to complete. Note that if the timeout passes and the orchestration is still not complete, then the http response message will contain the same response as `CreateCheckStatusResponse` is in your current code.

That being said, it is _highly_ discouraged to treat orchestrations as synchronous actions. They are designed to be run in an asynchronous fashion, which is why we provide an API surface that supports the 202 pattern. Orchestrations can often run for minutes, if not hours, so blocking on an HTTP request is often not feasible. It's also worth noting that the Azure Functions infrastructure will automatically cancel any request that takes longer than 230 seconds.

**Comment by asthanarht** [comment]
Thanks @ConnorMcMahon  and @olitomlinson  for Suggestion. Looks to me its not easy way to send ack to ASA.
