### ISSUE TITLE
Question: What kind of phenomenon will it be after breaking the limit maxConcurrentActivityFunctions value?

### ISSUE THREAD

**Issue by komayama** [Azure/azure-functions-durable-extension#1709]
I have a tiny question for durable functions setting (maxConcurrentActivityFunctions) in host.json
 
I'm using durable functions on Dynamic Plan. I think this setting value (maxConcurrentActivityFunctions) not fix on Dynamic Plan, If I'm not setting this value. when their function application is running on the large instance (CPU*4), maxConcurrentActivityFunctions value limit 10x so 40 activity function is limit.
If breaking the limit this value, what is happen on function host? I think over this value function host or instance will be reboot.

**Comment by cgillum** [comment]
Hi @komayama. The `maxConcurrentActivityFunctions` limit is automatically enforced by Durable Functions. It is not possible to exceed it. For example, if an orchestration does a fan-out of 100 activity functions, then the current app instance will only try to run 10, 20, or 40 of them at a time before executing the rest of the activity functions. The Consumption plan infrastructure (scale controller) will then see that functions are being throttled and automatically scale the app out to more instances.

The reason for this setting is if a developer needs more concurrency (to run more activities quickly without waiting to scale) or if they need less concurrency (because too many concurrent activities may consume too much CPU, memory, or network).

Even if it were possible to exceed this limit, the app would not recycle. The only reason the app would recycle is if it runs out of memory or consumes too many TCP connections (I believe 600 is the limit). The `maxConcurrentActivityFunctions` and `maxConcurrentOrchestratorFunctions` settings can help ensure that an app isn't consuming too much memory or TCP connections.

Let me know if that answers your question.

**Comment by ConnorMcMahon** [comment]
I do believe that @komayama is technically correct that our logic does not take into affect that "large" workers on consumption plans really only have one core available to them, so we should not set the concurrency to 40 despite there being 4 cores on the VM. This should be being fixed with #1646 as a part of our next release.
