### ISSUE TITLE
Cannot terminate orchestrations stuck in the pending state

### ISSUE THREAD

**Issue by morphvale** [Azure/azure-functions-durable-extension#1715]
### Description
This issue relates to [1380](https://github.com/Azure/azure-functions-durable-extension/issues/1380)

We use durable [singleton orchestrators](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=csharp#singleton-example) with something similar to the [human interaction pattern](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp#human).

Our workflow is the following:
Main function reacts to CosmosDB events. The events (DDD Pattern) come from our backend, and are, in this particular case, created when a device reports some data.

When we get the type of event we monitor with a particular value, we check if we already have an orchestrator started for this deviceId, with a RuntimeStatus of either Running, Pending, or ContinuedAsNew, and, depending on the result, either StartNewAsync(deviceId, orchestratorName, eventData) or RaiseEventAsync(instanceId, eventName, eventData).

The StartNewAsync will launch a singleton orchestrator which starts a durable timer, and awaits for either the timer to expire, or WaitForExternalEvent<eventName>(eventData), to decide if it should launch a activity or not.

Most of the time this works as expected. However, we have to monitor the instances table and query for orchestrators with RuntimeStatus Pending which is older than our timer expiration delay, as sometimes some orchestrators will remain stuck in this Pending state. The only solution we could reliably use so far is the one in the linked ticket, to manually set the stuck orchestrators to Terminated.

We've attempted to add additional code that checks if the orchestrator is expired (using the status LastUpdatedTime) and if this is longer than our timer expiration, TerminateAsync(deviceId, reason).
However, while this seems to work fine in development (where we can not really reproduce the stuck Pending RuntimeStatus, but we can only manually change it), in production, even though our logs point the method has been called, we still find stuck orchestrators.

Also, reducing the number of events we receive and process is not an option, since we still must meet our acceptance criteria for the feature.

### Expected behavior
TerminateAsync should terminate orchestrators stuck with RuntimeStatus Pending.

### Actual behavior
TerminateAsync does not terminate orchestrators stuck with RuntimeStatus Pending.

### Known workarounds
Open the instances table with Azure Storage Explorer, look for RuntimeStatus Pending orchestrators older than desired value, manually change RuntimeStatus to Terminated and save.

### App Details

- **Durable Functions extension version (v2.4.1)**:
- **Azure Functions runtime version (~3)**:
- **Programming language used (C#)**:

**Comment by morphvale** [comment]
@davidmrdavid opened ticket and linked, as requested.

**Comment by davidmrdavid** [comment]
Thanks @morphvale, I'll bring this up during our Scrum meeting today. We are currently nearing the end of a release cycle so there's not enough time to prioritize this for the immediate next release, but this will probably be one of our first work items for the upcoming one

**Comment by davidmrdavid** [comment]
Hey @morphvale, just a quick follow-up.
To debug issues like this, it is **crucial** if not almost necessary for us to be able to access the logs of an application that experienced this issue. Do you mind providing the following information so we can get started in our investigation:

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

Thanks!

**Comment by morphvale** [comment]
Hi @davidmrdavid 
We just got  a new orchestrator stuck, at 2021-03-10T16:26:14.347Z, which we have still not terminated (noticed it this morning).
We got approval to share the functions resources, however, we can only do this in a private conversation, and as long as this information does not go public. Is this something that is feasible?

**Comment by morphvale** [comment]
Hi @davidmrdavid 
We've also noticed that whenever and orchestrator remains stuck in _Pending_, it has the ExecutionId set to _null_. The other orchestrators which are not stuck appear to have a valid GUID.

**Comment by davidmrdavid** [comment]
Hi @morphvale, I understand your concern. Feel free to reach out to my private Microsoft email at `dajusto@microsoft.com` and we can discuss those private details there.

**Comment by ConnorMcMahon** [comment]
Orchestration instance id + region + approximate timestamp should be enough information for us to use if you are able to share those publicly.

Also, I believe that it is expected behavior that `Pending` orchestrations have no execution id. I don't think one is assigned until the orchestration executes for the first time, and that is when we move the orchestration from `Pending` to `Running`.

**Comment by davidmrdavid** [comment]
Hi @morphvale, I was just looking at this issue. Indeed, I can find a handful of discarded work-items in our logs, which usually represent orchestrators that are unable to process any work, sometimes due to a message-ordering race condition.

To help diagnose this issue further, I need to get a better understanding of your code. I'm confused about where these expiration timers are created. Are they created inside the orchestrator, or are they created in the durable client code, that is, the code that starts the orchestration? I'm asking because `Pending` orchestrations should correspond to orchestrations that have done no work, so I wouldn't expect the Pending orchestrator to start a timer. Could you please clarify the interaction between code components? Thanks!

**Comment by morphvale** [comment]
Hi @davidmrdavid 

Our workflow is the following:

We have a _CosmosDBTrigger_ function which reacts to events written to a ComosDB collection by our backend, which gathers data from certain sources.

An event which we process with this function has a counter and an id of its origin (there can be events from multiple origins with different ids, each will launch its own durable orchestrator using the unique origin id).

When this event triggers the function, we first try to _GetStatusAsync_ the status of an orchestrator with the origin id. If the orchestrator exists, and is in a _Running/Pending/ContinuedAsNew_ state, we then _RaiseEventAsync_ with the origin id, type and value of event. Otherwise, we _StartNewAsync_ a durable orchestrator (using the origin id).
When starting, this durable orchestrator registers a durable timer, and awaits _Task.WhenAny_ for either _WaitForExternalEvent_ of the same type as the counter or the durable timer to expire, to decide which activity to launch.

If _WaitForExternalEvent_ finishes first, with a received counter and a value of 0, the durable timer is canceled, and started again, waiting for same as before.
Otherwise, if the counter has a value higher than 0, the timer is canceled (maybe we should ignore canceling the durable timer here, and simply _TerminateAsync_ the orchestrator with the origin id?)

If no counter is received and the timer expiration passes, an activity is called from within the orchestrator, to perform our desired actions.

The counter can be received somewhere between several times a second to once every few minutes. We have no control over the frequency, as it depends on the data source.

**Comment by cgillum** [comment]
I took a look at this issue in the morning. I am able to see that at about 2021-03-11 15:02:50 UTC, a message was received to start a new instance of this orchestration (instance ID = **4f9bbc2b-c21e-41d5-886b-4a421a62d0bf**). However, something happened to the function app process where it seems to have died before the orchestration had a chance to checkpoint it's progress. 5 minutes later, as expected, another VM picked up the start message to re-execute it, but it seems the Durable Task engine may have gotten confused and failed to actually process it correctly, which is why it remained in Pending.

A few other notes:

> We've also noticed that whenever and orchestrator remains stuck in Pending, it has the ExecutionId set to null. The other orchestrators which are not stuck appear to have a valid GUID.

As Connor mentioned, this is normal and the ExecutionId will be added later. I'm actually making a fix in an active PR to make sure this is set even for the initial `Pending` record. There shouldn't be any runtime impact of this current behavior, however.

> I can find a handful of discarded work-items in our logs, which usually represent orchestrators that are unable to process any work, sometimes due to a message-ordering race condition.

There are indeed several discarded timer events. This is normal if a timer expires _after_ an orchestration completes because at that point the timer is no longer valid. However, I also noticed that the execution start message was getting discarded as well because the runtime appears to have gotten into a confused state (see my investigation notes above). This is not expected and needs more investigation.

I'll continue to look at this to try and figure out why the runtime is getting confused. Even if app processes stop executing (hang, crash, etc.), the expectation is that we can gracefully recover 100% of the time, so there is certainly a corner case here that needs to be fixed.

**Comment by cgillum** [comment]
After looking at this again, I think instance **4f9bbc2b-c21e-41d5-886b-4a421a62d0bf** may be a red herring. While there were definitely some strange issues it ran into, it doesn't appear that it ever actually got stuck in the Pending state. I also didn't see any termination requests during the time period I looked. I may need to look at a different instance.

**Comment by cgillum** [comment]
I spent more time looking at this and I think I understand what's happening. It seems to be a race condition between two things:

1. Restarting an instance of a completed orchestration
2. Sending an external event to the restarting instance

In one of the cases I looked at, I can see that two external events were sent to an orchestration that was being restarted. All three messages were received in the same dequeue batch and were processed together. However, because the external events arrived in the queue before the orchestration start message, we ended up loading the old, completed orchestration history instead of creating a new history for the new orchestration instance. The message processing pipeline then sees that the runtime status of this old instance is "Completed" and discards all three messages.

This behavior, however, is problematic if one of the messages in that batch is intended to create a new generation of the old instance. In this case, we already updated the Instances table with a Pending status for this ID, but then proceeded to erroneously discard the message that was supposed to start this new orchestration generation, leaving us in an inconsistent state. Subsequent Terminate messages were also discarded because the orchestration history indicated that the instance was already in a Completed state.

@morphvale this is a bug on our side where we need to handle the condition I mentioned above better to avoid getting into a confused state. I don't know if there is an easy workaround for you given the constraints you mentioned. I do wonder if you might be better of using [Durable Entities](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp) as part of your Cosmos DB message handling because entities can be started implicitly via events (signals) and thus don't have this weird race condition. If you need to call out to activities, your entity can still [start orchestrations](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableentitycontext.startneworchestration?view=azure-dotnet#Microsoft_Azure_WebJobs_Extensions_DurableTask_IDurableEntityContext_StartNewOrchestration_System_String_System_Object_System_String_), and you don't have to worry about the race condition because entities are single-threaded singletons.

**Comment by davidmrdavid** [comment]
Hi @morphvale, this issue should have been fixed with the latest release of the durable-extension: version 2.5.0. Could you please upgrade and let us know if you still experience this issue? Thanks!

**Comment by morphvale** [comment]
Hi @davidmrdavid, thank you for the update.
We are planning an update for our instances in the following days, and we'll still have to monitor for a few days just to confirm we're not seeing the issue anymore.
I will get back with information on this once the update and monitoring are deemed ready.

**Comment by morphvale** [comment]
Hi @davidmrdavid 

It's been almost two weeks since we updated our production instances and we have not observed the original issue since. For now, we consider this issue closed from our side.

Thank you for your help in getting this fixed.

**Comment by davidmrdavid** [comment]
This is wonderful to hear ✨! Please reach out again if you experience any further blockers or have questions :)
