### ISSUE TITLE
Performance Issue | Resolved...but not sure why

### ISSUE THREAD

**Issue by dsm0880** [Azure/azure-functions-durable-extension#1739]
Hey Durable Function guys. Long time user, long time fan :) We have an application that has been using the durable function platform since its GA and love working with it. Currently we are on 2.3.1. Over its lifetime we have had periodic performance issues. The symptom is not new, but root causes are always different. Glossing over how the queue gets into this state, simply put, queue messages become "stuck" in 1 or 2 control queues. "Stuck" in this case means high Dequeue Count...I'm talking 300-400. The queue messages then seem to "hoard" the throughput of the function app. Simply clearing a few of these (~10) releases a massive number of queued messages. 

- **This is my first question**. Why would a few bad apples (messages with high dequeue counts) poison the bunch (the rest of the queue messages in the control queue). We have seen this behavior before and I can't explain what is going on, hence the ticket.

Secondly, we have 4 control queues. While I read and feel as though I understand the leasing model between function app instances and the control queues, it "feels" like 2 of the 4 control queues take up the majority (if not all) the orchestrations.
- **This is my second question** - When these queues become "stuck," why does it only affect a minority (2 of the 4) control queues?

If you are interested in why the control queues result in messages with high dequeue counts, it was recently due to disabling an orchestration function directly in the portal. I believe you are addressing this in an upcoming release, but the framework does not handle that use case gracefully it appears. Another issue that seems to cause this is in the case of deleting the large message blobs directly without stopping the orchestration instance. You may say, "why the hell did you do that?"...but if you get an unexpectedly large message in production that tries to deserialize and consumes all your memory to only re-queue again, you would do anything you can to stop it too :) Not saying you should support that use case, but thought I should point that out.

Please feel free to point me to an article if that is easier,
Thanks,
Daniel

**Comment by cgillum** [comment]
Hey @dsm0880 thanks for reaching out! I'll try to address some of your questions:

> Why would a few bad apples (messages with high dequeue counts) poison the bunch (the rest of the queue messages in the control queue).

It depends on what happens when those bad apples get dequeued. For example, if it results in an out-of-memory exception, then your entire app can crash and all work stops until things can recover. If it results in an unhandled exception in the internal engine, then it will cause the internal dispatcher to back off for 10 seconds to avoid the potential of a tight failure loop. This, unfortunately, also slows everything down. Lastly, a bad message that can't be processed just eats up CPU cycles which can cause some slowness.

> When these queues become "stuck," why does it only affect a minority (2 of the 4) control queues?

I'm not sure what you mean when you say a queue becomes "stuck". You mentioned that some control queues take up most of the orchestrations, and this can happen if you generate your own instance IDs such that our hash algorithm doesn't distribute them evenly. This shouldn't happen with random GUID instance IDs, which is the default, but it might happen with app-generated instance IDs. If you're relating this point to the first question, it could be because one of those queues has "bad apples" in it, affecting all other orchestrations that are executing on the same app instance. If you are scaled out to multiple app instances, then the impact of bad apples is isolated such that some app instances (the ones that own the lease for the poisoned queue) will see slower processing while some app instances (which have leases on the good queues) will run just fine.

> If you are interested in why the control queues result in messages with high dequeue counts, it was recently due to disabling an orchestration function directly in the portal.

I'm not completely sure, but this might be the case I mentioned where we have an internal failure that results in the dispatcher waiting for 10 seconds before processing any more messages. I don't believe we handle the case very well where you schedule the execution of a function, but then disable that function after it has been scheduled and before it starts running.

If you'd like more insights into what's going on under the hood, consider enabling the [Durable Task Framework logging](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#durable-task-framework-logging). A lot of log information gets emitted, so you might want to stick with just warnings/errors to avoid big Application Insights billing increases, but having those logs will give you a lot of critical information the next time you encounter issues like these. We can also help diagnose issues faster if you can point us to specific log warnings and errors that you observed when reporting a problem. :)

Let us know if there are any other questions we can help answer!
