### ISSUE TITLE
Long delay in Orchestration completed and started event

### ISSUE THREAD

**Issue by ZeeshanFastian** [Azure/azure-functions-durable-extension#1791]
In my orchestration function, I have defined a loop of more than 1000 items. With-in the loop I have two activity functions. All calls are synchronous. This is working fine but sometimes I have noticed delays between Orchestration completed and start event. Please find the attached image.  In a loop of 1000 items, I usually face 5 -10 delays like that. Can someone please explain why I am facing these delays? 

![HubHistory](https://user-images.githubusercontent.com/22072244/114690292-385b8100-9d1f-11eb-822a-c9032c6dc01b.png)

**Comment by ConnorMcMahon** [comment]
@ZeeshanFastian, I can't identify quite why, but it looks like your application restarted mid-activity execution. When a worker grabs an activity to execute, it locks the queue message for 5 minutes, so if the worker that grabbed the queue message crashes before executing your code, another worker won't grab it until that visibility timeout expires. This visibility timeout is configurable in the host.json, but decreasing it lower than the maximum activity execution time could occasionally result in duplicate activity executions.

If you are experiencing this frequently, then something odd must be causing you application to be crashing fairly frequently. Maybe provide some additional instance ids + timestamps. When you provide these, please provide them as plain text so I don't need to copy them as an image.

**Comment by ZeeshanFastian** [comment]
Yes, this is happening quite often. In every job, we have noticed two to three times this delay is happening. Below you can find the delay details that we have faced during running single job.

Instance   Id | Event | Timestamp
-- | -- | --
dc441ec04de44c66802bbb1ee499ada3 | Completed | 2021-04-22T14:42:09.625Z
  | started | 2021-04-22T14:47:51.760Z
  |   |  
  | Completed | 2021-04-22T15:10:22.493Z
  | started | 2021-04-22T15:16:30.542Z
  |   |  
  | Completed | 2021-04-22T15:36:51.209Z
  | started | 2021-04-22T15:42:29.964Z
  |   |  
  |   |

**Comment by cgillum** [comment]
Just to clarify what these entries mean:
* **OrchestratorCompleted**: This means the orchestrator finished executing its most recent replay.
* **OrchestratorStarted**: This means the orchestrator was woken up because it was given work to do and is executing another replay.

The delays between "completed" and "started" don't necessarily indicate a problem - it could be very normal. A delay simply means that your orchestrator went to sleep waiting for an activity function to execute. The actual question that needs to be answered is why the _activity_ is taking 6'ish minutes to complete.  This delay is represented by the delay between **TaskScheduled** and **TaskCompleted**.

It sounds like Connor identified an application restart. I suggest taking a look at your logs in Application Insights to help figure out what's going on.
