### ISSUE TITLE
Multi-threading Detected in Orchestrator Function

### ISSUE THREAD

**Issue by dvmorris** [Azure/azure-functions-durable-extension#181]
I have an orchestrator function that loops over a series of records in an Azure Table and calls an Activity defined in the same class once for each iteration of the loop. 

When I try to execute the code, I get an error that says multi-threading was detected, and the function dies. Here is what the code looks like:

```
        [FunctionName("FunctionName")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context)
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("ConnectionString");
            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();
            CloudTable table = tableClient.GetTableReference("TableName");
            TableQuery<TableEntity> query = new TableQuery<TableEntity>().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, "PartitionKey"));

            var outputs = new List<string>();
            // query the table and get back an array of records
            var entities = await ExecuteQueryAsync(table, query);

            foreach (TableEntity entity in entities)
            {
                outputs.Add(await context.CallActivityAsync<string>("ActivityName", entity.RowKey));
            }

            return outputs;
        }
```

**Comment by cgillum** [comment]
This is because you are doing async I/O in the orchestrator function, which is not allowed. Take a look at this documentation to understand the rules for orchestrator functions: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-checkpointing-and-replay

To fix your orchestrator function, wrap your table storage logic in an activity function and call that activity function from your orchestrator function.
