### ISSUE TITLE
Intermittent issue with sub-orchestration not starting

### ISSUE THREAD

**Issue by danielrouleau** [Azure/azure-functions-durable-extension#1829]
### Description
We have an orchestration that calls a sub-orchestration that we never saw execute, and it still says the parent orchestration is in the running state. We'd have expected it to execute and return relatively quickly, and I didn't see it queued up anywhere to the best of my knowledge. This function app runs as an eternal orchestration and it runs through this loop of many sub-orchestrations for many iterations, but fails all of a sudden at this particular sub-orchestration after some period of time. The same thing happened for other orchestration instances at a later time after many successful iterations, but at the same area of code. Looking for any guidance or clues if possible from the internal logs.

### Expected behavior
Orchestration calls sub-orchestration, that sub-orchestration executes and returns to parent.

### Actual behavior
This runs successfully for some time and then fails at one of the sub-orchestrations that was previously successful. It always seems to fail around the same step in our overall workflow.

### Known workarounds
We currently have the customer start a whole new orchestration to work around the problem, since these are eternal orchestrations

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.3
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

- **Timeframe issue observed**: 2021-05-06T13:06:22Z
- **Function App name**: arcfm-gdbm-orchestration-eastus
- **Function name(s)**: PostVersionOrchestration
- **Azure region**: EastUS
- **Orchestration instance ID(s)**: 1c582efd-f130-41a3-8972-f4545298e5a5_PostInnerLoop
- **Azure storage account name**: arcfmgdbmeastus

A **working** example that ran slightly later would be instanceID bb0c27a5-3aa2-485e-84dd-c3a0629f3836_PostInnerLoop

Another failure
fa710dc7-4dd5-456d-b976-0e9090b97589_PostInnerLoop  at 2021-05-06T18:17:14Z

**Comment by danielrouleau** [comment]
As a follow-along to the above, we are seeing this now with some consistency, at least once every 2 days or so for this given app. Recreating the orchestration with a new ID gets it unstuck for about another day or so which is our current mitigation effort.

**Comment by cgillum** [comment]
Is the sub-orchestration you're referring to **1c582efd-f130-41a3-8972-f4545298e5a5_PostInnerLoop_BeforePrePostReconcileAH**? I noticed that the Durable Task Framework is deleting the start message for this sub-orchestration instance immediately after receiving it. I also noticed at the same time (2021-05-06 13:06:22.2086058) it's detecting an timer-fired message for an old iteration of this same sub-orchestration from exactly 5 minutes earlier. I can't help but wonder if there is some weird race condition related to your reuse of sub-orchestration instance IDs and the timing of your timers and start messages.

Unfortunately it's not obvious to me why this is happening, and there are some tracing bugs that are hiding some of the telemetry that I rely on to debug tricky issues like these. The tracing bugs and similar race conditions (with similar symptoms) will be fixed in an upcoming release, and I'm wondering if your issue will be resolved as well. For example, this PR might actually fix the issue you're running into as it addresses a class of related "orchestration not starting" issues: https://github.com/Azure/durabletask/pull/531

If I were to provide you with a prerelease build of one of our dependent nuget packages, would you be willing to try it and see if you can still reproduce the problem?

**Comment by danielrouleau** [comment]
Yes the BeforePrePostReconcileAH is the sub orchestration that fails to start. We could certainly try a prerelease nuget package to see if it affects the behavior, our customer that sees this often is the only one using this app service and is keen for a fix. I did have a suspicion our re-use of the IDs might be to blame and I could come up with a strategy to alter those but a fix like this would be preferable if it does prove to solve it.

**Comment by cgillum** [comment]
I've uploaded a prerelease version of this nuget package here: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.DurableTask.AzureStorage/1.8.6-preview. It hasn't gone through our full validation pipeline (which includes things like performance runs and compatibility checks) but it passes in our CI and I feel reasonably confident that it's a good build. If you could test it out to see whether it resolves the issue, that would be helpful as we prepare for the upcoming "official" release.

**Comment by danielrouleau** [comment]
We have run for a few days on this customer's instance with the above nuget and we have yet to see another instance of this issue which was happening almost daily so I have strong confidence this addressed the issue. Thanks for the assistance and we will look forward to rolling out with the final version when it is released.
