### ISSUE TITLE
Azure durable functions gets stuck and deadlocks further requests

### ISSUE THREAD

**Issue by mandarsj** [Azure/azure-functions-durable-extension#1878]
I have azure durable function designed to generate millions of IDs. However If a certain execution fails due to lesser service tier and less memory, The stateful nature of the durable function means, the historical state is preserved. I noticed, the failing function kept keeping my azure function memory at 80-90% even though it had been more than 5-6 hours since it first failed. 

There should be a maximum number of executions or something on this line. 

I had to go to azure function storage=>container(large messages) which stores durable functions history.

Only when I cleared it, the function was back to running normally.

**Comment by ConnorMcMahon** [comment]
@mandarsj,

It sounds like your orchestration history got so large that it could not be contained in your application's memory (1.5 GB limit on consumption plans, varies for dedicated or premium plans based on SKU). If your orchestration history is large enough to exceed the memory limitations of your SKU, the platform will kill your process, meaning that a single orchestration can effectively prevent your application from being able to run. We document this behavior and [describe workarounds here.](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#history-table)

>  Orchestration data stored in the History table includes output payloads from activity and sub-orchestrator functions. Payloads from external events are also stored in the History table. Because the full history is loaded into memory every time an orchestrator needs to execute, a large enough history can result in significant memory pressure on a given VM. The length and size of the orchestration history can be reduced by splitting large orchestrations into multiple sub-orchestrations or by reducing the size of outputs returned by the activity and sub-orchestrator functions it calls. Alternatively, you can reduce memory usage by lowering per-VM concurrency throttles to limit how many orchestrations are loaded into memory concurrently.

Another workaround not explicitly mentioned in the docs above is to pass around references to your large inputs/outputs instead of the raw data itself. We have a work item tracking a way to add an easy way to pass around your data as reference (#1682). It has some initial design work, but we are still working out some of the details, especially for languages other than .NET.
