### ISSUE TITLE
NullReferenceException in OnProcessWorkItemAsync on a completed instance

### ISSUE THREAD

**Issue by ltrain777** [Azure/azure-functions-durable-extension#1886]
### Description
Getting NullReferenceException on a completed instance with event ProcessWorkItemFailed. Looks like the orchestrator is retrying: "Backing off for 10 seconds until 5 successful operations"

### Expected behavior
Orchestrator shouldn't process completed orchestration instances.

### Actual behavior
NullReferenceException while processing a completed work item.

### Relevant source code snippets
```csharp
// insert code snippet here
```
Not sure if there any relevant code since it only happens on one instance. I haven't seen this error any where else in my app insights logging.

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: \<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" /\>
- **Azure Functions runtime version (1.0 or 2.0)**: azurefunctions: 3.0.15733.0
- **Programming language used**: CSharp dotnet core

### If deployed to Azure

- **Timeframe issue observed**: Instance created 2021-07-05T04:45:05Z, first NullRefException happened 7/5/2021, 4:52:56.971 AM
- **Function App name**: autoengine-prod
- **Function name(s)**: "Orchestrator", "runActionExecution", "invokeProviderRequest"
- **Azure region**: Central US
- **Orchestration instance ID(s)**: eead1c1f-0929-4670-9c3d-13b6f0ff20f0 and eead1c1f-0929-4670-9c3d-13b6f0ff20f0:*
- **Azure storage account name**: storageaccountautoea071

```json
{
    "HostInstanceId": "52955ebf-2745-44d1-a960-18cf6e00bb54",
    "FormattedMessage": "TaskOrchestrationDispatcher-d5746159e9d74465b3e1d0573f824e06-0: Unhandled exception with work item 'eead1c1f-0929-4670-9c3d-13b6f0ff20f0': System.NullReferenceException: Object reference not set to an instance of an object.\r\n at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem)\r\n at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskOrchestrationDispatcher.cs:line 191\r\n at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\\source\\durabletask\\src\\DurableTask.Core\\WorkItemDispatcher.cs:line 373\r\n\r\nBacking off for 10 seconds until 5 successful operations",
    "ProcessId": "7476",
    "LogLevel": "Error",
    "Category": "DurableTask.Core",
    "EventName": "ProcessWorkItemFailed",
    "EventId": "29",
    "prop__Details": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem)\r\n at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskOrchestrationDispatcher.cs:line 191\r\n at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\\source\\durabletask\\src\\DurableTask.Core\\WorkItemDispatcher.cs:line 373\r\n\r\nBacking off for 10 seconds until 5 successful operations",
    "prop__WorkItemId": "eead1c1f-0929-4670-9c3d-13b6f0ff20f0",
    "prop__Dispatcher": "TaskOrchestrationDispatcher-d5746159e9d74465b3e1d0573f824e06-0"
}
```

**Comment by ConnorMcMahon** [comment]
I may have fixed this null reference bug [here](https://github.com/Azure/durabletask/commit/29b0960223a82dd46ecf0e342dcadcec506fe04e), but I am not 100% positive. The null reference you are experiencing seems to be more damaging than mine, which just added some noise to the telemetry. I can take a deeper dive today.

**Comment by ltrain777** [comment]
Here's a little more logging from today.  This function app might have some issues as I see the ServiceBusTrigger function getting triggered twice for the same message, but from different HostInstances causing a MessageLockLostException on other jobs submitted, but so far the 'eead1c1f-0929-4670-9c3d-13b6f0ff20f0' instance is the only one that exhibits the NullReferenceException.

2021-07-07T20:19:04.630 [Warning] eead1c1f-0929-4670-9c3d-13b6f0ff20f0: Discarding [ExecutionStarted]: Duplicate start event

2021-07-07T20:19:04.686 [Error] TaskOrchestrationDispatcher-560a8205d2634344832a2c7909ea7ab9-0: Unhandled exception with work item 'eead1c1f-0929-4670-9c3d-13b6f0ff20f0': System.NullReferenceException: Object reference not set to an instance of an object.at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) .... (same as the above stack)...

2021-07-07T20:19:05.839 [Warning] eead1c1f-0929-4670-9c3d-13b6f0ff20f0: Message [ExecutionStarted] with ID 73af3ae8-34bb-4ada-8258-e50fa8916e2b has been dequeued 388 times and is now considered poison
2021-07-07T20:19:05.840 [Warning] eead1c1f-0929-4670-9c3d-13b6f0ff20f0: Abandoning [ExecutionStarted] message back to ampautoengineprod2-control-01 and setting a visibility delay of 600ms

**Comment by ConnorMcMahon** [comment]
Ok, so I have taken a deeper dive here, and this is a particularly weird edge case.

It looks like your app had the following circumstances.

1. Multiple ExecutionStarted events were scheduled for this instance in the same batch (One with execution id 601cf39495f54c8c9c1bcf7f8a344594 and another with ExecutionId 468c93f23ece49feb797fe908f0d3648).
2. DTFx picked one of the ExecutionStartedEvents (with the execution id 601cf39495f54c8c9c1bcf7f8a344594) to execute, and it executed the first round of the orchestration, and updated the instance history. Unfortunately, the worker crashed before it could delete the ExecutionStarted events from the control queue.
3. Those messages came back after the visibility timeout expired (5 minutes). This time, DTFx tried to execute the other execution id (468c93f23ece49feb797fe908f0d3648). This essentially restarted your orchestration at this point with a new execution id.
4. The original execution id (601cf39495f54c8c9c1bcf7f8a344594) ExecutionStarted event is the one that is causing the null-ref exceptions, which ends up abandoning the message and processing in an endless loop.

At this point, it is harder to reason about things. I'm not exactly sure why this is causing a null reference, because looking at the last log we see and the next missing log, I don't see a ton of opportunities for a null reference exception to happen, especially specifically in OnProcessWorkItemAsync() and not one of its helper methods like the stack trace seems to suggest. If you would be willing to help us by sending your history table for the instance id eead1c1f-0929-4670-9c3d-13b6f0ff20f0, that could help us diagnose this further.

Despite the fact that I haven't figured out the NullReferenceException, it looks like our recent work to prevent multiple concurrent ExecutionStartedEvents from processing would likely have prevented your app from getting in this state. This is out in v2.5.0 of the extension.

At this point, to remove the noise from the logs, I think the best course of action would be to delete the queue message with the id "73af3ae8-34bb-4ada-8258-e50fa8916e2b" would be helpful. Unfortunately, it is visible every 10 minutes and your app will be aggressively polling for it, so you may need to either have another console app that competes to grab the queue message or you could temporarily stop your application and then delete this problematic queue message when it becomes visible after 10 minutes.

**Comment by ltrain777** [comment]
I've updated my function app to use the v2.5.0 extension and will be testing it in my UAT environment. 

The history table for instance eead1c1f-0929-4670-9c3d-13b6f0ff20f0 and all of it's child orchestrations are attached.
[AmpAutoEngineProd2History.csv](https://github.com/Azure/azure-functions-durable-extension/files/6804928/AmpAutoEngineProd2History.csv)

I've stopped the app and looked for the queue message with id "73af3ae8-34bb-4ada-8258-e50fa8916e2b" in all of the 4 control queues but couldn't find that queue message over a 20 minute span. 

> Unfortunately, the worker crashed before it could delete the ExecutionStarted events from the control queue.

Is there anything I can do to figure out why the worker crashed?

I've switched our production app to another app instance with the same release so this app can strictly be used for debugging if needed.

**Comment by ConnorMcMahon** [comment]
@ltrain777,

I can take a look into why the worker crashed. I think looking at your history and our code I worked out why this would happen. I do believe our latest 2.5.0 extension's ExecutionStarted dedupe logic would prevent this from ever happening.

**Comment by ConnorMcMahon** [comment]
@ltrain777 

It looks like your app got scaled down due to being on more workers than you had partitions and the work item queue not requiring that amount of workers due to being mostly idle. There is work being done on the platform side to put instances into drain mode so they finish in-flight executions before getting kicked off the worker, but I don't think that is implemented across the fleet yet.

Like I mentioned before, our changes in 2.5.0 should prevent the null-ref code path from being hit, since it was due to an instance state corruption caused by duplicate ExecutionStarted events, so even if a worker gets scaled down suddenly you won't hit this bug anymore. If you still see this on v2.5.0 (or greater), let's reopen this issue.
