### ISSUE TITLE
Durable Azure Functions Control Queues Messages Increase on High or Constant Load

### ISSUE THREAD

**Issue by OTedikov** [Azure/azure-functions-durable-extension#1896]
Azure Functions v3, C#, .NET Core

<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

Azure Durable Functions are used in the following way:
- Orchestrator Function
- Activity Functions per Orchestrator Function (5 - 20), depends on Configuration passed as Input to Orchestrator Function
- Activity Function: Upload / Download from / to Azure Blob Storage, Read / Write from / to Azure SQL Database, Call External Web Api, ..., with duration 1 - 10 seconds under normal conditions, less often 10 - 60 seconds, much less often 1 - 10 minutes.
- Activity Functions are executed in a specific order, according to Pattern 1: Function Chaining
- Control Queues Count: 8
- Number of Orchestrator Function Executions: ~200 per minute

During the day usually both 8 Control Queues have ~10 -100 messages each and Work Items Queue have ~10-200 messages and these numbers do not increase.

For the recent 2 - 3 months we started noticing the following behavior:
1. For some particular Configurations passed as Input to Orchestrator Function with additional load (+ ~100 per minute), we have increase in Control Queues Messages, and after ~20 - 30 minutes each of 8 Control Queue has ~2000 - 3000 messages, while Work Items Queue still have the same ~10-200 messages.

When this additional Load finishes, Control Queue after 10-30 minutes backs to usual state with ~10 -100 messages each.

Is it normal behavior? If we have additional load why only Control Queues increase, but Work Item Queue does not?
Why Control Queue could possibly increase, can it be related to number of messages it should handle in memory? Can it be related to message size?

2. After a while, could be half a day, could be day, one of Control Queue increases to ~2000 - 5000 and constantly increase further, while other 7 does not increase. We do Function Application redeployment, which scales number of Server to 0, which frees up memory and Control Queue in a 10-30 minutes decreases to be same as other 7 Control Queues.
Always when this happens, we have OutOfMemoryException logged in Application Insights, which we think is a root cause of only 1 Control Queue to increase, which has Memory issue.

What could be the reason? Should we investigate Activity Functions we have for possible Memory Leaks? Should we take a look at Activity Function Request / Response sizes?

Thank you

**Comment by cgillum** [comment]
Long control queue lengths mean that there are a lot of messages that need to be processed by orchestration functions. Depending on your workload, this could include orchestration start messages, activity function reply messages, durable timer messages, or external event messages.

If you're seeing that control queue lengths are high, this means that orchestrations are not able to process all these events quickly enough to keep the queue length low. The speed at which these messages can be dequeued and processed depends on several factors:

* How expensive are the orchestrator function replays
* How big are the messages that the orchestration functions have to read (this can have a surprisingly big impact)
* What is your concurrency configuration for orchestrator functions per-node
* What is your pre-fetch buffer threshold (this can have a huge impact when you're doing fan-outs)

If all of the above factors have been considered and optimized, then you should look into increasing the number of partitions so that your orchestrations can be spread out across more workers.

It's easy for control queues to grow longer than work-item queues because only a single worker can read from a particular control queue whereas _all_ workers can read from the single work-item queue.

Take a look at our performance documentation for more information: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale

If you see a lot of messages for one control queue but not others, it could mean that either the distribution of your orchestrations across control queues is unbalanced because of the way you're generating instance IDs (the default behavior should leave them well-balanced) or it could mean that you have one extremely busy orchestration instance and the rest are not so busy. Alternatively, it could mean that the one worker which owns that queue is not healthy for some reason (CPU, memory, or some other stability issue).  Take a look at our diagnostic documentation for tips on how to debug your orchestrations: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics

**Comment by OTedikov** [comment]
@cgillum Thank you, will analyze your reply and get back with further observations and findings.

**Comment by OTedikov** [comment]
@cgillum 

Our case is rather either orchestration start messages or activity function reply messages, we do not have yet durable timer messages or external event messages.

**Speed at which Messages can be Dequeued from Control Queue**
- How expensive are the orchestrator function replays?
  Orchestrator function logic has Activity function invocations in order, between these invocations there is either no logic, just using output from previous Activity function invocation as input for next Activity function invocation or output assignment to local variable within Orchestrator function to be used at the end as log
- How big are the messages that the orchestration functions have to read (this can have a surprisingly big impact)?
  4 KB - 25 KB in most of the cases
- What is your concurrency configuration for orchestrator functions per-node
   Default values are used, no specific configuration. What is suggested concurrency configuration in our case?
- What is your pre-fetch buffer threshold (this can have a huge impact when you're doing fan-outs)
   Default values are used, no specific configuration. What is suggested pre-fetch buffer threshold in our case?

**Number of Partitions** 
- Should we try increasing it from 8 to 16?

**Instance ID Generation**
- Default behaviour is used

**Queue Health**
- We noticed that after deployment, which scales down number of servers to 0 and frees up a memory, then constantly memory usage starts to grow, and according to Memory Working Set metric chart when memory is more then ~700 MB, some of Control Queues start to grow with number of messages while all the other Control Queues remain with the same number of messages. Which rather means that we have potential issues with memory deallocation?

Thank you

**Comment by OTedikov** [comment]
@cgillum Did you have a chance to take a look?

**Comment by cgillum** [comment]
Hey @OTedikov, thanks for the ping and sorry for the delay on this. It looks like there's nothing specific to worry about for your case. I do have a couple other questions for you:

* What version of the Durable Extension are you using? We've discovered several performance issues in recent versions that can cause long delays in orchestration starts and control queue lengths to increase. If you're not already, make sure to upgrade to the latest extension version (v2.5.1) which has several critical performance fixes.
* Are you using [extendedSessions](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions)? This reduces the performance impact of replays, but at the cost of higher memory usage.

**Comment by OTedikov** [comment]
@cgillum Thank you for getting back.

Versions Used:
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

Extended Sessions:
We do not use extended sessions.

One thing I've noticed also, that at the moment of continuous load with Orchestrations which Activity Functions have MemoryStream usage like
using (var memoryStream = new MemoryStream())
{
    ...
}, Memory allocation grows and causes OutOfMemory exceptions.

Should we consider changing MemoryStream usage with RecyclableMemoryStreamManager approach?

Thank you

**Comment by cgillum** [comment]
> Should we consider changing MemoryStream usage with RecyclableMemoryStreamManager approach?

It's definitely a good idea because it will put a lot less pressure on the .NET GC and likely reduce overall memory usage at any given time.

Also, what kind of plan are you using for your Function app? If you're running into memory caps, the app process could be getting recycled, which would dramatically slow down queue processing. This is fairly common in cases we see and taking action to reduce memory consumption (code improvements and/or reduction in function execution concurrency) can help mitigate this. I believe you should be able to see events related to this in your Application Insights telemetry, or even in the _Diagnose and Solve problems_ blade in the Azure portal.

**Comment by OTedikov** [comment]
@cgillum ElasticPremium EP1 Plan.

**Comment by ConnorMcMahon** [comment]
@OTedikov, could you share a region, orchestration instance, id, and UTC timestamp? I think taking a look at our internal tooling to measure orchestration latency and memory consumption may help us diagnose your issues at this point.

**Comment by OTedikov** [comment]
@ConnorMcMahon 

Region: UK South

I am not sure how to better share with you orchestration instance, id, and UTC timestamp?
Do you want me to catch OutOfMemory Exception when it happens and provide you details based on that orchestration?

Thank you

**Comment by ConnorMcMahon** [comment]
The instance id is more of a way to anonymously share your application info with us without sharing app name. You can also just give us the app name and a timerange in the last 30 days that you experienced these slow downs, and that should be enough to take a look at what is going on for your app during that time.

**Comment by OTedikov** [comment]
@ConnorMcMahon 

Event time: Timestamp 8/23/2021, 4:44:24.427 PM (Local time) (Ukraine)
HostInstanceId: 9d9e8b45-af5d-4655-bdfe-21cc1e7021c1
InvocationId: ff3874f5-2947-45f0-a417-648a29f75a5d

Event time: 8/23/2021, 4:05:32.490 PM (Local time) (Ukraine)
HostInstanceId: 61e2e6bf-325c-47f4-8fa2-24dacff928c2
InvocationId: dbd341a2-8e2e-4e93-81f2-7893a940cd75

Event time: 8/20/2021, 6:46:09.812 PM (Local time) (Ukraine)
HostInstanceId: 715c4b66-1648-4656-b17c-de5869d8921e
InvocationId: e9ce5456-c45d-4901-aeac-9347630f9151

Please let me know if this information is sufficient for further troubleshooting on your side?
Thank you

**Comment by ConnorMcMahon** [comment]
@OTedikov, unfortunately, I didn't have as much time as I wanted to dive into this today, but I was able to find a few things.

1. Most of the slow down did seem to occur on Partition 5's control queue:
![image](https://user-images.githubusercontent.com/8934380/131200480-2e89794e-6ccc-44ad-948d-ddbabfd84767.png)
2. I did notice various OutOfMemory exceptions on your application at this time. This did seem to happen across all of the partition ids, so I'm not sure it explains the issue.

I noticed your app is on 2.4.0, and we have made various bug fixes to reliability and performance since then, so if possible, I recommend upgrading to v2.5.1 to get those updates.

I will take a closer look on Monday.

**Comment by OTedikov** [comment]
@cgillum Thank you on update.

Did you have a change to take a closer look?

**Comment by ConnorMcMahon** [comment]
Sorry, on call responsibilities took up more of my time earlier this week. Will take another look today.

**Comment by ConnorMcMahon** [comment]
@OTedikov,

I took a closer look, and Partition5 was not the only partition with issues, it was just the only one that median age actually caught the issue. Looking at average age shows a more clear picture:

![image](https://user-images.githubusercontent.com/8934380/131933756-6ff90b01-126a-4803-9bf3-9c88b581de4e.png)


Other partitions were also having application shutdowns due to out-of-memory exceptions. When this happens, it takes 5 minutes for us to see the queue message again due to visibility timeout.

We do provide [some documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#history-table) for concurrency knobs to tweak to reduce memory consumption. Also consider touching the storageProvider.controlQueueBufferThreshold. This controls how many queue items we prefetch, and it defaults to 256, so decreasing that can decrease memory if you have large activity/suborchestration inputs/outputs.

In general though, the best long term strategy to avoid high memory consumption though is to only pass large pieces of data as inputs and outputs if you actually need the data in your orchestration. If you don't, handling the data storage yourself and passing around a reference to that data back to the orchestration, it heavily reduces the size of the orchestration history we have to fetch every time we run your orchestrations. This also can reduce the number of times we have to download that data from blob storage, improving latency + throughput.
