### ISSUE TITLE
Fan-Out attempt causes InvalidOperationException

### ISSUE THREAD

**Issue by mmisztal1980** [Azure/azure-functions-durable-extension#19]
Hi,

Based on the **BackupSiteContent** sample, I wanted to created the following call-chain

- Func1 [TimerTrigger], has a `DurableOrchestrationClient`.
- Func1, calls Func2 using `StartNewAsync`
- Func2 [OrchestrationTrigger] has a `DurableOrchestrationContext`.
- Func2 is supposed to perform a Fan-Out to Func3
- Func3 [ActivityTrigger] has a `DurableActivityContext`
- Func3 should do the work and return the result to the caller.

This is what I'm getting in **Func2** :
![image](https://user-images.githubusercontent.com/1357057/28295056-51f3dc94-6b5e-11e7-82af-e48e3953017d.png)

Can you explain why the sample is behaving in a different way? I believe it should be have in the same way as **E2_BackupSiteContent** ?
Best regards

**Comment by cgillum** [comment]
Yes, the problem is your call to `await repository.GetAsync("GIOS")` on the 3rd line of your function body. Orchestrator functions don't support doing `await` on anything other than "durable tasks", which are effectively tasks that come from the `DurableOrchestrationContext` class.

More information on orchestrator code constraints can be found here: https://azure.github.io/azure-functions-durable-extension/articles/topics/checkpointing-and-replay.html#code-constraints

To work around this, you should wrap the call to `await repository.GetAsync("GIOS")` in a separate activity function and call it using `context.CallFunctionAsync`.
