### ISSUE TITLE
COnfiguration guide for the local emulator

### ISSUE THREAD

**Issue by zippy1981** [Azure/azure-functions-durable-extension#1934]
I would like to use the local emulator for local development, but docs on this repo are lacking.

[This doc](https://docs.microsoft.com/en-us/Azure/azure-functions/durable/durable-functions-storage-providers) should how to use hosts.json to configure the netherite and mssql extensions. I  tried guessing, but nothing is working. Is there any documentation for using it?

**Comment by sebastianburckhardt** [comment]
The docs could perhaps be more to the point, I will update them. Here is the short version.

1. Add the NuGet package `Microsoft.Azure.DurableTask.Netherite.AzureFunctions` to your function app project. 
2. Set the `AzureWebJobsStorage` configuration parameter to use local emulation (e.g. `set AzureWebJobsStorage=UseDevelopmentStorage=true;`). 
3. Set the `EventHubsConnection` configuration parameter to use local emulation (e.g. `set EventHubsConnection=Memory`). 
4. Modify the host.json to choose Netherite as the storage provide:
```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "type": "Netherite"
      }
    }
  }
}

Let me know if you run into trouble with these steps or if something is unclear.

**Comment by jdearing-neudesic** [comment]
I used the "long" development connection string because I'm using azurite and don't want to start the emulator and that basically works. However, its not really solving my problem. I have some functions that use regular queue triggers that are still need azurite or storage emulator or real azure storage.

I was hoping for something completely in process to eliminate the need for even azurite for local development. If I converted all my queue triggers to durable orchestrations could I set `UseDevelopmentStorage=false` and not need any external azure storage, storage emulation or azurite?

Yes this is for development only.

**Comment by zippy1981** [comment]
The above was my work account, consider that my author feedback, thanks.

**Comment by ConnorMcMahon** [comment]
@zippy1981

Just out of curiosity, what exactly is the reason that you want to remove dependency on Azure Storage emulator and/or Azurite?

We could theoretically add support for the DTFx.Emulator backend, but that would be a decent amount of work to document that use case + any dev work to light it up, just to avoid having to start up the storage emulator. 

In general, the different backends may have slightly different quirks and performance characteristics, so I don't know if I would recommend testing on another backend then you are planning to run in prod.

**Comment by sebastianburckhardt** [comment]
For what it is worth, I believe Azurite does indeed support configuring the port.

I haven't tried it myself but there is documentation here: 
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#blob-listening-port-configuration
