### ISSUE TITLE
Durable Functions - History Table logging tuples

### ISSUE THREAD

**Issue by brunotw** [Azure/azure-functions-durable-extension#1952]
Hi all, I've been playing around with Durable Functions for some weeks, today I noticed how tuple are logged into the history table. Even though my Activity Function returns a named tuple, the table history shows item1 and item 2.

![image](https://user-images.githubusercontent.com/21198314/125374453-f32b0780-e37e-11eb-8079-d4041123f2af.png)

History Table
![image](https://user-images.githubusercontent.com/21198314/125374766-98de7680-e37f-11eb-923b-34f07f50bd3c.png)

Am I missing anything here or that's the expected behaviour?

**Comment by cgillum** [comment]
This is a consequence of how tuples work in C#, and not really specific to Durable Functions.

Each field of a tuple is internally represented as `Item1`, `Item2`, etc. even though C# allows you to express them using friendly variable names. As a result, when we serialize the values of tuples, you will see `Item1` and `Item2` instead of `number` and `instanceId`. It's a little confusing, but the benefit of decoupling the runtime representation from the code representation is that you can use different names for the tuple fields and not break compatibility.

More information on this here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples#tuple-field-names.

> At compile time, the compiler replaces non-default field names with the corresponding default names. As a result, explicitly specified or inferred field names aren't available at run time.
