### ISSUE TITLE
Allow access to certain context methods from Activity functions

### ISSUE THREAD

**Issue by Ryanman** [Azure/azure-functions-durable-extension#198]
I hate being the guy to ask for a "Feature" so let me know if I'm off base. This issue is slightly related to [Issue 21](https://github.com/Azure/azure-functions-durable-extension/issues/21).

My scenario is that I have an orchestrator function that uses multiple Activity functions to interact with different 3rd party APIs. One of these API providers has aggressive rate limiting, but also tells you when you rate limit window resets. The activity function right now uses DateTime.Now and thread.sleep to wait for that window to open before retrying a batch operation.

Obviously that's not ideal. I'd much rather use the current date time from the context, and the timer that's available. I guess my question is twofold:

- Am I missing something in terms of what's availble to solve what I imagine is a common problem?
- Is it technically feasible to give activity functions access to some of the properties and methods in the context?

Thanks in advance for the discussion, loving developing durable functions so far.

**Comment by tohling** [comment]
@Ryanman , there is a newly documented [Monitoring pattern](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#pattern-4-monitoring) for Durable Functions. Could it be along the lines of what you are looking for?

**Comment by Ryanman** [comment]
This pattern may solve the problem and the approach matches what I've hacked together. I guess my issue is that if I take that monitoring pattern and put it into my Orchestrator method (where I have access to the context) then the activity function will be doing virtually nothing. 

In this scenario for instance I'm retrieving inventory for 100 items from the rate limited API. My orchestrator function (in my mind) should exist just as a broker - get the 100 items and pass them to the next activity in the orchestration. The activity should be the one making sure it interacts correctly with the API it's pinging.

Something like:

`[FunctionName("GetItems")]
public static async Task GetItems([ActivityTrigger] List<int> productIds)
{
	var products = new List<Product>();
	DateTime expiryTime = GetExpiryTime();

	foreach (var productId in productIds)
	{
		var itemIsRetrieved = false;
		while (!itemIsRetrieved && ParentOrchestrationContext.CurrentUtcDateTime < expiryTime)
		{
			var response = await _client.GetAsync($"someSite/api/GetProduct?productId={productId}");
			if (response.IsSuccessStatusCode)
			{
				products.Add(await response.Content.ReadAsAsync<Product>());
				itemIsRetrieved = true;
			}
			else
			{
				var timeToContinue =  GetNextWindowStart(response); 
				await ParentOrchestrationContext.CreateTimer(timeToContinue, CancellationToken.None);
			}
		}
	}
	return products;

   // Perform further work here, or let the orchestration end
}`

**Comment by cgillum** [comment]
I agree that sleeping in your activity function is not ideal. Unfortunately, activity functions are stateless so it's not practical for us to add support for things like timers in these activity functions.

Another option, though not perfect, is to specify a [retry policy](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-error-handling#automatic-retry-on-failure) when calling your activity function. You can use the [Handle](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.RetryOptions.html#Microsoft_Azure_WebJobs_RetryOptions_Handle) callback to retry only on rate-limiting errors. The challenge is that you can't dynamically schedule the retries, so you would need to come up with a retry interval that is "good enough". This may be the most practical option.

If you want to handle it perfectly, then I think you would need to wrap your activity function call in a try/catch inside a loop in your orchestrator function. In the catch block, you would check to see if the failure was related to rate-limiting, get the details, and then schedule a timer to retry later.

I'm going to close this for now since I think I've answered your question. But do let us know if you need more clarity.
