### ISSUE TITLE
RaiseEventAsync throws ArgumentException "No instance with ID '{instanceId}' was found."

### ISSUE THREAD

**Issue by shun-jiang** [Azure/azure-functions-durable-extension#1989]
**Background**
We have a durable function that calls an external service via an activity function and receives the returned result by waiting and listening for an external event ( `WaitForExternalEvent`).
There is an EventGrid triggered function that receives the result from the external service and sends the result to the orchestration (`RaiseEventAsync`).

**Problem**
We see the `RaiseEventAsync` method throws ArgumentException which message is "No instance with ID '{instanceId}' was found.". When the exception is thrown, `GetStatusAsync` returns null as the DurableOrchestrationStatus.  Then, the function retry after the exception is thrown, and `RaiseEventAsync` succeeds.

It seems like there is a race condition between the external event raise and the orchestration state update. 

Is it an expected use case? Is there a way to prevent it?

**Codes**

Orchestration
```
[FunctionName("RunOrchestration")]
public async Task RunOrchestration(
	[OrchestrationTrigger] IDurableOrchestrationContext context)
{
	 var inputData = context.GetInput<InputData>();
         inputData.OrchestrationInstanceId = context.InstanceId;
	 await context.CallActivityAsync<Result>("CallExternalService", inputData);
	 await context.WaitForExternalEvent<ExternalResult>(Constants.ExternalEventName, TimeSpan.FromMinutes(30));
}
```

EventGrid trigger function
```
[FunctionName("HandleExternalResult")]
[ExponentialBackoffRetry(5, "00:00:05", "00:01:00")]
public async Task HandleExternalResult(
	[EventGridTrigger]EventGridEvent eventGridEvent, 
	[DurableClient] IDurableOrchestrationClient client)
{
   if(eventGridEvent.TryGetData(out var externalResult))
   {
		try
		{
			await client.RaiseEventAsync(externalResult.OrchestrationInstanceId, 
				Constants.ExternalEventName, 
				externalResult);
		}
		catch (Exception e)
		{
			var durableOrchestrationStatus =  await client.GetStatusAsync(externalResult.OrchestrationInstanceId);
			
			//log durableOrchestrationStatus
			//throw exception to trigger the retry
			throw;
		}
   }
}
```

**Comment by cgillum** [comment]
This is unfortunately possible since we rely heavily on eventual consistency with the [Azure Storage provider](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers) in Durable Functions. That said, it shouldn't be too frequent. Here's what's going on behind the scenes:

When the orchestration is scheduled, we first add a message into a storage queue and then update the Instances table with a "Pending" status record for the instance you just started. Depending on the timing, it's possible the the orchestration may have started running and scheduled work before the client has had a chance to add the record to the Instances table. APIs like RaiseEventAsync and GetStateAsync read this record from the instances table to determine if the instance exists or not. If the orchestration and external service are running really fast (or if the client is running _really_ slow), then it's possible that your event grid trigger may run before the original client has finished writing its record to the Instances table record. In this case, the behavior you're seeing will happen.

Adding retry logic to your event grid trigger is a good way to work around this issue.

**Comment by shun-jiang** [comment]
@cgillum Thank you for your response. 

Based on our test, it happens about 1-3 times per 10K operations. Is it within the expected range? 

I cannot find any documentation about this issue, so not sure what to expect. It will be nice that there is documentation on that known issue or you can share with me that if it already exists.

Also, does the code logs when the instance table got updated? If yes, how can I locate the log if it is logged? I see there are logs in which category is "DurableTask.AzureStorage" and "DurableTask.Core" and various event names, but not sure how to diagnostics the problem with those logs. Is there any documentation?

**Comment by olitomlinson** [comment]
@shun-jiang adding retries will definitely fix this, I had the same when I was building a high-throughput system which needed the same pattern as what you've implemented.

As an aside, I notice you're binding your Function App directly to Event Grid. Just an FYI, but this model _can_ essentially DDOS your Function App due to the high level of concurrency that Event Grid attempts to achieve when delivering to Event to subscribers. In my experience, this concurrency was occasionally too much for my Consumption plan Function App which caused lots of failures and retries in EventGrid (which is costly due to the pricing model in EventGrid), so I had to slip an Azure Service Bus Queue between EventGrid and the Function App. This allowed the Function App to _pull_ work, rather than have work _forced_ onto it. 

Here's a nice short blog that summarizes what I'm saying https://yourazurecoach.com/2021/08/11/azure-service-bus-vs-event-grid/

**Comment by cgillum** [comment]
> Based on our test, it happens about 1-3 times per 10K operations. Is it within the expected range?

If your functions run very quickly, then this sounds about right. We unfortunately don't have documentation on this. I'm not exactly sure where we'd document it so that people can easily find it, but I'm open to suggestions if you have any.

> Also, does the code logs when the instance table got updated? If yes, how can I locate the log if it is logged?

Yes, you'll find this in the "DurableTask.AzureStorage" category (which can be [enabled in host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp#durable-task-framework-logging)) with the log level set to "Information". Look for the trace with a _TaskName_ property (it might be prefixed with "prop__") set to `InstanceStatusUpdate`. You should see a RuntimeStatus property that will say "Pending", "Running", "Completed", etc.

You can find the full list of available DurableTask.AzureStorage logs and all their fields here: https://github.com/Azure/durabletask/blob/main/src/DurableTask.AzureStorage/AnalyticsEventSource.cs
