### ISSUE TITLE
Stack overflow in Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers crashes Roslyn code analysis process

### ISSUE THREAD

**Issue by tmat** [Azure/azure-functions-durable-extension#2031]
Stack DurableTask analyzer crashes due to stack overflow:

```
Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.dll!Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorMethodCollector.FindInvokedMethods(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.MethodInformation parentMethodInformation)
```

See VS feedback https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1443435

**Comment by cgillum** [comment]
FYI @amdeel

**Comment by krmr** [comment]
While I am not the author of that VS feedback I am also experiencing the same problem. After digging into this a while I finally managed to put together a simple solution to reproduce the problem: https://github.com/krmr/FunctionAppRepro

The repro steps for me are simple:
1. Load the solution
2. Open FunctionApp/TestFunction.cs
3. After a while this will raise errors in Visual Studio due to the analyzer crashing.

From the stack trace it looks like OrchestratorMethodCollector.FindInvoedMethods somehow does not handle the recursion gracefully.

To me it looked like the issue is triggered by the referenced class library using `<LangVersion>latest</LangVersion>`, at least it seemed to work without that element.

**Comment by amdeel** [comment]
Hi @tmat and @krmr I believe I fixed the bug that was causing this issue. Thank you so much for the repro, it was really helpful when testing this issue. My latest changes resolve the issue on my local tests. Could you confirm that this preview package addresses the issue for your tests as well if you have a chance? Thanks!

I uploaded a preview package version 0.4.2-preview to our app-service myget feed. Connect to our feed with:
https://www.myget.org/F/azure-appservice/api/v3/index.json

<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.2-preview" />

**Comment by krmr** [comment]
Thanks, I have re-tested with the preview package and did not get any of the exceptions anymore.
