### ISSUE TITLE
Custom Exceptions thrown from activity functions have duplicated collection items

### ISSUE THREAD

**Issue by jamiepollard** [Azure/azure-functions-durable-extension#2038]
### Description
When throwing a custom exception that holds a list of items in a collection created at constructor time, the exception caught in the orchestrator contains duplicacated list items.

This happens when a simple list containing 1 item is created and populated in the constructor for the custom exception. The list looks fine when caught in the activity function, but if this is re-thrown (or just not caught) and is then caught in the orchestrator, the list contains 2 duplicate items instead of 1.

### Expected behavior
The collection state would be as it was when thrown in the activity function.

### Actual behavior
The collection state contains duplicated values.

### Relevant source code snippets
The following CustomException manifests the issue in the sample durable function project

```csharp
public class CustomException : Exception
{
  public List<string> Errors { get; set; }

  public CustomException()
  {
    this.Errors = new List<string>()
    {
      "A Single Error Message from CustomException (count should be 1?)"
    };
  }
}
```

Inside Orchestration:
```csharp
try
{
  await context.CallActivityAsync<string>("CustomException_Activity", string.Empty);
}
catch (Exception e)
{
  CustomException ex = e.InnerException as CustomException;
  // ex.Errors here has count 2 instead of 1
  outputs.AddRange(ex.Errors);
  log.LogInformation($"CustomException returned a collection with {ex.Errors.Count} items.");
}
```

### Known workarounds
n/a

### App Details

- Microsoft.Azure.WebJobs.Extensions.DurableTask v2.6.0:
- Microsoft.NET.Sdk.Functions v3.0.13:
- C#:

### Screenshots
State when exception is thrown:
![image](https://user-images.githubusercontent.com/615896/146737882-eacf322a-eaa7-4d52-8e81-28ca5b9852ab.png)

State when caught in the Orchestration function
![image](https://user-images.githubusercontent.com/615896/146738003-000242b6-e8a7-4ca9-a609-691184e60ade.png)

**Comment by cgillum** [comment]
I believe this is expected behavior when serializing/deserializing types in this way using Newtonsoft.Json (which is what we use), and isn't necessarily specific to Durable Functions.

Here's what I think is happening:

1. The serializer is creating a new instance of your custom exception by calling the default constructor.
2. The default constructor initializes the list with your exception message.
3. The serializer then tries to populate all the fields of the object
4. When populating the `Errors` property, instead of creating a new list object, it's adding any elements from the serialized payload to the existing list.

This results in the duplication that you're seeing.

My suggestion is to refactor your code to avoid populating the collection from inside the default constructor of your custom exception. Then, test the serialization/deserialization behavior using Newtonsoft.Json serializer to make sure you get the behavior you want.
