### ISSUE TITLE
Function to Purge instance history throws timeout

### ISSUE THREAD

**Issue by ichesa** [Azure/azure-functions-durable-extension#2129]
### Description
We have an Azure Function app with a process (timer function) running almost 24/7 that drops lots of information in the storage tables, blobs, etc. Our function app is limited to 59 minutes of execution time in host.json:

`"functionTimeout": "00:59:00"`

We implemented a timer function to clean the history of these tables (everything older than two days) following this approach from the documentation: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#purge-instance-history

The code is similar to this one:
```C#
public static Task Run(
            [TimerTrigger(0 0 0 * * *, RunOnStartup = false)]
            TimerInfo myTimer,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger logger)
        {
            return starter.PurgeInstanceHistoryAsync(
                DateTime.MinValue,
                DateTime.UtcNow.AddDays(2),
                new List<OrchestrationStatus>
                {
                    OrchestrationStatus.Completed,
                    OrchestrationStatus.Terminated
                });
        }
```

### Expected behavior
Clean history (tables and blobs) and timer function to end without any issues before 59 minutes.

During the last run (04/04/2022 00:00:00 UTC) we expected the process to delete (at least) this number of entries in the storage tables (information retrieved with "Microsoft Azure Storage Explorer" tool):
`Finished calculating statistics for table 'statlaswf2cpqa/WorkspacesSynchronisationInstances' ("CompletedTime ge datetime'2022-03-31T00:00Z' and CompletedTime lt datetime'2022-04-01T00:00Z' and RuntimeStatus eq 'Completed'"). Entity stats: 33698 entities, 10 custom properties. Completed at 04/04/2022 11:44.`

### Actual behavior
A timeout error is being logged in the application insights resource associated to this function app:

`Timeout value of 00:59:00 was exceeded by function: PurgeInstanceHistoryTimerTrigger`

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.6.0
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: 03/04/2022 00:00:00 UTC to 04/04/2022 02:00:00 UTC
- **Function App name**: func-atlas-wsf-cp-qa
- **Function name(s)**: PurgeInstanceHistoryTimerTrigger
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: Unknown
- **Azure storage account name**: statlaswf2cpqa

**Comment by cgillum** [comment]
This is expected if the number of rows in table storage is exceptionally large. Your query shows over 20K records in the instances table, but also included in the purge would be all associated records in the WorkspacesSynchronisationHistory table, which is expected to be several times this number. If there are any storage blobs for holding larger payloads, that will further increase the amount of time required to purge all the data.

The recommendation for cases like this is to:

* Purge during times when the app/storage account is likely to be idle.
* Try to purge more frequently to avoid large backlogs
* Retry if a timeout is exceeded - it should eventually complete.

**Comment by ichesa** [comment]
Hi Chris,

Thank you for your answer. My apologies for the late response.

Good to know that this is somehow expected and thank you again for your recommendations. Then, I will try to follow some of those approaches for a better handling of the purge operations.

Regards.

**Comment by lilyjma** [comment]
@ichesa -- Did Chris's recommendation unblock you? If yes, can we close this issue? Thanks!

**Comment by ichesa** [comment]
> @ichesa -- Did Chris's recommendation unblock you? If yes, can we close this issue? Thanks!

Hello @lilyjma ,

I was about to post here again related to this topic. I've tried with implementing the retry system suggested in this document: [Fixed delay retry](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#fixed-delay-retry)

After reviewing the requirements (engine version, libraries, etc.) I think the application meets the requirements (Microsoft.Azure.WebJobs is not added directly as a nuget package but it is a dependency of Microsoft.Azure.WebJobs.Extensions.DurableTask) so, I decided to give it a try and I have the new solution as it is now, running for more than a week. But it looks like it is not properly working because I am not able to see more than one 'timeout' exception each day in application insights (I guess I should see one per retry). Besides, I can still see old data that should have been deleted from the storage account (I changed the time to keep only data from the last day) so, I guess it is not working.

This is how the code looks like now:
```
[FixedDelayRetry(4, "00:00:59")]
public static Task Run(
[TimerTrigger(0 0 0 * * *, RunOnStartup = false)]
TimerInfo myTimer,
[DurableClient] IDurableOrchestrationClient starter,
ILogger logger)
{
	try
	{
		return starter.PurgeInstanceHistoryAsync(
		DateTime.MinValue,
		DateTime.UtcNow.AddDays(1),
		new List<OrchestrationStatus>
		{
			OrchestrationStatus.Completed,
			OrchestrationStatus.Terminated
		});
	}
	catch (Exception ex)
	{
		logger.LogError(ex, $"{formattedMessage}");
		return Task.FromException<PurgeHistoryResult>(ex);
	}
}
```
As you can also see above, I have also added a catch clause to drop a message in case that for any reason the timeout reaches that part of the code but, I do not see other messages in insights rather than the regular exceptions (I put just a placeholder above as an example). Maybe the timeout exception is not reaching the try-catch.

I have updated the Durable Functions extension version to 2.7.0 and I have even created a new storage account to be used with this function app, but it seems the problem has not gone. This code has been with this configuration for more than a week now.

Is there anything you may help with by seeing the logs? I update here the data about the environment and a time frame when you can see the exceptions thrown, in case you can help with it. Any help from you or @cgillum would be much appreciated.

### **App Details**

- Durable Functions extension version (e.g. v1.8.3): 2.7.0
- Azure Functions runtime version (1.0 or 2.0): v3
- Programming language used: C#

### **If deployed to Azure**

- Timeframe issue observed: 23/05/2022 00:00:00 UTC to 29/05/2022 23:59:00 UTC
- Function App name: func-atlas-wsf-cp-qa
- Function name(s): PurgeInstanceHistoryTimerTrigger
- Azure region: West Europe
- Orchestration instance ID(s): Unknown
- Azure storage account name: statlasws2cpqa
- Application Insights: appi-atlas-wsf-cp-qa

**Comment by cgillum** [comment]
Hi @ichesa, thanks for the additional details. Regarding some of your observations:

> it looks like it is not properly working because I am not able to see more than one 'timeout' exception each day in application insights (I guess I should see one per retry)

> I have also added a catch clause to drop a message in case that for any reason the timeout reaches that part of the code but, I do not see other messages in insights rather than the regular exceptions

I think both of these observations have the same basic explanation, which is that Function timeouts are not treated as failures and also not observable as exceptions. Rather, a function timeout is simply a trigger that tells the Functions runtime to recycle the host to force any executions to be terminated. Since your execution is terminating abnormally, it won't trigger any retry behavior. This is also why you won't ever be able to catch it in a catch block.

> I can still see old data that should have been deleted from the storage account (I changed the time to keep only data from the last day) so, I guess it is not working

You should see that *some* of the data is getting deleted, but possibly not all of it. Depending on how much data you have, it may take a long time to clear it all. This is unfortunately a limitation of the Azure Storage architecture.  The idea is that it should all get cleaned up via retries. However, as you pointed out, retries don't actually work because these aren't "failures", and from your experience it seems like the timer trigger won't re-run until the next scheduled interval.

As a next step, I suggest you instead use a queue trigger for this purge operation. Your timer trigger should then add a message to the queue instead of calling the purge API directly. This design will be more resilient to timeouts because the queue message will get added back to the queue if/when the host gets recycled. The purge operation will then be continually retried until it finishes. You'll just want to make sure to set a high value for `maxDequeueCount` in [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#host-json) to ensure this message doesn't get moved to the poison queue for long purge operations.

This discussion has highlighted some good usability issues in our current purge design, so we've opened an issue to track making improvements. If nothing else, we want to make the behavior a bit more obvious and not force you to deal with function timeouts: #2200

**Comment by ichesa** [comment]
Hi @cgillum ,

Thanks a lot for clarifying this. Then, I think I will be trying the approach you suggested with the queue trigger when I have some time for it. I will also let you know how it worked just to give you some feedback about it.

And it is really appreciated too that you are going to work on improvements on the purge design. I'd love to hear from you when that happens if possible.

Regards.

**Comment by davidmrdavid** [comment]
@ichesa, if your questions have been answered, would you mind closing this issue for now? You can always tag us in this thread once you have your experiment results and/or feedback :)
