### ISSUE TITLE
Not returning to suborchestrator after calling activity

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-functions-durable-extension#2135]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

We've successfully used Durable Functions for a year or more, and just recently getting an issue where the suborchestrator isn't returning from the activity.

This was working fine when we just had one set of Durable Functions, and we recently added two more, and I believe this is when the problem started.  

(UPDATE: just re-ran our original Durable Function, and realized it was seeing same behavior, but there's no functional code that's run after the suborchestrator's activity, so we never noticed it.  I'm not seeing our log messages that say the activity was successful, and the orchestration is left in Running state.)

I tried separating them out into separate function apps, and separate storage, thinking there was a problem using same storage account and task hub.

I'm totally stumped and blocked at this point.

I've trimmed my code down to the simple 'ping' case below.

### Expected behavior
> A clear and concise description of what you expected to happen.

Orchestration, suborchestration and activity to complete as expected.

### Actual behavior
> A clear and concise description of what actually happened.

I'm seeing these log messages in App Insights:
Attempting to create job [{job.Id}] entity workflow.
Sending ping [{ping}].
Received ping [{ping}].

But that's all I get; I never see:

Sent ping [{ping}].
Created job [{job.Id}] processing workflow.

It appears that the Ping method completes properly, and I can see it marked TaskCompleted.

After that, I see the events:
ExecutionStarted
OrchestrationStarted
OrchestrationCompleted

This reproduces exactly the same every time.  The serialized 'Job' is only about 5KB, so I don't think it's a memory issue.

Here's the key part I see in the logs (attached below).

Ping activity finishes, and after processing TaskCompleted, it executes CreatePingWorkflow but leaves itself in running state.
```
2022-04-10T07:33:41.422 [Information] fab972cedda44432a6441240e5a29dee:0: Task activity [Ping] completed successfully
2022-04-10T07:33:41.431 [Information] fab972cedda44432a6441240e5a29dee:0: Sending [TaskCompleted] message to knowledge-control-00 for instance 'fab972cedda44432a6441240e5a29dee:0'
2022-04-10T07:33:41.437 [Information] fab972cedda44432a6441240e5a29dee:0: Deleting [TaskScheduled] message from knowledge-workitems
2022-04-10T07:33:41.441 [Information] fab972cedda44432a6441240e5a29dee:0: Fetched [TaskCompleted] message from knowledge-control-00 (delay = 441ms)
2022-04-10T07:33:41.445 [Information] fab972cedda44432a6441240e5a29dee:0: Processing [TaskCompleted] (total delay = 445ms)
2022-04-10T07:33:41.445 [Debug] fab972cedda44432a6441240e5a29dee:0: Preparing to process a [TaskCompleted] message
2022-04-10T07:33:41.445 [Information] fab972cedda44432a6441240e5a29dee:0: Executing 'CreatePingWorkflow' orchestration logic
2022-04-10T07:33:41.447 [Debug] TaskActivityDispatcher-dfe70fa2702b4f908452067b7c5d7bb4-0: Finished processing work-item '7e3526a3-6612-4ecc-a3f3-81194cf0ebdc'
2022-04-10T07:33:41.455 [Information] Executing 'CreatePingWorkflow' (Reason='(null)', Id=7d9cf6a9-6075-4c34-bd78-42b50a141eb1)
2022-04-10T07:33:41.457 [Information] Executed 'CreatePingWorkflow' (Succeeded, Id=7d9cf6a9-6075-4c34-bd78-42b50a141eb1, Duration=8ms)
2022-04-10T07:33:41.457 [Information] fab972cedda44432a6441240e5a29dee:0: Function 'CreatePingWorkflow (Orchestrator)' awaited. IsReplay: False. State: Awaited. HubName: knowledge. AppName: unstruk-knowledge-perf-functions-jobs. SlotName: Production. ExtensionVersion: 2.6.1. SequenceNumber: 13.
2022-04-10T07:33:41.457 [Information] fab972cedda44432a6441240e5a29dee:0: Orchestration 'CreatePingWorkflow' awaited and scheduled 0 durable operation(s).
2022-04-10T07:33:41.467 [Information] fab972cedda44432a6441240e5a29dee:0: Appended 3 new events to the history table in 0ms
2022-04-10T07:33:41.473 [Information] fab972cedda44432a6441240e5a29dee:0: Updated Instances table and set the runtime status to 'Running'
2022-04-10T07:33:41.473 [Information] fab972cedda44432a6441240e5a29dee:0: Deleting [TaskCompleted] message from knowledge-control-00
```

[durable-logs.txt](https://github.com/Azure/azure-functions-durable-extension/files/8458511/durable-logs.txt)

### Relevant source code snippets
```csharp
        [FunctionName(nameof(CreateJobOrchestration))]
        public async Task CreateJobOrchestration(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            string correlationId = context.NewGuid().ToString();

            try
            {
                var job = context.GetInput<Job>();

                if (job == null)
                    throw new InvalidOperationException("Invalid job.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"[{correlationId}] Attempting to create job [{job.Id}] entity workflow.");

                await context.CallSubOrchestratorAsync(nameof(CreatePingWorkflow), "ping");

                if (!context.IsReplaying)
                    Logger.LogDebug($"[{correlationId}] Created job [{job.Id}] processing workflow.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"[{correlationId}] Successfully created job [{job.Id}] orchestration.");
            }
            catch (Exception e)
            {
                throw new InvalidOperationException($"Failed to create job orchestration.", e);
            }
        }

        [FunctionName(nameof(CreatePingWorkflow))]
        public async Task CreatePingWorkflow(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            string correlationId = context.NewGuid().ToString();

            try
            {
                var ping = context.GetInput<string>();

                if (!context.IsReplaying)
                    Logger.LogDebug($"[{correlationId}] Sending ping [{ping}].");

                ping = await context.CallActivityAsync<string>(nameof(Ping), ping);

                if (!context.IsReplaying)
                    Logger.LogDebug($"[{correlationId}] Sent ping [{ping}].");
            }
            catch (Exception e)
            {
                throw new InvalidOperationException($"Failed to create ping workflow.", e);
            }
        }

        [FunctionName(nameof(Ping))]
        public async Task<string> Ping(
            [ActivityTrigger] IDurableActivityContext context)
        {
            string correlationId = Guid.NewGuid().ToString();

            try
            {
                var ping = context.GetInput<string>();

                Logger.LogDebug($"[{correlationId}] Received ping [{ping}].");

                return ping;
            }
            catch (Exception e)
            {
                throw new InvalidOperationException($"Failed to ping.", e);
            }
        }
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.6.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4.0
- **Programming language used**: C#, .NET 6.0

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 12:20 AM PT, 4/10/22 (but have been debugging this for last several days)
- **Function App name**: unstruk-knowledge-perf-functions-jobs
- **Function name(s)**: CreateJobOrchestration, CreatePingWorkflow, Ping
- **Azure region**: southcentralus
- **Orchestration instance ID(s)**: d116bc25088547cd8c2b31bd349f763f
- **Azure storage account name**: unstrukknowledgejobsperf

**Comment by olitomlinson** [comment]
@kirk-marple 

When did you upgrade to 2.6.1 (or even .NET 6) ? Could it be that the behaviour has regressed since the update? Are you able to revert to the last version in a test environment and see if the error reproduces still?

**Comment by kirk-marple** [comment]
.NET 6 was ~4 months ago; I think it was over the Xmas holiday.   2.6.1 was in Feb, right after it came out.

This new Durable Function I just wrote a week or so ago, and that's when I noticed it.   It may have been happening with the previous Durable Function, but I didn't notice it, since functionally it was working - and I wouldn't have seen the missing logs w/o explicitly checking.

Definitely a good idea, thanks - and really my only next option, I'm rolling back now to 2.6.0 and will update back with any findings.

**Comment by kirk-marple** [comment]
Holy moley, just rolled back to 2.6.0, and it worked as expected.

Checked my new Durable Function and our legacy one, and they both run to completion now.

OK, definitely a bug in 2.6.1.

**Comment by olitomlinson** [comment]
@kirk-marple great find! Thanks for taking the time to try that out! It’s really appreciated!

pinging @cgillum - looks like there might be a regression in 2.6.1

**Comment by davidmrdavid** [comment]
Thanks for reaching out @kirk-marple, and thanks @olitomlinson for helping diagnose.

Indeed, we're following a few threads that _seem_ to indicate there might be a bug with SubOrchestrations getting stuck, but it's still too early for us to conclude that these are all related, but something does seem off _at first glance_.

@kirk-marple: please do let me know if this issue re-appears with 2.6.0. I'll suggest this as a mitigation to other threads that are experiencing similar symptoms to see if it helps. In the meantime, our investigation continues :-)

**Comment by davidmrdavid** [comment]
@kirk-marple, just a heads up - one of the other threads with subOrchestrations getting stuck was experiencing that issue in 2.6.0 so there's a chance this thread and that one (https://github.com/Azure/azure-functions-durable-extension/issues/2133) are unrelated. 

Do let us know if the issue re-appears with 2.6.0. Still investigating.

**Comment by davidmrdavid** [comment]
@kirk-marple: with 2.6.1 -  are you able to repro this locally, or only on Azure?

**Comment by kirk-marple** [comment]
@davidmrdavid Only on Azure; I don't have a great way to test all our moving parts locally (since we're using Event Hub and Event Grid), so I only test the functions on Azure.

**Comment by davidmrdavid** [comment]
@kirk-marple. I'm still investigating this, and trying to cross-reference with other similar reports. So far, it's been difficult to find a root cause since our other incidents seem to all be running on different setups (different extension versions, different Functions Hosts, issue starting at different times in the year) and so it's been challenging to identify a root cause. We'll continue digging deeper though.

In the meantime, I had two questions for you:
1) Any updates on this behavior from your end? I assume the issue has not re-ocurred since downgrading to 2.6.0, is that correct?
2) When's the _earliest_ timestamp and orchestration instanceId (if available) you have for this behavior?

Thanks!

**Comment by kirk-marple** [comment]
@davidmrdavid All good so far; not a single problem with 2.6.0.

Unfortunately I've rebuilt that environment via Terraform, so I don't have the App Insights history to check for the earliest timestamp.  It was probably within 2 days before posting this issue that I noticed it; spent a couple days banging my head on it before trimming the code down to the simple 'ping' methods.

**Comment by olitomlinson** [comment]
@davidmrdavid

if @kirk-marple could very kindly agree to upgrade to 2.6.1 and then run the same tests again, we would know with a high degree of certainty that there is a problem with 2.6.1 (and the positive results that @kirk-marple experienced as part of the down-grade to 2.6.0 were not a pleasant environmental coincidence)

**Comment by davidmrdavid** [comment]
Thanks for the suggestion @olitomlinson, but before doing so I'd like to see if I can prepare an extra-instrumented DF Extension release that would allow us to obtain more telemetry to debug this issue. I realize @kirk-marple  is not seeing this error since downgrading to 2.6.0, but that's not what I'm seeing in other cases so I'm trying to increase our telemetry output before asking users to collect more data :) .

I'll look to reply shortly with an update, it's just been busy in the past few days because of a certain Microsoft conference that's coming up next Month :-)

**Comment by kirk-marple** [comment]
@olitomlinson I noticed there's a new 2.7.0 out now.  Would you prefer we upgrade to that and re-test, or just to 2.6.1?

> if @kirk-marple could very kindly agree to upgrade to 2.6.1 and then run the same tests again, we would know with a high degree of certainty that there is a problem with 2.6.1 (and the positive results that @kirk-marple experienced as part of the down-grade to 2.6.0 were not a pleasant environmental coincidence)

**Comment by olitomlinson** [comment]
@kirk-marple if you could hold fire on that as @davidmrdavid looks to be preparing a special build of the extension which includes more telemetry :)

I take it everything is still working good for you on 2.6.0 so far?

**Comment by kirk-marple** [comment]
Yep, still working 100% on 2.6.0 so far.

**Comment by davidmrdavid** [comment]
@kirk-marple, just following up to your ping in our other thread.

I've been using pretty much the same reproducer as you shared, mostly just with log statements removed, and I haven't been able to repro this issue with it; I've tested locally and on Azure. I'm attaching the `.zip`'ed project I'm using to this thread.
[stuckRepro.zip](https://github.com/Azure/azure-functions-durable-extension/files/8587994/stuckRepro.zip)

As a sanity check - does my attached repro match your expectations? Is it at all possible to see if you're able to repro the stuck orchestrations issue with it?

**Comment by davidmrdavid** [comment]
Just following up here, @kirk-marple.

I want to provide an update on our investigation and our understanding of the facts so far.

**Behavior**

In summary, what we're seeing here is that the Durable Functions is entering an internally inconsistent state. You can see this in the very logs you provided, where it reads: "2022-04-10T07:33:41.457 [Information] fab972cedda44432a6441240e5a29dee:0: Orchestration 'CreatePingWorkflow' awaited and scheduled 0 durable operation(s)."

An orchestrator cannot await 0 operations, as that means there's nothing to await. This is why the orchestrator is getting stuck: it's waiting for "nothing" to complete.

**Known reproducers**

The only well-understood way to trigger this behavior is by `await`'ing a non-durable API. When this occurs, the DurableTask framework no longer has control over the execution of your code but it believes that it does. The result is that the internal orchestration replay will complete before your orchestration code, leading to the assertion that your code is still Running and has awaited 0 tasks.

A simple way to repro this yourself is by writing a hello-world orchestrator that, before returning, calls `await Task.Delay(90000);`. That orchestrator will never exit its `Running` state.

Obviously, there's no illegal awaits in the code you've provided; but I have to conclude that something else is throwing off DurableTask's orchestrator-thread management logic. I'm still unsure of the cause.

**Relation to the other reports**

As you know, this ticket reports similar behavior to another GitHub incident. We also have an internal report of this happening. So, in total, 3 reports.

All 3 reports exhibit similar behavior, but the way they've managed to avoid the issue all differ. In your case, you've avoided the issue by using DF Extension 2.6.0. That doesn't work for others: the other  2 reports experience it in 2.6.0. 

Our internal report found a particularly confusing solution: using a new storage account. Somehow, their code gets stuck as soon as they switch to using an older storage account, but they haven't experienced this issue since using a new one. At this point, this particular solution doesn't make sense to me as storage should play no role in this part of the framework, but I'm keeping all options in the back of my mind.

The only commonality I've found across incident reports is that, among the affected orchestrators I've observed, none of them have an explicit return value. This is a weak observation but I'd be interested in seeing if this can be repro'd on your end if you add a `return <someVal>` at the end of your PingPong reproducer above. Looking at the DurableTask code for managing orchestrators, I could see how an explicit return statement could short-circuit whatever is triggering this hidden "illegal await"-type of  behavior.

**Next steps on my end**

I considered the possibility of creating a private package with more telemetry for you to try, but I'm putting that on pause as I don't think those would bring that much extra clarity. I'll let you know if that changes.

I have started looking at ways to transition affected orchestrators to the `Failed` state. That way, at least you would have a known signal with which to retry your workflow. I thought I could easily do that through this PR (https://github.com/Azure/durabletask/pull/725) but it seems it will take some time before we're able to merge this.

**What I need / experiments I'd like to run*

I need a reliable reproducer. Unfortunately, the PingPong app above works fine on my end. As a sanity check, it would help me to know whether you're able to repro this locally at all. If you're only able to repro this only on Azure, then any pointers on how to minimally repro what you see would be greatly appreciated.

As already mentioned, I'd like to see if you can repro this with the explicit return-value. Also, it would be good to have confirmation that this continues in the latest DF Extension: 2.7.0.

That's all. Sorry for the wall of text, and thanks again for your help :)

**Comment by davidmrdavid** [comment]
Just following up here with an update.

The latest [DF Extension release (v2.7.1)](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.7.1) contains [a **simple** check to detect the suspected](https://github.com/Azure/azure-functions-durable-extension/pull/2168) root cause of this behavior. 

If this check triggers, we will throw an exception on your orchestrator code, which should come up in our internal telemetry. I believe it would also appear in your own log traces within Application Insights, but I don't know that for certain. Regardless, if the issue were to re-occur with this DF Extension version, this new telemetry would give us confirmation of whether this "illegal await" problem is to blame. 

To be clear: this new telemetry won't tell us where the illegal await is taking place, it will just confirm that it is occurring.

With that confirmation, we should be able to invest more resources into finding a root cause. Please let us know if you're able to repro this after upgrading to DF 2.7.1, if you decide to do so. Thanks!

**Comment by kirk-marple** [comment]
@davidmrdavid Sorry for delay, we were in the middle of shipping our v1.  I've had a chance to upgrade to 2.7.2, and I believe I'm still seeing the same issue.  I see it call an activity (LocateJobConnector), and then see nothing after that line in the logs.

6/6/2022, 1:43:41.610 PM (PDT)

b5f27b95-0125-512f-b185-102df64cb905: Function 'LocateJobConnector (Activity)' completed. ContinuedAsNew: False. IsReplay: False. Output: (328 bytes). State: Completed. HubName: knowledge. AppName: unstruk-knowledge-perf-functions-jobs. SlotName: Production. ExtensionVersion: 2.7.2. SequenceNumber: 27. TaskEventId: -1

Please let me know what other details you may need.

**Comment by davidmrdavid** [comment]
Re-opening as issue persists.

**Comment by davidmrdavid** [comment]
Thanks @kirk-marple, for the response.

I see from our logs that this workflow ran from 20:43:31.19, to 20:43:41.65 UTC (very little) before it got stuck.

To confirm with you, this is the sequence I observe:

1.  CreateJobProcessingWorkflow (orchestrator) starts
2. LocateJobConnector (Activity) is scheduled
3. CreateJobProcessingWorfklow (Orchestrator) awaits some Task (probably the Activity)
4. LocateJobConnector (Activity) starts
5. LocateJobConnector (Activity) completes
6. CreateJobProcessingWorfklow (Orchestrator) awaits some Task (**unclear what was awaited**)

Do your logs also match this sequence? In any case, this would match the theory that your orchestrator is suffering from this "illegal await" issue I've been describing in previous responses. To be clear, so far I have no evidence that your code is responsible for this illegal await; it would seem that something in the invocation pipeline is causing it instead.

Since this execution took place with DF Extension 2.7.2, I would have expected to see telemetry indicating that we've detected an illegal-await, but for some reason your applications' Durable Functions telemetry goes silent from 2022-06-06 19:15:14.6266962 to 2022-06-06 21:34:47.2028016 UTC, so I have no data for your orchestrator's execution. 

This is very strange. Can you please help provide some context here? Was your application running in this "silent" time-window (note the time is in UTC). What happened at 21:34 that could explain the application suddenly emitting telemetry again? I suspect, for instance, that maybe this is when you rolled back to Extension version ~2.6.0.

Given our lack of telemetry, I'm going to have to ask for a few more execution traces. I need to know if this lack of telemetry is a re-ocurring issue, or a weird transient error. Could you please repro this a few more times with 2.7.2? Ideally, we'd also get a few traces of your PingPong orchestrator above which is simple-enough to reason about.

In the meantime, let me tag @cgillum and @lilyjma, for visibility. I'll need help to diagnose this error, could use assistance.

**Comment by kirk-marple** [comment]
@davidmrdavid Yep, this is the sequence that gets run.

You can see the code below, and the next in line would be ProcessJobOrchestration, which appears to never run.

Interestingly, it appears that time window is actually when I rolled out 2.7.2.  I rolled back to 2.6.0 sometime after 2pm PDT which would match the end of that time window.

I'd be happy to send the code over for the functions/entity.  It uses a bunch of services via DI for the "real work", which you can just stub out, most likely.  So these methods are actually pretty simple to read through.

I'll go back to 2.7.2 and do some more testing with it, likely tomorrow PDT, and post back here when done.

```
        [FunctionName(nameof(CreateJobProcessingWorkflow))]
        public async Task CreateJobProcessingWorkflow(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            using var dop = TelemetryClient.StartOperation<DependencyTelemetry>($"Job processing");

            try
            {
                var job = context.GetInput<Job>();

                if (job == null)
                    throw new InvalidOperationException("Invalid job.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"Attempting to process job [{job.Id}] workflow.");

                var jconnector = await context.CallActivityAsync<JobProcessorConnector>(nameof(LocateJobConnector), job);

                if (jconnector == null)
                    throw new InvalidOperationException($"Invalid job [{job.Id}] connector.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"Attempting to call job [{job.Id}] started orchestrator.");

                await context.CallSubOrchestratorAsync(nameof(JobFunctions.ProcessJobOrchestration), GenerateJobOrchestration(JobOrchestrationTypes.Started, job, jconnector));

                if (!context.IsReplaying)
                    Logger.LogDebug($"Successfully called job [{job.Id}] started orchestrator.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"Attempting to call job [{job.Id}] running orchestrator.");

                await context.CallSubOrchestratorAsync(nameof(JobFunctions.ProcessJobOrchestration), GenerateJobOrchestration(JobOrchestrationTypes.Running, job, jconnector));

                if (!context.IsReplaying)
                    Logger.LogDebug($"Successfully called job [{job.Id}] running orchestrator.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"Attempting to call job [{job.Id}] finished orchestrator.");

                await context.CallSubOrchestratorAsync(nameof(JobFunctions.ProcessJobOrchestration), GenerateJobOrchestration(JobOrchestrationTypes.Finished, job, jconnector));

                if (!context.IsReplaying)
                    Logger.LogDebug($"Successfully called job [{job.Id}] finished orchestrator.");

                if (!context.IsReplaying)
                    Logger.LogDebug($"Successfully processed job workflow.");

                dop.Telemetry.Success = true;
            }
            catch (Exception e)
            {
                dop.Telemetry.Success = false;

                Logger.LogException($"Failed to process job workflow.", e);

                throw new InvalidOperationException($"Failed to process job workflow.", e);
            }
        }
```

Also here's the host.json that's been running today, if helpful:
```
{
    "version": "2.0",
    "extensions": {
        "durableTask": {
            "hubName": "knowledge",
            "extendedSessionsEnabled": false,
//            "extendedSessionIdleTimeoutInSeconds": 300,
            "storageProvider": {
                "partitionCount": 8,
                "maxQueuePollingInterval": "00:10:00",
                "useLegacyPartitionManagement": false,
                "workItemQueueVisibilityTimeout": "01:00:00"
            }
        },
        "eventHubs": {
            "batchCheckpointFrequency": 5,
            "eventProcessorOptions": {
                "maxBatchSize": 3,
                "prefetchCount": 10
            }
        }
    },
    "logging": {
        "LogLevel": {
            "Default": "Trace",
            "Microsoft": "Error",
            "Azure.Core": "Warning"
        },
        "ApplicationInsights": {
            "LogLevel": {
                "Default": "Trace",
                "Microsoft": "Error",
                "Azure.Core": "Warning"
            },
            "samplingSettings": {
                "isEnabled": true,
                "maxTelemetryItemsPerSecond": 200,
                "excludedTypes": "Dependency;Exception;Trace",
                "includedTypes": "PageView;Request;Event"
            },
            "enableLiveMetrics": false,
            "enableDependencyTracking": true,
            "enablePerformanceCountersCollection": true,
            "httpAutoCollectionOptions": {
                "enableHttpTriggerExtendedInfoCollection": false,
                "enableW3CDistributedTracing": false,
                "enableResponseHeaderInjection": true
            }
        }
    }
}
```

**Comment by davidmrdavid** [comment]
Thanks @kirk-marple.

I'll reach out internally to see what our debugging options are. We'll be waiting for your new traces as well.

I mostly wanted to note down that, from looking at your code now, we seem to be in a different situation that the one I observed in the related "illegal await" threads. In other threads, this issue occurred after the orchestrator was done performing all the work it could, nearing its return statement. In your case, it seems to be occurring early in the orchestrator, and there are still many sub-orchestrators to be invoked. 

I just wanted to call this out now, since it's different from the trends I've observed so far. 
In any case, I'll try to reach back with more options asap

**Comment by kirk-marple** [comment]
@davidmrdavid Just ran another test with 2.7.2.  Same results.  It appears to think it's finished after executing LocateJobConnector successfully.  Note, there were two job orchestrations submitted at same time.  Both had same result.

6/7/2022, 11:23:12.851 AM
Executed 'CreateJobProcessingWorkflow' (Succeeded, Id=c21056b2-ff3e-425d-a000-c8d443fef4ea, Duration=36ms)

6/7/2022, 11:23:21.261 AM
Executed 'CreateJobProcessingWorkflow' (Succeeded, Id=bf36c9b3-7c99-42ef-b234-fb4d873f2e62, Duration=41ms)

![image](https://user-images.githubusercontent.com/13594550/172455850-790facb5-525c-4938-9dd4-f5f06affc47b.png)

**Comment by davidmrdavid** [comment]
Thanks @kirk-marple.

Strangely enough I yet again see barely any telemetry for when you upgrade to 2.7.2, which is very anomalous. 

Let me engage the team to see how we can set up a debugging call. This is really bizarre.

**Comment by davidmrdavid** [comment]
@kirk-marple:

Please send me an email to `dajusto@microsoft.com` with your rough availability over the coming days and I'll look to set up a debugging session. 

We will still communicate through this thread as I engage more of the team, but it would be good to see if we can fast-track this investigation through a call. Thanks!

**Comment by schutztj** [comment]
@davidmrdavid 
Unfortunately, I'm still hitting this in 2.8.1 with similar conditions. We, too, are setting JsonConvert.DefaultSettings globally so I had a lot of hope for the latest release.  It seems that the second call to a Durable Entity from an orchestration via an entity proxy is triggering this (we do this frequently so there is clearly some other factor at play here) but I see the same:
[awaited and scheduled 0 durable operation(s)]

What can I provide to help further the investigation?

**Comment by davidmrdavid** [comment]
Hi @schutztj ,

Hmm, that's strange. Can you please create a separate issue with a minimal reproducer? That should allow us to take a closer look at this. Thanks!
