### ISSUE TITLE
Durable Function Orchestrator triggering multiple instances

### ISSUE THREAD

**Issue by leopinheirohk** [Azure/azure-functions-durable-extension#2190]
### Description
We have a durable function app to execute queries in Snowflake from Azure Data Factory. Recently, we have noticed some queries being executed twice, even though ADF only called that Function App once. Because of this, data in Snowflake is being corrupted or duplicated.

When looking at Function App logs, we can see that the first instance seems to be "dying" (it just stops logging), then another instance is triggered and completes successfully. 

The logs also show us that both instances have the same orchestration id and the start time of these instances coincide with the Snowflake logs of the queries running twice.

It seems to me that the Durable Function App Orchestrator is loosing track of the first instance, and to remediate this, it triggers a second one.

Please advise. Thanks.

### App Details

- **Region**: East US 2
- **Microsoft.Azure.WebJobs.Extensions.DurableTask**: Version="2.4.3"
- **Microsoft.NET.Sdk.Functions**: Version="3.0.11"
- **Programming language used**: c#

**Comment by cgillum** [comment]
Are these activities expected to be long running? I noticed that the second, successful run took about 50 minutes to complete. I'm wondering if your app may have been shut down while the first execution was still in progress. Also, what hosting plan are you using?

One thing to be aware of is that activity functions are internally triggered by queue messages, and just like any queue-triggered process, there is an **at least once** execution guarantee. This means your code should be prepared to have some executions occur more than once.  It's supposed to only happen in rare circumstances, like after a process crash, but it still may happen. I'm curious to understand whether your situation was one of those rare cases or if something else happened, resulting in this duplicate execution.

**Comment by cgillum** [comment]
Unfortunately, I couldn't find any information about your app. Would you be willing to share what region it's running in and copy/paste the instance ID (so that we can easily copy/paste it without typos)?  I'm interested to take a look and see why this is happening so frequently for you.

> Also, could you elaborate on this "your code should be prepared to have some executions occur more than once" .

Activity triggered functions have **at least once** execution guarantees. This is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-types-features-overview#activity-functions. You mentioned that this is resulting in corruption and/or duplication for your Snowflake data. This sounds like a big problem to me. It's unfortunately not possible for us to 100% guarantee that any activity function will always execute exactly once. This is just physics, unfortunately. To account for this, you should consider whether you can change the implementation of your activity functions or the Snowflake queries to be idempotent, so that duplicate executions don't have such negative side-effects.  This is not to say that we won't look into this issue, but rather to let you know that even if we discover and fix the root cause for your daily occurrences, there still could be other, more rare causes of duplicate executions.

Two more things I'll mention: one is that it looks like you're running a very old version of the Durable Functions extension (2.4.3). We recommend you upgrade to the latest version, 2.7.1 at the time of writing, since we regularly make reliability improvements, some of which may result in less likelihood of duplicate executions.

The other thing is that we're considering a feature to enable **at most once** execution guarantees, where we suspend your orchestration if we suspect the possibility of a duplicate execution. This is intended to help users that aren't able to make their activity functions idempotent. The downside is that it would require manual intervention to resume an orchestration in this way. Let me know if you think you might be in a situation where you'd need a feature like this.

**Comment by leopinheirohk** [comment]
Hi @cgillum did you have the chance to check why we are facing this problem so often, specially in the last 1 month?

**Comment by cgillum** [comment]
@leopinheirohk sorry - I've been having trouble finding data for your orchestration. Possibly the old age of your extension version could be a contributor, but so far I haven't been able to find that orchestration ID in our telemetry.

If you haven't already, you may want to open an official support request against Azure Functions. The support team may have better luck than I'm currently having. However, I'll keep trying in the meantime as I have cycles.

**Comment by cgillum** [comment]
It looks like you removed your screenshot. Can you share the exact time range again (in UTC)?

**Comment by leopinheirohk** [comment]
> you may want to open an official support request against Azure Functions

Sure I will try that

> It looks like you removed your screenshot. Can you share the exact time range again (in UTC)?

Here it is

First time:
**5/18/2022, 2:44:52.595 PM**
Host.Triggers.DurableTask
4a13c7b24ba140a39159ba0d3b40a7df: Function XXXX (Activity)' started. 

Second time:
**5/18/2022, 3:09:24.591 PM**
Host.Triggers.DurableTask
4a13c7b24ba140a39159ba0d3b40a7df: Function XXXX (Activity)' started

**Comment by cgillum** [comment]
I still can't find this instance anywhere in our telemetry for any region during those time ranges. By chance are you running your app on a platform *other than* Azure Functions or Azure App Service, like in AKS?

**Comment by leopinheirohk** [comment]
> I still can't find this instance anywhere in our telemetry for any region during those time ranges. By chance are you running your app on a platform _other than_ Azure Functions or Azure App Service, like in AKS?

@cgillum No, it is a ordinary Function App with Premium V2 price tier. I will open a proper support request with Function App so that we can potentially share more details to facilitate locating the telemetry data.

Thanks for you input anyway. There were a lot of things I wasn't aware of and you helped clarifying.
