### ISSUE TITLE
Orchestrations not failing when activity fails and a sub-orchestration is running

### ISSUE THREAD

**Issue by IGx89** [Azure/azure-functions-durable-extension#2283]
### Description
If my orchestration simply calls an activity that fails (throws an exception), my orchestration's runtime status changes to Failed as expected. If however I launch a sub-orchestration before the activity call that fails, my orchestration's status remains Running.

[The docs](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp#unhandled-exceptions) say "If an orchestrator function fails with an unhandled exception, the details of the exception are logged and the instance completes with a Failed status," so it remaining as Running when the orchestrator function fails seems like a bug?

### Expected behavior
Orchestration's runtime status changes to Failed

### Actual behavior
Orchestration's runtime status remains as Running, causing it to be in a stuck state.

### Relevant source code snippets
```csharp
[FunctionName("MyOrchestration")]
public async Task RunOrchestrator([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    _ = context.CallSubOrchestratorAsync("MySubOrchestration", $"{context.InstanceId}_SubOrchestration", "something");

    await context.CallActivityAsync("ActivityThatThrowsException", "something");
}
```

### Known workarounds
None that I've found so far. Maybe if I wrapped every activity call in a try/catch which manually terminated all sub orchestrations when an activity threw an exception, but that would be ugly.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.8.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Storage provider**: Azure Storage
- **Programming language used**: C#

**Comment by cgillum** [comment]
The reason your orchestration remains in the "Running" state is because the sub-orchestration it started is still running.

Orchestrations will not transition out of "Running" until all of its durable tasks are complete or cancelled. This problem is most commonly seen when people use the `CreateTimer()` API to create a durable timer but then allow the orchestrator to complete without either cancelling the timer or waiting for it to complete. It's the same thing here. It's not specific to sub-orchestrations or to failures. I would expect the same behavior (stuck in "Running") even if the activity completed succesfully.

**Comment by IGx89** [comment]
Thanks for your quick reply! Is that documented anywhere? Should I submit a request to update the documentation on the error handling page to mention this?

My orchestration method at the end makes a call to a cleanup activity that terminates any running sub-orchestrations (forgot to add it to my example above). Sounds like the recommended solution here would be that "ugly" workaround I mentioned above then? Would something like this work:

```csharp
[FunctionName("MyOrchestration")]
public async Task RunOrchestrator([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    try
    {
        _ = context.CallSubOrchestratorAsync("MySubOrchestration", $"{context.InstanceId}_SubOrchestration", "something");

        await context.CallActivityAsync("ActivityThatThrowsException", "something");
    }
    finally
    {
        await context.CallActivityAsync("MyOrchestration_Cleanup", context.InstanceId);
    }
}

[FunctionName("MyOrchestration_Cleanup")]
public async Task Cleanup(
    [ActivityTrigger] string parentInstanceId,
    ILogger log,
    [DurableClient] IDurableOrchestrationClient client)
{
    log.LogInformation($"Cleaning up for parent orchestration {parentInstanceId}");

    var searchResult = await client.ListInstancesAsync(new OrchestrationStatusQueryCondition
    {
        InstanceIdPrefix = $"{parentInstanceId}_"
    }, default);

    foreach (var result in searchResult.DurableOrchestrationState)
    {
        await client.TerminateAsync(result.InstanceId, "Parent terminated");
    }
}
```

**Comment by davidmrdavid** [comment]
Apologies for the late reply @IGx89. Yes I believe that's right: having a clean-up call at the end of an orchestrator's execution, both under success and failure conditions, would be the appropriate workaround to ensure your orchestrator exits the "Running" state as soon as possible. Otherwise, it will wait for its sub-tasks (such as sub-orchestrators) to complete.

We're aware that this is a bit confusing, but we cannot fix this without introducing a breaking change. It's definitely in consideration for a next major version, though we don't have any active plans towards a new major release at this time.

I'll be closing this issue as a workaround and explanation has been provided. Please feel free to re-open it if you need further assistance. Thanks!
