### ISSUE TITLE
Orchestration replays activities more than once when concurrent requests are sent

### ISSUE THREAD

**Issue by Kavitha-Desu-Caci** [Azure/azure-functions-durable-extension#2290]
### Description
> We are using durable functions to do long processing. Always when I sent concurrent requests (5 , 10 or 20) for orchestration which is taking more than 9min its always tries to run the activities multiple times. Sometimes 6 or 7 times also because of this it taking very long.  I can consistently reproduce this issue. 

### Expected behavior
> The activity should run only once.

###Actual behaviour
The Function App func-distancegenerationapi has 1 Orchestrator function DistanceGenerationOrchestratorFunction, and 2 Activity functions DistanceGenerationFormatResultActivityFunction and DistanceActivityFunction.

### App Details

- **Durable Functions extension version (2.4) but also tried with  v2.8.1 but no luck**:
- **Azure Functions runtime version ( 2.0)**:
- **Programming language used**: (C# .NET)

- **Timeframe issue observed**:  13/10/2022 3.30AM
- **Azure region**: UK South
- **Orchestration instance ID(s)**: 47e951d47adc48c3aa4cae4dfef8cca9, 44630ddb3fcb4ed38415b0ac4a2c5bf0, 10cd255c138442e5b2b6bbe177ddfef3

**Findings**
There are 4 scenarios like following 
1.	Expected scenarios(only start once for each activity trigger): 
instance id : 3abe1404ad674aa2a2f5213e97a1dc9f
![Expected one](https://user-images.githubusercontent.com/100154229/195758333-61dbbe20-ccbb-4577-b5f2-198360ff9d19.png)

2.2.	DistanceGenerationFormatResultActivityFunction started twice with around 6min gap. 
Instance id: 47e951d47adc48c3aa4cae4dfef8cca9
![FormatResultStartedTwice](https://user-images.githubusercontent.com/100154229/195758369-71441292-d7fd-47b1-8c44-1241eb1ea09a.png)

3.	DistanceActivityFunction started twice similar with around 6min interval. 
Instance id: 44630ddb3fcb4ed38415b0ac4a2c5bf0
![ActivityStartedTwice](https://user-images.githubusercontent.com/100154229/195758414-1ce0541a-3aff-4d4c-98b6-833c605303e9.png)

4.	Both activity trigger started several times.
Instance id: 10cd255c138442e5b2b6bbe177ddfef3
![FormatAndResultStartedTwice](https://user-images.githubusercontent.com/100154229/195758449-d61bea0a-e8ea-42bb-905f-583960035be5.png)

5.	To rule out the possibility of durable function extension version, you have updated the task version to the latest one 2.8.1 on prod-staging slot, while the intermittent issue still could be easily reproduced.

**Comment by Kavitha-Desu-Caci** [comment]
@cgillum - Any update on this issue will be much appreciated?

**Comment by cgillum** [comment]
Hi @Kavitha-Desu-Caci.

I took a look at **47e951d47adc48c3aa4cae4dfef8cca9**, and the problem seems to be that the app instance was shut down while the activity function was still running. I can confirm this as there is a shutdown event logged at 2022-10-13 05:29:10 UTC. As a result, another app instance restarted the aborted activity execution. I don't know exactly why it was shut down (it could have been a manual restart, a configuration change, or a scale operation, as examples), but this is what the telemetry indicates to me and explains why you have a duplicate execution. If you're using C#, then you can be notified about host shutdown events by using the [host cancellation token binding](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#cancellation-tokens). You won't be able to prevent the shutdown, but it will allow you to at least respond to it more gracefully.

I also looked at **10cd255c138442e5b2b6bbe177ddfef3**, which appears to be the same problem. However, in this case, it doesn't appear to be a scale operation because the same app instance that restarted is the same one that resumed the aborted activity invocation. This leads me to believe it's either a manual app restart or a configuration change.

So it seems to me this isn't directly related to concurrently starting orchestrations. Rather, it seems like your app instances are being restarted in the middle of your long activity executions. I suggest reviewing any operation logs you may have access to in order to identify the cause of the app instance restarts. If you need further help with this, you can try using the [Azure Functions Diagnose and Solve Problems tool](https://learn.microsoft.com/en-us/azure/azure-functions/functions-diagnostics) (which can provide more information about app restarts) or open a support request with Microsoft Azure.

**Comment by jviau** [comment]
@Kavitha-Desu-Caci - in addition to what @cgillum said, activities are a _at-least-once_ guarantee in durable (as opposed to _exactly-once_). Due to this, it is recommended you write your activities   to be idempotent. The reason is exactly what was described - activities may be interrupted due to external factors. Or even after an activity finishes, durable framework is interrupted before it can persist the activity completion and results, in which case it has to be ran again.

**Comment by Kavitha-Desu-Caci** [comment]
@cgillum  & @jviau - thank you so much for looking into this issue. I have checked all the logs and we have not done any activity at that time like restarting or something else. I reported this issue to Microsoft Azure team and they checked all the logs and confirmed that all seem like memory issues. It all seems the host shutting down is due to Durable Function App consumed a huge size of memory resources, which caused the related worker instance being under low memory situation, that’s why the platform shutdown related processes proactively.

**Comment by cgillum** [comment]
@Kavitha-Desu-Caci thanks for following up - that explanation makes sense to me. I'll go ahead and assume that you received some information about different ways to control memory usage. For example, [concurrency controls](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-perf-and-scale#concurrency-throttles) are available if the high memory usage is related to concurrency.
