### ISSUE TITLE
DurableEntityClient cannot retrieve large message from blob storage

### ISSUE THREAD

**Issue by nicolaor** [Azure/azure-functions-durable-extension#2420]
### Description
We have followed the official documentation to setup our durable functions for zero-downtime deployments (see: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-zero-downtime-deployment) 

With this scenario we have 3 different storage accounts configured:

1. **StorageAccount1** (shared between our 2 deployment slots)
- Instance and History tables are located in this Storage Account
- This Storage Account is referenced as the "AzureWebJobStorage" in the application settings of both slots

2. **StorageAccount2** (used by production slot)
- WorkItem and Control Queues for production slot are located in this Storage Account
- this is referenced as the "DurableManagementStorage" in the application settings of the production slot

3. **StorageAccount3** (used by CD slot)
- WorkItem and Control Queues for CD slot are located in this Storage Account
- this is referenced as the "DurableManagementStorage" in the application settings of the CD slot

Within our code (which is not always running in the context of a durable function), we are retrieving the state of Durable Entities using DurableClientFactory to create a DurableEntityClient by specifiying the following DurableClientOptions:
- ConnectionName -> set to AzureWebJobStorage (pointing to StorageAccount1)
- TaskHubName -> set to the same TaskHub used by the durable function
- IsEcternalClient -> true

In some rare scenarios, our Durable Entity State might contain more than 16KB of data, in which case the content gets written to a blob. The strange thing is that this blob container will be located in StorageAccount2 or StorageAccount3 and not in StorageAccount1 as we would expect.
Once a large message gets written to a blob and we then try to retrieve the Entity State using a DurableEntityClient, we get the below error:

> DurableTask.AzureStorage.Storage.DurableTaskStorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
>  ---> Microsoft.WindowsAzure.Storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
>    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
>    at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadRangeToStreamAsync(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, IProgress`1 progressHandler, CancellationToken cancellationToken)
>    at DurableTask.AzureStorage.Storage.AzureStorageClient.WrapFunctionWithReturnType(Func`3 storageRequest, OperationContext context, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 156
>    at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId)
>    at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String accountName, String operationName, String clientRequestId, Boolean force) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 136
> Request Information
> RequestID:99d56c46-601e-005e-2daf-554c71000000
> RequestDate:Mon, 13 Mar 2023 13:25:32 GMT
> StatusMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> ErrorCode:AuthenticationFailed
> ErrorMessage:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:99d56c46-601e-005e-2daf-554c71000000
> Time:2023-03-13T13:25:32.0168802Z

If we use a single Storage Account (without specifying a separate storage account for DurableManagementStorage) everything works correctly, so the issue seems not to be on our end.

### Expected behavior
It should be possible to retrieve Durable Entity State by using a DurableEntityClient even if separate storage accounts are configured   for DurableManagementStorage and AzureWebJobStorage

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.9.2 
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: C#

**Comment by sebastianburckhardt** [comment]
Still having a bit of trouble understanding what it is you are trying to do. 

What confuses me in your description is that you are saying the tables are stored in a different account than the queues, which is not something I think can work - the storage backend treats the combination of tables, queues, and blobs as a single logical "task hub"  that is always in a single storage account.  
Your situation is a bit different than what is described in the section "Status Check With Slot" in [https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-zero-downtime-deployment]. The latter suggests to use two task hubs (one per slot), and switch between these slots at a moment in time when the task hub for the current slot is idle, i.e. all orchestrations have completed. That article unfortunately appears to have been written before durable entities were added as a feature, because it cannot work that way for entities (entities are orchestrations that never complete, so you cannot wait for them to complete before swapping slots).

That said, your description suggests you are somewhat aware of that problem and devising a different solution.

**Comment by sebastianburckhardt** [comment]
Thanks for clarifying, I understand now. 

I took a look at the code and it appears indeed that as you have pointed out, the blobs that represent large messages are not stored in the tracking store as one might expect (because that is where the history tables linking to these blobs are being stored), but inside the default store. This seems not ideal, but also not necessarily an immediate problem, because the  blob links still point to the account where the blob is actually located.

So then the question becomes why the blob access fails. Based on your error message this appears to be an authentication issue. Most likely, the application either does not have the necessary permission for downloading the blob content from that URL, or is not using the necessary credentials. Are you using managed identity for access control, or connection strings?

**Comment by nicolaor** [comment]
Hi @sebastianburckhardt 

The problem with accessing the blob, is that an external client application (in our case this is a web application which visualizes the state of our durable entities) is only aware of the shared storage (the one containing the tables). The storage account(s) where the large messages get stored are completely unknown to that client.

In the external client application, we use the following approach to access durable entity state:
- We added the DurableClientFactory in startup -> builder.Services.AddDurableClientFactory();
- We then create a DurableEntityClient from that factory by using the following DurableClientOptions:
-- ConnectionName: reference to the connection string pointing to the shared storage account (where tables are located)
-- TaskHub: the taskhub name (same as the one configured for the durable functions)
-- IsExternalClient: true

![image](https://user-images.githubusercontent.com/89914175/227453558-b7b415b0-23c8-4b02-954a-2ab97a917365.png)

We are not accessing the storage with the managed identity here, but I don't think this is relevant. With this configuration, the external client is able to retrieve the entity states, it only fails once a large message is generated.

**Comment by sebastianburckhardt** [comment]
In my understanding this is a bug in the Azure Storage provider and I have filed an issue azure/durabletask#879.

**Comment by lilyjma** [comment]
The problem has been resolved per issue linked above. Closing this issue.
