### ISSUE TITLE
Graceful shutdown for Entity Functions

### ISSUE THREAD

**Issue by collins-benj** [Azure/azure-functions-durable-extension#2455]
**Is your feature request related to a problem? Please describe.**
There is currently no defined way to shut down an Entity Function called from a durable context, example:

```csharp
 await context.CallEntityAsync(
     ThrottleSender.SingletonEntityId,
     nameof(ThrottleSender.ProcessQueuedCommands)
 );
```

if a host shutdown occurs while `ProcessQueuedCommands` is running, there is no way for it to know to gracefully shutdown. There's no way for us to supply a cancellation token as input is serialized, and simply adding a cancellation token in method header of the entity function will also have no effect (cancellation is never requested, even when host (or partition, as discussed in #2437 ) shutdown occurs), for example:

```csharp
 public async Task<ThrottleSender> ProcessQueuedCommands(
     CancellationToken cancellationToken
)
{
     var endTime = DateTimeOffset.UtcNow; + TimeSpan.FromMinutes(5);
     while( !cancellationToken.IsCancellationRequested && DateTimeOffset.UtcNow < endTime)
     {
         // processing stuff here
     }
     // graceful shutdown operations here
}
```

**Are there any existing GitHub discussions or issues filed that help give some context to this proposal?**
https://github.com/Azure/azure-functions-durable-extension/issues/2437 spawned our interest in this feature

**Describe the solution you'd like**
We'd like to have cancellation token support within entity functions; that is, in the above example, if we request a cancellation token from DI, it should be activated to the `IsCancellationRequested = true` state when the functions host (or partition, as discussed in #2437 ) shuts down.

**Describe alternatives you've considered**
We haven't considered any other specific alternatives

**Additional context**
Not having graceful shutdown has exacerbated existing issues with split-brain entity processing when functions move hosts. More details in #2437.

**Comment by sebastianburckhardt** [comment]
Yes, cancellation of entity operations is a desirable feature that does not currently exist. One could imagine extending the API, such as by adding a `CancellationToken` property to `IDurableEntityContext`. It is not easy to add however since our internal APIs (how the backend talks to the extension) do not currently have the ability to signal a cancellation (neither for orchestration nor for entity instances).

As a workaround, you could try to process shorter batches inside ProcessQueuedCommands. For example, when an entity receives a ProcessQueuedCommands signal, instead of always processing the entire queue, process only as many entries as you are confident can be finished quickly. If something is left in the queue, *have the entity send another ProcessQueuedCommands signal to itself*. This means that the entity, right after saving its state, will immediately execute another ProcessQueuedCommands. That way, you are never accumulating a lot of changes for a long time, but writing changes back to storage more continuously.

**Comment by lilyjma** [comment]
@collins-benj Does Sebastian's suggestion work for you?

**Comment by collins-benj** [comment]
I don't think this suggestion would work for all our needs. When you say:
>  process only as many entries as you are confident can be finished quickly

what about in cases where processing a single entry can take longer than a reasonably short period of time? Is the suggestion to move away from doing so within the entity function?
