### ISSUE TITLE
Still Receiving Queue Polling Activity for deleted Azure Function

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#2475]
We seem to be receiving queue activity for a function that has been deleted in Azure.

We added logging on our storage account to see what the source of the traffic could be, but all I was able to find was an IP address that doesnt point to any provisioned appservice in our subscription.

The only reference to this deleted azure function was a fileshare that I found in the storage account, I thought deleting it would solve these phantom queue polling, but its still happening.

I also learnt that the queue polling can happen from the Scale Controller and the Function Host.

Is the Scale Controller polling my queue even though the Function host is gone?

I can provide details if need be.

**Comment by nytiannn** [comment]
@gorillapower ,Thanks! Is the function app a Durable Functions app? If so, could you provide more details so that we can investigate? Please see template below. 

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.
