### ISSUE TITLE
Azure Python durable function not scaling out with EP2 Plan

### ISSUE THREAD

**Issue by ameykale** [Azure/azure-functions-durable-extension#2529]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.
I have Azure Python durable function deployed with EP2 plan. Even though minimum instances and always ready instances are configured as three, the durable function did not scale out and created multiple instances. 

1. Plan: EP2
2. Minimum instances: 3
3. ready instances: 3
4. Maximum instances: 6
5. Function runtime version: 3.20
6. Python version: 3.8
7. functionTimeout: 7 hours
8. Http trigger

The function connects to Snowflake and executes queries.  Today,  one query was executing from the Python function and it was taking long time for execution. All the subsequent requests were queued into the same instance and were in the pending state. Eventually the  function timed out after 7 hours and then the rest of the requests were processed. I was expecting the other two instances to receive the subsequent requests as the first instance was blocked.

### Expected behavior
Other two ready instances to serve the requests rather than adding the request to the queue of the first instance.

### Actual behavior
The subsequent requests were added to the queue of the first instance. 

### App Details

- Durable Functions extension version 1.1.6
- Azure Functions runtime version 3.28
- Programming language used: Python

### If deployed to Azure

-Timeframe issue observed: 2023-07-26 9 PM to 2023-07-27 3 AM.
- Function name(s): copyIntoSnowflake
- Azure region: West US 2
- id: 219146e192fa694d
- operation_id: 5a80257178aced429f17c5f2b5165ea7
- invokationId: 19542c40-42c7-46f5-954f-b26bf37ad6c5
- hostInsatnceId: 2f0a0681-af5c-46f6-9341-c51dd68d1f26
> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by nytian** [comment]
Hi, thanks for the information provided.

If I understand correctly, you are asking why the other workers cannot process the message in the same queue? Well, for each orchestration queues/ control queue, only one worker can own the lease/ process the message at any single time. So, for the same queue, the following message cannot be processed by other workers if there is no partition movement among workers.

And partition movement can only happen when workers scale in/ out which is decided by the workload of the Durbale Functions App. I queried your function with the info provided, all the other queues worked fine. And I do recommend updating the DF extension version which is v2.10.0 now since you are using a very old version to avoid any known bugs. 

Please let me know if there is any other question.

**Comment by nytian** [comment]
Close the issue as no further response.
