### ISSUE TITLE
Passing a Stack variable between Orchestrators: Between executions, order of items in the Stack is not preserved

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-durable-extension#2551]
### App Details
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.10.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
  </ItemGroup>
  ...
</Project>
```
### Description
Consider the following Basic Function App.

```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace FunctionApp2;

public static class Function1
{
    [FunctionName("Function1_HttpStart")]
    public static async Task<HttpResponseMessage> HttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestMessage req,
        [DurableClient] IDurableOrchestrationClient starter,
        ILogger log)
    {
        var transitionRequest = new TransitionRequest
        {
            ParentTransitions = new Stack<Transition>()
        };
        transitionRequest.ParentTransitions ??= new Stack<Transition>();

        string instanceId = await starter.StartNewAsync("Function1", transitionRequest);

        log.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

        return starter.CreateCheckStatusResponse(req, instanceId);
    }

    [FunctionName("Function1")]
    public static async Task RunOrchestrator1([OrchestrationTrigger] IDurableOrchestrationContext context)
    {
        TransitionRequest transitionRequest = context.GetInput<TransitionRequest>();

        transitionRequest.ParentTransitions.Push(new Transition("T0", "For"));

        await context.CallSubOrchestratorAsync("Function2", transitionRequest);
    }

    [FunctionName("Function2")]
    public static async Task RunOrchestrator2([OrchestrationTrigger] IDurableOrchestrationContext context)
    {
        TransitionRequest transitionRequest = context.GetInput<TransitionRequest>();

        transitionRequest.ParentTransitions.Push(new Transition("T1", "For"));

        _ = await context.CallSubOrchestratorAsync<TransitionRequest>("Function1", transitionRequest);
    }
}

public record Transition(string Name, string Type);

public class TransitionRequest
{
    public Stack<Transition> ParentTransitions { get; set; }
}
```
### Expected behavior
When passing data between the orchestrators, in the `Stack` variable, the order of items should be preserved.

When the `Function1_HttpStart` is triggered, the `transitionRequest.ParentTransitions` stack variable should have items in the following order.
```
[0] T1
[1] T0
[2] T1
[3] T0
...
```

### Actual behavior
The `Stack` variable is going out of order.

1st run: Looking good
![image](https://github.com/Azure/azure-functions-durable-extension/assets/5653381/7b5b5057-9972-417e-a05e-c950ca6660fb)

2nd run: Looking good
![image](https://github.com/Azure/azure-functions-durable-extension/assets/5653381/5a581ad1-1442-46c6-b970-d21bf3c80640)

3rd run: **Order is messed up**
![image](https://github.com/Azure/azure-functions-durable-extension/assets/5653381/880febfa-cdf2-4ee8-9e80-a587b64ca451)

4th run: **Order is messed up**
![image](https://github.com/Azure/azure-functions-durable-extension/assets/5653381/865c69ba-8a4d-4706-b6dd-793401c6bf27)

**Comment by jaliyaudagedara** [comment]
Seems the issue is with Serialization/Deserialization.

```csharp
using Newtonsoft.Json;

var transitions = new Stack<Transition>();

transitions.Push(new Transition("T0", "For"));
transitions.Push(new Transition("T1", "For"));
transitions.Push(new Transition("T0", "For"));
transitions.Push(new Transition("T1", "For"));
transitions.Push(new Transition("T2", "For"));

var settings = new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.None,
    DateParseHandling = DateParseHandling.None,
};

string jsonString = JsonConvert.SerializeObject(transitions, settings);
var deserializedTransitions = JsonConvert.DeserializeObject<Stack<Transition>>(jsonString);

Console.WriteLine("--Original Popping--");
while (transitions.Count > 0)
{
    Transition transition = transitions.Pop();
    Console.WriteLine(transition);
}
Console.WriteLine("----------------------------------");

Console.WriteLine("--Serialize, Deserialize Popping--");
while (deserializedTransitions!.Count > 0)
{
    Transition transition = deserializedTransitions.Pop();
    Console.WriteLine(transition);
}

public record Transition(string Name, string Type);
```
Output
```
--Original Popping--
Transition { Name = T2, Type = For }
Transition { Name = T1, Type = For }
Transition { Name = T0, Type = For }
Transition { Name = T1, Type = For }
Transition { Name = T0, Type = For }
----------------------------------
--Serialize, Deserialize Popping--
Transition { Name = T0, Type = For }
Transition { Name = T1, Type = For }
Transition { Name = T0, Type = For }
Transition { Name = T1, Type = For }
Transition { Name = T2, Type = For }
```

**Comment by jaliyaudagedara** [comment]
@jviau,

I am sorry, I think you have got it all wrong.

I am definitely not saying a framework should have customer-specific behaviors.

The main issue is **When passing a Stack variable between Orchestrators, between executions, the order of items in the Stack is not preserved**. Do you think it's a custom-specific requirement? Forget about serialization (that's anyway all internals, I just explained the root cause), the whole purpose of anyone using a `Stack` is its LIFO behavior. So if that behavior is being broken by Durable Functions, don't you think it's an issue?

Could you please clarify?

**Comment by jviau** [comment]
> So if that behavior is being broken by Durable Functions, don't you think it's an issue?

As per your own comment, the behavior issue is with `Newtonsoft.Json`. It is not broken by durable functions; it is broken without durable in the picture at all. Durable performs serialization between all orchestrations and activities. This is by design as communication between them always goes through a queue/persistence layer, so serialization is required. Since serialization is a central part for durable, it is expected that you ensure your types serialize as you require. Your customization of `IMessageSerializerSettingsFactory` is not a workaround, this is the correct way to address this.

> ideally shouldn't this be supported by default in durable extensions?

No - we will only include default `Newtonsoft.Json` serialization behavior, if Newtonsoft does not correctly serialize `Stack` by default, then that is an issue to bring up with Newtonsoft, not durable functions. We will not perform customization like this because serialization logic is an implementation detail that will differ between customers. We, as a framework, do not have insight into what your specific requirements are and there is no way for us to satisfy all customers. Logic that one customer wants may cause issues for another. Instead, we offer an extension point - `IMessageSerializerSettingsFactory` - to give you the opportunity to introduce your custom serialization logic.

**Comment by jaliyaudagedara** [comment]
> It is not broken by durable functions; it is broken without durable in the picture at all

Correct, I agree.

I am sorry, I don't understand, why you keep thinking it's a specific customer requirement. It's like you saying when using a type of `X` and if it's serialized/deserialized as `Y`, and if someone is expecting it to be `X`, it's a customer-specific requirement. 

The issue is with `Newtonsoft.Json`, I completely agree. But from my own view as a consumer of Durable Functions, the maintainers should not say, It's some dependency issue, go ask them. Because I am using Durable Functions, and it's your choice to use whatever the dependencies. 

I'd expect Durable Functions as a whole to work as expected. And right now, yes, we can use `IMessageSerializerSettingsFactory `.

Anyway, there are already a couple of issues created in `Newtonsoft.Json` related to the `Stack` issue.

Not sure there is a point of going back and forth on the same argument.

**Comment by lilyjma** [comment]
@jaliyaudagedara - Thanks for the detailed issue and the suggestion. I'm the new PM on the team (Jeff isn't on the team anymore unfortunately). Based on the discussion, I think we can agree that this is bit of a gray area. Because we can't anticipate all possible scenarios customers have to make the right call, we left that at the liberty of the customer. But I also understand that as a customer, there are certain expectations/assumptions made regarding behavior, especially when things are spelled out explicitly. I think we can update our documentation [Data persistence and serialization in Durable Functions - Azure | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp-inproc#types-of-data-that-is-serialized-and-persisted) to be more explicit about the impact of serialization on order.

**Comment by jaliyaudagedara** [comment]
@lilyjma,

Thanks for the message. Welcome :) 

Yeah, I later noticed Jeff had moved out.

I can definitely understand and I do completely agree, a framework cannot (and should not) have customer-specific logic. 

But where I am coming from is: 
* If someone is using a `Stack<T>`, it's because of its nature which is `LIFO` and that is its primary functionality/responsibility. 
* And due to this known issue in `Newtonsoft.Json` that behavior is being broken when serializing/deserializing. 
* And .NET In-Process Durable Functions uses `Newtonsoft.Json`. 
* So when someone is using `Stack<T>` with Durable Functions, it isn't working as expected. 

I am sorry, I don't think it's a customer-specific requirement. that's globally expected behavior, I'd say `Stack<T>` should work as `Stack<T>` after all the internals within Durable Functions.

Saying that Durable Functions offer extensibility to customize the serialization behavior. 

If the issue with `Newtonsoft.Json` isn't addressed, then basically `Stack<T>` is pretty much useless within Durable Functions. It would be great if we could update the documentation, so that someone else who is going to be using `Stack<T>` with durable functions doesn't have to scratch their head when it's not working as a `Stack<T>`.
