### ISSUE TITLE
Timeout exception + output is null v.1.2.2-beta3

### ISSUE THREAD

**Issue by norage** [Azure/azure-functions-durable-extension#256]
I was experimenting with durable functions. It worked great for several days until it became very slow for some reason. 

Here's what happened:
I created a durable function (template) and added some new functionality and such, very basic. When the `await starter.StartNewAsync("Function1", null);` hits, it'll give two possible outcomes. Either it's takes too long for it to run/load or whatever and returns timeout exception, OR it'll run everything fine but the output value is null (but it should return `Saying hello to Tokyo` `Saying hello to Seattle` `Saying hello to London` . Usually it's the former.

Here's the log from command window: https://pastebin.com/Z1y9W9YF

What's worth mentioning is that I don't really recall if this problem started to occur after or before I cleaned the the entries in `DurableFunctionsHubHistory` (Cloud Explorer -> Storage Account -> (Development) -> Tables)

What I've tested so far:
- Reinstalled `WebJobs.Extentions.DurableTask` (also tested different versions)
- Reinstalled `Azure Functions and Web Jobs Tools` (Also tested the previous version)

Also, there seems to be no trouble when I test it on the cloud (not locally).

**Comment by cgillum** [comment]
The Azure Storage emulator can be painfully slow in some situations, and we were pretty aggressive about timeouts in this version of the extension.

Can you try adding the latest version of the DurableTask.AzureStorage nuget package to your project and see if just doing that solves the issue? We've made some fundamental performance and reliability improvements in the newer versions that will probably help.

**Comment by norage** [comment]
Adding `DurableTask.AzureStorage` did sadly not solve the problem, I've also tried the previous versions :(

**Comment by cgillum** [comment]
Can you share your orchestrator function code?

**Comment by norage** [comment]
Of course.
https://pastebin.com/zEzSSEDp. So this code worked fine JUST until the day before yesterday evening.
Also, as I mentioned before, the durable function template gives the same result as my code.

**Comment by cgillum** [comment]
Thanks for sharing the code - everything there looks perfectly fine. This is indeed very strange. We have a new release available with many fixes ([more info here](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.3.0-rc)) but I'm not sure if that will be helpful given how fundamental your example is.

By any chance is there another function app or process which could be reading messages from the same set of queues?  For example, is it possible you have two durable function apps using the same storage account? This can cause similar problems because they can steal messages from each other - resulting in unpredictable behavior.

Another thing we can try - have you tried running this in Azure? If you run it in Azure and tell me the region, approximate timeframe, and instance ID, then I can look into our internal telemetry and get a clearer picture of what is happening under the covers.

**Comment by cgillum** [comment]
Glad to hear your issue was resolved in the upgraded package! I'll close this issue since that problem is resolved. We can continue to discuss, however.

When you say "re-executes" could this be the replay behavior of orchestrator functions you're seeing? This may be expected. Take a look at the documentation here and let me know if that explains it: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-checkpointing-and-replay. This document might also be helpful: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-diagnostics#logging
