### ISSUE TITLE
NullReferenceException in v1.3.0-rc when querying an instance which doesn't exist

### ISSUE THREAD

**Issue by jeffputz** [Azure/azure-functions-durable-extension#261]
Since updating today to v1.3RC, we're getting null ref errors similar to this:

```
System.Exception: [demo]  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.DurableOrchestrationClient.<GetDurableOrchestrationStatusAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.DurableOrchestrationClient.<GetStatusAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AMS.Functions.GroupUpdateCalcDispatcher.<Run>d__0.MoveNext()
   --- End of inner exception stack trace ---
```

The signature of these functions looks like this:

```
[FunctionName("GroupUpdateCalcDispatcher")]
public static async Task Run([QueueTrigger(QueueNames.GroupCalculation)]string queueMessage, [OrchestrationClient]DurableOrchestrationClient starter, TraceWriter log)
```

If this is caused by the breaking changes, it's not obvious to me. Looking at the source, I'm assuming that it isn't getting the orchestration state, though it's a little black box for me to understand why. It's obviously triggering on the queue, because otherwise it wouldn't run at all.

**Comment by SimonLuckenuik** [comment]
I have the exact same issue, happens whenever the provided _instanceId_ doesn't exists: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.DurableOrchestrationClient.<GetDurableOrchestrationStatusAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.DurableOrchestrationClient.<GetStatusAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by cgillum** [comment]
Thanks for letting me know about this. **Is this impacting new function apps or existing ones?**

One of the changes we made in RC was to introduce an **Instances** table for handling all status queries. It was called out in this item in the release notes:

> * Create separate "Instances" table for storing orchestration status (#183) **[Breaking Change]**

Status queries previously went to the **History** table, which was slow and inefficient. The new model has status queries go to the new **Instances** table. This model gives us more of a CQRS architecture for managing state and enables us to make some big scalability improvements in the future.

This is a breaking change because upgraded function apps won't have any data in the **Instances** table. Status queries therefore won't have any data to fetch. We expected this issue, which is why we advised that this update only be used for new function apps.

**Can you please confirm whether this could be an upgrade issue?**

**Comment by jeffputz** [comment]
It doesn't seem reasonable to expect a new release with bug fixes to not be applied to existing functions (which were the test bed to find the bugs you fixed, by the way). Yes, this is an upgrade situation.

What's the resolution in the plumbing to make it work? It seems like there are two things broken here:
* A null ref can be passed into a function, unhandled.
* The state infrastructure can only be created once, ever, when it's new. That strikes me as fragile. Why would you not create new rows in the table if they're not there when they're scheduled to run?

**Comment by SimonLuckenuik** [comment]
I did clear all my tables and blob containers prior upgrading. This was to create a brand new orchestration execution.

**Comment by cgillum** [comment]
@jeffputz I apologize for the bad experience, but we put the preview label on this feature specifically because we need the flexibility to make occasional breaking changes. The warnings and versioning guidance are there to help ensure a safe transition from one version to another.

That said, if new instances aren't working either, then there's probably something broken in a way that is not expected. I'll investigate further and see if I can come up with a workaround and/or a fix to unblock both of you if you need help getting unblocked. Any additional information that can be provided would be helpful.

**Comment by cgillum** [comment]
I found the regression. There was a behavior change caused by this PR in **DurableTask.AzureStorage**: https://github.com/Azure/durabletask/pull/145. Basically, the return value when fetching instances that don't exist changed and resulted in the `NullReferenceException` in our extension.

I'll work on a fix and post it as a **v1.3.1-rc** version of the **Microsoft.Azure.WebJobs.Extensions.DurableTask** package. I'll also add a test to cover this scenario since it was clearly a miss on our part.

**Comment by jeffputz** [comment]
@cgillum Awesome, thanks for jumping all over that. What kind of time frame do you expect for the release? I appreciate the transparency.

**Comment by cgillum** [comment]
ETA is less than an hour. I have a fix tested and working locally and just need to run it through our CI and publish it to nuget. I'll post back here once it's available.

**Comment by SimonLuckenuik** [comment]
Working for us, thanks Chris for the quick turnaround time!
