### ISSUE TITLE
Output from prior instance leaked into new orchestration instance

### ISSUE THREAD

**Issue by gotters** [Azure/azure-functions-durable-extension#2640]
### Description
Running an orchestration with the same instance Id as a previously failed orchestration (sometimes) persists the original exception in the orchestration output, even though no failures/exceptions occurred on the new orchestration run

### Expected behavior
Every initialization of an orchestration should have a clean history with no messages/status/exceptions included from a prior orchestration , even if the orchestration is initialized with the same instance id as a prior one.

### Actual behavior
A prior exception is showing up in the output along with the completed/success status of the newest orchestration instance. (unable to reproduce locally but occurring in deployed environments)

### Relevant source code snippets
```csharp
    await client.StartNewAsync($"O_{nameof(DeploymentOrchestrator.ProcessDeployment)}", org.Id.ToString(), dParams);
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.7.1
- **Azure Functions extension version (1.0 or 2.0)**: 1.1.0
- **c#**:

**Comment by davidmrdavid** [comment]
Hi @gotters: Are you able to reproduce this in the latest DF Extension? I noticed you're still using version 2.7.1

**Comment by gotters** [comment]
Thanks @davidmrdavid , the challenge is that I can't reproduce locally in environment and not sure I can just go and deploy a higher version. Need to discuss with our team.
Is there anything I could be doing wrong in terms of implementation that could cause this or something I can do to prevent it with regards to initializing new orchestrations?

**Comment by gotters** [comment]
I noticed something further here...this typically seems to happen when there is an exception on the sub-orchestration called by 
context.CallSubOrchestratorAsync
If an exception is thrown there, which bubbles up into the main orchestrator and is delivered on the output when getting status.
On a subsequent run where there is NO exception, the sub-orchestration - even without an exception - will display the previou exception on the main orchestrator output.

Does this provide any further insight into the issue @davidmrdavid

**Comment by sebastianburckhardt** [comment]
I believe this is functioning as designed, though perhaps unexpected.

The problem is that you are using the same instanceId for the suborchestrator as in the previous execution.

One way to fix this is to not specify the instance id explicitly, but have it be determined by the system:

```
 string suborchestratorId = context.CallSubOrchestratorAsync(functionName, input);
```

If you prefer to construct your own instance ids (say, you want to be able to more easily query them), you can append a deterministically constructed suffix:
```
var monitorInstanceId = $"{context.InstanceId}_Refresh_{context.NewGuid()}";
```

(*note*: don't use `Guid.NewGuid` since it is not deterministic)

**Comment by gotters** [comment]
Thanks for the feedback. I figured this would be the issue, but is this really intended - surely when invoking a sub-orchestrator, given that all other properties are cleared, despite the same instance id, why would the output not also be cleared?

**Comment by sebastianburckhardt** [comment]
I am not sure what you mean by "properties being cleared". Do you mean properties of the parent orchestration? I don't think they are really cleared as much as just being overwritten by the new orchestration that starts. 

The situation is different for suborchestration instance ids because if there is already a completed orchestration with that same instance id, it assumes you want to use the result of the previous run. This is designed to avoid duplicate executions in situations where orchestration start messages get duplicated by the queues.
