### ISSUE TITLE
APIs to enumerate all orchestrations

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#316]
Hi @cgillum , 

As we talked, customer needs on the fly orchestrator status as simple as possible. 

We can develop it now since we've got DurableFunctionsHubInstances, we can implement it as a method of  Orchestrator client or REST API.  I'd like to contribute this feature since my customer wants it.

**Comment by k-miyake** [comment]
If we can get whether running status exists, Durable Functions's DevOps control will be simplified. For example, a situation of decide whether to start swap slots.

**Comment by cgillum** [comment]
Excellent, I would love to receive help with this. The work will need to be done in multiple parts, one part in the Durable Task Framework and one part in the Durable Functions extension. Here is my design suggestion:

### DurableTask.AzureStorage changes:
Lets update [ITrackingStore](https://github.com/Azure/durabletask/blob/9b9aa525ab87616ae97c2f0d43458241fb1ca318/src/DurableTask.AzureStorage/Tracking/ITrackingStore.cs#L63) with a new `GetStateAsync` overload, like this:

```csharp
Task<IList<OrchestrationState>> GetStateAsync();
```

This interface is implemented by two concrete classes, `AzureTableTrackingStore` and `InstanceStoreBackedTrackingStore`. You only need to add logic for `AzureTableTrackingStore`. The other classes implementation can throw `NotImplementedException`. As an optimization, maybe we can add some filtering parameters, but it's probably not required in the first version.

This new `GetStateAsync` overload is different from the others because it will query all orchestration instances in the task hub, not just one instance. It will need to scan the **Instances** table using the Azure Table Storage API to return all rows and convert each row into an `OrchestrationState` object. You can use the existing [GetStateAsync](https://github.com/Azure/durabletask/blob/9b9aa525ab87616ae97c2f0d43458241fb1ca318/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L255) implementation as a reference (maybe both methods can use the same common code).

Next, we'll need to update the [AzureStorageOrchestrationService](https://github.com/Azure/durabletask/blob/master/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs) class with a new public method, like `Task<IList<OrchestrationState>> GetStateAsync()`. This will be called by the Durable Functions extension to get the list of instances. This is not the best design, because it is specific to Azure Storage and cannot be used by other providers (like **DurableTask.ServiceBus**, but we can fix that later. Internally this new public method will call your new `GetStateAsync` method.

Let's make sure to create tests for this new logic as well in the **DurableTask.AzureStorage.Tests** project.

### Microsoft.Azure.WebJobs.Extensions.DurableTask changes:
*TODO: I will add more information about how to create the new REST API here later.*

Let me know if you have any questions or get stuck. @gled4er can also help since he is familiar with how to change this code.

**Comment by TsuyoshiUshio** [comment]
Hi @cgillum 
Thank you for your suggestion! I'll start to open a pull request and implement that. :)

**Comment by TsuyoshiUshio** [comment]
Hi @cgillum 
One question. At the DurableTask repo, which branch should I folk from? There is no dev branch and I can see a lot of branches.

**Comment by cgillum** [comment]
Ah, that's a very good question. The Durable Task Framework repo is not as well organized. I have just now created a branch named [**azure-storage**](https://github.com/Azure/durabletask/tree/azure-storage). Please create your fork from there.

**Comment by TsuyoshiUshio** [comment]
@cgillum  Thanks! :)

**Comment by gled4er** [comment]
Hello,

I will be happy to help with this feature.

Tsuyoshi let me know which part I can take.

Thank you!

Kanio

Sent from my Windows 10 phone

________________________________

**Comment by gled4er** [comment]
Thank you, Kanio.

Since I'm new to Durable Task, I'm not sure how to divide the parts or simple go with mob with sharing commit.  Let's discuss it in this afternoon in person.

Tsuyoshi

From: Kanio Dimitrov
Sent: Sunday, May 20, 2018 12:10 PM
To: Azure/azure-functions-durable-extension <reply@reply.github.com>; Azure/azure-functions-durable-extension <azure-functions-durable-extension@noreply.github.com>; Tsuyoshi Ushio <tsushi@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-functions-durable-extension] On the fly Orchestrator status (#316)

Hello,

I will be happy to help with this feature.

Tsuyoshi let me know which part I can take.

Thank you!

Kanio

Sent from my Windows 10 phone

________________________________

**Comment by gled4er** [comment]
Great!

Thank you!

Sent from my Windows 10 phone

________________________________
From: Tsuyoshi Ushio
Sent: Monday, May 21, 2018 9:31:51 AM
To: Kanio Dimitrov; Azure/azure-functions-durable-extension; Azure/azure-functions-durable-extension
Cc: Mention
Subject: RE: [Azure/azure-functions-durable-extension] On the fly Orchestrator status (#316)

Thank you, Kanio.

Since I’m new to Durable Task, I’m not sure how to divide the parts or simple go with mob with sharing commit.  Let’s discuss it in this afternoon in person.

Tsuyoshi

From: Kanio Dimitrov
Sent: Sunday, May 20, 2018 12:10 PM
To: Azure/azure-functions-durable-extension <reply@reply.github.com>; Azure/azure-functions-durable-extension <azure-functions-durable-extension@noreply.github.com>; Tsuyoshi Ushio <tsushi@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-functions-durable-extension] On the fly Orchestrator status (#316)

Hello,

I will be happy to help with this feature.

Tsuyoshi let me know which part I can take.

Thank you!

Kanio

Sent from my Windows 10 phone

________________________________

**Comment by cgillum** [comment]
PRs are merged and I've signed off on the documentation.
