### ISSUE TITLE
 I want to set "EventGridTopicEndpoint" in application settings

### ISSUE THREAD

**Issue by yuka1984** [Azure/azure-functions-durable-extension#331]
In PreCompile functions, I think that it is common for host.json to set before the build and publish with msbuild.
However, with this method, when using different EventGridTopic for staging and production, it is necessary to build a separate build for each environment.

If the value set in "EventGridTopicEndpoint" is found in AppSettingsKey, use Value of AppSettings, and if not found, use the value of "EventGridTopicEndpoint" as URL. I'd like you to make the change.

**Comment by yuka-abn** [comment]
I would like to create PR if this change is accepted.

**Comment by cgillum** [comment]
Did you want to create the PR or did you want us to create the PR? You mentioned previously that you would like us to make the change. But if you would like to create the PR, I would be happy to review and merge it.

To support this, we should update **LifeCycleNotificationHelper** to use the `NameResolver`. You already implemented this for `EventGridKeySettingName` [here](https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/LifeCycleNotificationHelper.cs#L27-L30). Now we just need to also use `NameResolver` for `EventGridTopicEndpoint`. However, I think you will want to use [NameResolver.TryResolveWholeString](https://github.com/Azure/azure-webjobs-sdk/blob/663a508e8a851629c26a51e7de3af36629dfd120/src/Microsoft.Azure.WebJobs.Host/NameResolverExtensions.cs#L22) extension method instead of `NameResolver.Resolve`.

With my suggestion, you could set `EventGridTopicEndpoint` is set as a URL just like today. To use an app setting, you use the `%` syntax. For example `%MyEventGridTopicAppSetting%`.

**Comment by cgillum** [comment]
The PR has been merged. We will include this in the next release (v1.5.0), which will come in the next week or two.
