### ISSUE TITLE
Too many orchestrations starting?

### ISSUE THREAD

**Issue by TheFairey** [Azure/azure-functions-durable-extension#364]
Hi,

I have a Q based Durable Function and in my host.json while trying to understand throughput and parallelism I experimented with setting:

```
  "durableTask": {
    "HubName": "xxxxx",
    "partitionCount": 2,
    "maxConcurrentActivityFunctions": 2,
    "maxConcurrentOrchestratorFunctions": 2
  },
  "queues": {
    "maxPollingInterval": 2000,
    "visibilityTimeout": "00:00:30",
    "batchSize": 4,
    "newBatchThreshold": 2
  }
```

From the page on Performance and Scale my understanding is that no matter how many instances get spun up as there are only 2 partitions then only 2 instances can access the control Qs? 

If there is a limit on concurrent Orchestrator functions of 2 there would only ever be 4 running and each one would grab 4 items from the Q and then another 4 when their running jobs drops to 1; so 5 max active at any point in time.

In the Instances table I'd expect never see more than approx 20 running instances and the rest would be pending. 

TBH I would have expected them to still be on the original Q but seems they get pulled of the Q and then queued up internally and set to Pending? 

What I actually see is a slower growth in "Running" entries than when I left things at the defaults but it slowly grows until there are well over 100 Running entries in the Instances table.

Am I missing something here as I was hoping I could use these controls to somehow limit the number of concurrent messages being processed to some kind of min/max window?

Cheers

**Comment by cgillum** [comment]
A few things I should mention:

* The `queues` section in host.json does not apply to Durable Functions.
* The `maxConcurrentActivityFunctions` and `maxConcurrentOrchestratorFunctions` sections do not impact queue behavior. They only impact how many functions will concurrently execute on a single VM.
* As many as 64 messages from the control queues can be internally buffered on each VM. I don't believe this is currently configurable, but we could add this as a new feature.

Does this information help answer your questions?

**Comment by cgillum** [comment]
Sorry for the delay. Yes, we try to read 32 messages at a time and use a backoff polling strategy if the queue(s) become empty.

In the default configuration, assuming that you have two single-core VMs, each one could concurrently execute 10 orchestrations on each VM. We buffer up to 64 control messages in memory, so you would end up with as many as **128** buffered messages across the two VMs.

**Comment by TheFairey** [comment]
Ahh so each VM (not orchestration) buffers the messages then gives them to the orchestrations on that VM. 

One follow up, whats the max polling delay if the Q has been empty for a while, i.e. 24hrs

**Comment by cgillum** [comment]
Correct. The max polling delay is 10 seconds.

**Comment by TheFairey** [comment]
Thanks for clarifying

**Comment by andylholloway** [comment]
Hi,
Is there a way to monitor whether a message has been dequeued from the work-item queue multiple times?

We have an Orchestration that receives large payloads of data and batches the data into smaller sub-batches e.g. 
The Orchestration receives a batch of, lets say, 5000 entities which it batches into 50 sub-batches of 100 entities. Then the Orchestration processes each batch by fanning-out all 100 entities to Activity Functions, which have the sole responsibility of sending a single entity to an API and await the response. 

We are noticing that if the API is slow to respond some of the entities are being resent, which causes the API to return a 409 because it has already processed the entity in a previous request. Looking at the App Insights logs I don't see anything that suggests the Orchestration is calling an Activity function with the same entity multiple times, but I can see that the Activity Function logging is appearing multiple times for the same entity, which makes me think it is because the work-item message is being dequeued multiple times.

Is it likely that messages are being pulled from the work-item queue because the Activity Functions are not able to complete quickly enough? 
@cgillum I see from one of your previous posts that the `queues` section in host.json does not apply to Durable Functions, does that mean there is no way to change the `polling frequency` or the `message visibility timeout` of the work-item queue?
