### ISSUE TITLE
Unable to bind DurableOrchestrationClient in Pre-compiled Azure Function

### ISSUE THREAD

**Issue by APErebus** [Azure/azure-functions-durable-extension#375]
Hi,

We've just tried implementing Durable Functions in a pre-compiled Azure Function and when running locally or on Azure we get this error:

> Function (trigger-function) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.our-function'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Our function looks like this (with some obfuscation):
```
public static Task Execute(TimerInfo timerInfo, DurableOrchestrationClient starter)
        {
            const string instanceId = "singleton-instance";

            //if the instance doesn't exists, start one
            if (starter.GetStatusAsync(instanceId) == null)
            {
                //this is a single pattern. I tmeans we only ever
                await starter.StartNewAsync(ProcessingFunction.Name, instanceId);

                _logger.Information("Started function with InstanceId: {InstanceId}", instanceId);
            }
        }
```

our function.json looks like this:

```
{
  "disabled": false,
  "scriptFile": "..\\bin\\Us.Functions.dll",
  "entryPoint": "Us.Functions.OurFunction.Execute",
  "bindings": [
    {
      "type": "timerTrigger",
      "name": "timerInfo",
      "direction": "in",
      "schedule": "0 5 * * * *"
    },
    {
      "type": "orchestrationClient",
      "name": "starter",
      "direction": "out"
    }
  ]
}
```

We had originally built the function project before the tooling for VS 2017 existed, so we've been using a web-project that has the actual `function.json` & CS code (using this guide https://blogs.msdn.microsoft.com/appserviceteam/2017/03/16/publishing-a-net-class-library-as-a-function-app/)

This is why we don't have the attributes etc of the newest tooling. We a re a little loathed to migrate right now as there is 20+ functions we need to change over and would like to avoid that in the short term if required. 

I added, via NuGet, DurableTask v1.5.0 and it all compiles correctly, but the function indexer doesn't seem to be able to find the durable task extension and therefore fails to bind.

We are using v 2.2 of the WebJobs SDK, extensions etc.

Is there anything obvious we are doing wrong or are we going to have to migrate to the tooling?

**Comment by cgillum** [comment]
I'm not completely sure, but I do know that the way extensions are loaded is different when using the newer attribute model vs. when using the function.json model. I believe the WebJobs SDK tries to load extensions by looking for things like `[OrchestrationClient]`. You don't have that, which is why it's probably not finding it.

One thing to try is to use the [non-precompiled method of adding extensions via the functions CLI](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install#visual-studio-code). Can you try installing it explicitly using this command in the root of your function app?

```bash
func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 1.5.0
```

That will create some new artifacts on the file system, and it's possible that the functions host will see them and load your extension correctly (no guarantees though, since I'm pretty sure this kind of setup has never been tested).

**Comment by APErebus** [comment]
Unfortunately that didn't work :(

We decided to take the hit and migrate the project to a V1 Functions Project in VS. Hopefully that will mean we don't get any issues in the future. 

Thanks for your help.
