### ISSUE TITLE
Is it possible get InvocationId of an Activity Function?

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#395]
We want be able to obtain the `InvocationId` of an Activity Function from the Orchestration Context. I know this is possible via the `context` parameter that is available inside a function invocation, but we need to be able to access it outside the function. We specifically need the`InvocationId` so we can link it to the storage logs that are created in table storage. Is something like this possible? 

My second question would be, is it possible to obtain the logs generated by the TraceWriter (C#) or context.log (Javascript) for a particular Activity Function, which would then not require use to retrieve them in Table Storage?

```
[FunctionName("TestRunner")]
public static async Task<List<Dictionary<string,string>>> TestRunnerFunc(
   [OrchestrationTrigger] DurableOrchestrationContext context,
   Microsoft.Azure.WebJobs.ExecutionContext ctx,
   TraceWriter log)
{
	object data = context.GetInput<List<Dictionary<string, string>>>();
	try
	{
                //get the logs of the activity function below
		List<Dictionary<string, string>> outData =
					await context.CallActivityAsync<List<Dictionary<string, string>>>("UserFunction", null);
		
		return outData;
	}
	catch (Exception ex)
	{
		throw;
	}
}
```

**Comment by cgillum** [comment]
Regarding invocation ID, more information about retrieving that can be found here: https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function (though you probably already know this).

If you want to use/see the invocation ID of an activity function outside of the function, then you can simply return it as a return value from your activity function. For example:

```csharp
[FunctionName("MyActivityFunc")]
public static async Task<string> MyActivityFunc(
    [ActivityTrigger] DurableActivityContext activityContext,
    ExecutionContext executionContext)
{
    return executionContext.InvocationId;
}
```

Regarding your second question, I don't know much about the logs which are stored in table storage, other than that those logs are being deprecated in favor of logs stored in [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring). However, in that case you would need to use `ILogger` instead of `TraceWriter` (which is also being deprecated).

Adding @brettsam who can confirm (or deny) what I'm saying, and may have more to add on this topic.

**Comment by gorillapower** [comment]
@cgillum Thanks for the response. Yes this confirms my thoughts that it wouldnt be possible to obtain the InvocationId outside of the Activity Function without actually returning it from within the function itself. 

I would like to use Application Insights and have already looked into using the Application Inisghts REST Api, but the data can be delayed by up to 5mins and also has rate limiting which may restrict us going forward.

**Comment by cgillum** [comment]
I see. Yes, if the log delay is a problem then there may not be much we can do, other than to suggest implementing your own log store. I realize this isn't ideal, but it will give you the most control.
