### ISSUE TITLE
Phantom activity function triggered 5 minutes after orchestration function completed successfully

### ISSUE THREAD

**Issue by AhmedAAshour** [Azure/azure-functions-durable-extension#398]
I am using a durable orchestration function to do some work. my logs showed an exception was thrown in one of the activity functions but not in the orchestration function even though it should be logged in both. When I checked our application insights for the instance using the following query:
> traces
| where customDimensions.Category == "Host.Triggers.DurableTask"
| extend functionName = customDimensions["prop__functionName"]
| extend instanceId = customDimensions["prop__instanceId"]
| extend state = customDimensions["prop__state"]
| extend isReplay = tobool(tolower(customDimensions["prop__isReplay"]))
| extend sequenceNumber = tolong(customDimensions["prop__sequenceNumber"]) 
| where isReplay != true
| where instanceId == targetInstanceId
| sort by timestamp asc, sequenceNumber asc
| project timestamp, functionName, state, instanceId, sequenceNumber, appName = cloud_RoleName

I noticed that a phantom instance of one of the activity functions started executing again nearly 5 minutes after the orchestration function had already completed successfully.
Can this issue be caused by my code? Is it the expected behavior of the Durable Functions?

**Instance ID: ffd147d376a6477e85973fe51af7a727
Region: Central US
Approximate timestamp: 2018-08-03T21:52:36.047**
I hope this information helps in debugging the issue.

**Comment by cgillum** [comment]
Thanks for this information - it makes investigations significantly easier :). I took a look at our internal storage logs and can confirm what you're seeing. This is what I'm observing:

* At **2018-08-03 21:53:09** your activity function finished executing for the first time. However, when we tried to delete the queue message associated with this execution, Azure Storage returned a **404 Not Found**. 
* At **2018-08-03 21:58:09** the message which we failed to delete became visible on the queue again, which tells us that it wasn't actually gone when we tried to delete it 5 minutes earlier. This message caused us to execute your activity function a second time. This duplicate execution failed, I assume, because this particular activity function is not idempotent.

Unfortunately we don't have a good understanding of how this situation could have happened. I noticed, however, that you're running an older version of the Durable Functions extension (**1.4.1.0**). If you upgrade to the latest version (currently 1.5.0) we have some additional logging in place that may help us investigate further (or may fix it - I haven't seen cases like this on the latest version).

**Comment by AhmedAAshour** [comment]
Thanks a lot for your prompt investigation and response, Chris. I really appreciate it.
I assume there is nothing we can do on our side to make sure this problem doesn't resurface again, except upgrading to the latest version of the extension. Right?
I'll keep you posted in case we face the issue again.

**Comment by cgillum** [comment]
Correct, this would not have been caused by anything your application is doing. I do suggest upgrading to the latest version though. Do let me know if you continue to see this behavior in newer versions of the extension.
