### ISSUE TITLE
POCO Request Objects/Classes getting created twice in Orchestrator after upgrade to 1.6.0

### ISSUE THREAD

**Issue by asalvo** [Azure/azure-functions-durable-extension#424]
Azure Functions SDK: 1.0.19
Azure Functions Core Tools (2.0.1-beta.36)
Function Runtime Version: 2.0.12050.0
Microsoft.Azure.WebJobs.Extensions.DurableTask: 1.6.0

After upgrading to the above versions, I am observing some weird behavior in a function that previously worked. My Orchestrator creates a new POCO request object and then passes this to an Activity using CallActivityAsync. What I started observing is that my POCO request object is getting created twice, and the second version is what is getting passed to CallActivityAsync. 

```
public static async Task RunDbBackup([OrchestrationTrigger] DurableOrchestrationContextBase ctx, TraceWriter log)
{
            Debug.WriteLine($"** {FunctionNames.Backup}. InstanceId: {ctx.InstanceId}, IsReplaying: {ctx.IsReplaying}");
            
            var now = ctx.CurrentUtcDateTime;
            var request = new SqlStartCopyRequest(ctx.CurrentUtcDateTime, "ResourceGroup", "SourceServer", "CopyExportTest", "Web-Dev", "DestServer", "Basic");

            var startResponse = await ctx.CallActivityAsync<SqlStartCopyResponse>(DatabaseBackupActivities.FunctionNames.StartAndMonitor, request);
}
```

```
public SqlStartCopyRequest(DateTime now, string sourceResourceGroup, string sourceServerName, string sourceDatabaseName, string copyResourceGroup, string copyServerName, string copyServiceLevelObjective)
        {
            Debug.WriteLine($"** {nameof(SqlStartCopyRequest)}. SourceDbName: {sourceDatabaseName}, CopyDbName: {CopyDatabaseName}, Now: {now}");

            SourceResourceGroup = sourceResourceGroup;
            SourceServerName = sourceServerName;
            SourceDatabaseName = sourceDatabaseName;
            CopyDatabaseName = $"{sourceDatabaseName}-{now}";
            CopyResourceGroup = copyResourceGroup;
            CopyServerName = copyServerName;
            CopyServiceLevelObjective = copyServiceLevelObjective;
        }
```

```
[FunctionName(FunctionNames.StartAndMonitor)]
        public static async Task<SqlStartCopyResponse> RunStartAndMonitor([ActivityTrigger] SqlStartCopyRequest request, TraceWriter log)
        {
            Debug.WriteLine($"** {FunctionNames.StartAndMonitor}. CopyDbName: {request.CopyDatabaseName}");
            var response = await Context.Instance.Get<ISqlManagementService>().StartCopyAsync(request);
            return response;
        }
```

Here is the output from the Debug output. You can see that SqlStartCopyRequest shows up twice, and the second time, the value passed in for Now is incorrect, and that it's the second instance of SqlStartCopyRequest that gets passed to my activity. 

```
** Db-Orch-Backup. InstanceId: 735e21698432450b912892120f648a41, IsReplaying: False
** SqlStartCopyRequest. SourceDbName: CopyExportTest, CopyDbName: , Now: 9/2/2018 03:35:03
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
** SqlStartCopyRequest. SourceDbName: CopyExportTest, CopyDbName: , Now: 1/1/0001 00:00:00
** Db-Backup-StartAndMonitor. CopyDbName: CopyExportTest-1/1/0001 00:00:00
```

I talked with another developer at another company working on a completely different project, and they are seeing the same thing since upgrading, their "request" objects are getting created twice.

**Comment by cgillum** [comment]
I took a look at this, created my own small repro, and didn't observe anything unusual. Here's my understanding of what's happening:

1. The first "create" is when you create the object directly in your orchestrator code.
2. The second "create" is when the deserializer reinitializes your object from the internal queue message.

Under the hood, when you call an activity function, it serializes your input data and saves it into a queue message. When the activity function reads that queue message, it deserializes it back into the destination type. We use Json.NET as the serializer, and that will call your constructor to initialize the object as part of deserialization. I don't know exactly how it works, but it's probably calling your constructor with default values and then setting your properties directly.

Generally speaking, serializeable POCO objects should not rely on constructors for initialization since a serialization engine won't know how to pass in parameters when recreating your object. In the past, I believe Json.NET would throw an exception if you try to serialize an object that doesn't have a default constructor - but maybe that changed in more recent versions to the current behavior.

In any case, everything seems to be behaving as designed. I would expect that previous releases behave the same way. Let me know if I'm misunderstanding the issue and I'd be happy to look into it further.
