### ISSUE TITLE
[Feature Request] Option to not store activity result in history table

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-durable-extension#425]
Use case: Functions that require download big file from azure blob storage

If I create a function which return that blob, the durable function will store the file in history table which is not desirable.

There must be an option to not store activity result in history table.
When failure occured, the framework will retry the download blob as the result is not stored in history table.

**Comment by gled4er** [comment]
Hello @andrew-vandenbrink,

If the file is big enough (If I remember correctly more than 2MB) it won't be stored in the History Table but it will be saved as a blob. Then only the link to the blob will be stored in the History Table.

Is that behavior good enough for you?

Thank you!

**Comment by andrew-vandenbrink** [comment]
Hi @gled4er , no, because there still cost to upload that big file to blob storage...

**Comment by gled4er** [comment]
Hello @andrew-vandenbrink,

Thank you for the reply!

If we don't store at all the file which is the return value from your activity function, we will not be able to get its value during the replay process. 

Maybe I don't understand completely your use case.

Can you provide more details please?

Thank you!

**Comment by andrew-vandenbrink** [comment]
There are some function that I need to always replaying or the result should not be stored anywhere.
function that return DateTime.Now 
function that return encrypted message
function that return secret, etc

When is this replay happen btw to be sure?

**Comment by gled4er** [comment]
Hello @andrew-vandenbrink,

Than you for the clarification.

Maybe @cgillum  can correct me here but I think currently is not possible to avoid persisting the output from the activity functions. 

One idea is to organize your activity functions in a way that the sensitive information is only used inside them and not outputted outside. This will introduce coupling between few functions but it can work as a temp workaround. 

In the same time, I think it will be great to implement a feature that prevents persisting data outputted from an activity function especially in the cases of PII or passwords as you mentioned. 

This will be also interesting trade-off because the feature will reduce the durability of the system and introduce possible challenging edge cases because we will not use Event Sourcing for all available data.

Thank you!

**Comment by cgillum** [comment]
Right, it's critical to our system that function outputs be stored in the history table (or in blob storage if they are large). There is no way around this, unfortunately. If it is sensitive data, then the best we can do is create a feature which allows you to have your data encrypted using a key you provide (note that all Azure Storage content is already encrypted at rest - so this would be a double-encryption so that even people with the storage account credentials cannot read it).

Otherwise, as was suggested, you will need to refactor your functions to not pass sensitive information as parameters or return values.
