### ISSUE TITLE
[Feature] Ability to set Custom Status via DurableActivityContext

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#443]
Some users have expressed desire to be able to set the Custom Status property on an orchestration from activity functions. Filing.

**Comment by cgillum** [comment]
What is the source of this desire? Why is setting it in the orchestrator not good enough? Said another way, what is it users want to accomplish that cannot be done in the current model?

**Comment by brandonh-msft** [comment]
> In general, I’m having a really hard time understand how to monitor the execution of these orchestrations, especially since we call other orchestrations which call other activities.  It’s not difficult to track just the top level orchestration using App Insights or Storage Explorer, but I haven’t figured out how to trace execution through all of the sub-functions.  Is that possible?  If A calls B which calls C, to have a list of all messages from A, B, and C? 

I suggested to them using CustomStatus and/or `TelemetryClient`. Response:

> We looked into using CustomStatus, but the API isn’t available from activities where most of the work is done, only at the orchestration level.  So it appears to be more of a high-level status rather than a logging API.
> 
> And yes, we’re going to be adding logging, but I was looking to see what tools came out of the box to track an orchestration workflow.

hence this request. hope that helps.

**Comment by cgillum** [comment]
I understand now. I think the real ask is how to do end-to-end tracing. My suggestion is to use `ILogger` and the orchestration instance ID to correlate logs.

Updating the custom status from activity functions won't really help with end-to-end tracing since it's intended for high-level status and not tracing.

**Comment by sehcheese** [comment]
@cgillum With a longer-running activity function, it would be helpful to be able to report a more granular status for the GetStatus API to show to the user. Not for error tracing, but for information on the progress of the task. Does that make sense?

**Comment by cgillum** [comment]
I agree this would be generally useful. I'll reopen this to track.

If I were to design such an API, it would look something like `DurableActivityContext.SetCustomStatusAsync(object status)`. Internally it would call a yet-to-be created API in the Durable Task Framework which directly updates the orchestration's custom status in the tracking store.

The downside of something like this is that you now could have multiple clients racing with each other to update the custom status (today no such race exists). It would therefore need to be used with caution.

**Comment by petrs-x** [comment]
@cgillum absolutely useful function. However as you mentioned link it directly to CustomStatus may lead to racing conditions. 

As we are running multiple I/O operations in parallel, i would suggest to have it implemented in different way so we can consolidate those outputs in orchestrator and then calculate the CustomStatus.

**Comment by srikanthnd** [comment]
I recently came across a situation where this feature will be very helpful and indeed having to set custom status from activity function makes a lot of sense.

Also, currently, every time the custom status is set, it over writes the previous value.  I would prefer to have an append functionality to the custom status as well instead of overwriting the previous value OR is there a specific reason why the custom status was designed to have a single value?

**Comment by cgillum** [comment]
> Also, currently, every time the custom status is set, it over writes the previous value. I would prefer to have an append functionality to the custom status as well instead of overwriting the previous value OR is there a specific reason why the custom status was designed to have a single value?

Custom status can be any object type that fits within the 16 KB limit. If your payload size is limited, you can simply use an ordered list as your custom status object.

If you need larger payloads or if you need activities to be able to save status, then another workaround would be to store these logs in a [Durable Entity](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities). That would also solve the race condition problem since entities are single-threaded, and may actually be a more appropriate long-term solution for this scenario.

**Comment by KavithaKommuri** [comment]
@cgillum - We have a similar situation as others where setting the custom status on activity function as our activity function is a long-running process and it would be really helpful for the users to know the progress of that process. Is there any way to achieve this?

**Comment by NickSevens** [comment]
@cgillum would there be a way in that scenario to retrieve and update the Entity from within an Activity?

**Comment by cgillum** [comment]
@NickSevens and @KavithaKommuri yes, definitely. Here is one potential solution that I think should work:

1. Use a durable entity to store custom status - there would be one entity per orchestration. The ID of the entity can be derived from the orchestration instance ID for simplicity.
2. use the `[DurableClient]` binding and [SignalEntityAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableentityclient.signalentityasync?view=azure-dotnet) within an activity function to send "update" operations to the appropriate status entity.
3. If the activity needs to read the status, it can similarly use the [ReadEntityStateAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableentityclient.readentitystateasync?view=azure-dotnet) method via the `[DurableClient]` binding.
4. Use the orchestration's custom status field to publish the name/location of the status entity so that external clients can also find it and query it.

**Comment by cgillum** [comment]
The "long running task progress update" scenario can also be implemented simply using external events from the activity function to the orchestrator function.

Here is a C# orchestration that kicks off a long-running task and receives periodic status updates:

```csharp
[FunctionName(nameof(Orchestration))]
public static async Task Orchestration(
    [OrchestrationTrigger] IDurableOrchestrationContext context)
{
    Task longRunningTask = context.CallActivityAsync("LongRunning", null);
    while (true)
    {
        Task<string> statusUpdateTask = context.WaitForExternalEvent<string>("StatusUpdate");
        Task completedTask = await Task.WhenAny(longRunningTask, statusUpdateTask);
        if (completedTask == longRunningTask)
        {
            // The long-running task has completed - we await it to ensure any failures are correctly surfaced
            await longRunningTask;
            break;
        }
        else
        {
            // We got a status update. Use the payload as the custom status.
            string status = await statusUpdateTask;
            context.SetCustomStatus(status);
        }
    }
}
```

And here is the activity function that periodically sends status updates:

```csharp
[FunctionName(nameof(LongRunning))]
public static async Task LongRunning(
    [ActivityTrigger] IDurableActivityContext context,
    [DurableClient] IDurableClient client)
{
    await DoWork();

    await client.RaiseEventAsync(context.InstanceId, "StatusUpdate", "33% complete...");

    await DoMoreWork();

    await client.RaiseEventAsync(context.InstanceId, "StatusUpdate", "66% complete...");

    await FinishUp();
}
```

This approach is nice because it doesn't have any race conditions, and works with any number of status updates. If you require strong guarantees about status update ordering, you could alternatively include some kind of sequencing information or timestamp in the event payload. The orchestrator function could then only update the custom status if the event it receives is newer than any other event it received.

**Comment by KavithaKommuri** [comment]
Thanks @cgillum . I have tried the suggestion that you mentioned before with durable entity and its working fine. But only thing with that approach is user needs a new URL to see the status.  The above approach seems to be good as orchestrator is dealing with setting the custom status. I will try the above approach also. thanks for looking into it.

**Comment by ChrisSchaller** [comment]
`DuarableEntities` can also be used to simulate a log running status entry. In the case of chained sub-orchestrations the nuances of which status to show when, and from what level could be vastly different depending on your implementation. _Remember that Activities themselves are not supposed to be so long-running that you could show periodic status updates, long running activities should be refactored into sub-orchestrations._

I think instead of supporting this request we instead improve the status query language to support inspecting the status of sub-orchestrations. 

> **Note** that we can easily raise events on the parent instance id as well as the current one.

**Comment by radhewro** [comment]
A custom status API on activity level would be awesome in 2022 too...

**Comment by IDrumsey** [comment]
@cgillum 
> The "long running task progress update" scenario can also be implemented simply using external events from the activity function to the orchestrator function.
> 
> Here is a C# orchestration that kicks off a long-running task and receives periodic status updates:
> 
> ```cs
> [FunctionName(nameof(Orchestration))]
> public static async Task Orchestration(
>     [OrchestrationTrigger] IDurableOrchestrationContext context)
> {
>     Task longRunningTask = context.CallActivityAsync("LongRunning", null);
>     while (true)
>     {
>         Task<string> statusUpdateTask = context.WaitForExternalEvent<string>("StatusUpdate");
>         Task completedTask = await Task.WhenAny(longRunningTask, statusUpdateTask);
>         if (completedTask == longRunningTask)
>         {
>             // The long-running task has completed - we await it to ensure any failures are correctly surfaced
>             await longRunningTask;
>             break;
>         }
>         else
>         {
>             // We got a status update. Use the payload as the custom status.
>             string status = await statusUpdateTask;
>             context.SetCustomStatus(status);
>         }
>     }
> }
> ```
> 
> And here is the activity function that periodically sends status updates:
> 
> ```cs
> [FunctionName(nameof(LongRunning))]
> public static async Task LongRunning(
>     [ActivityTrigger] IDurableActivityContext context,
>     [DurableClient] IDurableClient client)
> {
>     await DoWork();
> 
>     await client.RaiseEventAsync(context.InstanceId, "StatusUpdate", "33% complete...");
> 
>     await DoMoreWork();
> 
>     await client.RaiseEventAsync(context.InstanceId, "StatusUpdate", "66% complete...");
> 
>     await FinishUp();
> }
> ```
> 
> This approach is nice because it doesn't have any race conditions, and works with any number of status updates. If you require strong guarantees about status update ordering, you could alternatively include some kind of sequencing information or timestamp in the event payload. The orchestrator function could then only update the custom status if the event it receives is newer than any other event it received.

Is there a Python equivalent for this? I've been messing with it, but can't seem to get it to work.

Without raising any events, it works as you would expect -

*orchestrator function*
```py
def orchestrator_function(context: df.DurableOrchestrationContext):

    contextID = context.instance_id

    actTask = context.call_activity('testActivity', contextID)

    while True:

        statusUpdateTask = context.wait_for_external_event("statusUpdate")

        completedTask = yield context.task_any([actTask , statusUpdateTask])

        if completedTask == actTask :
            yield actTask 
            break
        else:
            status = yield statusUpdateTask
    

    return 'done'
```
*activity function*
```py
async def main(instanceID: str, starter: str) -> bool:

    orchestration = df.DurableOrchestrationClient(starter)

    time.sleep(2)

    # await orchestration.raise_event(instanceID, "statusUpdate", 'some state')

    x = 1

    time.sleep(2)

    # await orchestration.raise_event(instanceID, "statusUpdate", 'some other state')

    return True
```

*results*
```
{
    "runtimeStatus": "Completed",
    "input": "{}",
    "customStatus": null,
    "output": "done",
}
```


However, when I uncomment the raising of the events, it catches the first one, but then seems to restart the activity function (I say this because it reruns the first `time.sleep(2)`) and then just keeps catching the first event raised (never catching the second one) until finally it throws an exception.

*orchestrator function*
```py
def orchestrator_function(context: df.DurableOrchestrationContext):

    contextID = context.instance_id

    actTask = context.call_activity('testActivity', contextID)

    while True:

        statusUpdateTask = context.wait_for_external_event("statusUpdate")

        completedTask = yield context.task_any([actTask , statusUpdateTask])

        if completedTask == actTask :
            yield actTask 
            break
        else:
            status = yield statusUpdateTask
    

    return 'done'
```
*activity function*
```py
async def main(instanceID: str, starter: str) -> bool:

    orchestration = df.DurableOrchestrationClient(starter)

    time.sleep(2)

    await orchestration.raise_event(instanceID, "statusUpdate", 'some state')

    x = 1

    time.sleep(2)

    await orchestration.raise_event(instanceID, "statusUpdate", 'some other state')

    return True
```

*results*
```
{
    "runtimeStatus": "Failed",
    "input": "{}",
    "customStatus": null,
    "output": "Orchestrator function 'orchestratorFunction' failed: 'AtomicTask' object has no attribute 'append'",
}
```

I'm running this on Python 3.9.13 using Core Tools Version: 3.0.4669. Can you see something I'm not seeing?

**Comment by davidmrdavid** [comment]
Hi @IDrumsey: I just provided an update on the thread you linked (https://github.com/Azure/azure-functions-durable-python/issues/349) regarding the exception you're seeing. Let's continue the discussion there.

**Comment by jjrobert65** [comment]
@cgillum I am struggling to reconcile your C# example with any recent Azure Function example I've found.

With VS Community 2022 I create a new project using the Azure Functions template and choose "Durable Functions Orchestration".

I try to add your LongRunning() activity and it doesn't know about IDurableActivityContext or IDurableClient.

I see documentation for these interfaces but in Microsoft.Azure.**WebJob**s.Extensions.DurableTask

Should I be trying to use those from an Azure Function? I spent a little time trying to do that and could not seem to connect the dots.

Since a few years have gone by, is there a better/different way for the Activity to update the custom status?

**Comment by jjrobert65** [comment]
> the example I provided works for the .NET in-process programming model. However, the VS templates are probably defaulting you to the newer .NET out-of-process programming model, which uses completely new types. Take a look through this migration guide for ideas about how to translate the samples from in-proc to out-of-proc: https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview?source=recommendations#public-api-changes
> 
> I'm going to go ahead and close this issue since we don't currently have plans to support updating custom status natively from activity functions.

@cgillum Thanks, that got me most of the way there. I'm currently unsure how to get the orchestrator InstanceId from the activity in the out-of-process model. You have:

> `[ActivityTrigger] IDurableActivityContext context`

But the migration guide says:

> DurableActivityContext	No equivalent

I tried `[ActivityTrigger]TaskActivityContext context` based on the way most of the names map and it compiles but context is null when the Activity is called.

I can pass the instanceId directly to the Activity and get this working but is there a more correct way?

        Task longRunningTask = context.CallActivityAsync("LongRunning", context.InstanceId);

        ...

        [Function(nameof(LongRunning))]
        public static async Task LongRunning([ActivityTrigger] string orchestrationId,
            [DurableClient]DurableTaskClient client)

**Comment by cgillum** [comment]
@jjrobert65 try adding a `string instanceId` parameter to your activity function, separate from the trigger binding. it should automatically bind to the orchestration instance ID, without you needing to do anything special. Something like this:

```csharp
[Function(nameof(LongRunning))]
public static async Task LongRunning(
    [ActivityTrigger] MyInput someInput,
    [DurableClient] DurableTaskClient client,
    string instanceId /* the current orchestration instance ID */)
{
    // ...
}
```

The Durable Functions extension is designed to automatically populate a string parameter named `instanceId` to the orchestration's instance ID when using the activity trigger. This should work whether you're using the in-process model or the out-of-process model.
