### ISSUE TITLE
Incompatible Microsoft.Extensions.* dependencies for Functions 1.0 projects

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-durable-extension#446]
The current version of the nuget package has an dependency on Microsoft.Extensions.Configuration and Microsoft.Extensions.Configuration.Abstractions (both with version 2.1.1). This dependency causes a problem in functions V1 if you want to use the package Microsoft.Extensions.Configuration.Json

In V1 you want to use Microsoft.Extensions.Configuration.Json version 1.1.2, because this has an dependency on Newtonsoft.Json 9.0.1 (the same as functions V1).

But because version1.6 of this package has an dependency on 2.1.1, you are forced to use the Microsoft.Extensions.Configuration.Json version 2.1.1 as well. But this package has and depency on Newtonsoft.Json version > 11

As a result the functions in V1 sometimes gives an errors.

My solution:
- The net461 version has  dependencies on Microsoft.Extensions.Configuration and Microsoft.Extensions.Configuration.Abstractions (both with version 1.1.2)

Downgrading the dependencies versions could be breaking?

**Comment by cgillum** [comment]
So if I understand correctly, you're saying that Functions V1 customers who want to use `Microsoft.Extensions.Configuration.Json` have to use 1.1.2 because of the Newtonsoft.Json dependency. This is why I don't like dependencies. >_<

The actual use of `Microsoft.Extensions.Configuration.*` is actually very limited in the net461 version of the Durable extension, so I suspect downgrading should be safe. I might be able to remove the dependency entirely in that scenario, though it might require some code refactoring.

**Comment by mlankamp** [comment]
If you want, I could give it a try and create a PR

**Comment by cgillum** [comment]
Thanks for this PR! Sorry for the delay in acting on it.

It looks like your branch might not be completely up-to-date with the latest from **dev** (I'm seeing some unrelated commits show up in your PR). Also, there seems to be a bunch of HTML changes which I assume aren't intended to be part of this PR. If you can clean that up then I will merge this change.

**Comment by mlankamp** [comment]
Hi Chris,
I've recreated my PR, so the weird html files are gone. The pull request is now against the dev branch instead of master.

**Comment by cgillum** [comment]
The associated PR has been merged. This will go out with the next release.
