### ISSUE TITLE
Latency between scheduling and starting orchestrator

### ISSUE THREAD

**Issue by keesschollaart81** [Azure/azure-functions-durable-extension#449]
Hi. Im trying to include an Azure Functions Durable flow in an end-user scenario. The details of the scenario and all code (tailored to this issue) can be found in my example repository over [here](https://github.com/keesschollaart81/Realtime-Quotes-Example).

When I start an orchestrator in a function (trigger using HTTP) I observe a significant delay/latency between the 'Scheduled' and 'Started' state if the orchestrator.

![image](https://user-images.githubusercontent.com/6755359/46146120-41200080-c262-11e8-87f5-fe1f4e87e341.png)

This latency seems to grow when I add some user load:

![image](https://user-images.githubusercontent.com/6755359/46146724-ceb02000-c263-11e8-900b-3657c62db3f8.png)

[measured like this](https://github.com/keesschollaart81/Realtime-Quotes-Example/blob/master/Functions/Orchestration.cs#L48)

![image](https://user-images.githubusercontent.com/6755359/46146837-19ca3300-c264-11e8-8350-225454d79041.png)

I've tried a couple of things:
- Set `extendedSessionsEnabled` to true
- Switch between Consumption and Appservice plan

This does not seem to do much.

My question is: is having an orchestrator in a end-user flow something I can make performant? The docs suggest a latency of [max 30 seconds](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale#orchestrator-function-replay) which is way to much for me.

Looking forward to your views on this. I feel I'm very close to a cool architecture... :-)

**Comment by cgillum** [comment]
My apologies, this issue somehow fell off my radar. Some delay may be expected depending on factors like load on the storage account and load on the function app itself. 6 seconds feels pretty high. 30 seconds would be way too high. Do you have a recent repro with an up-to-date version of the extension? If you can share an instance ID and the Azure region you're running in, I can investigate.

**Comment by keesschollaart81** [comment]
Used versions can be found [here](https://github.com/keesschollaart81/Realtime-Quotes-Example/blob/master/Functions/Functions.csproj), all up to date / pretty recent.
Just to make sure, I just recreated the AppService & Hosting Plan but the behaviour is still the same.

Azure Region: West Europe. 
Example where latency between Orchestration Scheduled and Started is ~19 seconds:
Task/instance-Id: f8efe41fa7e64f2599c2f6e4ddf6a8d8
OperationId: BNgN/WjWZXw=
AppId: 7dd7161a-c8a2-455d-84a1-334bf5025377
Scheduled: 2018-10-23T10:56:26.480
Started: 2018-10-23T10:56:46.137

**Comment by cgillum** [comment]
Another customer opened a support case reporting similar symptoms. After looking through their Azure storage logs, I discovered an issue. This latency you're seeing is a bug. There should be very little (sub-second) latency between starting an orchestration and having it run, provided the storage account and the VM is not overloaded.

### Technical Details (mainly for my own reference)
The problem is specific to **Microsoft.Azure.WebJobs.Extensions.DurableTask**. What's supposed to happen is that whenever a message gets added to a queue by one function, the trigger listener gets signaled and immediately tries to read that message to minimize polling latency.

The issue I discovered after careful log inspection is that a client binding gets a separate **AzureStorageOrchestrationService** instance from the trigger listener. Those two instances have no knowledge of each other, so the client instance is unable to signal the trigger listener instance to notify it that a new message is available. The result is that the message doesn't get picked up until the trigger's next polling interval, which could be several seconds later.

If both the client and the trigger use the same **AzureStorageOrchestrationService**, then the signalling will work and the latencies will stay low.

I will work on the fix and include it in our next scheduled release (v1.7.0).

**Comment by cgillum** [comment]
Yep! This will go out with 1.7.0.
