### ISSUE TITLE
Orchestrator Concurrency - MaxConcurrentOrchestratorFunctions

### ISSUE THREAD

**Issue by AbhishekTripathi** [Azure/azure-functions-durable-extension#450]
As per the [document ](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale#concurrency-throttles) specifying maxConcurrentOrchestratorFunctions should limit the number of execution of the orchestrator on single VM. In my scenario, I have set the value to 1 in host.json. My expected behavior is to have single orchestrator running until completion but the observed behavior is that as soon as an activity function is awaited by the current orchestrator, another instance of orchestrator is invoked.
Is this expected behavior? What can be done to achieve my scenario where I don't want another orchestrator instances until my current orchestrator instance is completed either as a success or failure.

**Comment by AbhishekTripathi** [comment]
At the moment I am using SemaphoreSlim as a static instance to control concurrency of Orchestrator operator using synchronous wait(). Orchestrator waits indefinitely until the semaphore is finally released at the end of the operation. There should be a simple way to achieve this without depending on an external named event which is not always convenient.

**Comment by kashimiz** [comment]
The key word here is "concurrent." Because an orchestrator function does not run while it's waiting for the result of an activity function, To the Durable Task Framework, this looks like no orchestrator functions are running, so it starts up another one.

For a workaround, have you looked at [singleton orchestrators](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons)?
