### ISSUE TITLE
Orchestrator Function sometimes stays Pending for hours

### ISSUE THREAD

**Issue by martinewald** [Azure/azure-functions-durable-extension#471]
Hi

I have an Orchestrator Function (started by a QueueTrigger function) which sometimes stays in the RuntimeStatus Pending for a very long time, sometimes even for hours. As soon the Orchestrator continues (and it always wakes up eventually), the function is executed properly. The Orchestrator itself doesn't have much logic apart from starting 4 Functions sequentially. The subordinated functions are quite long running as I perform SharePoint Online actions like SiteCollection creation and Template Applying using the SharePointPnPCoreOnline Library. 

The funny thing is, sometimes it starts right away and runs smoothly without a hint of a problem...

How can I further investigate this problem. I just found the DurableFunctionsHubInstances Table which states that the Functions are in a Pending state. All Queue are empty a this time.

PartitionKey of one of the long running Orchestrators: 6517570c5e04475799c85fbe97db071b
Plan: Consumption
Region: West Europe
Azure Functions Version: v1 ->
I have to use Azure Functions v1 because i use the SharePointPnPCoreOnline and the Microsoft.SharePointOnline.CSOM Libraries which both are not available for .net standard.

**Comment by cgillum** [comment]
Thanks for the details. Your point about SharePoint dependencies being tied to the .NET Framework is also good data for us.

Have you configured Application Insights on your function app? That might help provide some clues. Here is one thing I noticed when looking at the instance ID you provided:

> The function 'ProjectProvisioningOrchestration' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the active orchestrator functions: 'ProjectProvisioningOrchestrationV2'.

So it looks to me that you started an orchestrator function named `ProjectProvisioningOrchestration`, but the runtime doesn't seem to think it exists. That's not normal since the call to start the orchestrator function should have failed immediately if a function of a particular name didn't exist. For that reason, it seems more likely to me that you have two different function apps competing for the same messages.

Looking more closely at our telemetry, that appears to be exactly the case. I see two function apps:
* OnlineO365Functions
* OnlineO365FunctionsV1

I can see that your orchestrator was started on **OnlineO365FunctionsV1** but **OnlineO365Functions** is constantly trying to run it (and failing). I can also see that both function apps are using the same Azure Storage connection string and have the exact same task hub name (_DurableFunctionsHub_, which is the default when none is specified in host.json). This seems to be the root cause.

The way to fix this is to either use separate storage accounts between your two function apps or to configure different a different task hub name in the host.json file of your respective function apps. Related documentation can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-task-hubs
