### ISSUE TITLE
Head 404 dependency issue when trying to write to Blob Storage

### ISSUE THREAD

**Issue by vinnytheviking** [Azure/azure-functions-durable-extension#484]
Good morning,

I have a durable function of which 1 of the activities is writing a file to blob storage.

Every single write throws a dependency issue in Application Insights, there's thousands for them since I'm writing a lot of files.

Every Put is preceeded by a HEAD that fails with a 404

![image](https://user-images.githubusercontent.com/1444491/47347816-f5694700-d6a7-11e8-8eb3-de20358ba482.png)

any ideas how i can reduce the 100s thousands of messages ?

I do currently create a SAS uri for the container where the blob goes but that made no difference at all.

**Comment by cgillum** [comment]
@brettsam I believe this is the same issue in Azure Functions 2.0 about logging dependency failures. Can you point us to that GitHub issue?

**Comment by brettsam** [comment]
Are you checking `blob.Exists()` before writing the blob? I'm guessing that's what is returning the 404. App Insights can't differentiate between a "good" and "bad" 404, so it thinks it is a failure.

The main issue is here: https://github.com/Azure/azure-webjobs-sdk/issues/1876. I've closed it b/c now we're chasing down the dangling issues that this didn't cover, and I'd like to keep them all separate since they're all unique.

We may need to provide a way to opt-out of certain dependency failures. @lmolkova and I have talked about it, but we've been able to work around it in other scenarios. But in this case -- you don't want to miss *all* failures (for example, if storage is down, you'd want to know) -- so it gets tricky. We'll see if we can come up with something.

**Comment by vinnytheviking** [comment]
Hi Brett, I don't check if the blob exists. 

I recently changed my code to use the datamovement library, I'm wondering if it does a check.

Do you by any chance know which of the AccessConditions won't do a blobExists call ?

I'm currently using _AccessCondition.GenerateEmptyCondition_ 

I'm aware of the 409 issues and have reduced them by moving the function storage to a separate account and removing the webdashboard app setting.

I just wondered if there was something similar for these 404s because they're being sent in email notifications and creating a lot of noise both in email and application insights.

Thanks for looking into this

**Comment by vinnytheviking** [comment]
Initially I used the library _Microsoft.WindowsAzure.Storage.DataMovement_ to do the blob upload.

I changed to the standard _Microsoft.WindowsAzure.Storage.Blob_ library for uploads and the 404's disappeared. Actually, the whole HEAD request disappeared.

**Comment by petr-x** [comment]
Hi, got the same issue. Found this on MS Docs https://docs.microsoft.com/en-us/azure/storage/common/storage-e2e-troubleshooting#some-causes-of-400-range-errors

...
Occurs if you are using an API call that creates the container or blob after checking whether it exists. The CreateIfNotExists APIs make a HEAD call first to check for the existence of the container or blob; if it does not exist, a 404 error is returned, and then a second PUT call is made to write the container or blob.
