### ISSUE TITLE
Orchestrations Stuck in Pending in Dev Branch

### ISSUE THREAD

**Issue by KevinDJones** [Azure/azure-functions-durable-extension#493]
I've been working on getting setup to contribute and am having issues running on dev. Any orchestration that gets scheduled by an HTTP trigger is getting stuck in pending. The HTTP trigger runs fine, schedules the orchestration (which I've confirmed does make it into Storage), but unlike in master, nothing else happens. Nothing runs.

I've pin pointed the issue to commit https://github.com/Azure/azure-functions-durable-extension/commit/8e7aa79e457ee89144b54f10f1db960eb1875d25 which was part of PR https://github.com/Azure/azure-functions-durable-extension/pull/473. This makes sense, as that PR changed the AzureStorage extension version from 1.3.1 to 1.3.2-rc.

I'm just wondering if there's something I'm missing or if others aren't having issues on dev. I've tried with both the Storage Emulator (v5.6) as well as a live connection string to Azure and saw the same results.

**Comment by cgillum** [comment]
CI's have been green so I'm a little surprised. Are you using .NET or JavaScript?

**Comment by KevinDJones** [comment]
@cgillum I'm using .NET. Just a barebones app to get up and running. I'm sure I'm missing something obvious. I'm going to make sure I've got that PR's other dependency loaded up right https://github.com/Azure/durabletask/pull/221 again

**Comment by cgillum** [comment]
There are three common causes for this kind of behavior:

1. There are two different function apps that are competing for messages in the same task hub. I just resolved a customer incident with this exact behavior and root cause earlier today.
2. A race condition bug that causes this to happen intermittently. This has been [fixed](https://github.com/Azure/azure-functions-durable-extension/issues/520) and will go out with the v1.7.0 release (due next week).
3. Some build problem (e.g. inconsistent versions of DLLs) that could be causing the host to fail to pick anything up. This problem might not be obvious unless you captured the ETW traces being emitted by the host process.

I've posted a version of v1.7.0 to the myget feed. You may want to try that out to rule out (2) and (3).

**Comment by KevinDJones** [comment]
Appears to be resolved now with version 1.7.0. Thanks @cgillum!

**Comment by cgillum** [comment]
Glad to hear! Thanks for letting me know.
