### ISSUE TITLE
ScriptHost fails to load Microsoft.Azure.WebJobs.Extensions.DurableTask.dll

### ISSUE THREAD

**Issue by mmisztal1980** [Azure/azure-functions-durable-extension#5]
When starting the script host locally, I get:

```
[04.07.2017 22:50:42] ScriptHost initialization failed
[04.07.2017 22:50:42] mscorlib: Could not load file or assembly 'file:///C:\BindingExtensions\DurableTask\Microsoft.Azure.WebJobs.Extensions.DurableTask.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515). An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
```

Please note that the **BindingExtensions** folder exists on **C:** and contains the **DurableTask** folder.

How can I fix this startup issue?
I'm running Win 10 x64 Pro, VS 2017 Update 2 + Functions Tooling

**Comment by cgillum** [comment]
That's a strange error message. Can you confirm that you're running VS 2017 version 15.3? Are you able to run functions locally when you remove the extension app setting?

________________________________

**Comment by cgillum** [comment]
I did a fresh setup on a clean Win10 VM and ran into the same issue. I wonder if it's some kind of trust issue since the zip package was downloaded from the internet. I'll investigate further.

**Comment by cgillum** [comment]
Found the problem. It's explained in more detail here: https://stackoverflow.com/questions/18016315/an-attempt-was-made-to-load-an-assembly-from-a-network-location-which-would-have

Basically, Windows is refusing to load the extension DLLs because they were downloaded from an "unsafe" location (a zip file from the internet). To work around this, you can do one of the following:

## Unprotect the DurableFunctionsBinding.zip file before extracting
This is the simplest method, which you can do before expanding the zip file:
1. Right-click DurableFunctionsBinding.zip 
2. Select Properties
3. Click Unblock
4. Unzip

This will ensure all files inside the archive can be safely loaded by the Functions runtime.

## Unprotect all extension files after extracting
If you already extracted the files, you can alternatively do the following to fix the issue:
1. Open a PowerShell prompt inside `C:\BindingExtensions`
2. Run the command `dir -Recurse | Unblock-File`

This will recursively unblock all files in the extension directory.

Sorry about the trouble - I'll work on updating the setup instructions.  I expect this will work for you.

**Comment by cgillum** [comment]
Leaving this active until the docs get updated. Note that this won't be a problem once we have proper extension setup implemented in Functions.

**Comment by mmisztal1980** [comment]
Unblock-File fixed the issue. Thanks Chris.

/Maciej
