### ISSUE TITLE
More insight in to publishing from local device to Portal.  

### ISSUE THREAD

**Issue by visualjeff** [Azure/azure-functions-durable-extension#531]
I'm unable to locate documentation related to publishing to the portal.  

What needs to be setup on the portal for a pushing a durable function from the local device to Azure? 

Even providing a link as to where this is documented would be helpful.

Thank you!

PS. I have the Javascript durable function running successfully on my local machine.

**Comment by kashimiz** [comment]
Hi @visualjeff,

The deployment process for a function app containing durable functions is the same as it is for any other function app. I assume since you're using JavaScript Durable Functions that you're working Visual Studio Code. VS Code's Azure Functions tooling allows you to select an existing function app in your Azure subscription, or create a new one from your editor. They have a step-by-step walkthrough to the extension [here](https://code.visualstudio.com/tutorials/functions-extension/deploy-app) (see sidebar for previous steps.)

If you're working directly from the Azure Functions core tools CLI, we document how to publish your function app [here.](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish) We also provide step-by-step quickstarts for VS Code and a number of other environments such as Linux and Visual Studio [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code) (see left sidebar.)

**Comment by visualjeff** [comment]
Thanks!
