### ISSUE TITLE
Orchestration stuck in Running after 3 retries

### ISSUE THREAD

**Issue by pvujic** [Azure/azure-functions-durable-extension#536]
Hi @cgillum 

We are having an issue with some orchestrations getting stuck as "Running" after 3 failing retries (CallActivityWithRetryAsync) on an activity.

Version: 1.6.2

One of the stuck orchestration's instanceId: 213928b0-21fb-4862-a271-da72a71d03c2

Already tried restarting the app, no effect..

**Comment by cgillum** [comment]
I see that this orchestration failed at 2018-11-29 08:27:08 after the 3 failing activity function retries. But yes, for some reason it doesn't appear to have actually updated the instance status. I'll need to take a closer look.

Do you know if you have this same problem in the v1.7.0 release? We made a bunch of important reliability fixes in that release, so I wonder if that might already have a fix.

**Comment by pvujic** [comment]
Thank you for the quick reponse. We have not rolled out the v1.7.0 yet.

So you think rolling out the app with the new version (1.7.0) and restarting would trigger the Running instances to proceed correctly (finish with status "Failed")?

**Comment by cgillum** [comment]
Restarting the app won't help because all messages associated with the orchestration have already been consumed. Upgrading to 1.7.0 would only help prevent future occurrences (assuming this isn't some new issue we've yet to discover). So I think you have a few mitigation options at this point:

1. Recreate the instance using the `StartNew` API and specifying the previous instance ID and input. This will overwrite the current instance and basically re-run from scratch.
2. If you want the instance status to be correctly updated to "Failed", you can manually update the **RuntimeStatus** column in the Instances table to **Failed** for this specific instance.
3. If you want to try and resurrect the instance and have it retry another time (assuming you've fixed the source of the failure), you can do (2) above and then use our [Rewind](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management#rewinding-instances-preview) API to restart the orchestrator from it's previous state (beware of the one [known issue](https://github.com/Azure/azure-functions-durable-extension/issues/444) though).

**Comment by pvujic** [comment]
Ok, then I'll try the 2nd approach and set the instances stuck in "Running" to "Failed". Hopefully that will not backfire in some unexpected way 🤞 

Also aware of the issue with the Rewind API. (I reported it)

Thanks!

**Comment by cgillum** [comment]
Thanks. Do let us know if you see issues like this again.
