### ISSUE TITLE
SetCustomStatus having no effect when using Await for async tasks inside OrchestrationTrigger

### ISSUE THREAD

**Issue by SkiddieTech** [Azure/azure-functions-durable-extension#554]
Case:
I have an Azure Durable function gathering data and writing it to an CosmosDB as a part of an data integration solution, in the same solution i have Logic Apps triggering the Azure Durable Function with different data (Synchronously), waiting for executions to finish ("CustomStatus" being a specific string) before triggering new ones. 

However when calling an task inside the OrchestrationTrigger functions using "Await", SetCustomStatus is unable to change / update it's value. 

`public static class BuggedFunction
    {
        private static HttpClient _client = new HttpClient();
        [FunctionName("BuggedFunction")]
        public static async Task Run([OrchestrationTrigger]DurableOrchestrationContextBase context, ILogger log)
        {
            
            log.LogInformation("Starting up!");

            context.SetCustomStatus("This status can be seen");

            var data = await _client.GetAsync("DATAURL");

            context.SetCustomStatus("This status will never appear");
            log.LogInformation("Completed!");
        }

    }`

The code above never never shows, "This status will never appear" as an CustomStatus. It Simply "stops" and will always show "This status can be seen". 
Also note that the runtimeStatus never hits "Complete", but stays infinitely at "Running"

This can be avoided by using `var data =_client.GetAsync("DATAURL").Result;` but as i want to avoid "Locking" the thread i need to use await. 

Suggestions?

**Comment by cgillum** [comment]
Hi @SkiddieTech, the problem is that your orchestration is getting stalled by your use of `HttpClient.GetAsync`. This is why you're never seeing the updated status, and is also why your orchestrator never completes. As a documented rule, an orchestrator function must **never** do any I/O or async work except when using methods defined on `DurableOrchestrationContext`.

Take a look at the [Code Contraints](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay#orchestrator-code-constraints) listed in our documentation. This one in particular:

> Orchestrator code must never initiate any async operation except by using the `DurableOrchestrationContext` API. For example, no `Task.Run`, `Task.Delay` or `HttpClient.SendAsync`. The Durable Task Framework executes orchestrator code on a single thread and cannot interact with any other threads that could be scheduled by other async APIs.

The correct way to write your orchestrator which needs to make an HTTP call is to create an activity function which wraps your HTTP call. In a future release, we will add our own support for [making HTTP calls directly from the orchestrator](https://github.com/Azure/azure-functions-durable-extension/issues/469), so that you won't always have to create a separate activity function.

Unfortunately we can't always auto-detect when someone does this (at least not that I'm aware of). However, if you scheduled another activity function after the `GetAsync` call, then you would have seen an exception telling you about the issue.

Let me know if you have any other questions about this.
