### ISSUE TITLE
Q: Action Cross Cutting Concerns

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#566]
How can I hook into durable-extension to have some code run pre/post action execution?

Thanks

**Comment by cgillum** [comment]
I'm not sure I understand the question. Can you provide an example of what you'd like to accomplish?

**Comment by espray** [comment]
@cgillum 
Logging/Metrics - I want to log, to Application Insights, what Action was executed and time it took to complete the action.

**Comment by cgillum** [comment]
Have you looked into our Application Insights integration? https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics. Our extension writes orchestration trace events there (function scheduled, started, completed, etc.). However, they are generic traces and may not work if you're tracking business logic.

Otherwise, the closest thing I'm aware of is a feature known is [Function Filters](https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters). It's in preview, and only supports pre-compiled .NET, but it might give you the flexibility you want. It's a generic WebJobs feature and not specific to Durable Functions, but I imagine one could use that to add custom instrumentation around activity function executions.
