### ISSUE TITLE
Missing function name in HTTP API response

### ISSUE THREAD

**Issue by karrocon** [Azure/azure-functions-durable-extension#567]
Function name is not included in the GET instances response. I was trying to get all running instances of a given function (not function app) but it does not seem to be possible as of now. Am I missing something?

**Comment by karrocon** [comment]
I saw that it is possible to retrieve the starting function name using the historyEvents but it seems that _show*_ query parameters are only working when asking for a single instance. If this feature is available when retrieving all instances we will save a lot of additional requests to perform the task I mentioned previously.

**Comment by kashimiz** [comment]
Hi @karrocon, let me confirm I understand your scenario correctly: do you want to retrieve, for all running instances of `FunctionName`, the expanded orchestration information (including history)?

At present our API doesn't expose a way to query instances by function name, but that sounds like a reasonable ask. I believe we don't return expanded orchestration information on the bulk instance queries due to the potential size of the returned response; @cgillum can you confirm?

**Comment by karrocon** [comment]
You are right. Actually, I would only need all running instances of `FunctionName`. The historyEvents is the workaround I found to achieve this.

Regarding including historyEvents within the bulk instance query, I can see in the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api) that it is supposed to be working but I understand the reason why it is not included.

**Comment by kashimiz** [comment]
It looks like our documentation is a bit unspecific on that point. I can see how it led to confusion; my apologies. I'll get a PR out to fix that and specify that the showHistory option is for since instance queries only.

**Comment by cgillum** [comment]
This has been fixed in the [v1.8.1 release](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.1).
