### ISSUE TITLE
Sub orchestration checkpoint [Question]

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-durable-extension#575]
I can't find it within the documentation here
https://docs.microsoft.com/en-gb/azure/azure-functions/durable/durable-functions-checkpointing-and-replay

I only see someone make a blog post about it here (number 5)
https://markheath.net/post/durable-functions-sub-orchestrations 

Is it true, if you use sub orchestration, there will be NO event sourcing history on activity functions inside sub orchestration? Thus it will simplify the event sourcing history as the blog claim?

```
try{
}
catch(Exception ex){
//Call activity A
//Call activity B
}
```
That pattern should be discouraged because, it will replay the exception?
Assuming there are more than one activities need to be called within catch statement
```
try{
}
catch(Exception ex){
//Call sub orchestrator
}
```

**Comment by cgillum** [comment]
I assume you talking about this:

> However, if sub-orchestrations are used, the event sourcing history for the parent orchestration can replace the entire call to a sub-orchestration with its serialized JSON output, greatly reducing the number of overall events stored against the parent orchestration.

Mark's statements are correct here. If you use a sub orchestration to encapsulate calls to activity A and activity B, the calls to those activities (and their results) do not need to be recorded in the parent orchestration's history.

It should be noted, however, that there is a small amount of constant overhead added because of the extra messages involved in scheduling the sub-orchestrator itself. But if the sub orchestration encapsulates a lot of activities, then the benefit of reducing the history size will likely be greater than this cost of scheduling a sub-orchestration.

Does that answer your question?

**Comment by andrew-vandenbrink** [comment]
Which one is the best practices?

Lot of activities within orchestration function (which means lot of replaying)
or
Encapsulate with sub orchestration when possible to avoid lot of replay

?

**Comment by cgillum** [comment]
It really depends on the design of your orchestration. From our performance testing, the actual cost of replay is not noticeable unless you have hundreds or thousands of actions. The times I've recommended sub-orchestrations are mainly when:

* Simplifying complex patterns - e.g. running multiple sequences in parallel.
* Improving the speed of fan-out / fan-in - e.g. instead of fanning out to 10K activities, fan-out to 100 sub-orchestrations, which each fan-out to 100 activities.
* Encapsulating logic that can be shared across multiple orchestrations.

Again, sub-orchestrations are not "free", so I generally don't recommend them unless you think they will actually help you in one of the these areas.

**Comment by andrew-vandenbrink** [comment]
ok thats clear, thanks!
