### ISSUE TITLE
Loading large files

### ISSUE THREAD

**Issue by tomrucki** [Azure/azure-functions-durable-extension#594]
What is currently the recommended approach for loading large files from blob storage?

I went through the docs and also issues here but I'm still not clear how to handle it. I know I can do IO only via activity functions but that means the file will be stored (duplicated) in history. So if I have the file already in blob storage is there a way to not duplicate it?

Just to briefly describe what I'm trying to do - large pdf lands in blob storage, I split it to individual pages, do some processing in parallel (fan-out) and wait for results.

**Comment by kashimiz** [comment]
Whatever you pass as an input or output to an orchestrator or activity function will end up as serialized JSON or, if over 63 KB, as compressed blob storage, [per @cgillum on the issue for large message support.](https://github.com/Azure/azure-functions-durable-extension/issues/26#issuecomment-380631996) The current Durable Functions extension isn't smart enough to recognize the scenario you describe and reuse an existing blob. I'm on the fence about this as a potential optimization; unless that blob could be guaranteed to be left otherwise untouched until the orchestrator completed, there'd be the potential to mess up the orchestrator's replay behavior. @cgillum?

**Comment by TheFairey** [comment]
Hi

We do something similar, what I do is have a single activity function that reads the PDF from blob storage, splits into into single page PDFs and stores them on blob storage and then returns a list of #numofpages filenames, assuming you have a consistent path. To be honest you could just return a count of pages and assume each PDF is just call <pagenumber>.pdf.

Then you trigger #numofpages activity functions in a fan out and each one gets the filename or just the page number and then each one reads the file from blob storage and then processes it.

This saves you having to pass files around.

Let me know if you need more detail to help.

Si

**Comment by tomrucki** [comment]
@TheFairey Thanks for the description of how you tackled the problem. It's quite similar to the one I have implemented in the end.
