### ISSUE TITLE
Introduce Custom LifeCycleNotification interface

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#602]
I want to add custom status to ETW logging.

In the current ETW logging, since I can not identify at which timing within the orchestrator it failed, I want to make it possible to identify by using custom status before executing the activity.

Thanks

**Comment by cgillum** [comment]
Can you provide a few more details?

* Are you asking about tracing [this custom orchestration status](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status) data or something else?
* If it's the custom orchestration status payload, do you need the full payload (up to 16 KB) to be written to the trace?
* Does it need to be ETW or can it just be Application Insights? Azure App Service consumes the ETW events internally, and I would prefer not put potentially sensitive customer data there.

**Comment by cgillum** [comment]
Ah, I see. You wrote an ETW listener to help debug orchestrator problems, but need more information to be included in the ETW events. Is that correct?

If you just need more information, one thing we do have is a `traceInputsAndOutputs` setting in [host.json](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-bindings#host-json). If you set this to `true` then you can see the input and output data for each function included in the Application Insights traces.

Otherwise, the only thing we have for custom error processing is our [Event Grid notifications](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-event-publishing), which you mentioned already in your blog post.

**Comment by shibayan** [comment]
>need more information to be included in the ETW events. Is that correct?
Yes!

>traceInputsAndOutputs
I did not know this option. I will try it.

>EventGrid notifications
I want to pluggable notification processing to EventGrid. (introduce Interface?)

Thanks

**Comment by shibayan** [comment]
The extension of LifeCycleNotificationHelper seemed to be good, I wrote a prototype.

https://github.com/Azure/azure-functions-durable-extension/compare/dev...shibayan:lifecycle-pluggable

**Comment by shibayan** [comment]
@cgillum I modified issue topic. Relative issue #613

Thanks!

**Comment by cgillum** [comment]
I just now looked at your prototype. This seems really nice. If you convert it into a PR, I would be happy to review it and we can make it part of the next feature release.

**Comment by shibayan** [comment]
I will create a pull request. Thank you!

**Comment by shibayan** [comment]
It was released in v1.8, it closes. Thank you.
