### ISSUE TITLE
Alerting on Orchestration Failure & Recovery

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#610]
We are relying on Orchestrators to run to completion and complete successfully. 

In the instance that an Orchestration goes into a Failed state (failure is inevitable), it is important that my Engineers can react to this, by knowing that there has been an error.

My initial thoughts was to build an Azure Monitor Alert based off the Orchestration Failure App Insights Metric going above 0. Great, I get an email alerting me of the failure.

| timestamp [UTC] | name | value |
|--------------------|-------|--------|
| 2019-02-15T09:38:04.0278211Z | Orchestrator Failures | 1 |

However, This doesn't really work as that metric represents an 'event' at a point in time i.e. "An orchestrator has Failed". 

In the next sampling window, if no new Orchestrators have failed, that value will drop back to 0 and Azure Monitor will publish an email saying that this has been Resolved, which isn't true. My Engineers would see this email and assume someone has fixed the Failed orchestrator.

| timestamp [UTC] | name | value |
|--------------------|-------|--------|
| 2019-02-15T09:38:05.606 | Orchestrator Failures | 0 |

**Alternatives?**

So now I'm looking for alternatives, and im thinking of using the Orchestrator Lifecycle Events that are published to Event Grid and persist each failure event to a persistant-store.

Then I can run a query against that store on a cron schedule to check if there are any Failed orchestrators.

Now the problem is that when I Resolve/fix a failed orchestrator (such as rewinding it, or admitting that the Orchestrator is terminally dead and deleting it) I now need to update that store to 'remove' the failed event, so that it doesn't get continually Alerted on.

**Conclusion**

What I'm getting at here is there is a lot of manual moving parts that I have to implement just to keep on track of if there are any currently failed orchestrators in the system. 

I don't want to take a dependency on the underlying operational Durable Functions store and look for Orchestrators that are failed as this is bad-practice and definitely wont scale for my needs as I'll be creating millions of short-lived orchestrators a day.

Do you have any suggestions on how I can get on top of this health monitoring issue with less moving parts to implement?

If not, can this be used as evidence in developing the Durable Functions framework to offer something like a health endpoint that reports back on how many currently failed Orchestrators exist in the whole system at this point time? I can then _easily_ create a cron schedule to query that endpoint and emit Application Insights custom Metrics to trigger Alerts. 

I appreciate that what I'm asking for may not be readily available as DF is essentially a decentralised system with no real supervisor (so no representation of the global state), but this problem is a real pain-point for me.

**Comment by olitomlinson** [comment]
Its also worth noting that I have considered using the Instance Management HTTP API to return a list of all the Orchestrators that are in a failed state, however in my use-case I will have millions of orchestration instances in the Instance table at any one time. Its likely that this API query would time out as it pages through all the Azure Storage Table Rows. Even if the query took 30 minutes to complete, thats still no good for Monitoring & Alerting purposes.

Any thoughts @cgillum

**Comment by cgillum** [comment]
Hey @olitomlinson sorry for the delay in responding to this issue. I think the problem you're trying to solve is similar to the problem my teams (Azure Functions and Azure App Service) need to solve when operating our own live service.

For tracking and alerting on orchestration failures, I strongly recommend you leverage our built-in [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#application-insights) integration (I think this is basically the same thing as the Azure Monitor approach you mentioned). We have a very similar system built on the same underlying infrastructure for monitoring Azure App Service (1 million VMs, 40+ data centers, etc.).

For the case you described, what you can do is create alerts that trigger based on the number of failures seen in a particular time window (e.g. a one hour window, depending on the support SLA you're targeting). You would want to set things up in such a way that an alert creates a ticket in your own system and notifies an on-call engineer to go investigate and resolve the issue. The separate ticketing system will ensure that issues continue to be tracked even if you pass the time window that you're monitoring. The incident is resolved when the ticket is closed rather than when you detect "no failures". As you mentioned, an email saying "no failures" is not helpful - that might work for monitoring HTTP traffic, but not for background jobs.

Of course, you could also use lifecycle notification events as the alerting mechanism instead of Azure Monitor / Application Insights alerting. The process would need to be the same - i.e. decoupling incident resolution from the notification system.

Let me know if this makes sense for your scenario.

**Comment by olitomlinson** [comment]
I think I get what you're saying.

I've had my current solution running for a few months now and its mostly working. Heres what I do:

1. Utilise the LifeCycle Notifications and when a Failed orchestration event occurs, write that orchestration Id into a 'Failures Table'.
2. Have a seperate Azure Function on a 1 minute schedule, that checks for the existence of any rows.
3. Publish a metric using App Insights with the count of Rows.
4. Set up a Azure Monitor alert that tracks for this value becoming greater than 0.

This works great for the most part, but we had to downgrade App Insights to use the last-gen [TrackMetric API](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackmetric) instead of the newer [GetMetric / TrackValue API](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#getmetric) as this new client-side preaggregation doesn't seem to work in our use case, (the metrics were not emitted/ingested with the correct timestamps, which caused false positives that Monitor Alerts were resolved)

Anyway back on topic, we use a combination of xMatters and Jira for on-call escalations so I'll put some thought into how we can better integrate that.

Many thanks!
