### ISSUE TITLE
[Question] Re-using Instance IDs of failed Orchestrators

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#659]
I need a bit of clarification around the behaviour of restarting existing Instances, thanks.

**Actual**
1. Introduce an Exception in an Activity so an Instance goes into terminal failed state.
2. Start an Orchestrator with ID 123 and Payload X ( `starter.StartNewAsync(...)`)
3. Instance 123 goes into a terminal failed state as expected.
4. Remove the forced exception in the Activity.
5. Start Orchestrator with ID 123 and Payload X  ( `starter.StartNewAsync(...)`)
6. Instance 123 restarts from the beginning and completes successfully.

**Expected**
I _assumed_ (rightly or wrongly) that trying to restart an Orchestrator with the same ID would throw? Is there any documentation that clarifies the behaviour of starting orchestrators where the ID is already assigned to an Instance that is in either terminal or non-terminal state?

**Notes**

On the restart of the Instance, there is a new `ExecutionId` assigned.
The restart looks to be rewriting the rows in the history table starting with `RowKey 0000000000000000` incrementing.

**Comment by cgillum** [comment]
The behavior you're seeing is currently by design. It's mentioned in the API documentation [here](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#Microsoft_Azure_WebJobs_DurableOrchestrationClient_StartNewAsync_). We also have some test cases which verify this behavior.

You might notice that you can even restart an in-flight orchestration that has _not yet completed or failed_. I'm not a fan of this behavior, but we're stuck with it for now. I'm thinking about whether we can instead throw an exception by the time we do the v2.0 release.

**Comment by olitomlinson** [comment]
Thanks @cgillum I always forget to look at the this part of the docs!

Yeah, I'm not a massive fan either. Luckily we have built our activities to hands-off to idempotent receivers so replaying an instance is not a problem in our case. 

But I can totally see a scenario where a user accidentally re-uses an instanceId and then the history gets rewritten, which could cause confusion when trying to diagnose what happened in that instance.
