### ISSUE TITLE
Q: Change Action behavior on Replay

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#662]
I want to run some logic if my action is replaying.

Can an Action taken an input parameter for `context.IsReplaying`? 
 - Another way to ask the question. When an Action is replayed, does it use the original input?

How can I test my Replay logic, can I force my Orchestrator to replay?

**Comment by espray** [comment]
@cgillum Sorry Activity not Action
`await context.CallActivityAsync("A_SayHello", context.IsReplaying)`
...
```
[FunctionName("A_SayHello")]
public static async Task ActivitySayHello([ActivityTrigger]bool IsReplaying input)
{
 // Would input == true if 'A_SayHello' is replaying
}
```

**Comment by cgillum** [comment]
Thanks for clarifying.

Actually, activity functions are never replayed. Only orchestrator functions are replayed. The only reason an activity function would ever execute a second time is if there is some kind of system failure which causes an activity function execution to stop before it had a chance to commit its result,

Does that help clear things up?

**Comment by espray** [comment]
@cgillum there are a number of reasons an the process could stop in the middle of an activity. A function timeout or deployment, could cause the process to stop inside an activity. With some local testing, I found my answer. The activity will be replayed with the original input. If this is not correct, please let me know.

Followup question. In an activity function, can I get the current CustomStatus or DurableOrchestrationContext? I think the answer is no, at least I could not find a way.
Maybe I could use a custom binding... Just think out loud. :)

**Comment by cgillum** [comment]
Yes, you are correct that restarted activity functions will use the same input. This is because the input is stored in an Azure Storage queue message which does not get deleted unless the activity function completed successfully.

Activity functions don't have access to the custom status or the orchestration context. The do have access to the instance ID, so they can either have orchestration status info passed to the activity function as a parameter or the activity can use the orchestration client binding to query the orchestrations status directly.

**Comment by espray** [comment]
@cgillum 
I set the Custom Status in the orchestration
`context.SetCustomStatus($"{context.InstanceId}, {context.IsReplaying}");`

Then in my activity function, I used the orchestration client to get the status 
`await orchestrationClient.GetStatusAsync(instanceId);`
I get a Microsoft.Azure.WebJobs.DurableOrchestrationStatus, but the `status.CustomStatus` is empty {}.
Also `RuntimeStatus == Microsoft.Azure.WebJobs.OrchestrationRuntimeStatus.Pending`

Shouldn't RuntimeStatus be Microsoft.Azure.WebJobs.OrchestrationRuntimeStatus.Running?
Can I flush the orchestration SetCustomStatus to force it to write immediately.

Maybe it would be better to marshal the data using a different mechanism

**Comment by cgillum** [comment]
The reason `status.CustomStatus` returns empty is probably due to a race condition between the orchestration being persisted and the activity function executing. I think the fact that the runtime status is `Pending` confirms this.  This is by design because activity functions may start executing before the orchestration finishes its checkpoint. I think you have two options:

* Have your activity function wait a few seconds before checking the custom status.
* Pass in the custom status as a parameter to the activity function.

The option you use depends on your requirements - i.e. depends on whether the activity function needs to have the latest status of the orchestrator or not.
