### ISSUE TITLE
Orchestration result has output pointing to blob storage when message size is around 32 kB

### ISSUE THREAD

**Issue by marcduiker** [Azure/azure-functions-durable-extension#693]
When dealing with large messages I'm seeing this output as the result of an Http triggered orchestration which I run locally:

```
HTTP/1.1 200 OK
Connection: close
Date: Tue, 09 Apr 2019 09:16:49 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 360

{
  "instanceId": "3d34e6c54cdb4ff8bc15cb3c4cb59dbb",
  "runtimeStatus": "Completed",
  "input": 30719,
  "customStatus": null,
  "output": "http://127.0.0.1:10000/devstoreaccount1/largemessages-largemessages/3d34e6c54cdb4ff8bc15cb3c4cb59dbb/history-0000000000000006-executioncompleted-result.json.gz",
  "createdTime": "2019-04-09T09:16:41Z",
  "lastUpdatedTime": "2019-04-09T09:16:44Z"
}
```

- Durable Functions extension version: v1.8.0
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

**To Reproduce**
See [this GH repo](https://github.com/marcduiker/durable-functions-large-messages) for the solution and saved responses.

**Expected behavior**
I was expecting to get the JSON response in the output field instead of the blob link. I am aware of issue #26 (large message support) but I thought that blobs were only used between the orchestrator and activity functions. It also appears that the size limit is 32kB instead of 64 kB. 

**Actual behavior**
When an orchestrator response is returned and the resulting message is larger than 32kB then the output field contains the link to blob (containing the message) in the storage account: 
` "output": "http://127.0.0.1:10000/devstoreaccount1/largemessages-largemessages/3d34e6c54cdb4ff8bc15cb3c4cb59dbb/history-0000000000000006-executioncompleted-result.json.gz",`

My questions: 
- Is this behavior by design?
- Is the message size limit configurable?

**Comment by olitomlinson** [comment]
Hey @marcduiker , this is by design.

There is an open enhancement that might satisfy your need https://github.com/Azure/azure-functions-durable-extension/issues/665

**Comment by marcduiker** [comment]
Thanks @olitomlinson, I didn't spot that issue :/. 

Still leaves the size limit unanswered. I see that messages of around 32kB are stored as blobs, nowhere near the 60kB limit.

**Comment by olitomlinson** [comment]
@marcduiker I've not seen a configurable limit documented anywhere, and a configurable limit doesn't appear to be referenced in any of the issues, so I would be inclined to say it doesn't exist. But I'm certainly not an authority on this :)

**Comment by cgillum** [comment]
The contents are GZip-compressed before being uploaded to blob storage. Could that be why you're seeing 32KB instead of 60KB?

**Comment by marcduiker** [comment]
@cgillum no that's not the case, unfortunately. The [zipped json](https://github.com/marcduiker/durable-functions-large-messages/blob/master/saved_responses/history-0000000000000006-executioncompleted-result.json.gz) is 178 bytes, the [unzipped json](https://github.com/marcduiker/durable-functions-large-messages/blob/master/saved_responses/history-0000000000000006-executioncompleted-result.json/history-0000000000000006-executioncompleted-result.json) is 30kB.

**Comment by SimonLuckenuik** [comment]
@cgillum, we just faced that specific problem today. The current behavior is not obvious and is not expected as well. 

I think Durable Function should be responsible to deserialize and return the content of that file. 

Currently, I will need to : 
1) deserialize "output" as a JToken
2) check if the content of the JToken is a string starting with a URL, if so it means know I need to get the file
3) check if the extension ends with '.gz', if so, unzip it otherwise read it as is, no unzip. 
4) Assuming that is a non-public blob container, so it means I will need to find which Storage account to use so that I can generate a SAS token in order to get the file or extract the relative path and use the Storage SDK to get the file directly... 
5) Deserialize the file content and use it.

It also means that I need to make sure that my output is never a single string and rather a complex structure to make sur that by mistake the start of the string returned is a URL...
