### ISSUE TITLE
Q: Disable Orchestration

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#738]
Can an Durable Orchestration be disabled through an app setting or host.json setting?

**Comment by cgillum** [comment]
*(I've moved this question to the `azure-functions-durable-extension` repo, since host.json doesn't apply for anything in the `durabletask` repo).*

You can disable functions via app settings as described [here](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function#functions-2x---all-languages), but not through host.json. 

However, be aware that the current behavior is to throw an exception if you try to invoke a disabled function. This is because the extension thinks that the function doesn't exist - i.e. disabling a function makes it invisible to the functions runtime.
