### ISSUE TITLE
Durable function Long running 

### ISSUE THREAD

**Issue by breddynet** [Azure/azure-functions-durable-extension#754]
Durable function is not working after processing 200k Records in Azure

I have to process over 1 million records in the activity 

Here is my configuration, Any help appreciated

 "durableTask": {
    "maxConcurrentActivityFunctions": 100,
    "maxConcurrentOrchestratorFunctions": 10,
    "extendedSessionsEnabled": true,
    "extendedSessionIdleTimeoutInSeconds": 600,
    "maxQueuePollingInterval": "00:00:30",
    "controlQueueBatchSize": 1000,
    "partitionCount": 30
  },

**Comment by cgillum** [comment]
Hi @breddynet, I'm going to need a bit more information.

* What do you mean when you say "Durable function is not working"? What is _exactly_ the issue you're encountering?
* What kind of orchestration logic are you using? For example, are the 200K records processed in a single activity function, or are they spread out across multiple activity functions?
* What region are you running in, and what is the instance ID of the orchestration that is not working? We have telemetry in Azure that can help us investigation, but I need more information about your app in order to find this telemetry.

Also, the maximum allowed `partitionCount` value is 16. Your app should not be able to start if it is set to `30` like you show in your configuration.

**Comment by breddynet** [comment]
i have one orchestrator and opening 1 million activities to process the data. 

foreach (var user in newUsers)
                    {
                        Task<string> identifierTask = context.CallActivityWithRetryAsync<string>("FnActivityUsers", retryOptions, user);
                        activityTasks.Add(identifierTask);
                    }
                
                await Task.WhenAll(activityTasks);

**Comment by ConnorMcMahon** [comment]
@breddynet nothing obviously wrong pops out at me given the config and orchestrator code you provided. Can you let us know the region you are running this app in, and provide us with the orchestration id for the failing instance?

**Comment by breddynet** [comment]
I will run the process tonight and update you the status on the issue.

**Comment by cgillum** [comment]
Generally speaking, I wouldn't recommend executing 1 million activity functions in parallel within a single orchestration. We routinely run tests with 100K parallel activity functions, but not as high as 1M. If you have 1 million records that you need to process, I suggest you either batch them so that a single activity function can process more than one record -or- try to break up your orchestration into multiple sub-orchestrations, each of which does its own fan-out. For example, creating 10 sub-orchestrations which each fan-out to 100K activity functions.

But if you already started a run with 1 million activity functions, we can investigate what happened if you provide the region and the orchestration instance ID, as Connor asked.
