### ISSUE TITLE
[WIP] Proposal: Object-oriented durable entities for .NET

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#763]
## Overview
This is a proposal for how to create an object-oriented development experience for durable entities in .NET. The idea is that this is an optional model that compliments the simple, function-based programming model in a way that scales better for complex entity types.

## Requirements
- [ ] Allow entities to be expressed as object-oriented class instances
- [ ] Compatibility with Azure Functions [dependency injection](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection)
- [ ] Support handling of all existing client operations (signal, call, HTTP-flavors, etc.)
- [ ] Leverage existing JSON serialization infrastructure
- [ ] Support for code-gen / declarative modeling scenarios

## Example 1: Counter
This is a really simple example showing how to model the Counter sample as a class.

```csharp
[DurableEntity("counter")]
public class CounterEntity
{
    [EntityState("value")]
    private int value;

    [EntityOperation("add")]
    public void Add(int amount) => this.value += amount;

    [EntityOperation("subtract")]
    public void Subtract(int amount) => this.value -= amount;

    [EntityOperation("reset")]
    public void Reset() => this.value = 0;

    [EntityOperation("get")]
    public int Get() => this.value;

    [FunctionName("Counter")]
    public static void Run([EntityTrigger] IDurableEntityContext ctx) 
        => ctx.Dispatch<CounterEntity>();
}
```
It has some key benefits over the default, functional model:

* No `switch` statements - this model scales better for large numbers of operations.
* Declarative - the skeleton can be generated from models, and strongly typed clients can be generated by reflecting over the class.
* Object-oriented - while not shown in this sample, polymorphism allows for powerful scenarios, like inheritance and dependency injection.

## Reflection and Dispatch
The entry point to the entity class is still a static function with the `[EntityTrigger]` trigger binding. This is required by the Functions runtime. It doesn't have to exist in the same class as the entity class, but it might be helpful to collocate it in this way. The implementation of this method can simply be `IDurableEntityContext.Dispatch<T>()` where `T` is a class that represents the durable entity.

> TBD is what the exact lifetime semantics of these objects are. Ideally the `T` type parameter could also be an interface, in which case resolution can be done via the built-in Azure Functions dependency injection functionality.

The entity class should be a concrete class that can be constructed using reflection - e.g. using [Activator.CreateInstance](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance). When the object instance is constructed, the entity state should be deserialized into the field marked by the `[EntityState]` attribute. Only one field can have this attribute. Any changes to this field should be automatically persisted whenever the entity state is normally persisted.

Each operation is represented as a method decorated with the `[EntityOperation(name)]` attribute where `name` is the name of the operation. The dispatcher will use the value of `IDurableEntityContext.OperationName` to know which method to invoke. The method would be allowed to have zero or one argument. If there is an argument, the dispatcher will try to deserialize the operation input into the argument's parameter type. Both complex and simple types should be supported and it should work the same as calling `IDurableEntityContext.GetInput<T>()` where `T` is the type of the parameter. If there is no parameter defined in the method, then there won't be any attempt to deserialize the operation input. A user can alternatively specify `JToken` (or some derivative) as the parameter type and the JSON operation value will be parsed and surfaced to user code directly as `JToken`, etc.

If an operation method has a return value, that return value will be used as the argument to `IDurableEntityContext.Return(object)`. If the return value is `void` or `Task`, then no value will be returned to the caller.

## Scenario: Code-gen / modeling
In this scenario, a tool is used to model entities declaratively. This could be as simple as a text-based DSL or a rich graphical drag-and-drop interface.

> NOTE: This is a hypothetical scenario. This proposal is not suggesting that we build any particular modeling language or code-gen tool. Rather, it is intended to highlight something a user could implement themselves.

The hypothetical DSL markup could look something like the following:

```json
{
  "type": "counter",
  "state": {
    "currentValue": "int"
  }, 
  "operations": {
    "add": { "input": { "amount": "int" } },
    "subtract": { "input": {"amount": "int" } },
    "reset": { },
    "get": { "output": "int" }
  }
}
```

A tool could then be used by a developer to convert the declarative model into a C# template:

```csharp
[DurableEntity("counter")]
public class CounterEntity
{
    [EntityState]
    private int currentValue;

    [EntityOperation("add")]
    public void Add(int amount) => throw new NotImplementedException();

    [EntityOperation("subtract")]
    public void Subtract(int amount) => throw new NotImplementedException();

    [EntityOperation("reset")]
    public void Reset() => throw new NotImplementedException();

    [EntityOperation("get")]
    public int Get() => throw new NotImplementedException();
}
```
At this point, the developer could then implement each of the operations.

**Comment by cgillum** [comment]
FYI @sebastianburckhardt, I'm proposing this as an alternative to https://github.com/Azure/azure-functions-durable-extension/pull/711. Note, however, that this proposal doesn't care whether the clients are strongly typed or not.

**Comment by sebastianburckhardt** [comment]
I think this solution is fine as far as just simplifying the dispatch is concerned, but the client side has not been really addressed here, and I think there are some problems with it.

When I first started #711, I actually started with the same design (using attributes on methods). However, it turns out that does not actually give us polymorphism, i.e. the ability of clients to interact with subtypes as of they were the supertype. I went through several designs in #711, eventually settling on a solution where the user declares *entity interfaces* which then allows polymorphism. 

Let me illustrate the main advantage of interfaces; imagine the counter example again, but now the counter entity also implements some other role (e.g. lifecycle listener). Using interfaces as in #711 we can say:

```csharp
[EntityInterface]
public interface ICounter 
{
    void Add(int amount);
    void Reset();
    int Get();
}

[EntityInterface]
public interface ILifecycleListener {
    void OnLifecycleEvent(LifeCycleEvent event);
}

[EntityClass]
public class CounterEntity : ICounter, ILifecycleListener
{
    [JsonProperty("value")]
    public int Value { get; set; }

    public void Add(int amount) => Value += amount;
    public void Reset() => Value  = 0;
    public int Get() =>Value;
    public void OnLifecycleEvent(LifeCycleEvent event) => throw new NotImplementedException();

    [FunctionName("Counter")]
    public static void Run([EntityTrigger] IDurableEntityContext ctx) 
        => ctx.Dispatch<CounterEntity>();
}

```
Now clients can call entities based on their interfaces, instead of their implementation. An entity class can implement any number of entity interfaces, and entity interfaces can be implemented by an number of entity classes.

there are some other small differences here as well. In general, I prefer to keep attributes to a minimum.

- instead of inventing new attributes for state (`EntityState`) we can just stick with existing attributes that control serialization (e.g. JsonProperty, DataMember, etc), as they already provide much control and are well documented.
- we can make the reflection-based operation dispatch case-insensitive by default so no need to worry about capitalized vs non-capitalized spellings of operation names.

In general, I suppose I would prefer to fix the few remaining open concerns around #711 than start over with an alternate design. The main thing to fix in #711 is interoperability with non-.NET clients, which can be achieved by implementing the reflection part a bit differently (but keeping the API mostly the same otherwise). The other open question was how to get similar benefits for activities and orchestrations which seems to be an orthogonal issue not addressed here.

**Comment by cgillum** [comment]
Thanks Sebastian for the feedback. What you're describing makes a lot of sense to me. Regarding #711, I think if we can make it fully interoperable with non-.NET clients (and therefore decouple it from any particular client-side implementation), then my concerns would be addressed.

You bring up good points about the use of `[JsonProperty]` rather than creating a new `[EntityState]` attribute. Just to clarify, is the assumption that you will serialize the whole `CounterEntity` class when persisting the state? I think that's fine but we may want to think about some of the corner cases involved in serializing polymorphic objects. For example, we might want to enforce a policy where users *must* explicitly declare which properties should be serialized so that we don't run into cases where unexpected fields end up getting serialized.

I think interfaces will still allow us to solve the declarative modeling scenario. Now that I think about it, interfaces might actually make them simpler because it's easier to code-gen an interface than it is a concrete type. I agree with this approach.

**Comment by sebastianburckhardt** [comment]
> we might want to enforce a policy where users must explicitly declare which properties should be serialized

When it comes to serialization of fields, I think both opt-in and opt-out have their dangers.  I think there is no general consensus on which one is better (Newtonsoft.Json is opt-out by default, DataContractSerializer is opt-in by default) although I probably prefer opt-in. In the end I think it is best to let those existing serialization mechanisms deal with the problem (especially since users who are already familiar with them expect them to behave a certain way) but we can encourage users to choose the opt-in, e.g. by putting  the `[JsonObject(MemberSerialization.OptIn)]` attribute on all our entity classes in the samples. 

>  it's easier to code-gen an interface than it is a concrete type

Yes, that was my experience too. For example, in #711 it was quite simple to use Castle.Core NuGet package to code-gen an interface proxy at runtime. This is the same package that is used in our unit testing (Moq).

**Comment by cgillum** [comment]
The latest commits in `dev` basically have this covered, but in a much simpler way than I proposed.
