### ISSUE TITLE
[Question] Durable Entity scalability targets

### ISSUE THREAD

**Issue by mattg23** [Azure/azure-functions-durable-extension#776]
Hi,

I'd like to know more about the targeted scalability of durable entities.
I've read the [Performance and scale in Durable Functions (Azure Functions)](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale) article, which doesn't mention entities (yet).

**Context:**
I am thinking about using entities for the read model side of a CQRS / EventSourcing app.
The durable entities won't be updated often, but read frequently and it's totally possible that we look at hundreds of thousands or even millions of entities down the road.

**Questions:**
- Is this a viable use case for durable entities?
- I guess the maximum number of entities is only capped by the underlying storage account?
- Have you guys run some tests regarding this?
- Do you have any documents / guidance ? 
- Is the read latency of one entity independent of the number of entities? 

I really like the durable entity model, but i'd like to make sure i'm looking at the right technology for my use case. If you guys haven't tested this scenario yet, maybe i can help with some testing / benchmarks.

**Comment by olitomlinson** [comment]
@mattg23 There is not much official on this yet. 

But from what I understand from a brief twitter conversation with @cgillum write-concurrency is limited to the amount of `partitions`, which is currently capped at 16.

Entities is in alpha at the moment so the API surface is still in-flux, so we might be a few months away from a GA release and a more stable understanding of its throughput characteristics.

However, hopefully the team will be able to give us some early direction soon, as I too am keen to explore some use-cases!

**Comment by sebastianburckhardt** [comment]
We have not really run tests at scale yet, so I don't want to give definite answers, but based on my estimates I think our current implementation would already work o.k. for the scenario you are describing, because it scales based on Azure table storage characteristics:

- if most entities are updated infrequently, then the total number of entities is bounded by Azure table storage, not by the runtime, because entities are loaded into RAM only when they are receiving messages.

- `ReadEntityState` translates to an Azure storage table query with a partition key that is the entity id, so it does not depend on the number of entities.

I can't give you absolute numbers without running some experiments (which I am planning to do) as I am not sure what throughput you get from Azure table storage these days.

**Comment by cgillum** [comment]
Closing this for now, but we will make a point of publishing scalability targets for Durable Entities in our documentation once we get closer to GA.

**Comment by oising** [comment]
> Closing this for now, but we will make a point of publishing scalability targets for Durable Entities in our documentation once we get closer to GA.

@cgillum Now that's you're GA, did you guys get around to writing such documentation?

**Comment by cgillum** [comment]
Yes, we added a number for entity operations per second (64 ops/sec for a single entity on an A1 instance). You can find it here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#performance-targets. However, it needs further update still. That number has likely increased since then due to some performance tweaks we made after this number was published. We also don’t yet have target numbers for multiple concurrent entities.

**Comment by oising** [comment]
@cgillum An update to fit 2.2.x release and with the new premium storagev2 tier, (assuming low storage costs - state is typically a constant size for a constant number of entities - it would be very useful/revealing. In my opinion, there seems to be an impression that durable entities are "toy" actors and that building anything large-ish on it is a dead end. I'd like to think this is short sighted. With reasonable planning, a durable entity model could be ported to Orleans without much work.

**Comment by olitomlinson** [comment]
Hey @oising 

I don’t believe Premium storage supports Tables, which is what Durable Functions currently utilises. 

Keep an eye out for the new Durable Functions back-end which is expecting to deliver greater throughput. This back-end is still in development at the moment, but it is great to see the DF Team listening to the community and evolving DF based on the feedback.

—-

Defining what is a ‘large’ system is very subjective and nuanced argument.

For example, here is a great use-case of someone pushing millions of Durable Entities to model IoT device’s. 

https://case.schollaart.net/2019/10/31/device-offline-detection-with-durable-entities.html

It’s worth baring in mind that Entities is barely half a year GA, compared to Orleans which is about 7 years old so it’s reasonable to expect that Entities has some maturing to do. 

Is there a specific use-case you would like to discuss where Durable Entities falls short? Any feedback would be very welcome!
