### ISSUE TITLE
Durable functions RuntimeStatus is never in status ContinuedAsNew

### ISSUE THREAD

**Issue by avantadore** [Azure/azure-functions-durable-extension#777]
If I put my Orchestration to sleep by calling ContinueAsNew(5 minutes)
Then after calling var instances = await client.GetStatusAsync() 
I expected to see instances[the_index_of_my_orchestration].RuntimeStatus with the value OrchestrationRuntimeStatus.ContinuedAsNew
But it always have the value Running.

**Investigative information**

- Durable Functions extension version:
- Function App version (1.0 or 2.0): 2.0
- Programming language used: c#

I've only tested this locally (so not deployed to Azure) on windows using Visual Studio

**Comment by avantadore** [comment]
Ok, seems to be by design (but pls confirm) - the state ContinuedAsNew state is the transition from running -> call to ContinueAsNew -> running. 

The documentation states that:
_Instance termination doesn't currently propagate. Activity functions and sub-orchestrations run to completion, regardless of whether you've terminated the orchestration instance that called them._
But will that be changed?

**Comment by cgillum** [comment]
Hi @avantadore yes, this is by design. `ContinueAsNew` is a transient state and it should be expected that an orchestration should very quickly move back into the `Running` state. In fact, in a recent update to [DurableTask.Core](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/) (one of our dependencies), a change was made to optimize the behavior of `ContinueAsNew` to skip past this transient state and immediately start executing the function code again, in which case you would never actually see the `ContinueAsNew` state.

Regarding your question on termination, I suggest following #506, which tracks adding support for propagated termination.
