### ISSUE TITLE
Question- slicing window execution 

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-functions-durable-extension#789]
Does Durable Functions have any plans to implement a feature where an activity can be executed given a slice of time with its state saved? For example, if I want to run some work from 1am to 2am, the same work 3am to 4am, and so on. If there is a failure in a slice of time then it would continue on and give me the option to retry that specific slice of time that failed. This is a concept that is a available in Data Factory which they call it tumbling window.

**Comment by cgillum** [comment]
We don't have that as a built-in feature, no. You might be able to build something like that by combining various features, like durable timers, `Task.WhenAny` API w/cancellation, etc., but it would definitely be very manual.

**Comment by chinarosesz** [comment]
I'm currently falling back to using HttpTrigger which takes in a start and end time, it allows me to execute that particular chunk if I need to. However, we still need something to call the endpoint, so far I've noticed that Logic Apps has sliding window and Azure Data Factory which has tumbling window for keeping track of the different slices. 

I'm thinking of using Logic Apps webhook to trigger the starter by passing in a start time and end time, is there a way for me to know when the activity function ends/fails/passes after I invoked starter->orchestrator->activity?

**Comment by cgillum** [comment]
Regarding this:

> I'm thinking of using Logic Apps webhook to trigger the starter by passing in a start time and end time, is there a way for me to know when the activity function ends/fails/passes after I invoked starter->orchestrator->activity?

I apologize if I'm misunderstanding, but couldn't you just `await` the activity function execution in your orchestration to know when it ends/fails/passes?

**Comment by chinarosesz** [comment]
Actually that’s already there and I can see whether the activity function fails or not in applications insights. On top of that I’m trying to figure out if I can propagate the error back to logic apps so if fails so I can go to logic apps and rerun that window. I can provide more examples too. Maybe I’m over complicating this, please feel free to provide any feedback.

**Comment by cgillum** [comment]
You mentioned re-running certain windows on failure: would the Durable Functions [automatic retry feature](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling#automatic-retry-on-failure) work for your scenario?

If you need to propagate a failure back to Logic Apps via an HTTP trigger, then one option is to have your HTTP trigger function block until the orchestration is finished and then return the result. We demonstrate how to do this in [this sample code](https://github.com/Azure/azure-functions-durable-extension/blob/f2e92b866aed1d085eed33d2a7bf50d9aecfb70d/samples/precompiled/HttpSyncStart.cs#L35-L39). This only works if your operation can complete or fail in less than ~4 minutes since Azure Functions / Azure App Service doesn't allow you to hold an HTTP request active for more than 230 seconds.

Another option for sending an orchestration's output back to the logic app is to leverage the [Async HTTP pattern, described in our docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#async-http). @jeffhollan actually wrote a blog that shows how this works: https://medium.com/@jeffhollan/calling-long-running-functions-from-logic-apps-6d7ba5044701

**Comment by chinarosesz** [comment]
Currently, I already have automatic retry enabled. Since this is a long running job which can take up to a day to finish, I think using Async HTTP pattern along with Logic Apps where sliding window timer is supported might be the solution.

**Comment by cgillum** [comment]
Yes, and as we discussed in person, I agree that leveraging Logic Apps with the Async HTTP pattern will be a great place to start for your scenario. I'll go ahead and close this issue.
