### ISSUE TITLE
[Enhancement] Durable Key Value Store

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#790]
**Disclaimer** I think I've talked myself out of the usefulness of this idea due to performance considerations, but I'm going to post it anyway just in case it can be used to spur other thoughts and ideas

----

I have the following workflow for a particular part of my Orchestration.

![image](https://user-images.githubusercontent.com/4224880/58746165-ff7bd100-8452-11e9-80d0-91f4c9fadb17.png)

Typically, I perform a GET against the external resource many times, and I can tolerate some data staleness, so I cache the result for 1 minute. Depending on which VM the activity runs on, it may miss or hit, but typically it reduces calls to my external system by about 90%, and speeds up the overall throughput of the orchestration which is my main objective here.

How do I optimise this further?

So my thought is "_Can I remove all the `control` and `work` queue transactions here as most of it is just pushing the same data backwards and forwards?_" 

If I can remove those transactions associated with repeatedly calling this activity, this frees up more bandwidth for the rest of the Orchestration activities to take advantage of.

----

My first thought was to move the caching element from inside the activity call into the Orchestrations hosts in-memory cache, but I'm pretty sure this would result in a non-deterministic workflow as during replay the cache may or may not be occupied and therefor may have to call the activity.

```
private static readonly MemoryCache _cache = new MemoryCache(new MemoryCacheOptions());

[FunctionName("OrchestrationTrigger")]
public static async Task<State> RunOrchestratorAsync([OrchestrationTrigger] DurableOrchestrationContextBase context)
{
    var key = "A"; //hardcoded for simplicity
    return await _cache.GetOrCreateAsync(key, async entry =>
    {
        return await context.CallActivityAsync<object>("Activity", key);
    });
    ...
}
```

----

So I'm thinking of a solution that looks something like this :

```
private static readonly MemoryCache _cache = new MemoryCache(new MemoryCacheOptions());

[FunctionName("OrchestrationTrigger")]
public static async Task<State> RunOrchestratorAsync([OrchestrationTrigger] DurableOrchestrationContextBase context)
{
    var key = "A";
    var value = await context.GetOrCreateAsync(key, async entry =>
    {
        return await _cache.GetOrCreateAsync(key, async entry =>
        {
            return await context.CallActivityAsync<object>("Activity", key);
        });
    });
    ...
}
```
The addition of the new `Durable​Orchestration​Context.GetOrCreateAsync()` API would allow me to store a deterministic value in the orchestration in the same way `Durable​Orchestration​Context.CurrentUtcDateTime` allows a deterministic approach to the getting the current date time.

I can then use a host-level static cache as per my example above to store my objects, meaning most orchestrations don't even have to make the call to the Activity once the cache is populated.

On the other hand, if the cache is empty and must make the call to the activity, thats okay because the history is deterministic through the use of the new `Context.GetOrCreateAsync()` API .

---

**Performance Considerations**

I don't think the above solution would work well if there was a lot of cache misses due to a low TLL or a wide range of actively used cache keys, as the call to `_cache.GetOrCreateAsync` would essentially block the orchestration until the result of the Activity completes and updates the cache. If I understand the internals of Durable Functions, **this would actually block the entire partition**, which would reduce overall throughput drastically.

In my use-case I'm typically making the same activity call with the same cache key thousands of times in a minute, so maybe the short-term blocking of the partition isn't so bad when trading off against the reduced `control` and `work` queue transactions?

**Comment by cgillum** [comment]
I'm not sure I fully understood the idea, but I will make a couple comments in case they are useful in your thought process:

* Rather than using activity functions as a means of caching data, I wonder if [durable entities](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-preview#entity-functions) would be a more natural fit. The problem with activity functions is that they can run on any VM so the probability of a cache hit also depends on whether the correct VM picks up the work-item queue message. Durable entities would not have this problem since they are stateful and triggered off the control-queue.
* I'm not sure I understood the point about blocking the partition. The only way you can block a partition is by having orchestrator functions actually blocking CPU threads (which should never happen if you're following the rules). It is possible to _overwhelm_ a partition and create delays by having large backlogs of messages in the same control queue, but that's more of a load problem and not something that the implementation of an orchestration could really cause on its own.
