### ISSUE TITLE
Question: Orchestration - Control CPU

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#792]
I have an orchestration that calls 3 activities and one sub orchestration that calls 2 activities. we needed around 4-5 workers (I3) to support around 150K orchestration executions (non-replay) over a 6 hour time frame. I have all the default knobs set and so now I am wondering what I can do to help control the CPU to less workers are needed. The I3's are a single core, so I wouldn't think I would need to tinker with the concurrency thresholds, so I was thinking of looking into the extended sessions. The average orchestration completes within 2 seconds, so what would you recommend for the timeout period?  It's difficult for me to simulate the load on our non-prod environments, so i am trying to minimize risk with the trial and error.

**Comment by cgillum** [comment]
1.4K over 6 hours (>4 orchestrations per minute) is a very non-demanding workload for Durable Functions itself. If it's requiring you to have 4-5 workers, then I imagine you must have some very CPU heavy activity functions. Is that correct?  Also, is the goal to reduce CPU per VM or to reduce the number of VMs? Those goals may actually be at odds with each other (decreasing one would naturally require you to increase the other), unless there is something you can do in your _application logic_ to reduce CPU usage. Let me know if I'm misunderstanding.

**Comment by mpaul31** [comment]
ah sorry, i fat fingered the # of calls, which is 1.5M. :)

I'm really trying to reduce the CPU per VM, so I know there are multiple knobs (orch concurrency, extended sessions) I can change.

**Comment by cgillum** [comment]
Got it, so 150K orchestrations over 6 hours averages out to 7 orchestrations/sec, which I think is achievable.

In terms of reducing per-VM CPU, the simple thing to do is to set a smaller `maxConcurrentActivityFunctions` value in **host.json**. The consequence of setting this to a smaller number is that each instance will use less CPU/memory, but you will also get less overall throughput with the same number of workers. You could also play with `maxConcurrentOrchestratorFunctions`, but that will likely have a more limited benefit orchestrator functions typically don't do a lot of CPU or memory-intensive work. But it ultimately depends on the characteristics of your workload.

From the description of your orchestrator functions, I don't think extended sessions is going to help much. Extended sessions are useful primarily when doing a lot of fan-out/fan-in because the overhead of replay starts to be much more noticeable. If you have a lot of distinct orchestration instances and they are all doing short sequential activity chains, then extended sessions won't do much for you, if anything at all.

**Comment by mpaul31** [comment]
Thanks @cgillum that helps a bunch. I'll try reducing the `maxConcurrentActivityFunctions` and see where it takes me.

**Comment by mpaul31** [comment]
One thing I forgot to include is the sub orchestration has a foreach loop that _could_ execute 0 to 3 times that awaits an activity. Would this influence your recommendation regarding extended sessions?

**Comment by cgillum** [comment]
Nope, even in this situation I wouldn't change my recommendation. Those activity functions are still running sequentially.

**Comment by mpaul31** [comment]
thanks man!
