### ISSUE TITLE
Random "Keyset does not exist" X509Certificate2 on Activity functions

### ISSUE THREAD

**Issue by kaluznyt** [Azure/azure-functions-durable-extension#808]
**Describe the bug**
I have a durable functions implemented in a fan-out pattern. Basically the orchestrator gets a list of blobs (1 activity function) from container, and then on each entry from the list run another activity function which basically decrypts the blob and inserts entry to table storage. Issue is that sometime / or some activity functions fail with Cryptographic exception "Keyset does not exist" while other decrypt the blobs successfully. Seems weird to me tried different things but doesn't have a clue, seems like an unsupported scenario or a bug.

Seems it's something about scaling, when it's run on a very small amount of data everything works fine so for example 10 vs 10k

**Investigative information**
- Durable Functions extension version:
- Function App version (1.0)
- Programming language used: c#

***If deployed to Azure***

- Timeframe issue observed: 17/07/2019 - 10-17 CEST
- Region: northeu
- Orchestration instance ID(s): 2648ef856eed4528914417bb48e2f00e

These are invocation ids of 2 functions started by the same orchestrator, 1 failed, 1 was successful:
Failure:
2019-06-17 15:28:03.168 Function started (Id=92174b6f-9930-4ec2-b836-9bc48c4b2856) 
Success:
2019-06-17 15:27:12.585 Function started (Id=5407777a-5b4f-44fb-87a3-08e6a28da041)

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

Run orchestrator, observe random errors on activity functions.

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
No errors.

**Actual behavior**
An error seems randomly occurring. 

**Screenshots**

**Known workarounds**
No workaround.

**Additional context**

- Development environment (ex. Visual Studio)
- Function invocation IDs

**Comment by cgillum** [comment]
Are you using the Azure Functions Consumption plan? I did notice one report of a similar issue on StackOverflow here (a workaround is mentioned as well): https://stackoverflow.com/questions/52111045/c-keyset-does-not-exist-in-azure-functions-on-consumption-plan

**Comment by kaluznyt** [comment]
Yes, using consumption plan indeed, I saw this thread as well, however hasn't tried the workaround due to usage of a third party library, but perhaps will try as I can see no other option, or perhaps switching to App Service / Premium plan would be an option ?

**Comment by cgillum** [comment]
Yes, I would suggest trying to see if you can reproduce this problem in the App Service or Elastic Premium plans. If it's reproducible there, then it would imply some kind of general App Service issue. Otherwise, if it works in those plans, then we know it's likely related to some of the Consumption-specific architecture. Either way, any data you can share would be helpful to us in identifying a fix.

**Comment by kaluznyt** [comment]
I tried the solution from the stackoverflow thread, and that actually mitigated the issue on consumption plan, so I went this route. Would be really nice to have this working on pure .net framework, however, it's probably difficult to get to the root cause of this.

**Comment by cgillum** [comment]
I do think it would be difficult to root cause this, and this repo unfortunately won't be a good place to track an investigation. If you are still interested in root causing this particular behavior, the best way forward will be to open a support ticket from the Azure Portal. That will ensure that the right team(s) will be engaged to investigate further. In any case, sorry about the trouble this issue may have caused you.
