### ISSUE TITLE
Expose EntityId of the parent DurableEntity when using EntityTrigger

### ISSUE THREAD

**Issue by msajid** [Azure/azure-functions-durable-extension#809]
It would be great if we can get EntityId of the parent DurableEntity (not Orchestrator) in a "context" of child DurableEntity. The information is available in DurableEntityContext under CurrentOperation property which is not accessible. I am trying to implement Actor hierarchy and passing the parent id with each message to child Entities to achieve this. It could also be useful for implementing parental supervisory strategy for child actors.

**Comment by cgillum** [comment]
@sebastianburckhardt what do you think?

**Comment by sebastianburckhardt** [comment]
Our entities do not have a hierarchy, so I am not sure what you mean by the "parent" of an entity?

There is a field called `RequestMessage.parentInstanceId` but this is not really the "parent", but just the instanceId of the sender of the message (we should probably change this field name to avoid confusion). This sender is not always an entity. It can be an entity, an orchestration, or a client (in which case the instanceId is null).

If we chose to expose this field I think we would have to distinguish all those cases. I think just returning the actual string value would not be appropriate since the instance ids of entities are really meant to be an internal representation.  

I think it is probably better if you are passing the entity ids yourself in the application. I think it is simpler that way and does not require a complicated API or explanation.



hierarchy. If I understand correctly, you are asking whether we can expose the "sender" of an operation as part of the operation context?

**Comment by msajid** [comment]
I was thinking about grouping actors under a parent actor so i can simulate actors families. For example in an IoT scenario i might have set of sensors representing a group that i can control using a "Coordinator" or "Parent" actor. And child actors react to messages only when sender is parent, or Parent can send a "Kill" message and child actor can do "context.DestructOnExit()" in reaction. since Actor processes one message at a time i was thinking about building a network of "Coordinators" to achieve concurrency. 

Passing entity id will also work. Currently i am using context.IsNewlyConstructed property to check if the Entity is newly constructed and read the "SenderId" as "Parent" from the input message and save it as a state along with other input data i need.    
hope i am using the DurableEntities the right way.

**Comment by sebastianburckhardt** [comment]
Sounds like a reasonable pattern. This can be done entirely at the application level (i.e. we don't need to build special support for it into the runtime).

Some advice:
- make sure you really need the parent. It is often not necessary.
- Try to involve the parent as little as possible: don't route all the traffic through the parent. 

 A good reason to use a parent is if you want to keep a list of all the children, so you can enumerate them. In that case, the design I would use is that the parent is an "observer" of the children, i.e. the children send a signal to the parent whenever they are created or deleted.
