### ISSUE TITLE
Question: How many Orchestrations can be running at the same time

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#813]
Is there any limit on how many orchestrations and activities can be running at any given point of time

**Comment by cgillum** [comment]
There is no hard limit. You can enforce concurrency controls which are per-instance, as described here: [Concurrency throttles](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#concurrency-throttles).

**Comment by kijujjav** [comment]
@cgillum , my application is running in an Isolated environment and I changed the maxConcurrentActivityFunctions and maxConcurrentOrchestratorFunctions to 50 and I am seeing some latency in orchestration processing. I am firing up 500 http calls to my application and each call creates around 20 orchestrations and 20 activities each.

**Comment by cgillum** [comment]
What kind of latency are you seeing? What is the CPU usage like on your VMs? Given the HTTP load you're sending, is it possible that you are setting your concurrency limits too low? Or perhaps you need to add more VMs to your Isolated environment? How many do you have now?

**Comment by kijujjav** [comment]
I am observing delays between orchestrations execution. I am using App Service so I am not sure about the VM's but I see maximum of 25% cpu usage and 30% memory usage for my app service. Could you recommend a number for concurrency numbers?  I am running on I2 in Isolated env (420 total ACU,
7 GB memory, Dv2-Series compute equivalent).

Also, i am using the same storage account for webJobs, Durable functions and storind data from my application. Can this affect the performance?

**Comment by cgillum** [comment]
You need to do your own testing to see what the best concurrency configuration is for your application. If you are seeing low CPU and memory usage, then you should consider _increasing_ your concurrency settings so that you get better utilization.  App Service Environments allow you to control the exact number of VMs, so if increasing concurrency does not help, then you should consider increasing the number of VMs in your plan.

Regarding your question about storage accounts, please refer to our documentation: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#storage-account-selection

> If not specified, the default `AzureWebJobsStorage` storage account is used. For performance-sensitive workloads, however, configuring a non-default storage account is recommended. Durable Functions uses Azure Storage heavily, and using a dedicated storage account isolates Durable Functions storage usage from the internal usage by the Azure Functions host.

So yes, separating your storage accounts can potentially increase your potential throughput, but only if throughput is the current bottleneck.
