### ISSUE TITLE
Improper Scaling on Azure Functions Premium Plan 

### ISSUE THREAD

**Issue by t-meyunu** [Azure/azure-functions-durable-extension#845]
### Description
I am running a Function App which is Service Bus Topic Triggered and can have messages anywhere from 1000 to 40000 messages. I have deployed the app on the EP1 Premium Plan but its not scaling as expected. Previously on the Consumption Plan it would to scale up to 50+ instances but now under the same load, it scales up to max 3/4 instances. Minimum number of instances is set to 2.

### Expected behavior
Functions should scale out to more instances.

### Actual behavior
Improper scaling even with large backlog of messages in Service Bus

### App Details

- **Durable Functions extension version**: 1.8.2
- **Azure Functions runtime version**: 2.0
- **Programming language used**: C#

### Screenshots
The problem mentioned can also be seen in the blue bars of the scaling graph. The graph shows number of instances orchestrators are running on vs timestamp. The run was for 50k messages (Start Time: 2019-07-03T10:01:00.425 UTC ). The number of servers remained at 3 even though there were around 35k messages in the service bus. It later scaled to 20 servers after 50 mins.
![scale](https://user-images.githubusercontent.com/52778433/61036187-35af5780-a3e6-11e9-8a46-d36c2f4932fd.PNG)

### If deployed to Azure

- **Timeframe issue observed**:   2019-07-02T12:59:53.423 UTC 
- **Function App name**: GenerationPremium
- **Azure region**: East US 2
- **Azure storage account name**: NORUDurableFramework

**Comment by cgillum** [comment]
That is odd. The scale heuristics between Consumption and Elastic Premium should be the same, so any difference between the two is likely due to a problem with allocating the necessary D-series VMs. Unfortunately my delay in investigating this means that we no longer have the telemetry we need to investigate.

Do you have a more recent repro of this problem that you can share? Also, to make sure this gets the right level of attention, would it be possible for you to open a support case with Azure to investigate? I would really like to make sure this is understood and resolved.
