### ISSUE TITLE
Disaster Recovery and Geo-Distribution Documentation

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#89]
We need documentation on how disaster recovery works with Durable Functions, which is a very important topic, particularly for the enterprise. This documentation could also include discussion of geo-distribution of work.

**Comment by cgillum** [comment]
Here is the PR: https://github.com/MicrosoftDocs/azure-docs/pull/7723

**Comment by CarlosSardo** [comment]
@cgillum here's the PR to the azure-docs-pr repository instead. Shall I delete the previous one #7723?

**Comment by cgillum** [comment]
@CarlosSardo yes you can delete the previous PR. However, note that there is feedback there which will need to be applied to the new PR.

**Comment by gled4er** [comment]
Hello @cgillum,

May I ask you when you have time to have a final review for this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/39677 ?

It should have all the previous issues resolved.

We believe that the PR is ready for merging but since it is a new one requires your approval.

Thank you!

**Comment by cgillum** [comment]
This has been merged.
