### ISSUE TITLE
HTTP APIs need proper documentation

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#9]
The documentation shows by example how the HTTP APIs work, but the actual protocol needs to be properly documented.

**Comment by ukluk** [comment]
Chris, Thank you very much for your help.
I did find the issue in my worker function.

fn1 is your HttpStart and if you look at the master branch it **does** have the quotes... but that was not the problem.

fn2 is almost the E1_SayHello, but I started to bring some of the dependencies in. One was DocDB client.

The problem is that the runtime environment doesn't pay nice with "Microsoft.Azure.DocumentDB": "1.15.0", It fails with MissingMethodException

But if a constructor fails inside the public static RUN function, even with try/catch, the worker aborts and bypasses the logs.

This aborts and hides the error:

```
public static async Task<string> Run(
		DurableOrchestrationContext context,
		TraceWriter log)
	{
        try
        {
            // Get request body from the Json string
            var activity = context.GetInput<TaskActivity>();
            activity.StartedUtc = DateTime.UtcNow; 
            log.Info($"Started contract for task with ID = '{activity.TaskId}'.");
            var client =new DocumentClient(new Uri(DOCDB_ENDPOINT_URL), DOCDB_PRIMARY_KEY, null);

```

But calling the client in a different method catches the error and shows the log
`            var client = PrepareClient(log);`

Where PrepareClient looks like:

```
private static DocumentClient PrepareClient(TraceWriter trace)
{
    DocumentClient client = null;
    try{
            client = new DocumentClient(new Uri(DOCDB_ENDPOINT_URL), DOCDB_PRIMARY_KEY, null);
    }
    catch(Exception ex2)
    {
        trace.Error(ex2.ToString());
    }
    return client;
}
```

**Comment by cgillum** [comment]
This is complete: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api
