### ISSUE TITLE
Activity fail to correctly deserialize DateTimeOffset and lose the offset

### ISSUE THREAD

**Issue by TristanApc** [Azure/azure-functions-durable-extension#934]
### Description
When an orchestrator call an activity and give it a DateTimeOffset as an input, the offset will be lost once deserialized in the activity.

### Expected behavior
I expect the activity to obtain the same DateTimeOffset passed to its input from the orchestrator that called it.

### Actual behavior
The activity obtain a DateTimeOffset with a different offset, resulting in a data loss.

### Relevant source code snippets
Case can be fully reproduced with this [repository](https://github.com/TristanApc/DurableFunction-DateTimeOffset-repro).

### Known workarounds
Either you change your input to string then parse it into DateTimeOffset or find a different strategy to prevent data loss.

### App Details

- **Durable Functions extension version v1.8.3**
- **Azure Functions runtime version 2.0**
- **Csharp**

**Comment by ConnorMcMahon** [comment]
In V2 now, there is now the additional workaround of injecting a `IMessageSerializerSettingsFactory` implementation.

We should be able to fix this as a non-breaking change in a release, but we are running out of time for 2.2.0. Pushing back to 2.2.1.

**Comment by ConnorMcMahon** [comment]
Punting to 2.3.0.

**Comment by cgillum** [comment]
@amdeel would your date/time serializer PR address this? https://github.com/Azure/durabletask/pull/441

**Comment by amdeel** [comment]
@TristanApc Thank you so much for the repro! I did use it to try to repro the issue, but failed. The DateTimeOffset appeared to be the same in your logs in your starter function, orchestrator, and activity. Let me know if I'm missing something.

Like @cgillum mentioned above, I very recently made a change involving strings used as inputs that "look" like date objects. The default serialization behavior takes these strings and turns them into DateTime objects (see [this](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DateParseHandling.htm) documentation if you're curious). However, we changed this default behavior in DurableFunctions so this will not happen and strings can be safely input without turning into date objects in deserialization. If you had input a string object to your activity and lost the offset when deserializing it in your activity, this would be fixed by this change (in our next release). Does this sound like the situation you were experiencing?

**Comment by amdeel** [comment]
@TristanApc Ah, I see my mistake. I was able to use your repro to verify this behavior by adjusting the offset. Thanks again for the repro, It helps a lot!

This will be fixed in our next release (PR: https://github.com/Azure/azure-functions-durable-extension/pull/1440). I tested this change and verified that it fixed the issue in your repro.
